
IF
  Exists("elemimix")
  Global("fl10t01","GLOBAL",4)
THEN RESPONSE #100
  GiveItemCreate("ax1h16","elemimix",0,0,0)
  SetGlobal("fl10t01","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("elemimix")
  Global("fl10t02","GLOBAL",4)
THEN RESPONSE #100
  GiveItemCreate("blun26","elemimix",0,0,0)
  SetGlobal("fl10t02","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("elemimix")
  Global("fl10t03","GLOBAL",4)
THEN RESPONSE #100
  GiveItemCreate("sw1h67","elemimix",0,0,0)
  SetGlobal("fl10t03","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("elemimix")
  Global("fl10t04","GLOBAL",4)
THEN RESPONSE #100
  GiveItemCreate("brac21","elemimix",0,0,0)
  SetGlobal("fl10t04","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("elemimix")
  Global("fl10t05","GLOBAL",4)
THEN RESPONSE #100
  GiveItemCreate("dagg21","elemimix",0,0,0)
  SetGlobal("fl10t05","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("elemimix")
  Global("fl10t06","GLOBAL",4)
THEN RESPONSE #100
  GiveItemCreate("halb10","elemimix",0,2,0)
  SetGlobal("fl10t06","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("elemimix")
  Global("fl10t07","GLOBAL",4)
THEN RESPONSE #100
  GiveItemCreate("helm27","elemimix",0,0,0)
  SetGlobal("fl10t07","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("elemimix")
  Global("fl10t08","GLOBAL",4)
THEN RESPONSE #100
  GiveItemCreate("sw1h60","elemimix",0,1,0)
  SetGlobal("fl10t08","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("elemimix")
  Global("fl10t09","GLOBAL",4)
THEN RESPONSE #100
  GiveItemCreate("plat21","elemimix",0,0,0)
  SetGlobal("fl10t09","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("elemimix")
  Global("fl10t10","GLOBAL",4)
THEN RESPONSE #100
  GiveItemCreate("ax1h14","elemimix",0,0,0)
  SetGlobal("fl10t10","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("elemimix")
  Global("fl10t11","GLOBAL",4)
THEN RESPONSE #100
  GiveItemCreate("sw1h62","elemimix",0,0,0)
  SetGlobal("fl10t11","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("elemimix")
  Global("fl10t12","GLOBAL",4)
THEN RESPONSE #100
  GiveItemCreate("sper11","elemimix",0,0,0)
  SetGlobal("fl10t12","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("elemimix")
  Global("fl10t13","GLOBAL",4)
THEN RESPONSE #100
  GiveItemCreate("staf21","elemimix",0,0,0)
  SetGlobal("fl10t13","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("elemimix")
  Global("fl10t14","GLOBAL",4)
THEN RESPONSE #100
  GiveItemCreate("sw1h58","elemimix",0,0,0)
  SetGlobal("fl10t14","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("elemimix")
  Global("fl10t15","GLOBAL",4)
THEN RESPONSE #100
  GiveItemCreate("sw1h66","elemimix",0,0,0)
  SetGlobal("fl10t15","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("elemimix")
  Global("fl10t16","GLOBAL",4)
THEN RESPONSE #100
  GiveItemCreate("sw1h70","elemimix",0,1,0)
  SetGlobal("fl10t16","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("elemimix")
  Global("fl10t17","GLOBAL",4)
THEN RESPONSE #100
  GiveItemCreate("sw2h21","elemimix",0,0,0)
  SetGlobal("fl10t17","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("elemimix")
  Global("fl10t18","GLOBAL",4)
THEN RESPONSE #100
  GiveItemCreate("xbow15","elemimix",0,0,0)
  SetGlobal("fl10t18","GLOBAL",-1)
  DestroySelf()
END
