
IF
  Exists("amlich01")
  Global("fl10t01","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("ax1h16","amlich01",0,0,0)
  SetGlobal("fl10t01","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("amlich01")
  Global("fl10t02","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("blun26","amlich01",0,0,0)
  SetGlobal("fl10t02","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("amlich01")
  Global("fl10t03","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("sw1h67","amlich01",0,0,0)
  SetGlobal("fl10t03","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("amlich01")
  Global("fl10t04","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("brac21","amlich01",0,0,0)
  SetGlobal("fl10t04","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("amlich01")
  Global("fl10t05","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("dagg21","amlich01",0,0,0)
  SetGlobal("fl10t05","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("amlich01")
  Global("fl10t06","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("halb10","amlich01",0,2,0)
  SetGlobal("fl10t06","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("amlich01")
  Global("fl10t07","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("helm27","amlich01",0,0,0)
  SetGlobal("fl10t07","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("amlich01")
  Global("fl10t08","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("sw1h60","amlich01",0,1,0)
  SetGlobal("fl10t08","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("amlich01")
  Global("fl10t09","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("plat21","amlich01",0,0,0)
  SetGlobal("fl10t09","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("amlich01")
  Global("fl10t10","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("ax1h14","amlich01",0,0,0)
  SetGlobal("fl10t10","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("amlich01")
  Global("fl10t11","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("sw1h62","amlich01",0,0,0)
  SetGlobal("fl10t11","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("amlich01")
  Global("fl10t12","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("sper11","amlich01",0,0,0)
  SetGlobal("fl10t12","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("amlich01")
  Global("fl10t13","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("staf21","amlich01",0,0,0)
  SetGlobal("fl10t13","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("amlich01")
  Global("fl10t14","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("sw1h58","amlich01",0,0,0)
  SetGlobal("fl10t14","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("amlich01")
  Global("fl10t15","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("sw1h66","amlich01",0,0,0)
  SetGlobal("fl10t15","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("amlich01")
  Global("fl10t16","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("sw1h70","amlich01",0,1,0)
  SetGlobal("fl10t16","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("amlich01")
  Global("fl10t17","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("sw2h21","amlich01",0,0,0)
  SetGlobal("fl10t17","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("amlich01")
  Global("fl10t18","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("xbow15","amlich01",0,0,0)
  SetGlobal("fl10t18","GLOBAL",-1)
  DestroySelf()
END
