
IF
  Exists("Bazdra03")
  Global("fl10t01","GLOBAL",9)
THEN RESPONSE #100
  GiveItemCreate("ax1h16","Bazdra03",0,0,0)
  SetGlobal("fl10t01","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Bazdra03")
  Global("fl10t02","GLOBAL",9)
THEN RESPONSE #100
  GiveItemCreate("blun26","Bazdra03",0,0,0)
  SetGlobal("fl10t02","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Bazdra03")
  Global("fl10t03","GLOBAL",9)
THEN RESPONSE #100
  GiveItemCreate("sw1h67","Bazdra03",0,0,0)
  SetGlobal("fl10t03","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Bazdra03")
  Global("fl10t04","GLOBAL",9)
THEN RESPONSE #100
  GiveItemCreate("brac21","Bazdra03",0,0,0)
  SetGlobal("fl10t04","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Bazdra03")
  Global("fl10t05","GLOBAL",9)
THEN RESPONSE #100
  GiveItemCreate("dagg21","Bazdra03",0,0,0)
  SetGlobal("fl10t05","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Bazdra03")
  Global("fl10t06","GLOBAL",9)
THEN RESPONSE #100
  GiveItemCreate("halb10","Bazdra03",0,2,0)
  SetGlobal("fl10t06","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Bazdra03")
  Global("fl10t07","GLOBAL",9)
THEN RESPONSE #100
  GiveItemCreate("helm27","Bazdra03",0,0,0)
  SetGlobal("fl10t07","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Bazdra03")
  Global("fl10t08","GLOBAL",9)
THEN RESPONSE #100
  GiveItemCreate("sw1h60","Bazdra03",0,1,0)
  SetGlobal("fl10t08","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Bazdra03")
  Global("fl10t09","GLOBAL",9)
THEN RESPONSE #100
  GiveItemCreate("plat21","Bazdra03",0,0,0)
  SetGlobal("fl10t09","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Bazdra03")
  Global("fl10t10","GLOBAL",9)
THEN RESPONSE #100
  GiveItemCreate("ax1h14","Bazdra03",0,0,0)
  SetGlobal("fl10t10","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Bazdra03")
  Global("fl10t11","GLOBAL",9)
THEN RESPONSE #100
  GiveItemCreate("sw1h62","Bazdra03",0,0,0)
  SetGlobal("fl10t11","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Bazdra03")
  Global("fl10t12","GLOBAL",9)
THEN RESPONSE #100
  GiveItemCreate("sper11","Bazdra03",0,0,0)
  SetGlobal("fl10t12","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Bazdra03")
  Global("fl10t13","GLOBAL",9)
THEN RESPONSE #100
  GiveItemCreate("staf21","Bazdra03",0,0,0)
  SetGlobal("fl10t13","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Bazdra03")
  Global("fl10t14","GLOBAL",9)
THEN RESPONSE #100
  GiveItemCreate("sw1h58","Bazdra03",0,0,0)
  SetGlobal("fl10t14","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Bazdra03")
  Global("fl10t15","GLOBAL",9)
THEN RESPONSE #100
  GiveItemCreate("sw1h66","Bazdra03",0,0,0)
  SetGlobal("fl10t15","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Bazdra03")
  Global("fl10t16","GLOBAL",9)
THEN RESPONSE #100
  GiveItemCreate("sw1h70","Bazdra03",0,1,0)
  SetGlobal("fl10t16","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Bazdra03")
  Global("fl10t17","GLOBAL",9)
THEN RESPONSE #100
  GiveItemCreate("sw2h21","Bazdra03",0,0,0)
  SetGlobal("fl10t17","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Bazdra03")
  Global("fl10t18","GLOBAL",9)
THEN RESPONSE #100
  GiveItemCreate("xbow15","Bazdra03",0,0,0)
  SetGlobal("fl10t18","GLOBAL",-1)
  DestroySelf()
END
