
IF
  Exists("gromg10")
  Global("fl11t01","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("blun30a","gromg10",0,0,0)
  SetGlobal("fl11t01","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("gromg08")
  Global("fl11t02","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("blun30b","gromg08",0,0,0)
  SetGlobal("fl11t02","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("gromg08")
  Global("fl11t03","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("brac22","gromg08",0,0,0)
  SetGlobal("fl11t03","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("gromg08")
  Global("fl11t04","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("figure01","gromg08",1,0,0)
  SetGlobal("fl11t04","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("gromg08")
  Global("fl11t05","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("quiver01","gromg08",0,0,0)
  SetGlobal("fl11t05","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("gromg08")
  Global("fl11t06","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("quiver02","gromg08",0,0,0)
  SetGlobal("fl11t06","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("gromg09")
  Global("fl11t07","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("quiver05","gromg09",0,0,0)
  SetGlobal("fl11t07","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("gromg09")
  Global("fl11t08","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("ring42","gromg09",1,0,0)
  SetGlobal("fl11t08","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("gromg10")
  Global("fl11t09","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("ring46","gromg10",0,0,0)
  SetGlobal("fl11t09","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("gromg08")
  Global("fl11t10","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("rods06","gromg08",10,0,0)
  SetGlobal("fl11t10","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("gromg08")
  Global("fl11t11","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("tome01","gromg08",1,0,0)
  SetGlobal("fl11t11","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("gromg08")
  Global("fl11t12","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("wand18","gromg08",6,5,0)
  SetGlobal("fl11t12","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("gromg08")
  Global("fl11t13","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("wand18","gromg08",6,5,0)
  SetGlobal("fl11t13","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("gromg08")
  Global("fl11t14","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("wand19","gromg08",1,0,0)
  SetGlobal("fl11t14","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("gromg09")
  Global("fl11t15","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("wand19","gromg09",1,0,0)
  SetGlobal("fl11t15","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("gromg08")
  Global("fl11t16","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("helm23","gromg08",0,0,0)
  SetGlobal("fl11t16","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("gromg09")
  Global("fl11t17","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("amul28","gromg09",0,0,0)
  SetGlobal("fl11t17","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("gromg09")
  Global("fl11t18","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("brac24","gromg09",0,0,0)
  SetGlobal("fl11t18","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("gromg08")
  Global("fl11t19","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("helm24","gromg08",0,0,0)
  SetGlobal("fl11t19","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("gromg10")
  Global("fl11t20","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("helm25","gromg10",0,0,0)
  SetGlobal("fl11t20","GLOBAL",-1)
  DestroySelf()
END
