
IF
  Exists("sengua03")
  Global("fl11t01","GLOBAL",14)
THEN RESPONSE #100
  GiveItemCreate("blun30a","sengua03",0,0,0)
  SetGlobal("fl11t01","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("sengua03")
  Global("fl11t02","GLOBAL",14)
THEN RESPONSE #100
  GiveItemCreate("blun30b","sengua03",0,0,0)
  SetGlobal("fl11t02","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("sengua03")
  Global("fl11t03","GLOBAL",14)
THEN RESPONSE #100
  GiveItemCreate("brac22","sengua03",0,0,0)
  SetGlobal("fl11t03","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("sengua03")
  Global("fl11t04","GLOBAL",14)
THEN RESPONSE #100
  GiveItemCreate("figure01","sengua03",1,0,0)
  SetGlobal("fl11t04","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("sengua03")
  Global("fl11t05","GLOBAL",14)
THEN RESPONSE #100
  GiveItemCreate("quiver01","sengua03",0,0,0)
  SetGlobal("fl11t05","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("sengua03")
  Global("fl11t06","GLOBAL",14)
THEN RESPONSE #100
  GiveItemCreate("quiver02","sengua03",0,0,0)
  SetGlobal("fl11t06","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("sengua03")
  Global("fl11t07","GLOBAL",14)
THEN RESPONSE #100
  GiveItemCreate("quiver05","sengua03",0,0,0)
  SetGlobal("fl11t07","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("sengua03")
  Global("fl11t08","GLOBAL",14)
THEN RESPONSE #100
  GiveItemCreate("ring42","sengua03",1,0,0)
  SetGlobal("fl11t08","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("sengua03")
  Global("fl11t09","GLOBAL",14)
THEN RESPONSE #100
  GiveItemCreate("ring46","sengua03",0,0,0)
  SetGlobal("fl11t09","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("sengua03")
  Global("fl11t10","GLOBAL",14)
THEN RESPONSE #100
  GiveItemCreate("rods06","sengua03",10,0,0)
  SetGlobal("fl11t10","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("sengua03")
  Global("fl11t11","GLOBAL",14)
THEN RESPONSE #100
  GiveItemCreate("tome01","sengua03",1,0,0)
  SetGlobal("fl11t11","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("sengua03")
  Global("fl11t12","GLOBAL",14)
THEN RESPONSE #100
  GiveItemCreate("wand18","sengua03",6,5,0)
  SetGlobal("fl11t12","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("sengua03")
  Global("fl11t13","GLOBAL",14)
THEN RESPONSE #100
  GiveItemCreate("wand18","sengua03",6,5,0)
  SetGlobal("fl11t13","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("sengua03")
  Global("fl11t14","GLOBAL",14)
THEN RESPONSE #100
  GiveItemCreate("wand19","sengua03",1,0,0)
  SetGlobal("fl11t14","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("sengua03")
  Global("fl11t15","GLOBAL",14)
THEN RESPONSE #100
  GiveItemCreate("wand19","sengua03",1,0,0)
  SetGlobal("fl11t15","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("sengua03")
  Global("fl11t16","GLOBAL",14)
THEN RESPONSE #100
  GiveItemCreate("helm23","sengua03",0,0,0)
  SetGlobal("fl11t16","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("sengua03")
  Global("fl11t17","GLOBAL",14)
THEN RESPONSE #100
  GiveItemCreate("amul28","sengua03",0,0,0)
  SetGlobal("fl11t17","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("sengua03")
  Global("fl11t18","GLOBAL",14)
THEN RESPONSE #100
  GiveItemCreate("brac24","sengua03",0,0,0)
  SetGlobal("fl11t18","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("sengua03")
  Global("fl11t19","GLOBAL",14)
THEN RESPONSE #100
  GiveItemCreate("helm24","sengua03",0,0,0)
  SetGlobal("fl11t19","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("sengua03")
  Global("fl11t20","GLOBAL",14)
THEN RESPONSE #100
  GiveItemCreate("helm25","sengua03",0,0,0)
  SetGlobal("fl11t20","GLOBAL",-1)
  DestroySelf()
END
