
IF
  Exists("tent")
  Global("fl11t01","GLOBAL",18)
THEN RESPONSE #100
  ActionOverride("tent",CreateItem("blun30a",0,0,0))
  SetGlobal("fl11t01","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("tent")
  Global("fl11t02","GLOBAL",18)
THEN RESPONSE #100
  ActionOverride("tent",CreateItem("blun30b",0,0,0))
  SetGlobal("fl11t02","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("tent")
  Global("fl11t03","GLOBAL",18)
THEN RESPONSE #100
  ActionOverride("tent",CreateItem("brac22",0,0,0))
  SetGlobal("fl11t03","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("tent")
  Global("fl11t04","GLOBAL",18)
THEN RESPONSE #100
  ActionOverride("tent",CreateItem("figure01",1,0,0))
  SetGlobal("fl11t04","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("tent")
  Global("fl11t05","GLOBAL",18)
THEN RESPONSE #100
  ActionOverride("tent",CreateItem("quiver01",0,0,0))
  SetGlobal("fl11t05","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("tent")
  Global("fl11t06","GLOBAL",18)
THEN RESPONSE #100
  ActionOverride("tent",CreateItem("quiver02",0,0,0))
  SetGlobal("fl11t06","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("tent")
  Global("fl11t07","GLOBAL",18)
THEN RESPONSE #100
  ActionOverride("tent",CreateItem("quiver05",0,0,0))
  SetGlobal("fl11t07","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("tent")
  Global("fl11t08","GLOBAL",18)
THEN RESPONSE #100
  ActionOverride("tent",CreateItem("ring42",1,0,0))
  SetGlobal("fl11t08","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("tent")
  Global("fl11t09","GLOBAL",18)
THEN RESPONSE #100
  ActionOverride("tent",CreateItem("ring46",0,0,0))
  SetGlobal("fl11t09","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("tent")
  Global("fl11t10","GLOBAL",18)
THEN RESPONSE #100
  ActionOverride("tent",CreateItem("rods06",10,0,0))
  SetGlobal("fl11t10","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("tent")
  Global("fl11t11","GLOBAL",18)
THEN RESPONSE #100
  ActionOverride("tent",CreateItem("tome01",1,0,0))
  SetGlobal("fl11t11","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("tent")
  Global("fl11t12","GLOBAL",18)
THEN RESPONSE #100
  ActionOverride("tent",CreateItem("wand18",6,5,0))
  SetGlobal("fl11t12","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("tent")
  Global("fl11t13","GLOBAL",18)
THEN RESPONSE #100
  ActionOverride("tent",CreateItem("wand18",6,5,0))
  SetGlobal("fl11t13","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("tent")
  Global("fl11t14","GLOBAL",18)
THEN RESPONSE #100
  ActionOverride("tent",CreateItem("wand19",1,0,0))
  SetGlobal("fl11t14","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("tent")
  Global("fl11t15","GLOBAL",18)
THEN RESPONSE #100
  ActionOverride("tent",CreateItem("wand19",1,0,0))
  SetGlobal("fl11t15","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("tent")
  Global("fl11t16","GLOBAL",18)
THEN RESPONSE #100
  ActionOverride("tent",CreateItem("helm23",0,0,0))
  SetGlobal("fl11t16","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("tent")
  Global("fl11t17","GLOBAL",18)
THEN RESPONSE #100
  ActionOverride("tent",CreateItem("amul28",0,0,0))
  SetGlobal("fl11t17","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("tent")
  Global("fl11t18","GLOBAL",18)
THEN RESPONSE #100
  ActionOverride("tent",CreateItem("brac24",0,0,0))
  SetGlobal("fl11t18","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("tent")
  Global("fl11t19","GLOBAL",18)
THEN RESPONSE #100
  ActionOverride("tent",CreateItem("helm24",0,0,0))
  SetGlobal("fl11t19","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("tent")
  Global("fl11t20","GLOBAL",18)
THEN RESPONSE #100
  ActionOverride("tent",CreateItem("helm25",0,0,0))
  SetGlobal("fl11t20","GLOBAL",-1)
  DestroySelf()
END
