
IF
  Exists("senill01")
  Global("fl11t01","GLOBAL",13)
THEN RESPONSE #100
  GiveItemCreate("blun30a","senill01",0,0,0)
  SetGlobal("fl11t01","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("senill01")
  Global("fl11t02","GLOBAL",13)
THEN RESPONSE #100
  GiveItemCreate("blun30b","senill01",0,0,0)
  SetGlobal("fl11t02","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("senill01")
  Global("fl11t03","GLOBAL",13)
THEN RESPONSE #100
  GiveItemCreate("brac22","senill01",0,0,0)
  SetGlobal("fl11t03","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("senill01")
  Global("fl11t04","GLOBAL",13)
THEN RESPONSE #100
  GiveItemCreate("figure01","senill01",1,0,0)
  SetGlobal("fl11t04","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("senill01")
  Global("fl11t05","GLOBAL",13)
THEN RESPONSE #100
  GiveItemCreate("quiver01","senill01",0,0,0)
  SetGlobal("fl11t05","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("senill01")
  Global("fl11t06","GLOBAL",13)
THEN RESPONSE #100
  GiveItemCreate("quiver02","senill01",0,0,0)
  SetGlobal("fl11t06","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("senill01")
  Global("fl11t07","GLOBAL",13)
THEN RESPONSE #100
  GiveItemCreate("quiver05","senill01",0,0,0)
  SetGlobal("fl11t07","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("senill01")
  Global("fl11t08","GLOBAL",13)
THEN RESPONSE #100
  GiveItemCreate("ring42","senill01",1,0,0)
  SetGlobal("fl11t08","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("senill01")
  Global("fl11t09","GLOBAL",13)
THEN RESPONSE #100
  GiveItemCreate("ring46","senill01",0,0,0)
  SetGlobal("fl11t09","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("senill01")
  Global("fl11t10","GLOBAL",13)
THEN RESPONSE #100
  GiveItemCreate("rods06","senill01",10,0,0)
  SetGlobal("fl11t10","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("senill01")
  Global("fl11t11","GLOBAL",13)
THEN RESPONSE #100
  GiveItemCreate("tome01","senill01",1,0,0)
  SetGlobal("fl11t11","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("senill01")
  Global("fl11t12","GLOBAL",13)
THEN RESPONSE #100
  GiveItemCreate("wand18","senill01",6,5,0)
  SetGlobal("fl11t12","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("senill01")
  Global("fl11t13","GLOBAL",13)
THEN RESPONSE #100
  GiveItemCreate("wand18","senill01",6,5,0)
  SetGlobal("fl11t13","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("senill01")
  Global("fl11t14","GLOBAL",13)
THEN RESPONSE #100
  GiveItemCreate("wand19","senill01",1,0,0)
  SetGlobal("fl11t14","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("senill01")
  Global("fl11t15","GLOBAL",13)
THEN RESPONSE #100
  GiveItemCreate("wand19","senill01",1,0,0)
  SetGlobal("fl11t15","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("senill01")
  Global("fl11t16","GLOBAL",13)
THEN RESPONSE #100
  GiveItemCreate("helm23","senill01",0,0,0)
  SetGlobal("fl11t16","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("senill01")
  Global("fl11t17","GLOBAL",13)
THEN RESPONSE #100
  GiveItemCreate("amul28","senill01",0,0,0)
  SetGlobal("fl11t17","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("senill01")
  Global("fl11t18","GLOBAL",13)
THEN RESPONSE #100
  GiveItemCreate("brac24","senill01",0,0,0)
  SetGlobal("fl11t18","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("senill01")
  Global("fl11t19","GLOBAL",13)
THEN RESPONSE #100
  GiveItemCreate("helm24","senill01",0,0,0)
  SetGlobal("fl11t19","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("senill01")
  Global("fl11t20","GLOBAL",13)
THEN RESPONSE #100
  GiveItemCreate("helm25","senill01",0,0,0)
  SetGlobal("fl11t20","GLOBAL",-1)
  DestroySelf()
END
