
IF
  Exists("amtgen01")
  Global("fl11t01","GLOBAL",15)
THEN RESPONSE #100
  GiveItemCreate("blun30a","amtgen01",0,0,0)
  SetGlobal("fl11t01","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("amtgen01")
  Global("fl11t02","GLOBAL",15)
THEN RESPONSE #100
  GiveItemCreate("blun30b","amtgen01",0,0,0)
  SetGlobal("fl11t02","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("amtgen01")
  Global("fl11t03","GLOBAL",15)
THEN RESPONSE #100
  GiveItemCreate("brac22","amtgen01",0,0,0)
  SetGlobal("fl11t03","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("amtgen01")
  Global("fl11t04","GLOBAL",15)
THEN RESPONSE #100
  GiveItemCreate("figure01","amtgen01",1,0,0)
  SetGlobal("fl11t04","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("amtgen01")
  Global("fl11t05","GLOBAL",15)
THEN RESPONSE #100
  GiveItemCreate("quiver01","amtgen01",0,0,0)
  SetGlobal("fl11t05","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("amtgen01")
  Global("fl11t06","GLOBAL",15)
THEN RESPONSE #100
  GiveItemCreate("quiver02","amtgen01",0,0,0)
  SetGlobal("fl11t06","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("amtgen01")
  Global("fl11t07","GLOBAL",15)
THEN RESPONSE #100
  GiveItemCreate("quiver05","amtgen01",0,0,0)
  SetGlobal("fl11t07","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("amtgen01")
  Global("fl11t08","GLOBAL",15)
THEN RESPONSE #100
  GiveItemCreate("ring42","amtgen01",1,0,0)
  SetGlobal("fl11t08","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("amtgen01")
  Global("fl11t09","GLOBAL",15)
THEN RESPONSE #100
  GiveItemCreate("ring46","amtgen01",0,0,0)
  SetGlobal("fl11t09","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("amtgen01")
  Global("fl11t10","GLOBAL",15)
THEN RESPONSE #100
  GiveItemCreate("rods06","amtgen01",10,0,0)
  SetGlobal("fl11t10","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("amtgen01")
  Global("fl11t11","GLOBAL",15)
THEN RESPONSE #100
  GiveItemCreate("tome01","amtgen01",1,0,0)
  SetGlobal("fl11t11","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("amtgen01")
  Global("fl11t12","GLOBAL",15)
THEN RESPONSE #100
  GiveItemCreate("wand18","amtgen01",6,5,0)
  SetGlobal("fl11t12","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("amtgen01")
  Global("fl11t13","GLOBAL",15)
THEN RESPONSE #100
  GiveItemCreate("wand18","amtgen01",6,5,0)
  SetGlobal("fl11t13","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("amtgen01")
  Global("fl11t14","GLOBAL",15)
THEN RESPONSE #100
  GiveItemCreate("wand19","amtgen01",1,0,0)
  SetGlobal("fl11t14","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("amtgen01")
  Global("fl11t15","GLOBAL",15)
THEN RESPONSE #100
  GiveItemCreate("wand19","amtgen01",1,0,0)
  SetGlobal("fl11t15","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("amtgen01")
  Global("fl11t16","GLOBAL",15)
THEN RESPONSE #100
  GiveItemCreate("helm23","amtgen01",0,0,0)
  SetGlobal("fl11t16","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("amtgen01")
  Global("fl11t17","GLOBAL",15)
THEN RESPONSE #100
  GiveItemCreate("amul28","amtgen01",0,0,0)
  SetGlobal("fl11t17","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("amtgen01")
  Global("fl11t18","GLOBAL",15)
THEN RESPONSE #100
  GiveItemCreate("brac24","amtgen01",0,0,0)
  SetGlobal("fl11t18","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("amtgen01")
  Global("fl11t19","GLOBAL",15)
THEN RESPONSE #100
  GiveItemCreate("helm24","amtgen01",0,0,0)
  SetGlobal("fl11t19","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("amtgen01")
  Global("fl11t20","GLOBAL",15)
THEN RESPONSE #100
  GiveItemCreate("helm25","amtgen01",0,0,0)
  SetGlobal("fl11t20","GLOBAL",-1)
  DestroySelf()
END
