
IF
  Exists("AMARCH01")
  Global("fl11t01","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("blun30a","AMARCH01",0,0,0)
  SetGlobal("fl11t01","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("AMARCH01")
  Global("fl11t02","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("blun30b","AMARCH01",0,0,0)
  SetGlobal("fl11t02","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("AMARCH01")
  Global("fl11t03","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("brac22","AMARCH01",0,0,0)
  SetGlobal("fl11t03","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("AMARCH01")
  Global("fl11t04","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("figure01","AMARCH01",1,0,0)
  SetGlobal("fl11t04","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("AMARCH01")
  Global("fl11t05","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("quiver01","AMARCH01",0,0,0)
  SetGlobal("fl11t05","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("AMARCH01")
  Global("fl11t06","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("quiver02","AMARCH01",0,0,0)
  SetGlobal("fl11t06","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("AMARCH01")
  Global("fl11t07","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("quiver05","AMARCH01",0,0,0)
  SetGlobal("fl11t07","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("AMARCH01")
  Global("fl11t08","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("ring42","AMARCH01",1,0,0)
  SetGlobal("fl11t08","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("AMARCH01")
  Global("fl11t09","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("ring46","AMARCH01",0,0,0)
  SetGlobal("fl11t09","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("AMARCH01")
  Global("fl11t10","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("rods06","AMARCH01",10,0,0)
  SetGlobal("fl11t10","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("AMARCH01")
  Global("fl11t11","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("tome01","AMARCH01",1,0,0)
  SetGlobal("fl11t11","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("AMARCH01")
  Global("fl11t12","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("wand18","AMARCH01",6,5,0)
  SetGlobal("fl11t12","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("AMARCH01")
  Global("fl11t13","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("wand18","AMARCH01",6,5,0)
  SetGlobal("fl11t13","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("AMARCH01")
  Global("fl11t14","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("wand19","AMARCH01",1,0,0)
  SetGlobal("fl11t14","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("AMARCH01")
  Global("fl11t15","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("wand19","AMARCH01",1,0,0)
  SetGlobal("fl11t15","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("AMARCH01")
  Global("fl11t16","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("helm23","AMARCH01",0,0,0)
  SetGlobal("fl11t16","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("AMARCH01")
  Global("fl11t17","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("amul28","AMARCH01",0,0,0)
  SetGlobal("fl11t17","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("AMARCH01")
  Global("fl11t18","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("brac24","AMARCH01",0,0,0)
  SetGlobal("fl11t18","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("AMARCH01")
  Global("fl11t19","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("helm24","AMARCH01",0,0,0)
  SetGlobal("fl11t19","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("AMARCH01")
  Global("fl11t20","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("helm25","AMARCH01",0,0,0)
  SetGlobal("fl11t20","GLOBAL",-1)
  DestroySelf()
END
