
IF
  Exists("elemimix")
  Global("fl11t01","GLOBAL",17)
THEN RESPONSE #100
  GiveItemCreate("blun30a","elemimix",0,0,0)
  SetGlobal("fl11t01","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("elemimix")
  Global("fl11t02","GLOBAL",17)
THEN RESPONSE #100
  GiveItemCreate("blun30b","elemimix",0,0,0)
  SetGlobal("fl11t02","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("elemimix")
  Global("fl11t03","GLOBAL",17)
THEN RESPONSE #100
  GiveItemCreate("brac22","elemimix",0,0,0)
  SetGlobal("fl11t03","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("elemimix")
  Global("fl11t04","GLOBAL",17)
THEN RESPONSE #100
  GiveItemCreate("figure01","elemimix",1,0,0)
  SetGlobal("fl11t04","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("elemimix")
  Global("fl11t05","GLOBAL",17)
THEN RESPONSE #100
  GiveItemCreate("quiver01","elemimix",0,0,0)
  SetGlobal("fl11t05","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("elemimix")
  Global("fl11t06","GLOBAL",17)
THEN RESPONSE #100
  GiveItemCreate("quiver02","elemimix",0,0,0)
  SetGlobal("fl11t06","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("elemimix")
  Global("fl11t07","GLOBAL",17)
THEN RESPONSE #100
  GiveItemCreate("quiver05","elemimix",0,0,0)
  SetGlobal("fl11t07","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("elemimix")
  Global("fl11t08","GLOBAL",17)
THEN RESPONSE #100
  GiveItemCreate("ring42","elemimix",1,0,0)
  SetGlobal("fl11t08","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("elemimix")
  Global("fl11t09","GLOBAL",17)
THEN RESPONSE #100
  GiveItemCreate("ring46","elemimix",0,0,0)
  SetGlobal("fl11t09","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("elemimix")
  Global("fl11t10","GLOBAL",17)
THEN RESPONSE #100
  GiveItemCreate("rods06","elemimix",10,0,0)
  SetGlobal("fl11t10","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("elemimix")
  Global("fl11t11","GLOBAL",17)
THEN RESPONSE #100
  GiveItemCreate("tome01","elemimix",1,0,0)
  SetGlobal("fl11t11","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("elemimix")
  Global("fl11t12","GLOBAL",17)
THEN RESPONSE #100
  GiveItemCreate("wand18","elemimix",6,5,0)
  SetGlobal("fl11t12","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("elemimix")
  Global("fl11t13","GLOBAL",17)
THEN RESPONSE #100
  GiveItemCreate("wand18","elemimix",6,5,0)
  SetGlobal("fl11t13","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("elemimix")
  Global("fl11t14","GLOBAL",17)
THEN RESPONSE #100
  GiveItemCreate("wand19","elemimix",1,0,0)
  SetGlobal("fl11t14","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("elemimix")
  Global("fl11t15","GLOBAL",17)
THEN RESPONSE #100
  GiveItemCreate("wand19","elemimix",1,0,0)
  SetGlobal("fl11t15","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("elemimix")
  Global("fl11t16","GLOBAL",17)
THEN RESPONSE #100
  GiveItemCreate("helm23","elemimix",0,0,0)
  SetGlobal("fl11t16","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("elemimix")
  Global("fl11t17","GLOBAL",17)
THEN RESPONSE #100
  GiveItemCreate("amul28","elemimix",0,0,0)
  SetGlobal("fl11t17","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("elemimix")
  Global("fl11t18","GLOBAL",17)
THEN RESPONSE #100
  GiveItemCreate("brac24","elemimix",0,0,0)
  SetGlobal("fl11t18","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("elemimix")
  Global("fl11t19","GLOBAL",17)
THEN RESPONSE #100
  GiveItemCreate("helm24","elemimix",0,0,0)
  SetGlobal("fl11t19","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("elemimix")
  Global("fl11t20","GLOBAL",17)
THEN RESPONSE #100
  GiveItemCreate("helm25","elemimix",0,0,0)
  SetGlobal("fl11t20","GLOBAL",-1)
  DestroySelf()
END
