
IF
  Exists("gorgoli")
  Global("fl12t01","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("compon01","gorgoli",1,0,0)
  SetGlobal("fl12t01","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("gorgoli")
  Global("fl12t02","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("compon02","gorgoli",0,0,0)
  SetGlobal("fl12t02","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("gorgoli")
  Global("fl12t03","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("compon03","gorgoli",0,0,0)
  SetGlobal("fl12t03","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("gorgoli")
  Global("fl12t04","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("compon04","gorgoli",0,0,0)
  SetGlobal("fl12t04","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("gorgoli")
  Global("fl12t05","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("compon05","gorgoli",0,0,0)
  SetGlobal("fl12t05","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("gorgoli")
  Global("fl12t06","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("compon06","gorgoli",0,0,0)
  SetGlobal("fl12t06","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("gorgoli")
  Global("fl12t07","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("compon07","gorgoli",0,0,0)
  SetGlobal("fl12t07","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("gorgoli")
  Global("fl12t08","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("compon08","gorgoli",0,0,0)
  SetGlobal("fl12t08","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("gorgoli")
  Global("fl12t09","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("compon09","gorgoli",0,0,0)
  SetGlobal("fl12t09","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("gorgoli")
  Global("fl12t10","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("compon10","gorgoli",0,0,0)
  SetGlobal("fl12t10","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("gorgoli")
  Global("fl12t11","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("compon11","gorgoli",0,0,0)
  SetGlobal("fl12t11","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("gorgoli")
  Global("fl12t12","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("compon12","gorgoli",0,0,0)
  SetGlobal("fl12t12","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("gorgoli")
  Global("fl12t13","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("compon13","gorgoli",0,0,0)
  SetGlobal("fl12t13","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("gorgoli")
  Global("fl12t14","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("compon14","gorgoli",0,0,0)
  SetGlobal("fl12t14","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("gorgoli")
  Global("fl12t15","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("compon15","gorgoli",0,0,0)
  SetGlobal("fl12t15","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("gorgoli")
  Global("fl12t16","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("compon17","gorgoli",0,0,0)
  SetGlobal("fl12t16","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("gorgoli")
  Global("fl12t17","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("compon18","gorgoli",1,0,0)
  SetGlobal("fl12t17","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("gorgoli")
  Global("fl12t18","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("tome02a","gorgoli",0,0,0)
  SetGlobal("fl12t18","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("gorgoli")
  Global("fl12t19","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("tome03a","gorgoli",0,0,0)
  SetGlobal("fl12t19","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("gorgoli")
  Global("fl12t20","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("tome04a","gorgoli",1,0,0)
  SetGlobal("fl12t20","GLOBAL",-1)
  DestroySelf()
END
