
IF
  Exists("Abazigal")
  Global("fl12t01","GLOBAL",19)
THEN RESPONSE #100
  GiveItemCreate("compon01","Abazigal",1,0,0)
  SetGlobal("fl12t01","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Abazigal")
  Global("fl12t02","GLOBAL",19)
THEN RESPONSE #100
  GiveItemCreate("compon02","Abazigal",0,0,0)
  SetGlobal("fl12t02","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Abazigal")
  Global("fl12t03","GLOBAL",19)
THEN RESPONSE #100
  GiveItemCreate("compon03","Abazigal",0,0,0)
  SetGlobal("fl12t03","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Abazigal")
  Global("fl12t04","GLOBAL",19)
THEN RESPONSE #100
  GiveItemCreate("compon04","Abazigal",0,0,0)
  SetGlobal("fl12t04","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Abazigal")
  Global("fl12t05","GLOBAL",19)
THEN RESPONSE #100
  GiveItemCreate("compon05","Abazigal",0,0,0)
  SetGlobal("fl12t05","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Abazigal")
  Global("fl12t06","GLOBAL",19)
THEN RESPONSE #100
  GiveItemCreate("compon06","Abazigal",0,0,0)
  SetGlobal("fl12t06","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Abazigal")
  Global("fl12t07","GLOBAL",19)
THEN RESPONSE #100
  GiveItemCreate("compon07","Abazigal",0,0,0)
  SetGlobal("fl12t07","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Abazigal")
  Global("fl12t08","GLOBAL",19)
THEN RESPONSE #100
  GiveItemCreate("compon08","Abazigal",0,0,0)
  SetGlobal("fl12t08","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Abazigal")
  Global("fl12t09","GLOBAL",19)
THEN RESPONSE #100
  GiveItemCreate("compon09","Abazigal",0,0,0)
  SetGlobal("fl12t09","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Abazigal")
  Global("fl12t10","GLOBAL",19)
THEN RESPONSE #100
  GiveItemCreate("compon10","Abazigal",0,0,0)
  SetGlobal("fl12t10","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Abazigal")
  Global("fl12t11","GLOBAL",19)
THEN RESPONSE #100
  GiveItemCreate("compon11","Abazigal",0,0,0)
  SetGlobal("fl12t11","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Abazigal")
  Global("fl12t12","GLOBAL",19)
THEN RESPONSE #100
  GiveItemCreate("compon12","Abazigal",0,0,0)
  SetGlobal("fl12t12","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Abazigal")
  Global("fl12t13","GLOBAL",19)
THEN RESPONSE #100
  GiveItemCreate("compon13","Abazigal",0,0,0)
  SetGlobal("fl12t13","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Abazigal")
  Global("fl12t14","GLOBAL",19)
THEN RESPONSE #100
  GiveItemCreate("compon14","Abazigal",0,0,0)
  SetGlobal("fl12t14","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Abazigal")
  Global("fl12t15","GLOBAL",19)
THEN RESPONSE #100
  GiveItemCreate("compon15","Abazigal",0,0,0)
  SetGlobal("fl12t15","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Abazigal")
  Global("fl12t16","GLOBAL",19)
THEN RESPONSE #100
  GiveItemCreate("compon17","Abazigal",0,0,0)
  SetGlobal("fl12t16","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Abazigal")
  Global("fl12t17","GLOBAL",19)
THEN RESPONSE #100
  GiveItemCreate("compon18","Abazigal",1,0,0)
  SetGlobal("fl12t17","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Abazigal")
  Global("fl12t18","GLOBAL",19)
THEN RESPONSE #100
  GiveItemCreate("tome02a","Abazigal",0,0,0)
  SetGlobal("fl12t18","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Abazigal")
  Global("fl12t19","GLOBAL",19)
THEN RESPONSE #100
  GiveItemCreate("tome03a","Abazigal",0,0,0)
  SetGlobal("fl12t19","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Abazigal")
  Global("fl12t20","GLOBAL",19)
THEN RESPONSE #100
  GiveItemCreate("tome04a","Abazigal",1,0,0)
  SetGlobal("fl12t20","GLOBAL",-1)
  DestroySelf()
END
