
IF
  Exists("GorSal")
  Global("fl12t01","GLOBAL",17)
THEN RESPONSE #100
  GiveItemCreate("compon01","GorSal",1,0,0)
  SetGlobal("fl12t01","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("GorSal")
  Global("fl12t02","GLOBAL",17)
THEN RESPONSE #100
  GiveItemCreate("compon02","GorSal",0,0,0)
  SetGlobal("fl12t02","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("GorSal")
  Global("fl12t03","GLOBAL",17)
THEN RESPONSE #100
  GiveItemCreate("compon03","GorSal",0,0,0)
  SetGlobal("fl12t03","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("GorSal")
  Global("fl12t04","GLOBAL",17)
THEN RESPONSE #100
  GiveItemCreate("compon04","GorSal",0,0,0)
  SetGlobal("fl12t04","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("GorSal")
  Global("fl12t05","GLOBAL",17)
THEN RESPONSE #100
  GiveItemCreate("compon05","GorSal",0,0,0)
  SetGlobal("fl12t05","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("GorSal")
  Global("fl12t06","GLOBAL",17)
THEN RESPONSE #100
  GiveItemCreate("compon06","GorSal",0,0,0)
  SetGlobal("fl12t06","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("GorSal")
  Global("fl12t07","GLOBAL",17)
THEN RESPONSE #100
  GiveItemCreate("compon07","GorSal",0,0,0)
  SetGlobal("fl12t07","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("GorSal")
  Global("fl12t08","GLOBAL",17)
THEN RESPONSE #100
  GiveItemCreate("compon08","GorSal",0,0,0)
  SetGlobal("fl12t08","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("GorSal")
  Global("fl12t09","GLOBAL",17)
THEN RESPONSE #100
  GiveItemCreate("compon09","GorSal",0,0,0)
  SetGlobal("fl12t09","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("GorSal")
  Global("fl12t10","GLOBAL",17)
THEN RESPONSE #100
  GiveItemCreate("compon10","GorSal",0,0,0)
  SetGlobal("fl12t10","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("GorSal")
  Global("fl12t11","GLOBAL",17)
THEN RESPONSE #100
  GiveItemCreate("compon11","GorSal",0,0,0)
  SetGlobal("fl12t11","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("GorSal")
  Global("fl12t12","GLOBAL",17)
THEN RESPONSE #100
  GiveItemCreate("compon12","GorSal",0,0,0)
  SetGlobal("fl12t12","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("GorSal")
  Global("fl12t13","GLOBAL",17)
THEN RESPONSE #100
  GiveItemCreate("compon13","GorSal",0,0,0)
  SetGlobal("fl12t13","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("GorSal")
  Global("fl12t14","GLOBAL",17)
THEN RESPONSE #100
  GiveItemCreate("compon14","GorSal",0,0,0)
  SetGlobal("fl12t14","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("GorSal")
  Global("fl12t15","GLOBAL",17)
THEN RESPONSE #100
  GiveItemCreate("compon15","GorSal",0,0,0)
  SetGlobal("fl12t15","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("GorSal")
  Global("fl12t16","GLOBAL",17)
THEN RESPONSE #100
  GiveItemCreate("compon17","GorSal",0,0,0)
  SetGlobal("fl12t16","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("GorSal")
  Global("fl12t17","GLOBAL",17)
THEN RESPONSE #100
  GiveItemCreate("compon18","GorSal",1,0,0)
  SetGlobal("fl12t17","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("GorSal")
  Global("fl12t18","GLOBAL",17)
THEN RESPONSE #100
  GiveItemCreate("tome02a","GorSal",0,0,0)
  SetGlobal("fl12t18","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("GorSal")
  Global("fl12t19","GLOBAL",17)
THEN RESPONSE #100
  GiveItemCreate("tome03a","GorSal",0,0,0)
  SetGlobal("fl12t19","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("GorSal")
  Global("fl12t20","GLOBAL",17)
THEN RESPONSE #100
  GiveItemCreate("tome04a","GorSal",1,0,0)
  SetGlobal("fl12t20","GLOBAL",-1)
  DestroySelf()
END
