
IF
  Exists("amlich01")
  Global("fl12t01","GLOBAL",6)
THEN RESPONSE #100
  GiveItemCreate("compon01","amlich01",1,0,0)
  SetGlobal("fl12t01","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("amlich01")
  Global("fl12t02","GLOBAL",6)
THEN RESPONSE #100
  GiveItemCreate("compon02","amlich01",0,0,0)
  SetGlobal("fl12t02","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("amlich01")
  Global("fl12t03","GLOBAL",6)
THEN RESPONSE #100
  GiveItemCreate("compon03","amlich01",0,0,0)
  SetGlobal("fl12t03","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("amlich01")
  Global("fl12t04","GLOBAL",6)
THEN RESPONSE #100
  GiveItemCreate("compon04","amlich01",0,0,0)
  SetGlobal("fl12t04","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("amlich01")
  Global("fl12t05","GLOBAL",6)
THEN RESPONSE #100
  GiveItemCreate("compon05","amlich01",0,0,0)
  SetGlobal("fl12t05","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("amlich01")
  Global("fl12t06","GLOBAL",6)
THEN RESPONSE #100
  GiveItemCreate("compon06","amlich01",0,0,0)
  SetGlobal("fl12t06","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("amlich01")
  Global("fl12t07","GLOBAL",6)
THEN RESPONSE #100
  GiveItemCreate("compon07","amlich01",0,0,0)
  SetGlobal("fl12t07","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("amlich01")
  Global("fl12t08","GLOBAL",6)
THEN RESPONSE #100
  GiveItemCreate("compon08","amlich01",0,0,0)
  SetGlobal("fl12t08","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("amlich01")
  Global("fl12t09","GLOBAL",6)
THEN RESPONSE #100
  GiveItemCreate("compon09","amlich01",0,0,0)
  SetGlobal("fl12t09","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("amlich01")
  Global("fl12t10","GLOBAL",6)
THEN RESPONSE #100
  GiveItemCreate("compon10","amlich01",0,0,0)
  SetGlobal("fl12t10","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("amlich01")
  Global("fl12t11","GLOBAL",6)
THEN RESPONSE #100
  GiveItemCreate("compon11","amlich01",0,0,0)
  SetGlobal("fl12t11","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("amlich01")
  Global("fl12t12","GLOBAL",6)
THEN RESPONSE #100
  GiveItemCreate("compon12","amlich01",0,0,0)
  SetGlobal("fl12t12","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("amlich01")
  Global("fl12t13","GLOBAL",6)
THEN RESPONSE #100
  GiveItemCreate("compon13","amlich01",0,0,0)
  SetGlobal("fl12t13","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("amlich01")
  Global("fl12t14","GLOBAL",6)
THEN RESPONSE #100
  GiveItemCreate("compon14","amlich01",0,0,0)
  SetGlobal("fl12t14","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("amlich01")
  Global("fl12t15","GLOBAL",6)
THEN RESPONSE #100
  GiveItemCreate("compon15","amlich01",0,0,0)
  SetGlobal("fl12t15","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("amlich01")
  Global("fl12t16","GLOBAL",6)
THEN RESPONSE #100
  GiveItemCreate("compon17","amlich01",0,0,0)
  SetGlobal("fl12t16","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("amlich01")
  Global("fl12t17","GLOBAL",6)
THEN RESPONSE #100
  GiveItemCreate("compon18","amlich01",1,0,0)
  SetGlobal("fl12t17","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("amlich01")
  Global("fl12t18","GLOBAL",6)
THEN RESPONSE #100
  GiveItemCreate("tome02a","amlich01",0,0,0)
  SetGlobal("fl12t18","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("amlich01")
  Global("fl12t19","GLOBAL",6)
THEN RESPONSE #100
  GiveItemCreate("tome03a","amlich01",0,0,0)
  SetGlobal("fl12t19","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("amlich01")
  Global("fl12t20","GLOBAL",6)
THEN RESPONSE #100
  GiveItemCreate("tome04a","amlich01",1,0,0)
  SetGlobal("fl12t20","GLOBAL",-1)
  DestroySelf()
END
