
IF
  Exists("hgber01")
  Global("fl12t01","GLOBAL",5)
THEN RESPONSE #100
  GiveItemCreate("compon01","hgber01",1,0,0)
  SetGlobal("fl12t01","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("hgber01")
  Global("fl12t02","GLOBAL",5)
THEN RESPONSE #100
  GiveItemCreate("compon02","hgber01",0,0,0)
  SetGlobal("fl12t02","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("hgber01")
  Global("fl12t03","GLOBAL",5)
THEN RESPONSE #100
  GiveItemCreate("compon03","hgber01",0,0,0)
  SetGlobal("fl12t03","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("hgber01")
  Global("fl12t04","GLOBAL",5)
THEN RESPONSE #100
  GiveItemCreate("compon04","hgber01",0,0,0)
  SetGlobal("fl12t04","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("hgber01")
  Global("fl12t05","GLOBAL",5)
THEN RESPONSE #100
  GiveItemCreate("compon05","hgber01",0,0,0)
  SetGlobal("fl12t05","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("hgber01")
  Global("fl12t06","GLOBAL",5)
THEN RESPONSE #100
  GiveItemCreate("compon06","hgber01",0,0,0)
  SetGlobal("fl12t06","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("hgber01")
  Global("fl12t07","GLOBAL",5)
THEN RESPONSE #100
  GiveItemCreate("compon07","hgber01",0,0,0)
  SetGlobal("fl12t07","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("hgber01")
  Global("fl12t08","GLOBAL",5)
THEN RESPONSE #100
  GiveItemCreate("compon08","hgber01",0,0,0)
  SetGlobal("fl12t08","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("hgber01")
  Global("fl12t09","GLOBAL",5)
THEN RESPONSE #100
  GiveItemCreate("compon09","hgber01",0,0,0)
  SetGlobal("fl12t09","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("hgber01")
  Global("fl12t10","GLOBAL",5)
THEN RESPONSE #100
  GiveItemCreate("compon10","hgber01",0,0,0)
  SetGlobal("fl12t10","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("hgber01")
  Global("fl12t11","GLOBAL",5)
THEN RESPONSE #100
  GiveItemCreate("compon11","hgber01",0,0,0)
  SetGlobal("fl12t11","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("hgber01")
  Global("fl12t12","GLOBAL",5)
THEN RESPONSE #100
  GiveItemCreate("compon12","hgber01",0,0,0)
  SetGlobal("fl12t12","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("hgber01")
  Global("fl12t13","GLOBAL",5)
THEN RESPONSE #100
  GiveItemCreate("compon13","hgber01",0,0,0)
  SetGlobal("fl12t13","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("hgber01")
  Global("fl12t14","GLOBAL",5)
THEN RESPONSE #100
  GiveItemCreate("compon14","hgber01",0,0,0)
  SetGlobal("fl12t14","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("hgber01")
  Global("fl12t15","GLOBAL",5)
THEN RESPONSE #100
  GiveItemCreate("compon15","hgber01",0,0,0)
  SetGlobal("fl12t15","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("hgber01")
  Global("fl12t16","GLOBAL",5)
THEN RESPONSE #100
  GiveItemCreate("compon17","hgber01",0,0,0)
  SetGlobal("fl12t16","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("hgber01")
  Global("fl12t17","GLOBAL",5)
THEN RESPONSE #100
  GiveItemCreate("compon18","hgber01",1,0,0)
  SetGlobal("fl12t17","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("hgber01")
  Global("fl12t18","GLOBAL",5)
THEN RESPONSE #100
  GiveItemCreate("tome02a","hgber01",0,0,0)
  SetGlobal("fl12t18","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("hgber01")
  Global("fl12t19","GLOBAL",5)
THEN RESPONSE #100
  GiveItemCreate("tome03a","hgber01",0,0,0)
  SetGlobal("fl12t19","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("hgber01")
  Global("fl12t20","GLOBAL",5)
THEN RESPONSE #100
  GiveItemCreate("tome04a","hgber01",1,0,0)
  SetGlobal("fl12t20","GLOBAL",-1)
  DestroySelf()
END
