
IF
  Exists("GorGit")
  Global("fl12t01","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("compon01","GorGit",1,0,0)
  SetGlobal("fl12t01","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("GorGit")
  Global("fl12t02","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("compon02","GorGit",0,0,0)
  SetGlobal("fl12t02","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("GorGit")
  Global("fl12t03","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("compon03","GorGit",0,0,0)
  SetGlobal("fl12t03","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("GorGit")
  Global("fl12t04","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("compon04","GorGit",0,0,0)
  SetGlobal("fl12t04","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("GorGit")
  Global("fl12t05","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("compon05","GorGit",0,0,0)
  SetGlobal("fl12t05","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("GorGit")
  Global("fl12t06","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("compon06","GorGit",0,0,0)
  SetGlobal("fl12t06","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("GorGit")
  Global("fl12t07","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("compon07","GorGit",0,0,0)
  SetGlobal("fl12t07","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("GorGit")
  Global("fl12t08","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("compon08","GorGit",0,0,0)
  SetGlobal("fl12t08","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("GorGit")
  Global("fl12t09","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("compon09","GorGit",0,0,0)
  SetGlobal("fl12t09","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("GorGit")
  Global("fl12t10","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("compon10","GorGit",0,0,0)
  SetGlobal("fl12t10","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("GorGit")
  Global("fl12t11","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("compon11","GorGit",0,0,0)
  SetGlobal("fl12t11","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("GorGit")
  Global("fl12t12","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("compon12","GorGit",0,0,0)
  SetGlobal("fl12t12","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("GorGit")
  Global("fl12t13","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("compon13","GorGit",0,0,0)
  SetGlobal("fl12t13","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("GorGit")
  Global("fl12t14","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("compon14","GorGit",0,0,0)
  SetGlobal("fl12t14","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("GorGit")
  Global("fl12t15","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("compon15","GorGit",0,0,0)
  SetGlobal("fl12t15","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("GorGit")
  Global("fl12t16","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("compon17","GorGit",0,0,0)
  SetGlobal("fl12t16","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("GorGit")
  Global("fl12t17","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("compon18","GorGit",1,0,0)
  SetGlobal("fl12t17","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("GorGit")
  Global("fl12t18","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("tome02a","GorGit",0,0,0)
  SetGlobal("fl12t18","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("GorGit")
  Global("fl12t19","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("tome03a","GorGit",0,0,0)
  SetGlobal("fl12t19","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("GorGit")
  Global("fl12t20","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("tome04a","GorGit",1,0,0)
  SetGlobal("fl12t20","GLOBAL",-1)
  DestroySelf()
END
