
IF
  Exists("senlich")
  Global("fl12t01","GLOBAL",8)
THEN RESPONSE #100
  GiveItemCreate("compon01","senlich",1,0,0)
  SetGlobal("fl12t01","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("senlich")
  Global("fl12t02","GLOBAL",8)
THEN RESPONSE #100
  GiveItemCreate("compon02","senlich",0,0,0)
  SetGlobal("fl12t02","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("senlich")
  Global("fl12t03","GLOBAL",8)
THEN RESPONSE #100
  GiveItemCreate("compon03","senlich",0,0,0)
  SetGlobal("fl12t03","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("senlich")
  Global("fl12t04","GLOBAL",8)
THEN RESPONSE #100
  GiveItemCreate("compon04","senlich",0,0,0)
  SetGlobal("fl12t04","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("senlich")
  Global("fl12t05","GLOBAL",8)
THEN RESPONSE #100
  GiveItemCreate("compon05","senlich",0,0,0)
  SetGlobal("fl12t05","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("senlich")
  Global("fl12t06","GLOBAL",8)
THEN RESPONSE #100
  GiveItemCreate("compon06","senlich",0,0,0)
  SetGlobal("fl12t06","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("senlich")
  Global("fl12t07","GLOBAL",8)
THEN RESPONSE #100
  GiveItemCreate("compon07","senlich",0,0,0)
  SetGlobal("fl12t07","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("senlich")
  Global("fl12t08","GLOBAL",8)
THEN RESPONSE #100
  GiveItemCreate("compon08","senlich",0,0,0)
  SetGlobal("fl12t08","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("senlich")
  Global("fl12t09","GLOBAL",8)
THEN RESPONSE #100
  GiveItemCreate("compon09","senlich",0,0,0)
  SetGlobal("fl12t09","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("senlich")
  Global("fl12t10","GLOBAL",8)
THEN RESPONSE #100
  GiveItemCreate("compon10","senlich",0,0,0)
  SetGlobal("fl12t10","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("senlich")
  Global("fl12t11","GLOBAL",8)
THEN RESPONSE #100
  GiveItemCreate("compon11","senlich",0,0,0)
  SetGlobal("fl12t11","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("senlich")
  Global("fl12t12","GLOBAL",8)
THEN RESPONSE #100
  GiveItemCreate("compon12","senlich",0,0,0)
  SetGlobal("fl12t12","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("senlich")
  Global("fl12t13","GLOBAL",8)
THEN RESPONSE #100
  GiveItemCreate("compon13","senlich",0,0,0)
  SetGlobal("fl12t13","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("senlich")
  Global("fl12t14","GLOBAL",8)
THEN RESPONSE #100
  GiveItemCreate("compon14","senlich",0,0,0)
  SetGlobal("fl12t14","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("senlich")
  Global("fl12t15","GLOBAL",8)
THEN RESPONSE #100
  GiveItemCreate("compon15","senlich",0,0,0)
  SetGlobal("fl12t15","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("senlich")
  Global("fl12t16","GLOBAL",8)
THEN RESPONSE #100
  GiveItemCreate("compon17","senlich",0,0,0)
  SetGlobal("fl12t16","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("senlich")
  Global("fl12t17","GLOBAL",8)
THEN RESPONSE #100
  GiveItemCreate("compon18","senlich",1,0,0)
  SetGlobal("fl12t17","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("senlich")
  Global("fl12t18","GLOBAL",8)
THEN RESPONSE #100
  GiveItemCreate("tome02a","senlich",0,0,0)
  SetGlobal("fl12t18","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("senlich")
  Global("fl12t19","GLOBAL",8)
THEN RESPONSE #100
  GiveItemCreate("tome03a","senlich",0,0,0)
  SetGlobal("fl12t19","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("senlich")
  Global("fl12t20","GLOBAL",8)
THEN RESPONSE #100
  GiveItemCreate("tome04a","senlich",1,0,0)
  SetGlobal("fl12t20","GLOBAL",-1)
  DestroySelf()
END
