
IF
  Exists("hgnya01")
  Global("fl12t01","GLOBAL",13)
THEN RESPONSE #100
  GiveItemCreate("compon01","hgnya01",1,0,0)
  SetGlobal("fl12t01","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("hgnya01")
  Global("fl12t02","GLOBAL",13)
THEN RESPONSE #100
  GiveItemCreate("compon02","hgnya01",0,0,0)
  SetGlobal("fl12t02","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("hgnya01")
  Global("fl12t03","GLOBAL",13)
THEN RESPONSE #100
  GiveItemCreate("compon03","hgnya01",0,0,0)
  SetGlobal("fl12t03","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("hgnya01")
  Global("fl12t04","GLOBAL",13)
THEN RESPONSE #100
  GiveItemCreate("compon04","hgnya01",0,0,0)
  SetGlobal("fl12t04","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("hgnya01")
  Global("fl12t05","GLOBAL",13)
THEN RESPONSE #100
  GiveItemCreate("compon05","hgnya01",0,0,0)
  SetGlobal("fl12t05","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("hgnya01")
  Global("fl12t06","GLOBAL",13)
THEN RESPONSE #100
  GiveItemCreate("compon06","hgnya01",0,0,0)
  SetGlobal("fl12t06","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("hgnya01")
  Global("fl12t07","GLOBAL",13)
THEN RESPONSE #100
  GiveItemCreate("compon07","hgnya01",0,0,0)
  SetGlobal("fl12t07","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("hgnya01")
  Global("fl12t08","GLOBAL",13)
THEN RESPONSE #100
  GiveItemCreate("compon08","hgnya01",0,0,0)
  SetGlobal("fl12t08","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("hgnya01")
  Global("fl12t09","GLOBAL",13)
THEN RESPONSE #100
  GiveItemCreate("compon09","hgnya01",0,0,0)
  SetGlobal("fl12t09","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("hgnya01")
  Global("fl12t10","GLOBAL",13)
THEN RESPONSE #100
  GiveItemCreate("compon10","hgnya01",0,0,0)
  SetGlobal("fl12t10","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("hgnya01")
  Global("fl12t11","GLOBAL",13)
THEN RESPONSE #100
  GiveItemCreate("compon11","hgnya01",0,0,0)
  SetGlobal("fl12t11","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("hgnya01")
  Global("fl12t12","GLOBAL",13)
THEN RESPONSE #100
  GiveItemCreate("compon12","hgnya01",0,0,0)
  SetGlobal("fl12t12","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("hgnya01")
  Global("fl12t13","GLOBAL",13)
THEN RESPONSE #100
  GiveItemCreate("compon13","hgnya01",0,0,0)
  SetGlobal("fl12t13","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("hgnya01")
  Global("fl12t14","GLOBAL",13)
THEN RESPONSE #100
  GiveItemCreate("compon14","hgnya01",0,0,0)
  SetGlobal("fl12t14","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("hgnya01")
  Global("fl12t15","GLOBAL",13)
THEN RESPONSE #100
  GiveItemCreate("compon15","hgnya01",0,0,0)
  SetGlobal("fl12t15","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("hgnya01")
  Global("fl12t16","GLOBAL",13)
THEN RESPONSE #100
  GiveItemCreate("compon17","hgnya01",0,0,0)
  SetGlobal("fl12t16","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("hgnya01")
  Global("fl12t17","GLOBAL",13)
THEN RESPONSE #100
  GiveItemCreate("compon18","hgnya01",1,0,0)
  SetGlobal("fl12t17","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("hgnya01")
  Global("fl12t18","GLOBAL",13)
THEN RESPONSE #100
  GiveItemCreate("tome02a","hgnya01",0,0,0)
  SetGlobal("fl12t18","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("hgnya01")
  Global("fl12t19","GLOBAL",13)
THEN RESPONSE #100
  GiveItemCreate("tome03a","hgnya01",0,0,0)
  SetGlobal("fl12t19","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("hgnya01")
  Global("fl12t20","GLOBAL",13)
THEN RESPONSE #100
  GiveItemCreate("tome04a","hgnya01",1,0,0)
  SetGlobal("fl12t20","GLOBAL",-1)
  DestroySelf()
END
