
IF
  Exists("Bazmonk")
  Global("fl12t01","GLOBAL",9)
THEN RESPONSE #100
  GiveItemCreate("compon01","Bazmonk",1,0,0)
  SetGlobal("fl12t01","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Bazmonk")
  Global("fl12t02","GLOBAL",9)
THEN RESPONSE #100
  GiveItemCreate("compon02","Bazmonk",0,0,0)
  SetGlobal("fl12t02","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Bazmonk")
  Global("fl12t03","GLOBAL",9)
THEN RESPONSE #100
  GiveItemCreate("compon03","Bazmonk",0,0,0)
  SetGlobal("fl12t03","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Bazmonk")
  Global("fl12t04","GLOBAL",9)
THEN RESPONSE #100
  GiveItemCreate("compon04","Bazmonk",0,0,0)
  SetGlobal("fl12t04","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Bazmonk")
  Global("fl12t05","GLOBAL",9)
THEN RESPONSE #100
  GiveItemCreate("compon05","Bazmonk",0,0,0)
  SetGlobal("fl12t05","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Bazmonk")
  Global("fl12t06","GLOBAL",9)
THEN RESPONSE #100
  GiveItemCreate("compon06","Bazmonk",0,0,0)
  SetGlobal("fl12t06","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Bazmonk")
  Global("fl12t07","GLOBAL",9)
THEN RESPONSE #100
  GiveItemCreate("compon07","Bazmonk",0,0,0)
  SetGlobal("fl12t07","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Bazmonk")
  Global("fl12t08","GLOBAL",9)
THEN RESPONSE #100
  GiveItemCreate("compon08","Bazmonk",0,0,0)
  SetGlobal("fl12t08","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Bazmonk")
  Global("fl12t09","GLOBAL",9)
THEN RESPONSE #100
  GiveItemCreate("compon09","Bazmonk",0,0,0)
  SetGlobal("fl12t09","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Bazmonk")
  Global("fl12t10","GLOBAL",9)
THEN RESPONSE #100
  GiveItemCreate("compon10","Bazmonk",0,0,0)
  SetGlobal("fl12t10","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Bazmonk")
  Global("fl12t11","GLOBAL",9)
THEN RESPONSE #100
  GiveItemCreate("compon11","Bazmonk",0,0,0)
  SetGlobal("fl12t11","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Bazmonk")
  Global("fl12t12","GLOBAL",9)
THEN RESPONSE #100
  GiveItemCreate("compon12","Bazmonk",0,0,0)
  SetGlobal("fl12t12","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Bazmonk")
  Global("fl12t13","GLOBAL",9)
THEN RESPONSE #100
  GiveItemCreate("compon13","Bazmonk",0,0,0)
  SetGlobal("fl12t13","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Bazmonk")
  Global("fl12t14","GLOBAL",9)
THEN RESPONSE #100
  GiveItemCreate("compon14","Bazmonk",0,0,0)
  SetGlobal("fl12t14","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Bazmonk")
  Global("fl12t15","GLOBAL",9)
THEN RESPONSE #100
  GiveItemCreate("compon15","Bazmonk",0,0,0)
  SetGlobal("fl12t15","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Bazmonk")
  Global("fl12t16","GLOBAL",9)
THEN RESPONSE #100
  GiveItemCreate("compon17","Bazmonk",0,0,0)
  SetGlobal("fl12t16","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Bazmonk")
  Global("fl12t17","GLOBAL",9)
THEN RESPONSE #100
  GiveItemCreate("compon18","Bazmonk",1,0,0)
  SetGlobal("fl12t17","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Bazmonk")
  Global("fl12t18","GLOBAL",9)
THEN RESPONSE #100
  GiveItemCreate("tome02a","Bazmonk",0,0,0)
  SetGlobal("fl12t18","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Bazmonk")
  Global("fl12t19","GLOBAL",9)
THEN RESPONSE #100
  GiveItemCreate("tome03a","Bazmonk",0,0,0)
  SetGlobal("fl12t19","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Bazmonk")
  Global("fl12t20","GLOBAL",9)
THEN RESPONSE #100
  GiveItemCreate("tome04a","Bazmonk",1,0,0)
  SetGlobal("fl12t20","GLOBAL",-1)
  DestroySelf()
END
