
IF
  Exists("shelf4")
  Global("fl13t01","GLOBAL",4)
THEN RESPONSE #100
  ActionOverride("shelf4",CreateItem("scrlb4",1,0,0))
  SetGlobal("fl13t01","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("shelf4")
  Global("fl13t02","GLOBAL",4)
THEN RESPONSE #100
  ActionOverride("shelf4",CreateItem("slng08",0,1,0))
  SetGlobal("fl13t02","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("shelf4")
  Global("fl13t03","GLOBAL",4)
THEN RESPONSE #100
  ActionOverride("shelf4",CreateItem("helm34",0,0,0))
  SetGlobal("fl13t03","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("shelf4")
  Global("fl13t04","GLOBAL",4)
THEN RESPONSE #100
  ActionOverride("shelf4",CreateItem("helm26",0,0,0))
  SetGlobal("fl13t04","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("shelf4")
  Global("fl13t05","GLOBAL",4)
THEN RESPONSE #100
  ActionOverride("shelf4",CreateItem("ring02",0,0,0))
  SetGlobal("fl13t05","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("shelf4")
  Global("fl13t06","GLOBAL",4)
THEN RESPONSE #100
  ActionOverride("shelf4",CreateItem("dagg23",0,0,0))
  SetGlobal("fl13t06","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("shelf4")
  Global("fl13t07","GLOBAL",4)
THEN RESPONSE #100
  ActionOverride("shelf4",CreateItem("dart08",0,0,0))
  SetGlobal("fl13t07","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("shelf4")
  Global("fl13t08","GLOBAL",4)
THEN RESPONSE #100
  ActionOverride("shelf4",CreateItem("staf23",0,0,0))
  SetGlobal("fl13t08","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("shelf4")
  Global("fl13t09","GLOBAL",4)
THEN RESPONSE #100
  ActionOverride("shelf4",CreateItem("boot12",2,0,0))
  SetGlobal("fl13t09","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("shelf4")
  Global("fl13t10","GLOBAL",4)
THEN RESPONSE #100
  ActionOverride("shelf4",CreateItem("wand18",5,5,0))
  SetGlobal("fl13t10","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("shelf4")
  Global("fl13t11","GLOBAL",4)
THEN RESPONSE #100
  ActionOverride("shelf4",CreateItem("wand18",5,5,0))
  SetGlobal("fl13t11","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("shelf4")
  Global("fl13t12","GLOBAL",4)
THEN RESPONSE #100
  ActionOverride("shelf4",CreateItem("helm31",0,0,0))
  SetGlobal("fl13t12","GLOBAL",-1)
  DestroySelf()
END
