
IF
  Exists("gormind")
  Global("fl13t01","GLOBAL",8)
THEN RESPONSE #100
  GiveItemCreate("scrlb4","gormind",1,0,0)
  SetGlobal("fl13t01","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("gormind")
  Global("fl13t02","GLOBAL",8)
THEN RESPONSE #100
  GiveItemCreate("slng08","gormind",0,1,0)
  SetGlobal("fl13t02","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("gormind")
  Global("fl13t03","GLOBAL",8)
THEN RESPONSE #100
  GiveItemCreate("helm34","gormind",0,0,0)
  SetGlobal("fl13t03","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("gormind")
  Global("fl13t04","GLOBAL",8)
THEN RESPONSE #100
  GiveItemCreate("helm26","gormind",0,0,0)
  SetGlobal("fl13t04","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("gormind")
  Global("fl13t05","GLOBAL",8)
THEN RESPONSE #100
  GiveItemCreate("ring02","gormind",0,0,0)
  SetGlobal("fl13t05","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("gormind")
  Global("fl13t06","GLOBAL",8)
THEN RESPONSE #100
  GiveItemCreate("dagg23","gormind",0,0,0)
  SetGlobal("fl13t06","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("gormind")
  Global("fl13t07","GLOBAL",8)
THEN RESPONSE #100
  GiveItemCreate("dart08","gormind",0,0,0)
  SetGlobal("fl13t07","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("gormind")
  Global("fl13t08","GLOBAL",8)
THEN RESPONSE #100
  GiveItemCreate("staf23","gormind",0,0,0)
  SetGlobal("fl13t08","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("gormind")
  Global("fl13t09","GLOBAL",8)
THEN RESPONSE #100
  GiveItemCreate("boot12","gormind",2,0,0)
  SetGlobal("fl13t09","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("gormind")
  Global("fl13t10","GLOBAL",8)
THEN RESPONSE #100
  GiveItemCreate("wand18","gormind",5,5,0)
  SetGlobal("fl13t10","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("gormind")
  Global("fl13t11","GLOBAL",8)
THEN RESPONSE #100
  GiveItemCreate("wand18","gormind",5,5,0)
  SetGlobal("fl13t11","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("gormind")
  Global("fl13t12","GLOBAL",8)
THEN RESPONSE #100
  GiveItemCreate("helm31","gormind",0,0,0)
  SetGlobal("fl13t12","GLOBAL",-1)
  DestroySelf()
END
