
IF
  Exists("gromnir")
  Global("fl13t01","GLOBAL",2)
THEN RESPONSE #100
  GiveItemCreate("scrlb4","gromnir",1,0,0)
  SetGlobal("fl13t01","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("gromnir")
  Global("fl13t02","GLOBAL",2)
THEN RESPONSE #100
  GiveItemCreate("slng08","gromnir",0,1,0)
  SetGlobal("fl13t02","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("gromnir")
  Global("fl13t03","GLOBAL",2)
THEN RESPONSE #100
  GiveItemCreate("helm34","gromnir",0,0,0)
  SetGlobal("fl13t03","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("gromnir")
  Global("fl13t04","GLOBAL",2)
THEN RESPONSE #100
  GiveItemCreate("helm26","gromnir",0,0,0)
  SetGlobal("fl13t04","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("gromnir")
  Global("fl13t05","GLOBAL",2)
THEN RESPONSE #100
  GiveItemCreate("ring02","gromnir",0,0,0)
  SetGlobal("fl13t05","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("gromnir")
  Global("fl13t06","GLOBAL",2)
THEN RESPONSE #100
  GiveItemCreate("dagg23","gromnir",0,0,0)
  SetGlobal("fl13t06","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("gromnir")
  Global("fl13t07","GLOBAL",2)
THEN RESPONSE #100
  GiveItemCreate("dart08","gromnir",0,0,0)
  SetGlobal("fl13t07","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("gromnir")
  Global("fl13t08","GLOBAL",2)
THEN RESPONSE #100
  GiveItemCreate("staf23","gromnir",0,0,0)
  SetGlobal("fl13t08","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("gromnir")
  Global("fl13t09","GLOBAL",2)
THEN RESPONSE #100
  GiveItemCreate("boot12","gromnir",2,0,0)
  SetGlobal("fl13t09","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("gromnir")
  Global("fl13t10","GLOBAL",2)
THEN RESPONSE #100
  GiveItemCreate("wand18","gromnir",5,5,0)
  SetGlobal("fl13t10","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("gromnir")
  Global("fl13t11","GLOBAL",2)
THEN RESPONSE #100
  GiveItemCreate("wand18","gromnir",5,5,0)
  SetGlobal("fl13t11","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("gromnir")
  Global("fl13t12","GLOBAL",2)
THEN RESPONSE #100
  GiveItemCreate("helm31","gromnir",0,0,0)
  SetGlobal("fl13t12","GLOBAL",-1)
  DestroySelf()
END
