
IF
  Exists("gorfirg")
  Global("fl13t01","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("scrlb4","gorfirg",1,0,0)
  SetGlobal("fl13t01","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("gorfirg")
  Global("fl13t02","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("slng08","gorfirg",0,1,0)
  SetGlobal("fl13t02","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("gorfirg")
  Global("fl13t03","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("helm34","gorfirg",0,0,0)
  SetGlobal("fl13t03","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("gorfirg")
  Global("fl13t04","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("helm26","gorfirg",0,0,0)
  SetGlobal("fl13t04","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("gorfirg")
  Global("fl13t05","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("ring02","gorfirg",0,0,0)
  SetGlobal("fl13t05","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("gorfirg")
  Global("fl13t06","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("dagg23","gorfirg",0,0,0)
  SetGlobal("fl13t06","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("gorfirg")
  Global("fl13t07","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("dart08","gorfirg",0,0,0)
  SetGlobal("fl13t07","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("gorfirg")
  Global("fl13t08","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("staf23","gorfirg",0,0,0)
  SetGlobal("fl13t08","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("gorfirg")
  Global("fl13t09","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("boot12","gorfirg",2,0,0)
  SetGlobal("fl13t09","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("gorfirg")
  Global("fl13t10","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("wand18","gorfirg",5,5,0)
  SetGlobal("fl13t10","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("gorfirg")
  Global("fl13t11","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("wand18","gorfirg",5,5,0)
  SetGlobal("fl13t11","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("gorfirg")
  Global("fl13t12","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("helm31","gorfirg",0,0,0)
  SetGlobal("fl13t12","GLOBAL",-1)
  DestroySelf()
END
