
IF
  Exists("gorlic01")
  Global("fl13t01","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("scrlb4","gorlic01",1,0,0)
  SetGlobal("fl13t01","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("gorlic01")
  Global("fl13t02","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("slng08","gorlic01",0,1,0)
  SetGlobal("fl13t02","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("gorlic01")
  Global("fl13t03","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("helm34","gorlic01",0,0,0)
  SetGlobal("fl13t03","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("gorlic01")
  Global("fl13t04","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("helm26","gorlic01",0,0,0)
  SetGlobal("fl13t04","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("gorlic01")
  Global("fl13t05","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("ring02","gorlic01",0,0,0)
  SetGlobal("fl13t05","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("gorlic01")
  Global("fl13t06","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("dagg23","gorlic01",0,0,0)
  SetGlobal("fl13t06","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("gorlic01")
  Global("fl13t07","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("dart08","gorlic01",0,0,0)
  SetGlobal("fl13t07","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("gorlic01")
  Global("fl13t08","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("staf23","gorlic01",0,0,0)
  SetGlobal("fl13t08","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("gorlic01")
  Global("fl13t09","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("boot12","gorlic01",2,0,0)
  SetGlobal("fl13t09","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("gorlic01")
  Global("fl13t10","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("wand18","gorlic01",5,5,0)
  SetGlobal("fl13t10","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("gorlic01")
  Global("fl13t11","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("wand18","gorlic01",5,5,0)
  SetGlobal("fl13t11","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("gorlic01")
  Global("fl13t12","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("helm31","gorlic01",0,0,0)
  SetGlobal("fl13t12","GLOBAL",-1)
  DestroySelf()
END
