
IF
  Exists("GorChr")
  Global("fl13t01","GLOBAL",7)
THEN RESPONSE #100
  GiveItemCreate("scrlb4","GorChr",1,0,0)
  SetGlobal("fl13t01","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("GorChr")
  Global("fl13t02","GLOBAL",7)
THEN RESPONSE #100
  GiveItemCreate("slng08","GorChr",0,1,0)
  SetGlobal("fl13t02","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("GorChr")
  Global("fl13t03","GLOBAL",7)
THEN RESPONSE #100
  GiveItemCreate("helm34","GorChr",0,0,0)
  SetGlobal("fl13t03","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("GorChr")
  Global("fl13t04","GLOBAL",7)
THEN RESPONSE #100
  GiveItemCreate("helm26","GorChr",0,0,0)
  SetGlobal("fl13t04","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("GorChr")
  Global("fl13t05","GLOBAL",7)
THEN RESPONSE #100
  GiveItemCreate("ring02","GorChr",0,0,0)
  SetGlobal("fl13t05","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("GorChr")
  Global("fl13t06","GLOBAL",7)
THEN RESPONSE #100
  GiveItemCreate("dagg23","GorChr",0,0,0)
  SetGlobal("fl13t06","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("GorChr")
  Global("fl13t07","GLOBAL",7)
THEN RESPONSE #100
  GiveItemCreate("dart08","GorChr",0,0,0)
  SetGlobal("fl13t07","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("GorChr")
  Global("fl13t08","GLOBAL",7)
THEN RESPONSE #100
  GiveItemCreate("staf23","GorChr",0,0,0)
  SetGlobal("fl13t08","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("GorChr")
  Global("fl13t09","GLOBAL",7)
THEN RESPONSE #100
  GiveItemCreate("boot12","GorChr",2,0,0)
  SetGlobal("fl13t09","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("GorChr")
  Global("fl13t10","GLOBAL",7)
THEN RESPONSE #100
  GiveItemCreate("wand18","GorChr",5,5,0)
  SetGlobal("fl13t10","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("GorChr")
  Global("fl13t11","GLOBAL",7)
THEN RESPONSE #100
  GiveItemCreate("wand18","GorChr",5,5,0)
  SetGlobal("fl13t11","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("GorChr")
  Global("fl13t12","GLOBAL",7)
THEN RESPONSE #100
  GiveItemCreate("helm31","GorChr",0,0,0)
  SetGlobal("fl13t12","GLOBAL",-1)
  DestroySelf()
END
