
IF
  Exists("bazeye01")
  Global("fl13t01","GLOBAL",3)
THEN RESPONSE #100
  GiveItemCreate("scrlb4","bazeye01",1,0,0)
  SetGlobal("fl13t01","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("bazeye01")
  Global("fl13t02","GLOBAL",3)
THEN RESPONSE #100
  GiveItemCreate("slng08","bazeye01",0,1,0)
  SetGlobal("fl13t02","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("bazeye01")
  Global("fl13t03","GLOBAL",3)
THEN RESPONSE #100
  GiveItemCreate("helm34","bazeye01",0,0,0)
  SetGlobal("fl13t03","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("bazeye01")
  Global("fl13t04","GLOBAL",3)
THEN RESPONSE #100
  GiveItemCreate("helm26","bazeye01",0,0,0)
  SetGlobal("fl13t04","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("bazeye01")
  Global("fl13t05","GLOBAL",3)
THEN RESPONSE #100
  GiveItemCreate("ring02","bazeye01",0,0,0)
  SetGlobal("fl13t05","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("bazeye01")
  Global("fl13t06","GLOBAL",3)
THEN RESPONSE #100
  GiveItemCreate("dagg23","bazeye01",0,0,0)
  SetGlobal("fl13t06","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("bazeye01")
  Global("fl13t07","GLOBAL",3)
THEN RESPONSE #100
  GiveItemCreate("dart08","bazeye01",0,0,0)
  SetGlobal("fl13t07","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("bazeye01")
  Global("fl13t08","GLOBAL",3)
THEN RESPONSE #100
  GiveItemCreate("staf23","bazeye01",0,0,0)
  SetGlobal("fl13t08","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("bazeye01")
  Global("fl13t09","GLOBAL",3)
THEN RESPONSE #100
  GiveItemCreate("boot12","bazeye01",2,0,0)
  SetGlobal("fl13t09","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("bazeye01")
  Global("fl13t10","GLOBAL",3)
THEN RESPONSE #100
  GiveItemCreate("wand18","bazeye01",5,5,0)
  SetGlobal("fl13t10","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("bazeye01")
  Global("fl13t11","GLOBAL",3)
THEN RESPONSE #100
  GiveItemCreate("wand18","bazeye01",5,5,0)
  SetGlobal("fl13t11","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("bazeye01")
  Global("fl13t12","GLOBAL",3)
THEN RESPONSE #100
  GiveItemCreate("helm31","bazeye01",0,0,0)
  SetGlobal("fl13t12","GLOBAL",-1)
  DestroySelf()
END
