
IF
  Exists("sewrak01")
  Global("fl1t01","GLOBAL",14)
THEN RESPONSE #100
  GiveItemCreate("amul16","sewrak01",0,0,0)
  SetGlobal("fl1t01","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("sewrak01")
  Global("fl1t02","GLOBAL",14)
THEN RESPONSE #100
  GiveItemCreate("boot02","sewrak01",0,0,0)
  SetGlobal("fl1t02","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("sewrak01")
  Global("fl1t03","GLOBAL",14)
THEN RESPONSE #100
  GiveItemCreate("belt09","sewrak01",1,0,0)
  SetGlobal("fl1t03","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("sewrak01")
  Global("fl1t04","GLOBAL",14)
THEN RESPONSE #100
  GiveItemCreate("misc3h","sewrak01",1,0,0)
  SetGlobal("fl1t04","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("sewrak01")
  Global("fl1t05","GLOBAL",14)
THEN RESPONSE #100
  GiveItemCreate("ring26","sewrak01",1,0,0)
  SetGlobal("fl1t05","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("sewrak01")
  Global("fl1t06","GLOBAL",14)
THEN RESPONSE #100
  GiveItemCreate("misc3l","sewrak01",3,0,0)
  SetGlobal("fl1t06","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("sewrak01")
  Global("fl1t07","GLOBAL",14)
THEN RESPONSE #100
  GiveItemCreate("blun23","sewrak01",0,0,0)
  SetGlobal("fl1t07","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("sewrak01")
  Global("fl1t08","GLOBAL",14)
THEN RESPONSE #100
  GiveItemCreate("brac09","sewrak01",0,0,0)
  SetGlobal("fl1t08","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("sewrak01")
  Global("fl1t09","GLOBAL",14)
THEN RESPONSE #100
  GiveItemCreate("rods05","sewrak01",0,0,0)
  SetGlobal("fl1t09","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("sewrak01")
  Global("fl1t10","GLOBAL",14)
THEN RESPONSE #100
  GiveItemCreate("misc3i","sewrak01",1,0,0)
  SetGlobal("fl1t10","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("sewrak01")
  Global("fl1t11","GLOBAL",14)
THEN RESPONSE #100
  GiveItemCreate("ring35","sewrak01",0,0,0)
  SetGlobal("fl1t11","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("sewrak01")
  Global("fl1t12","GLOBAL",14)
THEN RESPONSE #100
  GiveItemCreate("scrl16","sewrak01",1,0,0)
  SetGlobal("fl1t12","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("sewrak01")
  Global("fl1t13","GLOBAL",14)
THEN RESPONSE #100
  GiveItemCreate("xbow03","sewrak01",0,0,0)
  SetGlobal("fl1t13","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("sewrak01")
  Global("fl1t14","GLOBAL",14)
THEN RESPONSE #100
  GiveItemCreate("leat06","sewrak01",0,0,0)
  SetGlobal("fl1t14","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("sewrak01")
  Global("fl1t15","GLOBAL",14)
THEN RESPONSE #100
  GiveItemCreate("ring36","sewrak01",0,0,0)
  SetGlobal("fl1t15","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("sewrak01")
  Global("fl1t16","GLOBAL",14)
THEN RESPONSE #100
  GiveItemCreate("staf10","sewrak01",0,10,0)
  SetGlobal("fl1t16","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("sewrak01")
  Global("fl1t17","GLOBAL",14)
THEN RESPONSE #100
  GiveItemCreate("misc3p","sewrak01",3,0,0)
  SetGlobal("fl1t17","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("sewrak01")
  Global("fl1t18","GLOBAL",14)
THEN RESPONSE #100
  GiveItemCreate("sper03","sewrak01",0,0,0)
  SetGlobal("fl1t18","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("sewrak01")
  Global("fl1t19","GLOBAL",14)
THEN RESPONSE #100
  GiveItemCreate("ring30","sewrak01",1,0,0)
  SetGlobal("fl1t19","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("sewrak01")
  Global("fl1t20","GLOBAL",14)
THEN RESPONSE #100
  GiveItemCreate("boot01","sewrak01",0,0,0)
  SetGlobal("fl1t20","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("sewrak01")
  Global("fl1t21","GLOBAL",14)
THEN RESPONSE #100
  GiveItemCreate("brac04","sewrak01",0,0,0)
  SetGlobal("fl1t21","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("sewrak01")
  Global("fl1t22","GLOBAL",14)
THEN RESPONSE #100
  GiveItemCreate("brac17","sewrak01",0,0,0)
  SetGlobal("fl1t22","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("sewrak01")
  Global("fl1t23","GLOBAL",14)
THEN RESPONSE #100
  GiveItemCreate("helm18","sewrak01",0,0,0)
  SetGlobal("fl1t23","GLOBAL",-1)
  DestroySelf()
END
