
IF
  Exists("pbhunt03")
  Global("fl1t01","GLOBAL",20)
THEN RESPONSE #100
  GiveItemCreate("amul16","pbhunt03",0,0,0)
  SetGlobal("fl1t01","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("pbhunt05")
  Global("fl1t02","GLOBAL",20)
THEN RESPONSE #100
  GiveItemCreate("boot02","pbhunt05",0,0,0)
  SetGlobal("fl1t02","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("pbhunt05")
  Global("fl1t03","GLOBAL",20)
THEN RESPONSE #100
  GiveItemCreate("belt09","pbhunt05",1,0,0)
  SetGlobal("fl1t03","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("pbhunt03")
  Global("fl1t04","GLOBAL",20)
THEN RESPONSE #100
  GiveItemCreate("misc3h","pbhunt03",1,0,0)
  SetGlobal("fl1t04","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("pbhunt01")
  Global("fl1t05","GLOBAL",20)
THEN RESPONSE #100
  GiveItemCreate("ring26","pbhunt01",1,0,0)
  SetGlobal("fl1t05","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("pbhunt01")
  Global("fl1t06","GLOBAL",20)
THEN RESPONSE #100
  GiveItemCreate("misc3l","pbhunt01",3,0,0)
  SetGlobal("fl1t06","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("pbhunt01")
  Global("fl1t07","GLOBAL",20)
THEN RESPONSE #100
  GiveItemCreate("blun23","pbhunt01",0,0,0)
  SetGlobal("fl1t07","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("pbhunt05")
  Global("fl1t08","GLOBAL",20)
THEN RESPONSE #100
  GiveItemCreate("brac09","pbhunt05",0,0,0)
  SetGlobal("fl1t08","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("pbhunt04")
  Global("fl1t09","GLOBAL",20)
THEN RESPONSE #100
  GiveItemCreate("rods05","pbhunt04",0,0,0)
  SetGlobal("fl1t09","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("pbhunt05")
  Global("fl1t10","GLOBAL",20)
THEN RESPONSE #100
  GiveItemCreate("misc3i","pbhunt05",1,0,0)
  SetGlobal("fl1t10","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("pbhunt05")
  Global("fl1t11","GLOBAL",20)
THEN RESPONSE #100
  GiveItemCreate("ring35","pbhunt05",0,0,0)
  SetGlobal("fl1t11","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("pbhunt04")
  Global("fl1t12","GLOBAL",20)
THEN RESPONSE #100
  GiveItemCreate("scrl16","pbhunt04",1,0,0)
  SetGlobal("fl1t12","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("pbhunt05")
  Global("fl1t13","GLOBAL",20)
THEN RESPONSE #100
  GiveItemCreate("xbow03","pbhunt05",0,0,0)
  SetGlobal("fl1t13","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("pbhunt03")
  Global("fl1t14","GLOBAL",20)
THEN RESPONSE #100
  GiveItemCreate("leat06","pbhunt03",0,0,0)
  SetGlobal("fl1t14","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("pbhunt04")
  Global("fl1t15","GLOBAL",20)
THEN RESPONSE #100
  GiveItemCreate("ring36","pbhunt04",0,0,0)
  SetGlobal("fl1t15","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("pbhunt04")
  Global("fl1t16","GLOBAL",20)
THEN RESPONSE #100
  GiveItemCreate("staf10","pbhunt04",0,10,0)
  SetGlobal("fl1t16","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("pbhunt04")
  Global("fl1t17","GLOBAL",20)
THEN RESPONSE #100
  GiveItemCreate("misc3p","pbhunt04",3,0,0)
  SetGlobal("fl1t17","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("pbhunt03")
  Global("fl1t18","GLOBAL",20)
THEN RESPONSE #100
  GiveItemCreate("sper03","pbhunt03",0,0,0)
  SetGlobal("fl1t18","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("pbhunt04")
  Global("fl1t19","GLOBAL",20)
THEN RESPONSE #100
  GiveItemCreate("ring30","pbhunt04",1,0,0)
  SetGlobal("fl1t19","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("pbhunt03")
  Global("fl1t20","GLOBAL",20)
THEN RESPONSE #100
  GiveItemCreate("boot01","pbhunt03",0,0,0)
  SetGlobal("fl1t20","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("pbhunt03")
  Global("fl1t21","GLOBAL",20)
THEN RESPONSE #100
  GiveItemCreate("brac04","pbhunt03",0,0,0)
  SetGlobal("fl1t21","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("pbhunt05")
  Global("fl1t22","GLOBAL",20)
THEN RESPONSE #100
  GiveItemCreate("brac17","pbhunt05",0,0,0)
  SetGlobal("fl1t22","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("pbhunt01")
  Global("fl1t23","GLOBAL",20)
THEN RESPONSE #100
  GiveItemCreate("helm18","pbhunt01",0,0,0)
  SetGlobal("fl1t23","GLOBAL",-1)
  DestroySelf()
END
