
IF
  Exists("beast")
  Global("fl1t01","GLOBAL",15)
THEN RESPONSE #100
  GiveItemCreate("amul16","beast",0,0,0)
  SetGlobal("fl1t01","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("beast")
  Global("fl1t02","GLOBAL",15)
THEN RESPONSE #100
  GiveItemCreate("boot02","beast",0,0,0)
  SetGlobal("fl1t02","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("beast")
  Global("fl1t03","GLOBAL",15)
THEN RESPONSE #100
  GiveItemCreate("belt09","beast",1,0,0)
  SetGlobal("fl1t03","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("beast")
  Global("fl1t04","GLOBAL",15)
THEN RESPONSE #100
  GiveItemCreate("misc3h","beast",1,0,0)
  SetGlobal("fl1t04","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("beast")
  Global("fl1t05","GLOBAL",15)
THEN RESPONSE #100
  GiveItemCreate("ring26","beast",1,0,0)
  SetGlobal("fl1t05","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("beast")
  Global("fl1t06","GLOBAL",15)
THEN RESPONSE #100
  GiveItemCreate("misc3l","beast",3,0,0)
  SetGlobal("fl1t06","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("beast")
  Global("fl1t07","GLOBAL",15)
THEN RESPONSE #100
  GiveItemCreate("blun23","beast",0,0,0)
  SetGlobal("fl1t07","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("beast")
  Global("fl1t08","GLOBAL",15)
THEN RESPONSE #100
  GiveItemCreate("brac09","beast",0,0,0)
  SetGlobal("fl1t08","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("beast")
  Global("fl1t09","GLOBAL",15)
THEN RESPONSE #100
  GiveItemCreate("rods05","beast",0,0,0)
  SetGlobal("fl1t09","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("beast")
  Global("fl1t10","GLOBAL",15)
THEN RESPONSE #100
  GiveItemCreate("misc3i","beast",1,0,0)
  SetGlobal("fl1t10","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("beast")
  Global("fl1t11","GLOBAL",15)
THEN RESPONSE #100
  GiveItemCreate("ring35","beast",0,0,0)
  SetGlobal("fl1t11","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("beast")
  Global("fl1t12","GLOBAL",15)
THEN RESPONSE #100
  GiveItemCreate("scrl16","beast",1,0,0)
  SetGlobal("fl1t12","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("beast")
  Global("fl1t13","GLOBAL",15)
THEN RESPONSE #100
  GiveItemCreate("xbow03","beast",0,0,0)
  SetGlobal("fl1t13","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("beast")
  Global("fl1t14","GLOBAL",15)
THEN RESPONSE #100
  GiveItemCreate("leat06","beast",0,0,0)
  SetGlobal("fl1t14","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("beast")
  Global("fl1t15","GLOBAL",15)
THEN RESPONSE #100
  GiveItemCreate("ring36","beast",0,0,0)
  SetGlobal("fl1t15","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("beast")
  Global("fl1t16","GLOBAL",15)
THEN RESPONSE #100
  GiveItemCreate("staf10","beast",0,10,0)
  SetGlobal("fl1t16","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("beast")
  Global("fl1t17","GLOBAL",15)
THEN RESPONSE #100
  GiveItemCreate("misc3p","beast",3,0,0)
  SetGlobal("fl1t17","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("beast")
  Global("fl1t18","GLOBAL",15)
THEN RESPONSE #100
  GiveItemCreate("sper03","beast",0,0,0)
  SetGlobal("fl1t18","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("beast")
  Global("fl1t19","GLOBAL",15)
THEN RESPONSE #100
  GiveItemCreate("ring30","beast",1,0,0)
  SetGlobal("fl1t19","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("beast")
  Global("fl1t20","GLOBAL",15)
THEN RESPONSE #100
  GiveItemCreate("boot01","beast",0,0,0)
  SetGlobal("fl1t20","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("beast")
  Global("fl1t21","GLOBAL",15)
THEN RESPONSE #100
  GiveItemCreate("brac04","beast",0,0,0)
  SetGlobal("fl1t21","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("beast")
  Global("fl1t22","GLOBAL",15)
THEN RESPONSE #100
  GiveItemCreate("brac17","beast",0,0,0)
  SetGlobal("fl1t22","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("beast")
  Global("fl1t23","GLOBAL",15)
THEN RESPONSE #100
  GiveItemCreate("helm18","beast",0,0,0)
  SetGlobal("fl1t23","GLOBAL",-1)
  DestroySelf()
END
