
IF
  Exists("Gaal")
  Global("fl1t01","GLOBAL",3)
THEN RESPONSE #100
  GiveItemCreate("amul16","Gaal",0,0,0)
  SetGlobal("fl1t01","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Gaal")
  Global("fl1t02","GLOBAL",3)
THEN RESPONSE #100
  GiveItemCreate("boot02","Gaal",0,0,0)
  SetGlobal("fl1t02","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Gaal")
  Global("fl1t03","GLOBAL",3)
THEN RESPONSE #100
  GiveItemCreate("belt09","Gaal",1,0,0)
  SetGlobal("fl1t03","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Gaal")
  Global("fl1t04","GLOBAL",3)
THEN RESPONSE #100
  GiveItemCreate("misc3h","Gaal",1,0,0)
  SetGlobal("fl1t04","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Gaal")
  Global("fl1t05","GLOBAL",3)
THEN RESPONSE #100
  GiveItemCreate("ring26","Gaal",1,0,0)
  SetGlobal("fl1t05","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Gaal")
  Global("fl1t06","GLOBAL",3)
THEN RESPONSE #100
  GiveItemCreate("misc3l","Gaal",3,0,0)
  SetGlobal("fl1t06","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Gaal")
  Global("fl1t07","GLOBAL",3)
THEN RESPONSE #100
  GiveItemCreate("blun23","Gaal",0,0,0)
  SetGlobal("fl1t07","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Gaal")
  Global("fl1t08","GLOBAL",3)
THEN RESPONSE #100
  GiveItemCreate("brac09","Gaal",0,0,0)
  SetGlobal("fl1t08","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Gaal")
  Global("fl1t09","GLOBAL",3)
THEN RESPONSE #100
  GiveItemCreate("rods05","Gaal",0,0,0)
  SetGlobal("fl1t09","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Gaal")
  Global("fl1t10","GLOBAL",3)
THEN RESPONSE #100
  GiveItemCreate("misc3i","Gaal",1,0,0)
  SetGlobal("fl1t10","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Gaal")
  Global("fl1t11","GLOBAL",3)
THEN RESPONSE #100
  GiveItemCreate("ring35","Gaal",0,0,0)
  SetGlobal("fl1t11","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Gaal")
  Global("fl1t12","GLOBAL",3)
THEN RESPONSE #100
  GiveItemCreate("scrl16","Gaal",1,0,0)
  SetGlobal("fl1t12","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Gaal")
  Global("fl1t13","GLOBAL",3)
THEN RESPONSE #100
  GiveItemCreate("xbow03","Gaal",0,0,0)
  SetGlobal("fl1t13","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Gaal")
  Global("fl1t14","GLOBAL",3)
THEN RESPONSE #100
  GiveItemCreate("leat06","Gaal",0,0,0)
  SetGlobal("fl1t14","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Gaal")
  Global("fl1t15","GLOBAL",3)
THEN RESPONSE #100
  GiveItemCreate("ring36","Gaal",0,0,0)
  SetGlobal("fl1t15","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Gaal")
  Global("fl1t16","GLOBAL",3)
THEN RESPONSE #100
  GiveItemCreate("staf10","Gaal",0,10,0)
  SetGlobal("fl1t16","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Gaal")
  Global("fl1t17","GLOBAL",3)
THEN RESPONSE #100
  GiveItemCreate("misc3p","Gaal",3,0,0)
  SetGlobal("fl1t17","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Gaal")
  Global("fl1t18","GLOBAL",3)
THEN RESPONSE #100
  GiveItemCreate("sper03","Gaal",0,0,0)
  SetGlobal("fl1t18","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Gaal")
  Global("fl1t19","GLOBAL",3)
THEN RESPONSE #100
  GiveItemCreate("ring30","Gaal",1,0,0)
  SetGlobal("fl1t19","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Gaal")
  Global("fl1t20","GLOBAL",3)
THEN RESPONSE #100
  GiveItemCreate("boot01","Gaal",0,0,0)
  SetGlobal("fl1t20","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Gaal")
  Global("fl1t21","GLOBAL",3)
THEN RESPONSE #100
  GiveItemCreate("brac04","Gaal",0,0,0)
  SetGlobal("fl1t21","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Gaal")
  Global("fl1t22","GLOBAL",3)
THEN RESPONSE #100
  GiveItemCreate("brac17","Gaal",0,0,0)
  SetGlobal("fl1t22","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Gaal")
  Global("fl1t23","GLOBAL",3)
THEN RESPONSE #100
  GiveItemCreate("helm18","Gaal",0,0,0)
  SetGlobal("fl1t23","GLOBAL",-1)
  DestroySelf()
END
