
IF
  Exists("container7")
  Global("fl24t01","GLOBAL",8)
THEN RESPONSE #100
  ActionOverride("container7",CreateItem("brac01",1,0,0))
  SetGlobal("fl24t01","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("container7")
  Global("fl24t02","GLOBAL",8)
THEN RESPONSE #100
  ActionOverride("container7",CreateItem("brac01",0,0,0))
  SetGlobal("fl24t02","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("container7")
  Global("fl24t03","GLOBAL",8)
THEN RESPONSE #100
  ActionOverride("container7",CreateItem("bow06",0,0,0))
  SetGlobal("fl24t03","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("container7")
  Global("fl24t04","GLOBAL",8)
THEN RESPONSE #100
  ActionOverride("container7",CreateItem("chan02",0,0,0))
  SetGlobal("fl24t04","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("container7")
  Global("fl24t05","GLOBAL",8)
THEN RESPONSE #100
  ActionOverride("container7",CreateItem("chan02",0,0,0))
  SetGlobal("fl24t05","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("container7")
  Global("fl24t06","GLOBAL",8)
THEN RESPONSE #100
  ActionOverride("container7",CreateItem("chan02",0,0,0))
  SetGlobal("fl24t06","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("container7")
  Global("fl24t07","GLOBAL",8)
THEN RESPONSE #100
  ActionOverride("container7",CreateItem("leat02",0,0,0))
  SetGlobal("fl24t07","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("container7")
  Global("fl24t08","GLOBAL",8)
THEN RESPONSE #100
  ActionOverride("container7",CreateItem("leat06",0,0,0))
  SetGlobal("fl24t08","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("container7")
  Global("fl24t09","GLOBAL",8)
THEN RESPONSE #100
  ActionOverride("container7",CreateItem("ring20",19,0,0))
  SetGlobal("fl24t09","GLOBAL",-1)
  DestroySelf()
END
