
IF
  Exists("ZARGAL")
  Global("fl25t01","GLOBAL",6)
THEN RESPONSE #100
  GiveItemCreate("amul15","ZARGAL",10,0,0)
  SetGlobal("fl25t01","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("ZARGAL")
  Global("fl25t02","GLOBAL",6)
THEN RESPONSE #100
  GiveItemCreate("ax1h02","ZARGAL",0,0,0)
  SetGlobal("fl25t02","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("ZARGAL")
  Global("fl25t03","GLOBAL",6)
THEN RESPONSE #100
  GiveItemCreate("blun03","ZARGAL",0,0,0)
  SetGlobal("fl25t03","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("ZARGAL")
  Global("fl25t04","GLOBAL",6)
THEN RESPONSE #100
  GiveItemCreate("blun05","ZARGAL",0,0,0)
  SetGlobal("fl25t04","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("ZARGAL")
  Global("fl25t05","GLOBAL",6)
THEN RESPONSE #100
  GiveItemCreate("bow02","ZARGAL",0,0,0)
  SetGlobal("fl25t05","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("ZARGAL")
  Global("fl25t07","GLOBAL",6)
THEN RESPONSE #100
  GiveItemCreate("hamm02","ZARGAL",0,0,0)
  SetGlobal("fl25t07","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("ZARGAL")
  Global("fl25t08","GLOBAL",6)
THEN RESPONSE #100
  GiveItemCreate("misc42","ZARGAL",0,0,0)
  SetGlobal("fl25t08","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("ZARGAL")
  Global("fl25t09","GLOBAL",6)
THEN RESPONSE #100
  GiveItemCreate("sper03","ZARGAL",0,0,0)
  SetGlobal("fl25t09","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("ZARGAL")
  Global("fl25t10","GLOBAL",6)
THEN RESPONSE #100
  GiveItemCreate("xbow03","ZARGAL",0,0,0)
  SetGlobal("fl25t10","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("ZARGAL")
  Global("fl25t13","GLOBAL",6)
THEN RESPONSE #100
  GiveItemCreate("sw1h02","ZARGAL",0,0,0)
  SetGlobal("fl25t13","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("ZARGAL")
  Global("fl25t14","GLOBAL",6)
THEN RESPONSE #100
  GiveItemCreate("sw1h05","ZARGAL",0,0,0)
  SetGlobal("fl25t14","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("ZARGAL")
  Global("fl25t15","GLOBAL",6)
THEN RESPONSE #100
  GiveItemCreate("sw1h08","ZARGAL",0,0,0)
  SetGlobal("fl25t15","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("ZARGAL")
  Global("fl25t16","GLOBAL",6)
THEN RESPONSE #100
  GiveItemCreate("wand07","ZARGAL",6,0,0)
  SetGlobal("fl25t16","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("ZARGAL")
  Global("fl25t17","GLOBAL",6)
THEN RESPONSE #100
  GiveItemCreate("sw1h02","ZARGAL",0,0,0)
  SetGlobal("fl25t17","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("ZARGAL")
  Global("fl25t18","GLOBAL",6)
THEN RESPONSE #100
  GiveItemCreate("hamm02","ZARGAL",0,0,0)
  SetGlobal("fl25t18","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("ZARGAL")
  Global("fl25t19","GLOBAL",6)
THEN RESPONSE #100
  GiveItemCreate("staf02","ZARGAL",0,0,0)
  SetGlobal("fl25t19","GLOBAL",-1)
  DestroySelf()
END
