
IF
  Exists("TEYNGAN")
  Global("fl25t01","GLOBAL",13)
THEN RESPONSE #100
  GiveItemCreate("amul15","TEYNGAN",10,0,0)
  SetGlobal("fl25t01","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("TEYNGAN")
  Global("fl25t02","GLOBAL",13)
THEN RESPONSE #100
  GiveItemCreate("ax1h02","TEYNGAN",0,0,0)
  SetGlobal("fl25t02","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("TEYNGAN")
  Global("fl25t03","GLOBAL",13)
THEN RESPONSE #100
  GiveItemCreate("blun03","TEYNGAN",0,0,0)
  SetGlobal("fl25t03","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("TEYNGAN")
  Global("fl25t04","GLOBAL",13)
THEN RESPONSE #100
  GiveItemCreate("blun05","TEYNGAN",0,0,0)
  SetGlobal("fl25t04","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("TEYNGAN")
  Global("fl25t05","GLOBAL",13)
THEN RESPONSE #100
  GiveItemCreate("bow02","TEYNGAN",0,0,0)
  SetGlobal("fl25t05","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("TEYNGAN")
  Global("fl25t07","GLOBAL",13)
THEN RESPONSE #100
  GiveItemCreate("hamm02","TEYNGAN",0,0,0)
  SetGlobal("fl25t07","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("TEYNGAN")
  Global("fl25t08","GLOBAL",13)
THEN RESPONSE #100
  GiveItemCreate("misc42","TEYNGAN",0,0,0)
  SetGlobal("fl25t08","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("TEYNGAN")
  Global("fl25t09","GLOBAL",13)
THEN RESPONSE #100
  GiveItemCreate("sper03","TEYNGAN",0,0,0)
  SetGlobal("fl25t09","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("TEYNGAN")
  Global("fl25t10","GLOBAL",13)
THEN RESPONSE #100
  GiveItemCreate("xbow03","TEYNGAN",0,0,0)
  SetGlobal("fl25t10","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("TEYNGAN")
  Global("fl25t13","GLOBAL",13)
THEN RESPONSE #100
  GiveItemCreate("sw1h02","TEYNGAN",0,0,0)
  SetGlobal("fl25t13","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("TEYNGAN")
  Global("fl25t14","GLOBAL",13)
THEN RESPONSE #100
  GiveItemCreate("sw1h05","TEYNGAN",0,0,0)
  SetGlobal("fl25t14","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("TEYNGAN")
  Global("fl25t15","GLOBAL",13)
THEN RESPONSE #100
  GiveItemCreate("sw1h08","TEYNGAN",0,0,0)
  SetGlobal("fl25t15","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("TEYNGAN")
  Global("fl25t16","GLOBAL",13)
THEN RESPONSE #100
  GiveItemCreate("wand07","TEYNGAN",6,0,0)
  SetGlobal("fl25t16","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("TEYNGAN")
  Global("fl25t17","GLOBAL",13)
THEN RESPONSE #100
  GiveItemCreate("sw1h02","TEYNGAN",0,0,0)
  SetGlobal("fl25t17","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("TEYNGAN")
  Global("fl25t18","GLOBAL",13)
THEN RESPONSE #100
  GiveItemCreate("hamm02","TEYNGAN",0,0,0)
  SetGlobal("fl25t18","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("TEYNGAN")
  Global("fl25t19","GLOBAL",13)
THEN RESPONSE #100
  GiveItemCreate("staf02","TEYNGAN",0,0,0)
  SetGlobal("fl25t19","GLOBAL",-1)
  DestroySelf()
END
