
IF
  Exists("container9")
  Global("fl25t01","GLOBAL",9)
THEN RESPONSE #100
  ActionOverride("container9",CreateItem("amul15",10,0,0))
  SetGlobal("fl25t01","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("container9")
  Global("fl25t02","GLOBAL",9)
THEN RESPONSE #100
  ActionOverride("container9",CreateItem("ax1h02",0,0,0))
  SetGlobal("fl25t02","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("container9")
  Global("fl25t03","GLOBAL",9)
THEN RESPONSE #100
  ActionOverride("container9",CreateItem("blun03",0,0,0))
  SetGlobal("fl25t03","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("container9")
  Global("fl25t04","GLOBAL",9)
THEN RESPONSE #100
  ActionOverride("container9",CreateItem("blun05",0,0,0))
  SetGlobal("fl25t04","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("container9")
  Global("fl25t05","GLOBAL",9)
THEN RESPONSE #100
  ActionOverride("container9",CreateItem("bow02",0,0,0))
  SetGlobal("fl25t05","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("container9")
  Global("fl25t07","GLOBAL",9)
THEN RESPONSE #100
  ActionOverride("container9",CreateItem("hamm02",0,0,0))
  SetGlobal("fl25t07","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("container9")
  Global("fl25t08","GLOBAL",9)
THEN RESPONSE #100
  ActionOverride("container9",CreateItem("misc42",0,0,0))
  SetGlobal("fl25t08","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("container9")
  Global("fl25t09","GLOBAL",9)
THEN RESPONSE #100
  ActionOverride("container9",CreateItem("sper03",0,0,0))
  SetGlobal("fl25t09","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("container9")
  Global("fl25t10","GLOBAL",9)
THEN RESPONSE #100
  ActionOverride("container9",CreateItem("xbow03",0,0,0))
  SetGlobal("fl25t10","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("container9")
  Global("fl25t13","GLOBAL",9)
THEN RESPONSE #100
  ActionOverride("container9",CreateItem("sw1h02",0,0,0))
  SetGlobal("fl25t13","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("container9")
  Global("fl25t14","GLOBAL",9)
THEN RESPONSE #100
  ActionOverride("container9",CreateItem("sw1h05",0,0,0))
  SetGlobal("fl25t14","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("container9")
  Global("fl25t15","GLOBAL",9)
THEN RESPONSE #100
  ActionOverride("container9",CreateItem("sw1h08",0,0,0))
  SetGlobal("fl25t15","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("container9")
  Global("fl25t16","GLOBAL",9)
THEN RESPONSE #100
  ActionOverride("container9",CreateItem("wand07",6,0,0))
  SetGlobal("fl25t16","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("container9")
  Global("fl25t17","GLOBAL",9)
THEN RESPONSE #100
  ActionOverride("container9",CreateItem("sw1h02",0,0,0))
  SetGlobal("fl25t17","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("container9")
  Global("fl25t18","GLOBAL",9)
THEN RESPONSE #100
  ActionOverride("container9",CreateItem("hamm02",0,0,0))
  SetGlobal("fl25t18","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("container9")
  Global("fl25t19","GLOBAL",9)
THEN RESPONSE #100
  ActionOverride("container9",CreateItem("staf02",0,0,0))
  SetGlobal("fl25t19","GLOBAL",-1)
  DestroySelf()
END
