
IF
  Exists("Mulahey")
  Global("fl25t01","GLOBAL",20)
THEN RESPONSE #100
  GiveItemCreate("amul15","Mulahey",10,0,0)
  SetGlobal("fl25t01","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Mulahey")
  Global("fl25t02","GLOBAL",20)
THEN RESPONSE #100
  GiveItemCreate("ax1h02","Mulahey",0,0,0)
  SetGlobal("fl25t02","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Mulahey")
  Global("fl25t03","GLOBAL",20)
THEN RESPONSE #100
  GiveItemCreate("blun03","Mulahey",0,0,0)
  SetGlobal("fl25t03","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Mulahey")
  Global("fl25t04","GLOBAL",20)
THEN RESPONSE #100
  GiveItemCreate("blun05","Mulahey",0,0,0)
  SetGlobal("fl25t04","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Mulahey")
  Global("fl25t05","GLOBAL",20)
THEN RESPONSE #100
  GiveItemCreate("bow02","Mulahey",0,0,0)
  SetGlobal("fl25t05","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Mulahey")
  Global("fl25t07","GLOBAL",20)
THEN RESPONSE #100
  GiveItemCreate("hamm02","Mulahey",0,0,0)
  SetGlobal("fl25t07","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Mulahey")
  Global("fl25t08","GLOBAL",20)
THEN RESPONSE #100
  GiveItemCreate("misc42","Mulahey",0,0,0)
  SetGlobal("fl25t08","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Mulahey")
  Global("fl25t09","GLOBAL",20)
THEN RESPONSE #100
  GiveItemCreate("sper03","Mulahey",0,0,0)
  SetGlobal("fl25t09","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Mulahey")
  Global("fl25t10","GLOBAL",20)
THEN RESPONSE #100
  GiveItemCreate("xbow03","Mulahey",0,0,0)
  SetGlobal("fl25t10","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Mulahey")
  Global("fl25t13","GLOBAL",20)
THEN RESPONSE #100
  GiveItemCreate("sw1h02","Mulahey",0,0,0)
  SetGlobal("fl25t13","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Mulahey")
  Global("fl25t14","GLOBAL",20)
THEN RESPONSE #100
  GiveItemCreate("sw1h05","Mulahey",0,0,0)
  SetGlobal("fl25t14","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Mulahey")
  Global("fl25t15","GLOBAL",20)
THEN RESPONSE #100
  GiveItemCreate("sw1h08","Mulahey",0,0,0)
  SetGlobal("fl25t15","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Mulahey")
  Global("fl25t16","GLOBAL",20)
THEN RESPONSE #100
  GiveItemCreate("wand07","Mulahey",6,0,0)
  SetGlobal("fl25t16","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Mulahey")
  Global("fl25t17","GLOBAL",20)
THEN RESPONSE #100
  GiveItemCreate("sw1h02","Mulahey",0,0,0)
  SetGlobal("fl25t17","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Mulahey")
  Global("fl25t18","GLOBAL",20)
THEN RESPONSE #100
  GiveItemCreate("hamm02","Mulahey",0,0,0)
  SetGlobal("fl25t18","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Mulahey")
  Global("fl25t19","GLOBAL",20)
THEN RESPONSE #100
  GiveItemCreate("staf02","Mulahey",0,0,0)
  SetGlobal("fl25t19","GLOBAL",-1)
  DestroySelf()
END
