
IF
  Exists("container1")
  Global("fl25t01","GLOBAL",1)
THEN RESPONSE #100
  ActionOverride("container1",CreateItem("amul15",10,0,0))
  SetGlobal("fl25t01","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("container1")
  Global("fl25t02","GLOBAL",1)
THEN RESPONSE #100
  ActionOverride("container1",CreateItem("ax1h02",0,0,0))
  SetGlobal("fl25t02","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("container1")
  Global("fl25t03","GLOBAL",1)
THEN RESPONSE #100
  ActionOverride("container1",CreateItem("blun03",0,0,0))
  SetGlobal("fl25t03","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("container1")
  Global("fl25t04","GLOBAL",1)
THEN RESPONSE #100
  ActionOverride("container1",CreateItem("blun05",0,0,0))
  SetGlobal("fl25t04","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("container1")
  Global("fl25t05","GLOBAL",1)
THEN RESPONSE #100
  ActionOverride("container1",CreateItem("bow02",0,0,0))
  SetGlobal("fl25t05","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("container1")
  Global("fl25t07","GLOBAL",1)
THEN RESPONSE #100
  ActionOverride("container1",CreateItem("hamm02",0,0,0))
  SetGlobal("fl25t07","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("container1")
  Global("fl25t08","GLOBAL",1)
THEN RESPONSE #100
  ActionOverride("container1",CreateItem("misc42",0,0,0))
  SetGlobal("fl25t08","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("container1")
  Global("fl25t09","GLOBAL",1)
THEN RESPONSE #100
  ActionOverride("container1",CreateItem("sper03",0,0,0))
  SetGlobal("fl25t09","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("container1")
  Global("fl25t10","GLOBAL",1)
THEN RESPONSE #100
  ActionOverride("container1",CreateItem("xbow03",0,0,0))
  SetGlobal("fl25t10","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("container1")
  Global("fl25t13","GLOBAL",1)
THEN RESPONSE #100
  ActionOverride("container1",CreateItem("sw1h02",0,0,0))
  SetGlobal("fl25t13","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("container1")
  Global("fl25t14","GLOBAL",1)
THEN RESPONSE #100
  ActionOverride("container1",CreateItem("sw1h05",0,0,0))
  SetGlobal("fl25t14","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("container1")
  Global("fl25t15","GLOBAL",1)
THEN RESPONSE #100
  ActionOverride("container1",CreateItem("sw1h08",0,0,0))
  SetGlobal("fl25t15","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("container1")
  Global("fl25t16","GLOBAL",1)
THEN RESPONSE #100
  ActionOverride("container1",CreateItem("wand07",6,0,0))
  SetGlobal("fl25t16","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("container1")
  Global("fl25t17","GLOBAL",1)
THEN RESPONSE #100
  ActionOverride("container1",CreateItem("sw1h02",0,0,0))
  SetGlobal("fl25t17","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("container1")
  Global("fl25t18","GLOBAL",1)
THEN RESPONSE #100
  ActionOverride("container1",CreateItem("hamm02",0,0,0))
  SetGlobal("fl25t18","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("container1")
  Global("fl25t19","GLOBAL",1)
THEN RESPONSE #100
  ActionOverride("container1",CreateItem("staf02",0,0,0))
  SetGlobal("fl25t19","GLOBAL",-1)
  DestroySelf()
END
