
IF
  Exists("ALEXANDER")
  Global("fl26t01","GLOBAL",22)
THEN RESPONSE #100
  GiveItemCreate("amul14","ALEXANDER",0,0,0)
  SetGlobal("fl26t01","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("SENDAI")
  Global("fl26t02","GLOBAL",22)
THEN RESPONSE #100
  GiveItemCreate("book07","SENDAI",1,0,0)
  SetGlobal("fl26t02","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("SENDAI")
  Global("fl26t03","GLOBAL",22)
THEN RESPONSE #100
  GiveItemCreate("brac07","SENDAI",0,0,0)
  SetGlobal("fl26t03","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("SENDAI")
  Global("fl26t04","GLOBAL",22)
THEN RESPONSE #100
  GiveItemCreate("brac08","SENDAI",0,0,0)
  SetGlobal("fl26t04","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("SENDAI")
  Global("fl26t05","GLOBAL",22)
THEN RESPONSE #100
  GiveItemCreate("misc41","SENDAI",0,0,0)
  SetGlobal("fl26t05","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("ALEXANDER")
  Global("fl26t06","GLOBAL",22)
THEN RESPONSE #100
  GiveItemCreate("ring04","ALEXANDER",0,0,0)
  SetGlobal("fl26t06","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("SENDAI")
  Global("fl26t07","GLOBAL",22)
THEN RESPONSE #100
  GiveItemCreate("leat07","SENDAI",0,0,0)
  SetGlobal("fl26t07","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("SENDAI")
  Global("fl26t08","GLOBAL",22)
THEN RESPONSE #100
  GiveItemCreate("scrl09","SENDAI",1,0,0)
  SetGlobal("fl26t08","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("SENDAI")
  Global("fl26t09","GLOBAL",22)
THEN RESPONSE #100
  GiveItemCreate("clck01","SENDAI",0,0,0)
  SetGlobal("fl26t09","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("DELGOD")
  Global("fl26t10","GLOBAL",22)
THEN RESPONSE #100
  GiveItemCreate("wand05","DELGOD",8,8,0)
  SetGlobal("fl26t10","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("DELGOD")
  Global("fl26t11","GLOBAL",22)
THEN RESPONSE #100
  GiveItemCreate("wand05","DELGOD",12,12,0)
  SetGlobal("fl26t11","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("DELGOD")
  Global("fl26t12","GLOBAL",22)
THEN RESPONSE #100
  GiveItemCreate("wand05","DELGOD",16,16,0)
  SetGlobal("fl26t12","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("ALEXANDER")
  Global("fl26t13","GLOBAL",22)
THEN RESPONSE #100
  GiveItemCreate("ring06","ALEXANDER",0,0,0)
  SetGlobal("fl26t13","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("ALEXANDER")
  Global("fl26t14","GLOBAL",22)
THEN RESPONSE #100
  GiveItemCreate("belt04","ALEXANDER",0,0,0)
  SetGlobal("fl26t14","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("SENDAI")
  Global("fl26t15","GLOBAL",22)
THEN RESPONSE #100
  GiveItemCreate("belt02","SENDAI",0,0,0)
  SetGlobal("fl26t15","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("DELGOD")
  Global("fl26t16","GLOBAL",22)
THEN RESPONSE #100
  GiveItemCreate("boot01","DELGOD",0,0,0)
  SetGlobal("fl26t16","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("SENDAI")
  Global("fl26t17","GLOBAL",22)
THEN RESPONSE #100
  GiveItemCreate("belt03","SENDAI",0,0,0)
  SetGlobal("fl26t17","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("SENDAI")
  Global("fl26t18","GLOBAL",22)
THEN RESPONSE #100
  GiveItemCreate("boot05","SENDAI",0,0,0)
  SetGlobal("fl26t18","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("SENDAI")
  Global("fl26t19","GLOBAL",22)
THEN RESPONSE #100
  GiveItemCreate("brac03","SENDAI",0,0,0)
  SetGlobal("fl26t19","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("ALEXANDER")
  Global("fl26t20","GLOBAL",22)
THEN RESPONSE #100
  GiveItemCreate("brac04","ALEXANDER",0,0,0)
  SetGlobal("fl26t20","GLOBAL",-1)
  DestroySelf()
END
