
IF
  Exists("KYSUS")
  Global("fl26t01","GLOBAL",16)
THEN RESPONSE #100
  GiveItemCreate("amul14","KYSUS",0,0,0)
  SetGlobal("fl26t01","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("REZDAN")
  Global("fl26t02","GLOBAL",16)
THEN RESPONSE #100
  GiveItemCreate("book07","REZDAN",1,0,0)
  SetGlobal("fl26t02","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("DRASUS")
  Global("fl26t03","GLOBAL",16)
THEN RESPONSE #100
  GiveItemCreate("brac07","DRASUS",0,0,0)
  SetGlobal("fl26t03","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("DRASUS")
  Global("fl26t04","GLOBAL",16)
THEN RESPONSE #100
  GiveItemCreate("brac08","DRASUS",0,0,0)
  SetGlobal("fl26t04","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("GENTHORE")
  Global("fl26t05","GLOBAL",16)
THEN RESPONSE #100
  GiveItemCreate("misc41","GENTHORE",0,0,0)
  SetGlobal("fl26t05","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("GENTHORE")
  Global("fl26t06","GLOBAL",16)
THEN RESPONSE #100
  GiveItemCreate("ring04","GENTHORE",0,0,0)
  SetGlobal("fl26t06","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("REZDAN")
  Global("fl26t07","GLOBAL",16)
THEN RESPONSE #100
  GiveItemCreate("leat07","REZDAN",0,0,0)
  SetGlobal("fl26t07","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("GENTHORE")
  Global("fl26t08","GLOBAL",16)
THEN RESPONSE #100
  GiveItemCreate("scrl09","GENTHORE",1,0,0)
  SetGlobal("fl26t08","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("KYSUS")
  Global("fl26t09","GLOBAL",16)
THEN RESPONSE #100
  GiveItemCreate("clck01","KYSUS",0,0,0)
  SetGlobal("fl26t09","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("KYSUS")
  Global("fl26t10","GLOBAL",16)
THEN RESPONSE #100
  GiveItemCreate("wand05","KYSUS",8,8,0)
  SetGlobal("fl26t10","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("KYSUS")
  Global("fl26t11","GLOBAL",16)
THEN RESPONSE #100
  GiveItemCreate("wand05","KYSUS",12,12,0)
  SetGlobal("fl26t11","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("KYSUS")
  Global("fl26t12","GLOBAL",16)
THEN RESPONSE #100
  GiveItemCreate("wand05","KYSUS",16,16,0)
  SetGlobal("fl26t12","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("KYSUS")
  Global("fl26t13","GLOBAL",16)
THEN RESPONSE #100
  GiveItemCreate("ring06","KYSUS",0,0,0)
  SetGlobal("fl26t13","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("REZDAN")
  Global("fl26t14","GLOBAL",16)
THEN RESPONSE #100
  GiveItemCreate("belt04","REZDAN",0,0,0)
  SetGlobal("fl26t14","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("GENTHORE")
  Global("fl26t15","GLOBAL",16)
THEN RESPONSE #100
  GiveItemCreate("belt02","GENTHORE",0,0,0)
  SetGlobal("fl26t15","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("DRASUS")
  Global("fl26t16","GLOBAL",16)
THEN RESPONSE #100
  GiveItemCreate("boot01","DRASUS",0,0,0)
  SetGlobal("fl26t16","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("GENTHORE")
  Global("fl26t17","GLOBAL",16)
THEN RESPONSE #100
  GiveItemCreate("belt03","GENTHORE",0,0,0)
  SetGlobal("fl26t17","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("DRASUS")
  Global("fl26t18","GLOBAL",16)
THEN RESPONSE #100
  GiveItemCreate("boot05","DRASUS",0,0,0)
  SetGlobal("fl26t18","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("KYSUS")
  Global("fl26t19","GLOBAL",16)
THEN RESPONSE #100
  GiveItemCreate("brac03","KYSUS",0,0,0)
  SetGlobal("fl26t19","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("KYSUS")
  Global("fl26t20","GLOBAL",16)
THEN RESPONSE #100
  GiveItemCreate("brac04","KYSUS",0,0,0)
  SetGlobal("fl26t20","GLOBAL",-1)
  DestroySelf()
END
