
IF
  Exists("Mulahey")
  Global("fl26t01","GLOBAL",17)
THEN RESPONSE #100
  GiveItemCreate("amul14","Mulahey",0,0,0)
  SetGlobal("fl26t01","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Mulahey")
  Global("fl26t02","GLOBAL",17)
THEN RESPONSE #100
  GiveItemCreate("book07","Mulahey",1,0,0)
  SetGlobal("fl26t02","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Mulahey")
  Global("fl26t03","GLOBAL",17)
THEN RESPONSE #100
  GiveItemCreate("brac07","Mulahey",0,0,0)
  SetGlobal("fl26t03","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Mulahey")
  Global("fl26t04","GLOBAL",17)
THEN RESPONSE #100
  GiveItemCreate("brac08","Mulahey",0,0,0)
  SetGlobal("fl26t04","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Mulahey")
  Global("fl26t05","GLOBAL",17)
THEN RESPONSE #100
  GiveItemCreate("misc41","Mulahey",0,0,0)
  SetGlobal("fl26t05","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Mulahey")
  Global("fl26t06","GLOBAL",17)
THEN RESPONSE #100
  GiveItemCreate("ring04","Mulahey",0,0,0)
  SetGlobal("fl26t06","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Mulahey")
  Global("fl26t07","GLOBAL",17)
THEN RESPONSE #100
  GiveItemCreate("leat07","Mulahey",0,0,0)
  SetGlobal("fl26t07","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Mulahey")
  Global("fl26t08","GLOBAL",17)
THEN RESPONSE #100
  GiveItemCreate("scrl09","Mulahey",1,0,0)
  SetGlobal("fl26t08","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Mulahey")
  Global("fl26t09","GLOBAL",17)
THEN RESPONSE #100
  GiveItemCreate("clck01","Mulahey",0,0,0)
  SetGlobal("fl26t09","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Mulahey")
  Global("fl26t10","GLOBAL",17)
THEN RESPONSE #100
  GiveItemCreate("wand05","Mulahey",8,8,0)
  SetGlobal("fl26t10","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Mulahey")
  Global("fl26t11","GLOBAL",17)
THEN RESPONSE #100
  GiveItemCreate("wand05","Mulahey",12,12,0)
  SetGlobal("fl26t11","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Mulahey")
  Global("fl26t12","GLOBAL",17)
THEN RESPONSE #100
  GiveItemCreate("wand05","Mulahey",16,16,0)
  SetGlobal("fl26t12","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Mulahey")
  Global("fl26t13","GLOBAL",17)
THEN RESPONSE #100
  GiveItemCreate("ring06","Mulahey",0,0,0)
  SetGlobal("fl26t13","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Mulahey")
  Global("fl26t14","GLOBAL",17)
THEN RESPONSE #100
  GiveItemCreate("belt04","Mulahey",0,0,0)
  SetGlobal("fl26t14","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Mulahey")
  Global("fl26t15","GLOBAL",17)
THEN RESPONSE #100
  GiveItemCreate("belt02","Mulahey",0,0,0)
  SetGlobal("fl26t15","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Mulahey")
  Global("fl26t16","GLOBAL",17)
THEN RESPONSE #100
  GiveItemCreate("boot01","Mulahey",0,0,0)
  SetGlobal("fl26t16","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Mulahey")
  Global("fl26t17","GLOBAL",17)
THEN RESPONSE #100
  GiveItemCreate("belt03","Mulahey",0,0,0)
  SetGlobal("fl26t17","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Mulahey")
  Global("fl26t18","GLOBAL",17)
THEN RESPONSE #100
  GiveItemCreate("boot05","Mulahey",0,0,0)
  SetGlobal("fl26t18","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Mulahey")
  Global("fl26t19","GLOBAL",17)
THEN RESPONSE #100
  GiveItemCreate("brac03","Mulahey",0,0,0)
  SetGlobal("fl26t19","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Mulahey")
  Global("fl26t20","GLOBAL",17)
THEN RESPONSE #100
  GiveItemCreate("brac04","Mulahey",0,0,0)
  SetGlobal("fl26t20","GLOBAL",-1)
  DestroySelf()
END
