
IF
  Exists("Davaeorn")
  Global("fl26t01","GLOBAL",18)
THEN RESPONSE #100
  GiveItemCreate("amul14","Davaeorn",0,0,0)
  SetGlobal("fl26t01","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Davaeorn")
  Global("fl26t02","GLOBAL",18)
THEN RESPONSE #100
  GiveItemCreate("book07","Davaeorn",1,0,0)
  SetGlobal("fl26t02","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Davaeorn")
  Global("fl26t03","GLOBAL",18)
THEN RESPONSE #100
  GiveItemCreate("brac07","Davaeorn",0,0,0)
  SetGlobal("fl26t03","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Davaeorn")
  Global("fl26t04","GLOBAL",18)
THEN RESPONSE #100
  GiveItemCreate("brac08","Davaeorn",0,0,0)
  SetGlobal("fl26t04","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Davaeorn")
  Global("fl26t05","GLOBAL",18)
THEN RESPONSE #100
  GiveItemCreate("misc41","Davaeorn",0,0,0)
  SetGlobal("fl26t05","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Davaeorn")
  Global("fl26t06","GLOBAL",18)
THEN RESPONSE #100
  GiveItemCreate("ring04","Davaeorn",0,0,0)
  SetGlobal("fl26t06","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Davaeorn")
  Global("fl26t07","GLOBAL",18)
THEN RESPONSE #100
  GiveItemCreate("leat07","Davaeorn",0,0,0)
  SetGlobal("fl26t07","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Davaeorn")
  Global("fl26t08","GLOBAL",18)
THEN RESPONSE #100
  GiveItemCreate("scrl09","Davaeorn",1,0,0)
  SetGlobal("fl26t08","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Davaeorn")
  Global("fl26t09","GLOBAL",18)
THEN RESPONSE #100
  GiveItemCreate("clck01","Davaeorn",0,0,0)
  SetGlobal("fl26t09","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Davaeorn")
  Global("fl26t10","GLOBAL",18)
THEN RESPONSE #100
  GiveItemCreate("wand05","Davaeorn",8,8,0)
  SetGlobal("fl26t10","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Davaeorn")
  Global("fl26t11","GLOBAL",18)
THEN RESPONSE #100
  GiveItemCreate("wand05","Davaeorn",12,12,0)
  SetGlobal("fl26t11","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Davaeorn")
  Global("fl26t12","GLOBAL",18)
THEN RESPONSE #100
  GiveItemCreate("wand05","Davaeorn",16,16,0)
  SetGlobal("fl26t12","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Davaeorn")
  Global("fl26t13","GLOBAL",18)
THEN RESPONSE #100
  GiveItemCreate("ring06","Davaeorn",0,0,0)
  SetGlobal("fl26t13","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Davaeorn")
  Global("fl26t14","GLOBAL",18)
THEN RESPONSE #100
  GiveItemCreate("belt04","Davaeorn",0,0,0)
  SetGlobal("fl26t14","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Davaeorn")
  Global("fl26t15","GLOBAL",18)
THEN RESPONSE #100
  GiveItemCreate("belt02","Davaeorn",0,0,0)
  SetGlobal("fl26t15","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Davaeorn")
  Global("fl26t16","GLOBAL",18)
THEN RESPONSE #100
  GiveItemCreate("boot01","Davaeorn",0,0,0)
  SetGlobal("fl26t16","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Davaeorn")
  Global("fl26t17","GLOBAL",18)
THEN RESPONSE #100
  GiveItemCreate("belt03","Davaeorn",0,0,0)
  SetGlobal("fl26t17","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Davaeorn")
  Global("fl26t18","GLOBAL",18)
THEN RESPONSE #100
  GiveItemCreate("boot05","Davaeorn",0,0,0)
  SetGlobal("fl26t18","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Davaeorn")
  Global("fl26t19","GLOBAL",18)
THEN RESPONSE #100
  GiveItemCreate("brac03","Davaeorn",0,0,0)
  SetGlobal("fl26t19","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Davaeorn")
  Global("fl26t20","GLOBAL",18)
THEN RESPONSE #100
  GiveItemCreate("brac04","Davaeorn",0,0,0)
  SetGlobal("fl26t20","GLOBAL",-1)
  DestroySelf()
END
