
IF
  Exists("NIEMAIN")
  Global("fl26t01","GLOBAL",5)
THEN RESPONSE #100
  GiveItemCreate("amul14","NIEMAIN",0,0,0)
  SetGlobal("fl26t01","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("WILLIAM")
  Global("fl26t02","GLOBAL",5)
THEN RESPONSE #100
  GiveItemCreate("book07","WILLIAM",1,0,0)
  SetGlobal("fl26t02","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("OULAM")
  Global("fl26t03","GLOBAL",5)
THEN RESPONSE #100
  GiveItemCreate("brac07","OULAM",0,0,0)
  SetGlobal("fl26t03","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("WILLIAM")
  Global("fl26t04","GLOBAL",5)
THEN RESPONSE #100
  GiveItemCreate("brac08","WILLIAM",0,0,0)
  SetGlobal("fl26t04","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("NIEMAIN")
  Global("fl26t05","GLOBAL",5)
THEN RESPONSE #100
  GiveItemCreate("misc41","NIEMAIN",0,0,0)
  SetGlobal("fl26t05","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("NIEMAIN")
  Global("fl26t06","GLOBAL",5)
THEN RESPONSE #100
  GiveItemCreate("ring04","NIEMAIN",0,0,0)
  SetGlobal("fl26t06","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("OULAM")
  Global("fl26t07","GLOBAL",5)
THEN RESPONSE #100
  GiveItemCreate("leat07","OULAM",0,0,0)
  SetGlobal("fl26t07","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("NIEMAIN")
  Global("fl26t08","GLOBAL",5)
THEN RESPONSE #100
  GiveItemCreate("scrl09","NIEMAIN",1,0,0)
  SetGlobal("fl26t08","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("OULAM")
  Global("fl26t09","GLOBAL",5)
THEN RESPONSE #100
  GiveItemCreate("clck01","OULAM",0,0,0)
  SetGlobal("fl26t09","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("OULAM")
  Global("fl26t10","GLOBAL",5)
THEN RESPONSE #100
  GiveItemCreate("wand05","OULAM",8,8,0)
  SetGlobal("fl26t10","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("NIEMAIN")
  Global("fl26t11","GLOBAL",5)
THEN RESPONSE #100
  GiveItemCreate("wand05","NIEMAIN",12,12,0)
  SetGlobal("fl26t11","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("WILLIAM")
  Global("fl26t12","GLOBAL",5)
THEN RESPONSE #100
  GiveItemCreate("wand05","WILLIAM",16,16,0)
  SetGlobal("fl26t12","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("WHEBER")
  Global("fl26t13","GLOBAL",5)
THEN RESPONSE #100
  GiveItemCreate("ring06","WHEBER",0,0,0)
  SetGlobal("fl26t13","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("WILLIAM")
  Global("fl26t14","GLOBAL",5)
THEN RESPONSE #100
  GiveItemCreate("belt04","WILLIAM",0,0,0)
  SetGlobal("fl26t14","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("OULAM")
  Global("fl26t15","GLOBAL",5)
THEN RESPONSE #100
  GiveItemCreate("belt02","OULAM",0,0,0)
  SetGlobal("fl26t15","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("WHEBER")
  Global("fl26t16","GLOBAL",5)
THEN RESPONSE #100
  GiveItemCreate("boot01","WHEBER",0,0,0)
  SetGlobal("fl26t16","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("WHEBER")
  Global("fl26t17","GLOBAL",5)
THEN RESPONSE #100
  GiveItemCreate("belt03","WHEBER",0,0,0)
  SetGlobal("fl26t17","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("OULAM")
  Global("fl26t18","GLOBAL",5)
THEN RESPONSE #100
  GiveItemCreate("boot05","OULAM",0,0,0)
  SetGlobal("fl26t18","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("NIEMAIN")
  Global("fl26t19","GLOBAL",5)
THEN RESPONSE #100
  GiveItemCreate("brac03","NIEMAIN",0,0,0)
  SetGlobal("fl26t19","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("OULAM")
  Global("fl26t20","GLOBAL",5)
THEN RESPONSE #100
  GiveItemCreate("brac04","OULAM",0,0,0)
  SetGlobal("fl26t20","GLOBAL",-1)
  DestroySelf()
END
