
IF
  Exists("WILLIAM")
  Global("fl26t01","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("amul14","WILLIAM",0,0,0)
  SetGlobal("fl26t01","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("WILLIAM")
  Global("fl26t02","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("book07","WILLIAM",1,0,0)
  SetGlobal("fl26t02","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("WILLIAM")
  Global("fl26t03","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("brac07","WILLIAM",0,0,0)
  SetGlobal("fl26t03","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("WILLIAM")
  Global("fl26t04","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("brac08","WILLIAM",0,0,0)
  SetGlobal("fl26t04","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("WILLIAM")
  Global("fl26t05","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("misc41","WILLIAM",0,0,0)
  SetGlobal("fl26t05","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("WILLIAM")
  Global("fl26t06","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("ring04","WILLIAM",0,0,0)
  SetGlobal("fl26t06","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("WILLIAM")
  Global("fl26t07","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("leat07","WILLIAM",0,0,0)
  SetGlobal("fl26t07","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("WILLIAM")
  Global("fl26t08","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("scrl09","WILLIAM",1,0,0)
  SetGlobal("fl26t08","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("WILLIAM")
  Global("fl26t09","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("clck01","WILLIAM",0,0,0)
  SetGlobal("fl26t09","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("WILLIAM")
  Global("fl26t10","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("wand05","WILLIAM",8,8,0)
  SetGlobal("fl26t10","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("WILLIAM")
  Global("fl26t11","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("wand05","WILLIAM",12,12,0)
  SetGlobal("fl26t11","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("WILLIAM")
  Global("fl26t12","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("wand05","WILLIAM",16,16,0)
  SetGlobal("fl26t12","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("WILLIAM")
  Global("fl26t13","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("ring06","WILLIAM",0,0,0)
  SetGlobal("fl26t13","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("WILLIAM")
  Global("fl26t14","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("belt04","WILLIAM",0,0,0)
  SetGlobal("fl26t14","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("WILLIAM")
  Global("fl26t15","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("belt02","WILLIAM",0,0,0)
  SetGlobal("fl26t15","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("WILLIAM")
  Global("fl26t16","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("boot01","WILLIAM",0,0,0)
  SetGlobal("fl26t16","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("WILLIAM")
  Global("fl26t17","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("belt03","WILLIAM",0,0,0)
  SetGlobal("fl26t17","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("WILLIAM")
  Global("fl26t18","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("boot05","WILLIAM",0,0,0)
  SetGlobal("fl26t18","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("WILLIAM")
  Global("fl26t19","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("brac03","WILLIAM",0,0,0)
  SetGlobal("fl26t19","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("WILLIAM")
  Global("fl26t20","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("brac04","WILLIAM",0,0,0)
  SetGlobal("fl26t20","GLOBAL",-1)
  DestroySelf()
END
