
IF
  Exists("Ardenor")
  Global("fl26t01","GLOBAL",21)
THEN RESPONSE #100
  GiveItemCreate("amul14","Ardenor",0,0,0)
  SetGlobal("fl26t01","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Ardenor")
  Global("fl26t02","GLOBAL",21)
THEN RESPONSE #100
  GiveItemCreate("book07","Ardenor",1,0,0)
  SetGlobal("fl26t02","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Ardenor")
  Global("fl26t03","GLOBAL",21)
THEN RESPONSE #100
  GiveItemCreate("brac07","Ardenor",0,0,0)
  SetGlobal("fl26t03","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Ardenor")
  Global("fl26t04","GLOBAL",21)
THEN RESPONSE #100
  GiveItemCreate("brac08","Ardenor",0,0,0)
  SetGlobal("fl26t04","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Ardenor")
  Global("fl26t05","GLOBAL",21)
THEN RESPONSE #100
  GiveItemCreate("misc41","Ardenor",0,0,0)
  SetGlobal("fl26t05","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Ardenor")
  Global("fl26t06","GLOBAL",21)
THEN RESPONSE #100
  GiveItemCreate("ring04","Ardenor",0,0,0)
  SetGlobal("fl26t06","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Ardenor")
  Global("fl26t07","GLOBAL",21)
THEN RESPONSE #100
  GiveItemCreate("leat07","Ardenor",0,0,0)
  SetGlobal("fl26t07","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Ardenor")
  Global("fl26t08","GLOBAL",21)
THEN RESPONSE #100
  GiveItemCreate("scrl09","Ardenor",1,0,0)
  SetGlobal("fl26t08","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Ardenor")
  Global("fl26t09","GLOBAL",21)
THEN RESPONSE #100
  GiveItemCreate("clck01","Ardenor",0,0,0)
  SetGlobal("fl26t09","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Ardenor")
  Global("fl26t10","GLOBAL",21)
THEN RESPONSE #100
  GiveItemCreate("wand05","Ardenor",8,8,0)
  SetGlobal("fl26t10","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Ardenor")
  Global("fl26t11","GLOBAL",21)
THEN RESPONSE #100
  GiveItemCreate("wand05","Ardenor",12,12,0)
  SetGlobal("fl26t11","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Ardenor")
  Global("fl26t12","GLOBAL",21)
THEN RESPONSE #100
  GiveItemCreate("wand05","Ardenor",16,16,0)
  SetGlobal("fl26t12","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Ardenor")
  Global("fl26t13","GLOBAL",21)
THEN RESPONSE #100
  GiveItemCreate("ring06","Ardenor",0,0,0)
  SetGlobal("fl26t13","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Ardenor")
  Global("fl26t14","GLOBAL",21)
THEN RESPONSE #100
  GiveItemCreate("belt04","Ardenor",0,0,0)
  SetGlobal("fl26t14","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Ardenor")
  Global("fl26t15","GLOBAL",21)
THEN RESPONSE #100
  GiveItemCreate("belt02","Ardenor",0,0,0)
  SetGlobal("fl26t15","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Ardenor")
  Global("fl26t16","GLOBAL",21)
THEN RESPONSE #100
  GiveItemCreate("boot01","Ardenor",0,0,0)
  SetGlobal("fl26t16","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Ardenor")
  Global("fl26t17","GLOBAL",21)
THEN RESPONSE #100
  GiveItemCreate("belt03","Ardenor",0,0,0)
  SetGlobal("fl26t17","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Ardenor")
  Global("fl26t18","GLOBAL",21)
THEN RESPONSE #100
  GiveItemCreate("boot05","Ardenor",0,0,0)
  SetGlobal("fl26t18","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Ardenor")
  Global("fl26t19","GLOBAL",21)
THEN RESPONSE #100
  GiveItemCreate("brac03","Ardenor",0,0,0)
  SetGlobal("fl26t19","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Ardenor")
  Global("fl26t20","GLOBAL",21)
THEN RESPONSE #100
  GiveItemCreate("brac04","Ardenor",0,0,0)
  SetGlobal("fl26t20","GLOBAL",-1)
  DestroySelf()
END
