
IF
  Exists("Tranzig")
  Global("fl26t01","GLOBAL",8)
THEN RESPONSE #100
  GiveItemCreate("amul14","Tranzig",0,0,0)
  SetGlobal("fl26t01","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Tranzig")
  Global("fl26t02","GLOBAL",8)
THEN RESPONSE #100
  GiveItemCreate("book07","Tranzig",1,0,0)
  SetGlobal("fl26t02","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Tranzig")
  Global("fl26t03","GLOBAL",8)
THEN RESPONSE #100
  GiveItemCreate("brac07","Tranzig",0,0,0)
  SetGlobal("fl26t03","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Tranzig")
  Global("fl26t04","GLOBAL",8)
THEN RESPONSE #100
  GiveItemCreate("brac08","Tranzig",0,0,0)
  SetGlobal("fl26t04","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Tranzig")
  Global("fl26t05","GLOBAL",8)
THEN RESPONSE #100
  GiveItemCreate("misc41","Tranzig",0,0,0)
  SetGlobal("fl26t05","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Tranzig")
  Global("fl26t06","GLOBAL",8)
THEN RESPONSE #100
  GiveItemCreate("ring04","Tranzig",0,0,0)
  SetGlobal("fl26t06","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Tranzig")
  Global("fl26t07","GLOBAL",8)
THEN RESPONSE #100
  GiveItemCreate("leat07","Tranzig",0,0,0)
  SetGlobal("fl26t07","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Tranzig")
  Global("fl26t08","GLOBAL",8)
THEN RESPONSE #100
  GiveItemCreate("scrl09","Tranzig",1,0,0)
  SetGlobal("fl26t08","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Tranzig")
  Global("fl26t09","GLOBAL",8)
THEN RESPONSE #100
  GiveItemCreate("clck01","Tranzig",0,0,0)
  SetGlobal("fl26t09","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Tranzig")
  Global("fl26t10","GLOBAL",8)
THEN RESPONSE #100
  GiveItemCreate("wand05","Tranzig",8,8,0)
  SetGlobal("fl26t10","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Tranzig")
  Global("fl26t11","GLOBAL",8)
THEN RESPONSE #100
  GiveItemCreate("wand05","Tranzig",12,12,0)
  SetGlobal("fl26t11","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Tranzig")
  Global("fl26t12","GLOBAL",8)
THEN RESPONSE #100
  GiveItemCreate("wand05","Tranzig",16,16,0)
  SetGlobal("fl26t12","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Tranzig")
  Global("fl26t13","GLOBAL",8)
THEN RESPONSE #100
  GiveItemCreate("ring06","Tranzig",0,0,0)
  SetGlobal("fl26t13","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Tranzig")
  Global("fl26t14","GLOBAL",8)
THEN RESPONSE #100
  GiveItemCreate("belt04","Tranzig",0,0,0)
  SetGlobal("fl26t14","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Tranzig")
  Global("fl26t15","GLOBAL",8)
THEN RESPONSE #100
  GiveItemCreate("belt02","Tranzig",0,0,0)
  SetGlobal("fl26t15","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Tranzig")
  Global("fl26t16","GLOBAL",8)
THEN RESPONSE #100
  GiveItemCreate("boot01","Tranzig",0,0,0)
  SetGlobal("fl26t16","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Tranzig")
  Global("fl26t17","GLOBAL",8)
THEN RESPONSE #100
  GiveItemCreate("belt03","Tranzig",0,0,0)
  SetGlobal("fl26t17","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Tranzig")
  Global("fl26t18","GLOBAL",8)
THEN RESPONSE #100
  GiveItemCreate("boot05","Tranzig",0,0,0)
  SetGlobal("fl26t18","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Tranzig")
  Global("fl26t19","GLOBAL",8)
THEN RESPONSE #100
  GiveItemCreate("brac03","Tranzig",0,0,0)
  SetGlobal("fl26t19","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Tranzig")
  Global("fl26t20","GLOBAL",8)
THEN RESPONSE #100
  GiveItemCreate("brac04","Tranzig",0,0,0)
  SetGlobal("fl26t20","GLOBAL",-1)
  DestroySelf()
END
