
IF
  Exists("DEGROD")
  Global("fl27t01","GLOBAL",13)
THEN RESPONSE #100
  GiveItemCreate("amul01","DEGROD",10,0,0)
  SetGlobal("fl27t01","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("DEGROD")
  Global("fl27t02","GLOBAL",13)
THEN RESPONSE #100
  GiveItemCreate("book05","DEGROD",1,0,0)
  SetGlobal("fl27t02","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("DEGROD")
  Global("fl27t03","GLOBAL",13)
THEN RESPONSE #100
  GiveItemCreate("book06","DEGROD",1,0,0)
  SetGlobal("fl27t03","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("DEGROD")
  Global("fl27t04","GLOBAL",13)
THEN RESPONSE #100
  GiveItemCreate("book08","DEGROD",1,0,0)
  SetGlobal("fl27t04","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("DEGROD")
  Global("fl27t05","GLOBAL",13)
THEN RESPONSE #100
  GiveItemCreate("clck15","DEGROD",0,0,0)
  SetGlobal("fl27t05","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("DEGROD")
  Global("fl27t06","GLOBAL",13)
THEN RESPONSE #100
  GiveItemCreate("clck16","DEGROD",0,0,0)
  SetGlobal("fl27t06","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("DEGROD")
  Global("fl27t07","GLOBAL",13)
THEN RESPONSE #100
  GiveItemCreate("clck17","DEGROD",0,0,0)
  SetGlobal("fl27t07","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("DEGROD")
  Global("fl27t09","GLOBAL",13)
THEN RESPONSE #100
  GiveItemCreate("ring02","DEGROD",0,0,0)
  SetGlobal("fl27t09","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("DEGROD")
  Global("fl27t10","GLOBAL",13)
THEN RESPONSE #100
  GiveItemCreate("sw1h09","DEGROD",0,0,0)
  SetGlobal("fl27t10","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("DEGROD")
  Global("fl27t11","GLOBAL",13)
THEN RESPONSE #100
  GiveItemCreate("wand06","DEGROD",12,0,0)
  SetGlobal("fl27t11","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("DEGROD")
  Global("fl27t12","GLOBAL",13)
THEN RESPONSE #100
  GiveItemCreate("wand06","DEGROD",10,0,0)
  SetGlobal("fl27t12","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("DEGROD")
  Global("fl27t13","GLOBAL",13)
THEN RESPONSE #100
  GiveItemCreate("wand11","DEGROD",20,0,0)
  SetGlobal("fl27t13","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("DEGROD")
  Global("fl27t14","GLOBAL",13)
THEN RESPONSE #100
  GiveItemCreate("plat05","DEGROD",0,0,0)
  SetGlobal("fl27t14","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("DEGROD")
  Global("fl27t15","GLOBAL",13)
THEN RESPONSE #100
  GiveItemCreate("brac06","DEGROD",0,0,0)
  SetGlobal("fl27t15","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("DEGROD")
  Global("fl27t16","GLOBAL",13)
THEN RESPONSE #100
  GiveItemCreate("amul16","DEGROD",0,0,0)
  SetGlobal("fl27t16","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("DEGROD")
  Global("fl27t17","GLOBAL",13)
THEN RESPONSE #100
  GiveItemCreate("ring22","DEGROD",20,0,0)
  SetGlobal("fl27t17","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("DEGROD")
  Global("fl27t18","GLOBAL",13)
THEN RESPONSE #100
  GiveItemCreate("dagg04","DEGROD",0,0,0)
  SetGlobal("fl27t18","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("DEGROD")
  Global("fl27t19","GLOBAL",13)
THEN RESPONSE #100
  GiveItemCreate("plat04","DEGROD",0,0,0)
  SetGlobal("fl27t19","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("DEGROD")
  Global("fl27t20","GLOBAL",13)
THEN RESPONSE #100
  GiveItemCreate("ring02","DEGROD",0,0,0)
  SetGlobal("fl27t20","GLOBAL",-1)
  DestroySelf()
END
