
IF
  Exists("DESRET")
  Global("fl27t01","GLOBAL",15)
THEN RESPONSE #100
  GiveItemCreate("amul01","DESRET",10,0,0)
  SetGlobal("fl27t01","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("DESRET")
  Global("fl27t02","GLOBAL",15)
THEN RESPONSE #100
  GiveItemCreate("book05","DESRET",1,0,0)
  SetGlobal("fl27t02","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("DESRET")
  Global("fl27t03","GLOBAL",15)
THEN RESPONSE #100
  GiveItemCreate("book06","DESRET",1,0,0)
  SetGlobal("fl27t03","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("DESRET")
  Global("fl27t04","GLOBAL",15)
THEN RESPONSE #100
  GiveItemCreate("book08","DESRET",1,0,0)
  SetGlobal("fl27t04","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("VAYYA")
  Global("fl27t05","GLOBAL",15)
THEN RESPONSE #100
  GiveItemCreate("clck15","VAYYA",0,0,0)
  SetGlobal("fl27t05","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("VAYYA")
  Global("fl27t06","GLOBAL",15)
THEN RESPONSE #100
  GiveItemCreate("clck16","VAYYA",0,0,0)
  SetGlobal("fl27t06","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("VAYYA")
  Global("fl27t07","GLOBAL",15)
THEN RESPONSE #100
  GiveItemCreate("clck17","VAYYA",0,0,0)
  SetGlobal("fl27t07","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("DESRET")
  Global("fl27t09","GLOBAL",15)
THEN RESPONSE #100
  GiveItemCreate("ring02","DESRET",0,0,0)
  SetGlobal("fl27t09","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("DESRET")
  Global("fl27t10","GLOBAL",15)
THEN RESPONSE #100
  GiveItemCreate("sw1h09","DESRET",0,0,0)
  SetGlobal("fl27t10","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("VAYYA")
  Global("fl27t11","GLOBAL",15)
THEN RESPONSE #100
  GiveItemCreate("wand06","VAYYA",12,0,0)
  SetGlobal("fl27t11","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("VAYYA")
  Global("fl27t12","GLOBAL",15)
THEN RESPONSE #100
  GiveItemCreate("wand06","VAYYA",10,0,0)
  SetGlobal("fl27t12","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("VAYYA")
  Global("fl27t13","GLOBAL",15)
THEN RESPONSE #100
  GiveItemCreate("wand11","VAYYA",20,0,0)
  SetGlobal("fl27t13","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("VAYYA")
  Global("fl27t14","GLOBAL",15)
THEN RESPONSE #100
  GiveItemCreate("plat05","VAYYA",0,0,0)
  SetGlobal("fl27t14","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("VAYYA")
  Global("fl27t15","GLOBAL",15)
THEN RESPONSE #100
  GiveItemCreate("brac06","VAYYA",0,0,0)
  SetGlobal("fl27t15","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("VAYYA")
  Global("fl27t16","GLOBAL",15)
THEN RESPONSE #100
  GiveItemCreate("amul16","VAYYA",0,0,0)
  SetGlobal("fl27t16","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("DESRET")
  Global("fl27t17","GLOBAL",15)
THEN RESPONSE #100
  GiveItemCreate("ring22","DESRET",20,0,0)
  SetGlobal("fl27t17","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("DESRET")
  Global("fl27t18","GLOBAL",15)
THEN RESPONSE #100
  GiveItemCreate("dagg04","DESRET",0,0,0)
  SetGlobal("fl27t18","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("VAYYA")
  Global("fl27t19","GLOBAL",15)
THEN RESPONSE #100
  GiveItemCreate("plat04","VAYYA",0,0,0)
  SetGlobal("fl27t19","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("VAYYA")
  Global("fl27t20","GLOBAL",15)
THEN RESPONSE #100
  GiveItemCreate("ring02","VAYYA",0,0,0)
  SetGlobal("fl27t20","GLOBAL",-1)
  DestroySelf()
END
