
IF
  Exists("Davaeorn")
  Global("fl27t01","GLOBAL",8)
THEN RESPONSE #100
  GiveItemCreate("amul01","Davaeorn",10,0,0)
  SetGlobal("fl27t01","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Davaeorn")
  Global("fl27t02","GLOBAL",8)
THEN RESPONSE #100
  GiveItemCreate("book05","Davaeorn",1,0,0)
  SetGlobal("fl27t02","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Davaeorn")
  Global("fl27t03","GLOBAL",8)
THEN RESPONSE #100
  GiveItemCreate("book06","Davaeorn",1,0,0)
  SetGlobal("fl27t03","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Davaeorn")
  Global("fl27t04","GLOBAL",8)
THEN RESPONSE #100
  GiveItemCreate("book08","Davaeorn",1,0,0)
  SetGlobal("fl27t04","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Davaeorn")
  Global("fl27t05","GLOBAL",8)
THEN RESPONSE #100
  GiveItemCreate("clck15","Davaeorn",0,0,0)
  SetGlobal("fl27t05","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Davaeorn")
  Global("fl27t06","GLOBAL",8)
THEN RESPONSE #100
  GiveItemCreate("clck16","Davaeorn",0,0,0)
  SetGlobal("fl27t06","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Davaeorn")
  Global("fl27t07","GLOBAL",8)
THEN RESPONSE #100
  GiveItemCreate("clck17","Davaeorn",0,0,0)
  SetGlobal("fl27t07","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Davaeorn")
  Global("fl27t09","GLOBAL",8)
THEN RESPONSE #100
  GiveItemCreate("ring02","Davaeorn",0,0,0)
  SetGlobal("fl27t09","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Davaeorn")
  Global("fl27t10","GLOBAL",8)
THEN RESPONSE #100
  GiveItemCreate("sw1h09","Davaeorn",0,0,0)
  SetGlobal("fl27t10","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Davaeorn")
  Global("fl27t11","GLOBAL",8)
THEN RESPONSE #100
  GiveItemCreate("wand06","Davaeorn",12,0,0)
  SetGlobal("fl27t11","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Davaeorn")
  Global("fl27t12","GLOBAL",8)
THEN RESPONSE #100
  GiveItemCreate("wand06","Davaeorn",10,0,0)
  SetGlobal("fl27t12","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Davaeorn")
  Global("fl27t13","GLOBAL",8)
THEN RESPONSE #100
  GiveItemCreate("wand11","Davaeorn",20,0,0)
  SetGlobal("fl27t13","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Davaeorn")
  Global("fl27t14","GLOBAL",8)
THEN RESPONSE #100
  GiveItemCreate("plat05","Davaeorn",0,0,0)
  SetGlobal("fl27t14","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Davaeorn")
  Global("fl27t15","GLOBAL",8)
THEN RESPONSE #100
  GiveItemCreate("brac06","Davaeorn",0,0,0)
  SetGlobal("fl27t15","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Davaeorn")
  Global("fl27t16","GLOBAL",8)
THEN RESPONSE #100
  GiveItemCreate("amul16","Davaeorn",0,0,0)
  SetGlobal("fl27t16","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Davaeorn")
  Global("fl27t17","GLOBAL",8)
THEN RESPONSE #100
  GiveItemCreate("ring22","Davaeorn",20,0,0)
  SetGlobal("fl27t17","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Davaeorn")
  Global("fl27t18","GLOBAL",8)
THEN RESPONSE #100
  GiveItemCreate("dagg04","Davaeorn",0,0,0)
  SetGlobal("fl27t18","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Davaeorn")
  Global("fl27t19","GLOBAL",8)
THEN RESPONSE #100
  GiveItemCreate("plat04","Davaeorn",0,0,0)
  SetGlobal("fl27t19","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Davaeorn")
  Global("fl27t20","GLOBAL",8)
THEN RESPONSE #100
  GiveItemCreate("ring02","Davaeorn",0,0,0)
  SetGlobal("fl27t20","GLOBAL",-1)
  DestroySelf()
END
