
IF
  Exists("Arkion")
  Global("fl27t01","GLOBAL",5)
THEN RESPONSE #100
  GiveItemCreate("amul01","Arkion",10,0,0)
  SetGlobal("fl27t01","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Arkion")
  Global("fl27t02","GLOBAL",5)
THEN RESPONSE #100
  GiveItemCreate("book05","Arkion",1,0,0)
  SetGlobal("fl27t02","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Arkion")
  Global("fl27t03","GLOBAL",5)
THEN RESPONSE #100
  GiveItemCreate("book06","Arkion",1,0,0)
  SetGlobal("fl27t03","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Arkion")
  Global("fl27t04","GLOBAL",5)
THEN RESPONSE #100
  GiveItemCreate("book08","Arkion",1,0,0)
  SetGlobal("fl27t04","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Arkion")
  Global("fl27t05","GLOBAL",5)
THEN RESPONSE #100
  GiveItemCreate("clck15","Arkion",0,0,0)
  SetGlobal("fl27t05","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Arkion")
  Global("fl27t06","GLOBAL",5)
THEN RESPONSE #100
  GiveItemCreate("clck16","Arkion",0,0,0)
  SetGlobal("fl27t06","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Arkion")
  Global("fl27t07","GLOBAL",5)
THEN RESPONSE #100
  GiveItemCreate("clck17","Arkion",0,0,0)
  SetGlobal("fl27t07","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Arkion")
  Global("fl27t09","GLOBAL",5)
THEN RESPONSE #100
  GiveItemCreate("ring02","Arkion",0,0,0)
  SetGlobal("fl27t09","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Arkion")
  Global("fl27t10","GLOBAL",5)
THEN RESPONSE #100
  GiveItemCreate("sw1h09","Arkion",0,0,0)
  SetGlobal("fl27t10","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Arkion")
  Global("fl27t11","GLOBAL",5)
THEN RESPONSE #100
  GiveItemCreate("wand06","Arkion",12,0,0)
  SetGlobal("fl27t11","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Arkion")
  Global("fl27t12","GLOBAL",5)
THEN RESPONSE #100
  GiveItemCreate("wand06","Arkion",10,0,0)
  SetGlobal("fl27t12","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Arkion")
  Global("fl27t13","GLOBAL",5)
THEN RESPONSE #100
  GiveItemCreate("wand11","Arkion",20,0,0)
  SetGlobal("fl27t13","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Arkion")
  Global("fl27t14","GLOBAL",5)
THEN RESPONSE #100
  GiveItemCreate("plat05","Arkion",0,0,0)
  SetGlobal("fl27t14","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Arkion")
  Global("fl27t15","GLOBAL",5)
THEN RESPONSE #100
  GiveItemCreate("brac06","Arkion",0,0,0)
  SetGlobal("fl27t15","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Arkion")
  Global("fl27t16","GLOBAL",5)
THEN RESPONSE #100
  GiveItemCreate("amul16","Arkion",0,0,0)
  SetGlobal("fl27t16","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Arkion")
  Global("fl27t17","GLOBAL",5)
THEN RESPONSE #100
  GiveItemCreate("ring22","Arkion",20,0,0)
  SetGlobal("fl27t17","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Arkion")
  Global("fl27t18","GLOBAL",5)
THEN RESPONSE #100
  GiveItemCreate("dagg04","Arkion",0,0,0)
  SetGlobal("fl27t18","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Arkion")
  Global("fl27t19","GLOBAL",5)
THEN RESPONSE #100
  GiveItemCreate("plat04","Arkion",0,0,0)
  SetGlobal("fl27t19","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Arkion")
  Global("fl27t20","GLOBAL",5)
THEN RESPONSE #100
  GiveItemCreate("ring02","Arkion",0,0,0)
  SetGlobal("fl27t20","GLOBAL",-1)
  DestroySelf()
END
