
IF
  Exists("Ragefast")
  Global("fl27t01","GLOBAL",7)
THEN RESPONSE #100
  GiveItemCreate("amul01","Ragefast",10,0,0)
  SetGlobal("fl27t01","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Ragefast")
  Global("fl27t02","GLOBAL",7)
THEN RESPONSE #100
  GiveItemCreate("book05","Ragefast",1,0,0)
  SetGlobal("fl27t02","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Ragefast")
  Global("fl27t03","GLOBAL",7)
THEN RESPONSE #100
  GiveItemCreate("book06","Ragefast",1,0,0)
  SetGlobal("fl27t03","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Ragefast")
  Global("fl27t04","GLOBAL",7)
THEN RESPONSE #100
  GiveItemCreate("book08","Ragefast",1,0,0)
  SetGlobal("fl27t04","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Ragefast")
  Global("fl27t05","GLOBAL",7)
THEN RESPONSE #100
  GiveItemCreate("clck15","Ragefast",0,0,0)
  SetGlobal("fl27t05","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Ragefast")
  Global("fl27t06","GLOBAL",7)
THEN RESPONSE #100
  GiveItemCreate("clck16","Ragefast",0,0,0)
  SetGlobal("fl27t06","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Ragefast")
  Global("fl27t07","GLOBAL",7)
THEN RESPONSE #100
  GiveItemCreate("clck17","Ragefast",0,0,0)
  SetGlobal("fl27t07","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Ragefast")
  Global("fl27t09","GLOBAL",7)
THEN RESPONSE #100
  GiveItemCreate("ring02","Ragefast",0,0,0)
  SetGlobal("fl27t09","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Ragefast")
  Global("fl27t10","GLOBAL",7)
THEN RESPONSE #100
  GiveItemCreate("sw1h09","Ragefast",0,0,0)
  SetGlobal("fl27t10","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Ragefast")
  Global("fl27t11","GLOBAL",7)
THEN RESPONSE #100
  GiveItemCreate("wand06","Ragefast",12,0,0)
  SetGlobal("fl27t11","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Ragefast")
  Global("fl27t12","GLOBAL",7)
THEN RESPONSE #100
  GiveItemCreate("wand06","Ragefast",10,0,0)
  SetGlobal("fl27t12","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Ragefast")
  Global("fl27t13","GLOBAL",7)
THEN RESPONSE #100
  GiveItemCreate("wand11","Ragefast",20,0,0)
  SetGlobal("fl27t13","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Ragefast")
  Global("fl27t14","GLOBAL",7)
THEN RESPONSE #100
  GiveItemCreate("plat05","Ragefast",0,0,0)
  SetGlobal("fl27t14","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Ragefast")
  Global("fl27t15","GLOBAL",7)
THEN RESPONSE #100
  GiveItemCreate("brac06","Ragefast",0,0,0)
  SetGlobal("fl27t15","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Ragefast")
  Global("fl27t16","GLOBAL",7)
THEN RESPONSE #100
  GiveItemCreate("amul16","Ragefast",0,0,0)
  SetGlobal("fl27t16","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Ragefast")
  Global("fl27t17","GLOBAL",7)
THEN RESPONSE #100
  GiveItemCreate("ring22","Ragefast",20,0,0)
  SetGlobal("fl27t17","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Ragefast")
  Global("fl27t18","GLOBAL",7)
THEN RESPONSE #100
  GiveItemCreate("dagg04","Ragefast",0,0,0)
  SetGlobal("fl27t18","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Ragefast")
  Global("fl27t19","GLOBAL",7)
THEN RESPONSE #100
  GiveItemCreate("plat04","Ragefast",0,0,0)
  SetGlobal("fl27t19","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Ragefast")
  Global("fl27t20","GLOBAL",7)
THEN RESPONSE #100
  GiveItemCreate("ring02","Ragefast",0,0,0)
  SetGlobal("fl27t20","GLOBAL",-1)
  DestroySelf()
END
