
IF
  Exists("DICK")
  Global("fl27t01","GLOBAL",14)
THEN RESPONSE #100
  GiveItemCreate("amul01","DICK",10,0,0)
  SetGlobal("fl27t01","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("DICK")
  Global("fl27t02","GLOBAL",14)
THEN RESPONSE #100
  GiveItemCreate("book05","DICK",1,0,0)
  SetGlobal("fl27t02","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("DICK")
  Global("fl27t03","GLOBAL",14)
THEN RESPONSE #100
  GiveItemCreate("book06","DICK",1,0,0)
  SetGlobal("fl27t03","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("DICK")
  Global("fl27t04","GLOBAL",14)
THEN RESPONSE #100
  GiveItemCreate("book08","DICK",1,0,0)
  SetGlobal("fl27t04","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("DICK")
  Global("fl27t05","GLOBAL",14)
THEN RESPONSE #100
  GiveItemCreate("clck15","DICK",0,0,0)
  SetGlobal("fl27t05","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("DICK")
  Global("fl27t06","GLOBAL",14)
THEN RESPONSE #100
  GiveItemCreate("clck16","DICK",0,0,0)
  SetGlobal("fl27t06","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("DICK")
  Global("fl27t07","GLOBAL",14)
THEN RESPONSE #100
  GiveItemCreate("clck17","DICK",0,0,0)
  SetGlobal("fl27t07","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("DICK")
  Global("fl27t09","GLOBAL",14)
THEN RESPONSE #100
  GiveItemCreate("ring02","DICK",0,0,0)
  SetGlobal("fl27t09","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("DICK")
  Global("fl27t10","GLOBAL",14)
THEN RESPONSE #100
  GiveItemCreate("sw1h09","DICK",0,0,0)
  SetGlobal("fl27t10","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("DICK")
  Global("fl27t11","GLOBAL",14)
THEN RESPONSE #100
  GiveItemCreate("wand06","DICK",12,0,0)
  SetGlobal("fl27t11","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("DICK")
  Global("fl27t12","GLOBAL",14)
THEN RESPONSE #100
  GiveItemCreate("wand06","DICK",10,0,0)
  SetGlobal("fl27t12","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("DICK")
  Global("fl27t13","GLOBAL",14)
THEN RESPONSE #100
  GiveItemCreate("wand11","DICK",20,0,0)
  SetGlobal("fl27t13","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("DICK")
  Global("fl27t14","GLOBAL",14)
THEN RESPONSE #100
  GiveItemCreate("plat05","DICK",0,0,0)
  SetGlobal("fl27t14","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("DICK")
  Global("fl27t15","GLOBAL",14)
THEN RESPONSE #100
  GiveItemCreate("brac06","DICK",0,0,0)
  SetGlobal("fl27t15","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("DICK")
  Global("fl27t16","GLOBAL",14)
THEN RESPONSE #100
  GiveItemCreate("amul16","DICK",0,0,0)
  SetGlobal("fl27t16","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("DICK")
  Global("fl27t17","GLOBAL",14)
THEN RESPONSE #100
  GiveItemCreate("ring22","DICK",20,0,0)
  SetGlobal("fl27t17","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("DICK")
  Global("fl27t18","GLOBAL",14)
THEN RESPONSE #100
  GiveItemCreate("dagg04","DICK",0,0,0)
  SetGlobal("fl27t18","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("DICK")
  Global("fl27t19","GLOBAL",14)
THEN RESPONSE #100
  GiveItemCreate("plat04","DICK",0,0,0)
  SetGlobal("fl27t19","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("DICK")
  Global("fl27t20","GLOBAL",14)
THEN RESPONSE #100
  GiveItemCreate("ring02","DICK",0,0,0)
  SetGlobal("fl27t20","GLOBAL",-1)
  DestroySelf()
END
