
IF
  Exists("SCHLUMPSA")
  Global("fl27t01","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("amul01","SCHLUMPSA",10,0,0)
  SetGlobal("fl27t01","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("SCHLUMPSA")
  Global("fl27t02","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("book05","SCHLUMPSA",1,0,0)
  SetGlobal("fl27t02","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("SCHLUMPSA")
  Global("fl27t03","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("book06","SCHLUMPSA",1,0,0)
  SetGlobal("fl27t03","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("SCHLUMPSA")
  Global("fl27t04","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("book08","SCHLUMPSA",1,0,0)
  SetGlobal("fl27t04","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("SCHLUMPSA")
  Global("fl27t05","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("clck15","SCHLUMPSA",0,0,0)
  SetGlobal("fl27t05","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("SCHLUMPSA")
  Global("fl27t06","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("clck16","SCHLUMPSA",0,0,0)
  SetGlobal("fl27t06","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("SCHLUMPSA")
  Global("fl27t07","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("clck17","SCHLUMPSA",0,0,0)
  SetGlobal("fl27t07","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("SCHLUMPSA")
  Global("fl27t09","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("ring02","SCHLUMPSA",0,0,0)
  SetGlobal("fl27t09","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("SCHLUMPSA")
  Global("fl27t10","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("sw1h09","SCHLUMPSA",0,0,0)
  SetGlobal("fl27t10","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("SCHLUMPSA")
  Global("fl27t11","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("wand06","SCHLUMPSA",12,0,0)
  SetGlobal("fl27t11","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("SCHLUMPSA")
  Global("fl27t12","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("wand06","SCHLUMPSA",10,0,0)
  SetGlobal("fl27t12","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("SCHLUMPSA")
  Global("fl27t13","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("wand11","SCHLUMPSA",20,0,0)
  SetGlobal("fl27t13","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("SCHLUMPSA")
  Global("fl27t14","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("plat05","SCHLUMPSA",0,0,0)
  SetGlobal("fl27t14","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("SCHLUMPSA")
  Global("fl27t15","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("brac06","SCHLUMPSA",0,0,0)
  SetGlobal("fl27t15","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("SCHLUMPSA")
  Global("fl27t16","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("amul16","SCHLUMPSA",0,0,0)
  SetGlobal("fl27t16","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("SCHLUMPSA")
  Global("fl27t17","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("ring22","SCHLUMPSA",20,0,0)
  SetGlobal("fl27t17","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("SCHLUMPSA")
  Global("fl27t18","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("dagg04","SCHLUMPSA",0,0,0)
  SetGlobal("fl27t18","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("SCHLUMPSA")
  Global("fl27t19","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("plat04","SCHLUMPSA",0,0,0)
  SetGlobal("fl27t19","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("SCHLUMPSA")
  Global("fl27t20","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("ring02","SCHLUMPSA",0,0,0)
  SetGlobal("fl27t20","GLOBAL",-1)
  DestroySelf()
END
