
IF
  Exists("krystin")
  Global("fl28t01","GLOBAL",9)
THEN RESPONSE #100
  GiveItemCreate("book04","krystin",1,0,0)
  SetGlobal("fl28t01","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Slythe")
  Global("fl28t02","GLOBAL",9)
THEN RESPONSE #100
  GiveItemCreate("clck02","Slythe",0,0,0)
  SetGlobal("fl28t02","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Slythe")
  Global("fl28t03","GLOBAL",9)
THEN RESPONSE #100
  GiveItemCreate("leat08","Slythe",0,0,0)
  SetGlobal("fl28t03","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("krystin")
  Global("fl28t04","GLOBAL",9)
THEN RESPONSE #100
  GiveItemCreate("helm06","krystin",0,0,0)
  SetGlobal("fl28t04","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Slythe")
  Global("fl28t05","GLOBAL",9)
THEN RESPONSE #100
  GiveItemCreate("misc75","Slythe",0,0,0)
  SetGlobal("fl28t05","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("krystin")
  Global("fl28t06","GLOBAL",9)
THEN RESPONSE #100
  GiveItemCreate("ring08_","krystin",0,0,0)
  SetGlobal("fl28t06","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("krystin")
  Global("fl28t07","GLOBAL",9)
THEN RESPONSE #100
  GiveItemCreate("brac10","krystin",0,0,0)
  SetGlobal("fl28t07","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("krystin")
  Global("fl28t08","GLOBAL",9)
THEN RESPONSE #100
  GiveItemCreate("sw1h06","krystin",0,0,0)
  SetGlobal("fl28t08","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("krystin")
  Global("fl28t09","GLOBAL",9)
THEN RESPONSE #100
  GiveItemCreate("wand04","krystin",13,0,0)
  SetGlobal("fl28t09","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("krystin")
  Global("fl28t10","GLOBAL",9)
THEN RESPONSE #100
  GiveItemCreate("wand10","krystin",8,0,0)
  SetGlobal("fl28t10","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("krystin")
  Global("fl28t11","GLOBAL",9)
THEN RESPONSE #100
  GiveItemCreate("wand10","krystin",20,0,0)
  SetGlobal("fl28t11","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("krystin")
  Global("fl28t12","GLOBAL",9)
THEN RESPONSE #100
  GiveItemCreate("xbow06","krystin",0,0,0)
  SetGlobal("fl28t12","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Slythe")
  Global("fl28t13","GLOBAL",9)
THEN RESPONSE #100
  GiveItemCreate("ring07","Slythe",0,0,0)
  SetGlobal("fl28t13","GLOBAL",-1)
  DestroySelf()
END
