
IF
  Exists("container5")
  Global("fl28t01","GLOBAL",1)
THEN RESPONSE #100
  ActionOverride("container5",CreateItem("book04",1,0,0))
  SetGlobal("fl28t01","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("container5")
  Global("fl28t02","GLOBAL",1)
THEN RESPONSE #100
  ActionOverride("container5",CreateItem("clck02",0,0,0))
  SetGlobal("fl28t02","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("container5")
  Global("fl28t03","GLOBAL",1)
THEN RESPONSE #100
  ActionOverride("container5",CreateItem("leat08",0,0,0))
  SetGlobal("fl28t03","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("container5")
  Global("fl28t04","GLOBAL",1)
THEN RESPONSE #100
  ActionOverride("container5",CreateItem("helm06",0,0,0))
  SetGlobal("fl28t04","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("container5")
  Global("fl28t05","GLOBAL",1)
THEN RESPONSE #100
  ActionOverride("container5",CreateItem("misc75",0,0,0))
  SetGlobal("fl28t05","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("container5")
  Global("fl28t06","GLOBAL",1)
THEN RESPONSE #100
  ActionOverride("container5",CreateItem("ring08_",0,0,0))
  SetGlobal("fl28t06","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("container5")
  Global("fl28t07","GLOBAL",1)
THEN RESPONSE #100
  ActionOverride("container5",CreateItem("brac10",0,0,0))
  SetGlobal("fl28t07","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("container5")
  Global("fl28t08","GLOBAL",1)
THEN RESPONSE #100
  ActionOverride("container5",CreateItem("sw1h06",0,0,0))
  SetGlobal("fl28t08","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("container5")
  Global("fl28t09","GLOBAL",1)
THEN RESPONSE #100
  ActionOverride("container5",CreateItem("wand04",13,0,0))
  SetGlobal("fl28t09","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("container5")
  Global("fl28t10","GLOBAL",1)
THEN RESPONSE #100
  ActionOverride("container5",CreateItem("wand10",8,0,0))
  SetGlobal("fl28t10","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("container5")
  Global("fl28t11","GLOBAL",1)
THEN RESPONSE #100
  ActionOverride("container5",CreateItem("wand10",20,0,0))
  SetGlobal("fl28t11","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("container5")
  Global("fl28t12","GLOBAL",1)
THEN RESPONSE #100
  ActionOverride("container5",CreateItem("xbow06",0,0,0))
  SetGlobal("fl28t12","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("container5")
  Global("fl28t13","GLOBAL",1)
THEN RESPONSE #100
  ActionOverride("container5",CreateItem("ring07",0,0,0))
  SetGlobal("fl28t13","GLOBAL",-1)
  DestroySelf()
END
