
IF
  Exists("lendar")
  Global("fl28t01","GLOBAL",5)
THEN RESPONSE #100
  GiveItemCreate("book04","lendar",1,0,0)
  SetGlobal("fl28t01","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("lendar")
  Global("fl28t02","GLOBAL",5)
THEN RESPONSE #100
  GiveItemCreate("clck02","lendar",0,0,0)
  SetGlobal("fl28t02","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("lendar")
  Global("fl28t03","GLOBAL",5)
THEN RESPONSE #100
  GiveItemCreate("leat08","lendar",0,0,0)
  SetGlobal("fl28t03","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("lendar")
  Global("fl28t04","GLOBAL",5)
THEN RESPONSE #100
  GiveItemCreate("helm06","lendar",0,0,0)
  SetGlobal("fl28t04","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("lendar")
  Global("fl28t05","GLOBAL",5)
THEN RESPONSE #100
  GiveItemCreate("misc75","lendar",0,0,0)
  SetGlobal("fl28t05","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("lendar")
  Global("fl28t06","GLOBAL",5)
THEN RESPONSE #100
  GiveItemCreate("ring08_","lendar",0,0,0)
  SetGlobal("fl28t06","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("lendar")
  Global("fl28t07","GLOBAL",5)
THEN RESPONSE #100
  GiveItemCreate("brac10","lendar",0,0,0)
  SetGlobal("fl28t07","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("lendar")
  Global("fl28t08","GLOBAL",5)
THEN RESPONSE #100
  GiveItemCreate("sw1h06","lendar",0,0,0)
  SetGlobal("fl28t08","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("lendar")
  Global("fl28t09","GLOBAL",5)
THEN RESPONSE #100
  GiveItemCreate("wand04","lendar",13,0,0)
  SetGlobal("fl28t09","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("lendar")
  Global("fl28t10","GLOBAL",5)
THEN RESPONSE #100
  GiveItemCreate("wand10","lendar",8,0,0)
  SetGlobal("fl28t10","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("lendar")
  Global("fl28t11","GLOBAL",5)
THEN RESPONSE #100
  GiveItemCreate("wand10","lendar",20,0,0)
  SetGlobal("fl28t11","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("lendar")
  Global("fl28t12","GLOBAL",5)
THEN RESPONSE #100
  GiveItemCreate("xbow06","lendar",0,0,0)
  SetGlobal("fl28t12","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("lendar")
  Global("fl28t13","GLOBAL",5)
THEN RESPONSE #100
  GiveItemCreate("ring07","lendar",0,0,0)
  SetGlobal("fl28t13","GLOBAL",-1)
  DestroySelf()
END
