
IF
  Exists("Rieltar")
  Global("fl28t01","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("book04","Rieltar",1,0,0)
  SetGlobal("fl28t01","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Rieltar")
  Global("fl28t02","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("clck02","Rieltar",0,0,0)
  SetGlobal("fl28t02","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Rieltar")
  Global("fl28t03","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("leat08","Rieltar",0,0,0)
  SetGlobal("fl28t03","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Rieltar")
  Global("fl28t04","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("helm06","Rieltar",0,0,0)
  SetGlobal("fl28t04","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Rieltar")
  Global("fl28t05","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("misc75","Rieltar",0,0,0)
  SetGlobal("fl28t05","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Rieltar")
  Global("fl28t06","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("ring08_","Rieltar",0,0,0)
  SetGlobal("fl28t06","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Rieltar")
  Global("fl28t07","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("brac10","Rieltar",0,0,0)
  SetGlobal("fl28t07","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Rieltar")
  Global("fl28t08","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("sw1h06","Rieltar",0,0,0)
  SetGlobal("fl28t08","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Rieltar")
  Global("fl28t09","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("wand04","Rieltar",13,0,0)
  SetGlobal("fl28t09","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Rieltar")
  Global("fl28t10","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("wand10","Rieltar",8,0,0)
  SetGlobal("fl28t10","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Rieltar")
  Global("fl28t11","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("wand10","Rieltar",20,0,0)
  SetGlobal("fl28t11","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Rieltar")
  Global("fl28t12","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("xbow06","Rieltar",0,0,0)
  SetGlobal("fl28t12","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Rieltar")
  Global("fl28t13","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("ring07","Rieltar",0,0,0)
  SetGlobal("fl28t13","GLOBAL",-1)
  DestroySelf()
END
