
IF
  Exists("Garan")
  Global("fl29t01","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("book08","Garan",1,0,0)
  SetGlobal("fl29t01","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Garan")
  Global("fl29t02","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("brac11","Garan",0,0,0)
  SetGlobal("fl29t02","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Garan")
  Global("fl29t04","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("wand05","Garan",20,0,0)
  SetGlobal("fl29t04","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Garan")
  Global("fl29t05","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("wand06","Garan",9,0,0)
  SetGlobal("fl29t05","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Garan")
  Global("fl29t06","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("wand06","Garan",29,0,0)
  SetGlobal("fl29t06","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Garan")
  Global("fl29t07","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("wand07","Garan",5,0,0)
  SetGlobal("fl29t07","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Garan")
  Global("fl29t08","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("wand07","Garan",9,0,0)
  SetGlobal("fl29t08","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Garan")
  Global("fl29t09","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("wand07","Garan",16,0,0)
  SetGlobal("fl29t09","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Garan")
  Global("fl29t10","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("wand11","Garan",25,0,0)
  SetGlobal("fl29t10","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Garan")
  Global("fl29t11","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("ax1h07","Garan",1,1,0)
  SetGlobal("fl29t11","GLOBAL",-1)
  DestroySelf()
END
