
IF
  Exists("chimneycontainer")
  Global("fl29t01","GLOBAL",7)
THEN RESPONSE #100
  ActionOverride("chimneycontainer",CreateItem("book08",1,0,0))
  SetGlobal("fl29t01","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("chimneycontainer")
  Global("fl29t02","GLOBAL",7)
THEN RESPONSE #100
  ActionOverride("chimneycontainer",CreateItem("brac11",0,0,0))
  SetGlobal("fl29t02","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("chimneycontainer")
  Global("fl29t04","GLOBAL",7)
THEN RESPONSE #100
  ActionOverride("chimneycontainer",CreateItem("wand05",20,0,0))
  SetGlobal("fl29t04","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("chimneycontainer")
  Global("fl29t05","GLOBAL",7)
THEN RESPONSE #100
  ActionOverride("chimneycontainer",CreateItem("wand06",9,0,0))
  SetGlobal("fl29t05","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("chimneycontainer")
  Global("fl29t06","GLOBAL",7)
THEN RESPONSE #100
  ActionOverride("chimneycontainer",CreateItem("wand06",29,0,0))
  SetGlobal("fl29t06","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("chimneycontainer")
  Global("fl29t07","GLOBAL",7)
THEN RESPONSE #100
  ActionOverride("chimneycontainer",CreateItem("wand07",5,0,0))
  SetGlobal("fl29t07","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("chimneycontainer")
  Global("fl29t08","GLOBAL",7)
THEN RESPONSE #100
  ActionOverride("chimneycontainer",CreateItem("wand07",9,0,0))
  SetGlobal("fl29t08","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("chimneycontainer")
  Global("fl29t09","GLOBAL",7)
THEN RESPONSE #100
  ActionOverride("chimneycontainer",CreateItem("wand07",16,0,0))
  SetGlobal("fl29t09","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("chimneycontainer")
  Global("fl29t10","GLOBAL",7)
THEN RESPONSE #100
  ActionOverride("chimneycontainer",CreateItem("wand11",25,0,0))
  SetGlobal("fl29t10","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("chimneycontainer")
  Global("fl29t11","GLOBAL",7)
THEN RESPONSE #100
  ActionOverride("chimneycontainer",CreateItem("ax1h07",1,1,0))
  SetGlobal("fl29t11","GLOBAL",-1)
  DestroySelf()
END
