
IF
  Exists("pthral05")
  Global("fl2t01","GLOBAL",3)
THEN RESPONSE #100
  GiveItemCreate("shld07","pthral05",0,0,0)
  SetGlobal("fl2t01","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("pthral05")
  Global("fl2t02","GLOBAL",3)
THEN RESPONSE #100
  GiveItemCreate("sw2h03","pthral05",0,0,0)
  SetGlobal("fl2t02","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("pthral05")
  Global("fl2t03","GLOBAL",3)
THEN RESPONSE #100
  GiveItemCreate("ring28","pthral05",1,1,0)
  SetGlobal("fl2t03","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("pthral05")
  Global("fl2t04","GLOBAL",3)
THEN RESPONSE #100
  GiveItemCreate("ring29","pthral05",1,1,0)
  SetGlobal("fl2t04","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("pthral05")
  Global("fl2t05","GLOBAL",3)
THEN RESPONSE #100
  GiveItemCreate("leat08","pthral05",0,0,0)
  SetGlobal("fl2t05","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("pthral05")
  Global("fl2t06","GLOBAL",3)
THEN RESPONSE #100
  GiveItemCreate("dagg17","pthral05",0,0,0)
  SetGlobal("fl2t06","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("pthral05")
  Global("fl2t07","GLOBAL",3)
THEN RESPONSE #100
  GiveItemCreate("brac07","pthral05",0,0,0)
  SetGlobal("fl2t07","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("pthral05")
  Global("fl2t08","GLOBAL",3)
THEN RESPONSE #100
  GiveItemCreate("amul22","pthral05",1,0,0)
  SetGlobal("fl2t08","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("pthral05")
  Global("fl2t09","GLOBAL",3)
THEN RESPONSE #100
  GiveItemCreate("chan17","pthral05",0,0,0)
  SetGlobal("fl2t09","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("pthral05")
  Global("fl2t10","GLOBAL",3)
THEN RESPONSE #100
  GiveItemCreate("clck06","pthral05",0,0,0)
  SetGlobal("fl2t10","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("pthral05")
  Global("fl2t11","GLOBAL",3)
THEN RESPONSE #100
  GiveItemCreate("leat16","pthral05",0,0,0)
  SetGlobal("fl2t11","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("pthral05")
  Global("fl2t12","GLOBAL",3)
THEN RESPONSE #100
  GiveItemCreate("leat18","pthral05",0,0,0)
  SetGlobal("fl2t12","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("pthral05")
  Global("fl2t14","GLOBAL",3)
THEN RESPONSE #100
  GiveItemCreate("sw2h12","pthral05",0,0,0)
  SetGlobal("fl2t14","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("pthral05")
  Global("fl2t15","GLOBAL",3)
THEN RESPONSE #100
  GiveItemCreate("leat17","pthral05",1,0,0)
  SetGlobal("fl2t15","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("pthral05")
  Global("fl2t16","GLOBAL",3)
THEN RESPONSE #100
  GiveItemCreate("helm06","pthral05",0,0,0)
  SetGlobal("fl2t16","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("pthral05")
  Global("fl2t17","GLOBAL",3)
THEN RESPONSE #100
  GiveItemCreate("wand12","pthral05",50,0,0)
  SetGlobal("fl2t17","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("pthral05")
  Global("fl2t18","GLOBAL",3)
THEN RESPONSE #100
  GiveItemCreate("sw1h54c","pthral05",0,0,0)
  SetGlobal("fl2t18","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("pthral05")
  Global("fl2t19","GLOBAL",3)
THEN RESPONSE #100
  GiveItemCreate("clck27","pthral05",1,1,1)
  SetGlobal("fl2t19","GLOBAL",-1)
  DestroySelf()
END
