
IF
  Exists("obshal01")
  Global("fl2t01","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("shld07","obshal01",0,0,0)
  SetGlobal("fl2t01","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("obshal02")
  Global("fl2t02","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("sw2h03","obshal02",0,0,0)
  SetGlobal("fl2t02","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("obshal05")
  Global("fl2t03","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("ring28","obshal05",1,1,0)
  SetGlobal("fl2t03","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("obshal02")
  Global("fl2t04","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("ring29","obshal02",1,1,0)
  SetGlobal("fl2t04","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("obshal03")
  Global("fl2t05","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("leat08","obshal03",0,0,0)
  SetGlobal("fl2t05","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("pries18a")
  Global("fl2t06","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("dagg17","pries18a",0,0,0)
  SetGlobal("fl2t06","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("obshal03")
  Global("fl2t07","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("brac07","obshal03",0,0,0)
  SetGlobal("fl2t07","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("obshal01")
  Global("fl2t08","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("amul22","obshal01",1,0,0)
  SetGlobal("fl2t08","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("obshal01")
  Global("fl2t09","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("chan17","obshal01",0,0,0)
  SetGlobal("fl2t09","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("obshal06")
  Global("fl2t10","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("clck06","obshal06",0,0,0)
  SetGlobal("fl2t10","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("obshal02")
  Global("fl2t11","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("leat16","obshal02",0,0,0)
  SetGlobal("fl2t11","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("pries18a")
  Global("fl2t12","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("leat18","pries18a",0,0,0)
  SetGlobal("fl2t12","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("obshal03")
  Global("fl2t14","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("sw2h12","obshal03",0,0,0)
  SetGlobal("fl2t14","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("obshal01")
  Global("fl2t15","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("leat17","obshal01",1,0,0)
  SetGlobal("fl2t15","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("obshal03")
  Global("fl2t16","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("helm06","obshal03",0,0,0)
  SetGlobal("fl2t16","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("obshal03")
  Global("fl2t17","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("wand12","obshal03",50,0,0)
  SetGlobal("fl2t17","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("obshal03")
  Global("fl2t18","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("sw1h54c","obshal03",0,0,0)
  SetGlobal("fl2t18","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("obshal05")
  Global("fl2t19","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("clck27","obshal05",1,1,1)
  SetGlobal("fl2t19","GLOBAL",-1)
  DestroySelf()
END
