
IF
  Exists("theshal")
  Global("fl2t01","GLOBAL",6)
THEN RESPONSE #100
  GiveItemCreate("shld07","theshal",0,0,0)
  SetGlobal("fl2t01","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("theshal")
  Global("fl2t02","GLOBAL",6)
THEN RESPONSE #100
  GiveItemCreate("sw2h03","theshal",0,0,0)
  SetGlobal("fl2t02","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("theshal")
  Global("fl2t03","GLOBAL",6)
THEN RESPONSE #100
  GiveItemCreate("ring28","theshal",1,1,0)
  SetGlobal("fl2t03","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("theshal")
  Global("fl2t04","GLOBAL",6)
THEN RESPONSE #100
  GiveItemCreate("ring29","theshal",1,1,0)
  SetGlobal("fl2t04","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("theshal")
  Global("fl2t05","GLOBAL",6)
THEN RESPONSE #100
  GiveItemCreate("leat08","theshal",0,0,0)
  SetGlobal("fl2t05","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("theshal")
  Global("fl2t06","GLOBAL",6)
THEN RESPONSE #100
  GiveItemCreate("dagg17","theshal",0,0,0)
  SetGlobal("fl2t06","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("theshal")
  Global("fl2t07","GLOBAL",6)
THEN RESPONSE #100
  GiveItemCreate("brac07","theshal",0,0,0)
  SetGlobal("fl2t07","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("theshal")
  Global("fl2t08","GLOBAL",6)
THEN RESPONSE #100
  GiveItemCreate("amul22","theshal",1,0,0)
  SetGlobal("fl2t08","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("theshal")
  Global("fl2t09","GLOBAL",6)
THEN RESPONSE #100
  GiveItemCreate("chan17","theshal",0,0,0)
  SetGlobal("fl2t09","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("theshal")
  Global("fl2t10","GLOBAL",6)
THEN RESPONSE #100
  GiveItemCreate("clck06","theshal",0,0,0)
  SetGlobal("fl2t10","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("theshal")
  Global("fl2t11","GLOBAL",6)
THEN RESPONSE #100
  GiveItemCreate("leat16","theshal",0,0,0)
  SetGlobal("fl2t11","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("theshal")
  Global("fl2t12","GLOBAL",6)
THEN RESPONSE #100
  GiveItemCreate("leat18","theshal",0,0,0)
  SetGlobal("fl2t12","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("theshal")
  Global("fl2t14","GLOBAL",6)
THEN RESPONSE #100
  GiveItemCreate("sw2h12","theshal",0,0,0)
  SetGlobal("fl2t14","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("theshal")
  Global("fl2t15","GLOBAL",6)
THEN RESPONSE #100
  GiveItemCreate("leat17","theshal",1,0,0)
  SetGlobal("fl2t15","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("theshal")
  Global("fl2t16","GLOBAL",6)
THEN RESPONSE #100
  GiveItemCreate("helm06","theshal",0,0,0)
  SetGlobal("fl2t16","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("theshal")
  Global("fl2t17","GLOBAL",6)
THEN RESPONSE #100
  GiveItemCreate("wand12","theshal",50,0,0)
  SetGlobal("fl2t17","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("theshal")
  Global("fl2t18","GLOBAL",6)
THEN RESPONSE #100
  GiveItemCreate("sw1h54c","theshal",0,0,0)
  SetGlobal("fl2t18","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("theshal")
  Global("fl2t19","GLOBAL",6)
THEN RESPONSE #100
  GiveItemCreate("clck27","theshal",1,1,1)
  SetGlobal("fl2t19","GLOBAL",-1)
  DestroySelf()
END
