
IF
  Exists("ppmind01")
  Global("fl2t01","GLOBAL",14)
THEN RESPONSE #100
  GiveItemCreate("shld07","ppmind01",0,0,0)
  SetGlobal("fl2t01","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("ppmind01")
  Global("fl2t02","GLOBAL",14)
THEN RESPONSE #100
  GiveItemCreate("sw2h03","ppmind01",0,0,0)
  SetGlobal("fl2t02","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("ppmind01")
  Global("fl2t03","GLOBAL",14)
THEN RESPONSE #100
  GiveItemCreate("ring28","ppmind01",1,1,0)
  SetGlobal("fl2t03","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("ppmind01")
  Global("fl2t04","GLOBAL",14)
THEN RESPONSE #100
  GiveItemCreate("ring29","ppmind01",1,1,0)
  SetGlobal("fl2t04","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("ppmind01")
  Global("fl2t05","GLOBAL",14)
THEN RESPONSE #100
  GiveItemCreate("leat08","ppmind01",0,0,0)
  SetGlobal("fl2t05","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("ppmind01")
  Global("fl2t06","GLOBAL",14)
THEN RESPONSE #100
  GiveItemCreate("dagg17","ppmind01",0,0,0)
  SetGlobal("fl2t06","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("ppmind01")
  Global("fl2t07","GLOBAL",14)
THEN RESPONSE #100
  GiveItemCreate("brac07","ppmind01",0,0,0)
  SetGlobal("fl2t07","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("ppmind01")
  Global("fl2t08","GLOBAL",14)
THEN RESPONSE #100
  GiveItemCreate("amul22","ppmind01",1,0,0)
  SetGlobal("fl2t08","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("ppmind01")
  Global("fl2t09","GLOBAL",14)
THEN RESPONSE #100
  GiveItemCreate("chan17","ppmind01",0,0,0)
  SetGlobal("fl2t09","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("ppmind01")
  Global("fl2t10","GLOBAL",14)
THEN RESPONSE #100
  GiveItemCreate("clck06","ppmind01",0,0,0)
  SetGlobal("fl2t10","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("ppmind01")
  Global("fl2t11","GLOBAL",14)
THEN RESPONSE #100
  GiveItemCreate("leat16","ppmind01",0,0,0)
  SetGlobal("fl2t11","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("ppmind01")
  Global("fl2t12","GLOBAL",14)
THEN RESPONSE #100
  GiveItemCreate("leat18","ppmind01",0,0,0)
  SetGlobal("fl2t12","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("ppmind01")
  Global("fl2t14","GLOBAL",14)
THEN RESPONSE #100
  GiveItemCreate("sw2h12","ppmind01",0,0,0)
  SetGlobal("fl2t14","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("ppmind01")
  Global("fl2t15","GLOBAL",14)
THEN RESPONSE #100
  GiveItemCreate("leat17","ppmind01",1,0,0)
  SetGlobal("fl2t15","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("ppmind01")
  Global("fl2t16","GLOBAL",14)
THEN RESPONSE #100
  GiveItemCreate("helm06","ppmind01",0,0,0)
  SetGlobal("fl2t16","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("ppmind01")
  Global("fl2t17","GLOBAL",14)
THEN RESPONSE #100
  GiveItemCreate("wand12","ppmind01",50,0,0)
  SetGlobal("fl2t17","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("ppmind01")
  Global("fl2t18","GLOBAL",14)
THEN RESPONSE #100
  GiveItemCreate("sw1h54c","ppmind01",0,0,0)
  SetGlobal("fl2t18","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("ppmind01")
  Global("fl2t19","GLOBAL",14)
THEN RESPONSE #100
  GiveItemCreate("clck27","ppmind01",1,1,1)
  SetGlobal("fl2t19","GLOBAL",-1)
  DestroySelf()
END
