
IF
  Exists("tellan")
  Global("fl30t01","GLOBAL",2)
THEN RESPONSE #100
  GiveItemCreate("amul17","tellan",10,0,0)
  SetGlobal("fl30t01","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("tellan")
  Global("fl30t02","GLOBAL",2)
THEN RESPONSE #100
  GiveItemCreate("blun11","tellan",0,0,0)
  SetGlobal("fl30t02","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("tellan")
  Global("fl30t03","GLOBAL",2)
THEN RESPONSE #100
  GiveItemCreate("ring05","tellan",7,0,0)
  SetGlobal("fl30t03","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("tellan")
  Global("fl30t05","GLOBAL",2)
THEN RESPONSE #100
  GiveItemCreate("leat09","tellan",0,0,0)
  SetGlobal("fl30t05","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("tellan")
  Global("fl30t07","GLOBAL",2)
THEN RESPONSE #100
  GiveItemCreate("staf06","tellan",0,0,0)
  SetGlobal("fl30t07","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("tellan")
  Global("fl30t08","GLOBAL",2)
THEN RESPONSE #100
  GiveItemCreate("sw1h23","tellan",0,0,0)
  SetGlobal("fl30t08","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("tellan")
  Global("fl30t09","GLOBAL",2)
THEN RESPONSE #100
  GiveItemCreate("wand10","tellan",5,0,0)
  SetGlobal("fl30t09","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("tellan")
  Global("fl30t10","GLOBAL",2)
THEN RESPONSE #100
  GiveItemCreate("wand10","tellan",6,0,0)
  SetGlobal("fl30t10","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("tellan")
  Global("fl30t11","GLOBAL",2)
THEN RESPONSE #100
  GiveItemCreate("staf07","tellan",0,0,0)
  SetGlobal("fl30t11","GLOBAL",-1)
  DestroySelf()
END
