
IF
  Exists("chest01")
  Global("fl30t01","GLOBAL",7)
THEN RESPONSE #100
  ActionOverride("chest01",CreateItem("amul17",10,0,0))
  SetGlobal("fl30t01","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("chest01")
  Global("fl30t02","GLOBAL",7)
THEN RESPONSE #100
  ActionOverride("chest01",CreateItem("blun11",0,0,0))
  SetGlobal("fl30t02","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("chest01")
  Global("fl30t03","GLOBAL",7)
THEN RESPONSE #100
  ActionOverride("chest01",CreateItem("ring05",7,0,0))
  SetGlobal("fl30t03","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("chest01")
  Global("fl30t05","GLOBAL",7)
THEN RESPONSE #100
  ActionOverride("chest01",CreateItem("leat09",0,0,0))
  SetGlobal("fl30t05","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("chest01")
  Global("fl30t07","GLOBAL",7)
THEN RESPONSE #100
  ActionOverride("chest01",CreateItem("staf06",0,0,0))
  SetGlobal("fl30t07","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("chest01")
  Global("fl30t08","GLOBAL",7)
THEN RESPONSE #100
  ActionOverride("chest01",CreateItem("sw1h23",0,0,0))
  SetGlobal("fl30t08","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("chest01")
  Global("fl30t09","GLOBAL",7)
THEN RESPONSE #100
  ActionOverride("chest01",CreateItem("wand10",5,0,0))
  SetGlobal("fl30t09","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("chest01")
  Global("fl30t10","GLOBAL",7)
THEN RESPONSE #100
  ActionOverride("chest01",CreateItem("wand10",6,0,0))
  SetGlobal("fl30t10","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("chest01")
  Global("fl30t11","GLOBAL",7)
THEN RESPONSE #100
  ActionOverride("chest01",CreateItem("staf07",0,0,0))
  SetGlobal("fl30t11","GLOBAL",-1)
  DestroySelf()
END
