
IF
  Exists("islsir")
  Global("fl30t01","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("amul17","islsir",10,0,0)
  SetGlobal("fl30t01","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("islsir")
  Global("fl30t02","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("blun11","islsir",0,0,0)
  SetGlobal("fl30t02","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("islsir")
  Global("fl30t03","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("ring05","islsir",7,0,0)
  SetGlobal("fl30t03","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("islsir")
  Global("fl30t05","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("leat09","islsir",0,0,0)
  SetGlobal("fl30t05","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("islsir")
  Global("fl30t07","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("staf06","islsir",0,0,0)
  SetGlobal("fl30t07","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("islsir")
  Global("fl30t08","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("sw1h23","islsir",0,0,0)
  SetGlobal("fl30t08","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("islsir")
  Global("fl30t09","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("wand10","islsir",5,0,0)
  SetGlobal("fl30t09","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("islsir")
  Global("fl30t10","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("wand10","islsir",6,0,0)
  SetGlobal("fl30t10","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("islsir")
  Global("fl30t11","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("staf07","islsir",0,0,0)
  SetGlobal("fl30t11","GLOBAL",-1)
  DestroySelf()
END
