
IF
  Exists("chest01")
  Global("fl31t01","GLOBAL",5)
THEN RESPONSE #100
  ActionOverride("chest01",CreateItem("clck03",0,0,0))
  SetGlobal("fl31t01","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("chest01")
  Global("fl31t02","GLOBAL",5)
THEN RESPONSE #100
  ActionOverride("chest01",CreateItem("plat08",0,0,0))
  SetGlobal("fl31t02","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("chest01")
  Global("fl31t03","GLOBAL",5)
THEN RESPONSE #100
  ActionOverride("chest01",CreateItem("sw1h24",0,0,0))
  SetGlobal("fl31t03","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("chest01")
  Global("fl31t04","GLOBAL",5)
THEN RESPONSE #100
  ActionOverride("chest01",CreateItem("sw2h07_",0,0,0))
  SetGlobal("fl31t04","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("chest01")
  Global("fl31t05","GLOBAL",5)
THEN RESPONSE #100
  ActionOverride("chest01",CreateItem("staf05",20,0,0))
  SetGlobal("fl31t05","GLOBAL",-1)
  DestroySelf()
END
