
IF
  Exists("container36")
  Global("fl31t01","GLOBAL",4)
THEN RESPONSE #100
  ActionOverride("container36",CreateItem("clck03",0,0,0))
  SetGlobal("fl31t01","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("container36")
  Global("fl31t02","GLOBAL",4)
THEN RESPONSE #100
  ActionOverride("container36",CreateItem("plat08",0,0,0))
  SetGlobal("fl31t02","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("container36")
  Global("fl31t03","GLOBAL",4)
THEN RESPONSE #100
  ActionOverride("container36",CreateItem("sw1h24",0,0,0))
  SetGlobal("fl31t03","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("container36")
  Global("fl31t04","GLOBAL",4)
THEN RESPONSE #100
  ActionOverride("container36",CreateItem("sw2h07_",0,0,0))
  SetGlobal("fl31t04","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("container36")
  Global("fl31t05","GLOBAL",4)
THEN RESPONSE #100
  ActionOverride("container36",CreateItem("staf05",20,0,0))
  SetGlobal("fl31t05","GLOBAL",-1)
  DestroySelf()
END
