
IF
  Exists("tarnor")
  Global("fl3t01","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("belt06","tarnor",1,0,0)
  SetGlobal("fl3t01","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("draug")
  Global("fl3t02","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("ring31","draug",0,0,0)
  SetGlobal("fl3t02","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("rengaa")
  Global("fl3t03","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("helm20","rengaa",0,0,0)
  SetGlobal("fl3t03","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("draug")
  Global("fl3t04","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("clck03","draug",0,0,0)
  SetGlobal("fl3t04","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("tarnor")
  Global("fl3t05","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("slng05","tarnor",0,0,0)
  SetGlobal("fl3t05","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("gaius")
  Global("fl3t07","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("clck15","gaius",0,0,0)
  SetGlobal("fl3t07","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("draug")
  Global("fl3t08","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("clck16","draug",0,0,0)
  SetGlobal("fl3t08","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("gaius")
  Global("fl3t09","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("clck17","gaius",0,0,0)
  SetGlobal("fl3t09","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("tarnor")
  Global("fl3t10","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("halb09a","tarnor",0,0,0)
  SetGlobal("fl3t10","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("gaius")
  Global("fl3t11","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("blun24","gaius",0,0,0)
  SetGlobal("fl3t11","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("draug")
  Global("fl3t12","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("brac11","draug",0,0,0)
  SetGlobal("fl3t12","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("gall")
  Global("fl3t13","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("leat13","gall",0,0,0)
  SetGlobal("fl3t13","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("gaius")
  Global("fl3t14","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("misc3m","gaius",3,0,0)
  SetGlobal("fl3t14","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("rengaa")
  Global("fl3t15","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("misc3o","rengaa",3,0,0)
  SetGlobal("fl3t15","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("gaius")
  Global("fl3t16","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("hamm03","gaius",0,0,0)
  SetGlobal("fl3t16","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("gaius")
  Global("fl3t17","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("clck24","gaius",0,0,0)
  SetGlobal("fl3t17","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("draug")
  Global("fl3t18","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("chan09","draug",0,0,0)
  SetGlobal("fl3t18","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("gall")
  Global("fl3t19","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("halb08","gall",0,0,0)
  SetGlobal("fl3t19","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("gaius")
  Global("fl3t20","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("sper07","gaius",0,0,0)
  SetGlobal("fl3t20","GLOBAL",-1)
  DestroySelf()
END
