
IF
  Exists("container4")
  Global("fl3t01","GLOBAL",8)
THEN RESPONSE #100
  ActionOverride("container4",CreateItem("belt06",1,0,0))
  SetGlobal("fl3t01","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("container4")
  Global("fl3t02","GLOBAL",8)
THEN RESPONSE #100
  ActionOverride("container4",CreateItem("ring31",0,0,0))
  SetGlobal("fl3t02","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("container4")
  Global("fl3t03","GLOBAL",8)
THEN RESPONSE #100
  ActionOverride("container4",CreateItem("helm20",0,0,0))
  SetGlobal("fl3t03","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("container4")
  Global("fl3t04","GLOBAL",8)
THEN RESPONSE #100
  ActionOverride("container4",CreateItem("clck03",0,0,0))
  SetGlobal("fl3t04","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("container4")
  Global("fl3t05","GLOBAL",8)
THEN RESPONSE #100
  ActionOverride("container4",CreateItem("slng05",0,0,0))
  SetGlobal("fl3t05","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("container4")
  Global("fl3t07","GLOBAL",8)
THEN RESPONSE #100
  ActionOverride("container4",CreateItem("clck15",0,0,0))
  SetGlobal("fl3t07","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("container4")
  Global("fl3t08","GLOBAL",8)
THEN RESPONSE #100
  ActionOverride("container4",CreateItem("clck16",0,0,0))
  SetGlobal("fl3t08","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("container4")
  Global("fl3t09","GLOBAL",8)
THEN RESPONSE #100
  ActionOverride("container4",CreateItem("clck17",0,0,0))
  SetGlobal("fl3t09","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("container4")
  Global("fl3t10","GLOBAL",8)
THEN RESPONSE #100
  ActionOverride("container4",CreateItem("halb09a",0,0,0))
  SetGlobal("fl3t10","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("container4")
  Global("fl3t11","GLOBAL",8)
THEN RESPONSE #100
  ActionOverride("container4",CreateItem("blun24",0,0,0))
  SetGlobal("fl3t11","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("container4")
  Global("fl3t12","GLOBAL",8)
THEN RESPONSE #100
  ActionOverride("container4",CreateItem("brac11",0,0,0))
  SetGlobal("fl3t12","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("container4")
  Global("fl3t13","GLOBAL",8)
THEN RESPONSE #100
  ActionOverride("container4",CreateItem("leat13",0,0,0))
  SetGlobal("fl3t13","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("container4")
  Global("fl3t14","GLOBAL",8)
THEN RESPONSE #100
  ActionOverride("container4",CreateItem("misc3m",3,0,0))
  SetGlobal("fl3t14","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("container4")
  Global("fl3t15","GLOBAL",8)
THEN RESPONSE #100
  ActionOverride("container4",CreateItem("misc3o",3,0,0))
  SetGlobal("fl3t15","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("container4")
  Global("fl3t16","GLOBAL",8)
THEN RESPONSE #100
  ActionOverride("container4",CreateItem("hamm03",0,0,0))
  SetGlobal("fl3t16","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("container4")
  Global("fl3t17","GLOBAL",8)
THEN RESPONSE #100
  ActionOverride("container4",CreateItem("clck24",0,0,0))
  SetGlobal("fl3t17","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("container4")
  Global("fl3t18","GLOBAL",8)
THEN RESPONSE #100
  ActionOverride("container4",CreateItem("chan09",0,0,0))
  SetGlobal("fl3t18","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("container4")
  Global("fl3t19","GLOBAL",8)
THEN RESPONSE #100
  ActionOverride("container4",CreateItem("halb08",0,0,0))
  SetGlobal("fl3t19","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("container4")
  Global("fl3t20","GLOBAL",8)
THEN RESPONSE #100
  ActionOverride("container4",CreateItem("sper07",0,0,0))
  SetGlobal("fl3t20","GLOBAL",-1)
  DestroySelf()
END
