
IF
  Exists("tazok")
  Global("fl3t01","GLOBAL",7)
THEN RESPONSE #100
  GiveItemCreate("belt06","tazok",1,0,0)
  SetGlobal("fl3t01","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("tazok")
  Global("fl3t02","GLOBAL",7)
THEN RESPONSE #100
  GiveItemCreate("ring31","tazok",0,0,0)
  SetGlobal("fl3t02","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("tazok")
  Global("fl3t03","GLOBAL",7)
THEN RESPONSE #100
  GiveItemCreate("helm20","tazok",0,0,0)
  SetGlobal("fl3t03","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("tazok")
  Global("fl3t04","GLOBAL",7)
THEN RESPONSE #100
  GiveItemCreate("clck03","tazok",0,0,0)
  SetGlobal("fl3t04","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("tazok")
  Global("fl3t05","GLOBAL",7)
THEN RESPONSE #100
  GiveItemCreate("slng05","tazok",0,0,0)
  SetGlobal("fl3t05","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("tazok")
  Global("fl3t07","GLOBAL",7)
THEN RESPONSE #100
  GiveItemCreate("clck15","tazok",0,0,0)
  SetGlobal("fl3t07","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("tazok")
  Global("fl3t08","GLOBAL",7)
THEN RESPONSE #100
  GiveItemCreate("clck16","tazok",0,0,0)
  SetGlobal("fl3t08","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("tazok")
  Global("fl3t09","GLOBAL",7)
THEN RESPONSE #100
  GiveItemCreate("clck17","tazok",0,0,0)
  SetGlobal("fl3t09","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("tazok")
  Global("fl3t10","GLOBAL",7)
THEN RESPONSE #100
  GiveItemCreate("halb09a","tazok",0,0,0)
  SetGlobal("fl3t10","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("tazok")
  Global("fl3t11","GLOBAL",7)
THEN RESPONSE #100
  GiveItemCreate("blun24","tazok",0,0,0)
  SetGlobal("fl3t11","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("tazok")
  Global("fl3t12","GLOBAL",7)
THEN RESPONSE #100
  GiveItemCreate("brac11","tazok",0,0,0)
  SetGlobal("fl3t12","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("tazok")
  Global("fl3t13","GLOBAL",7)
THEN RESPONSE #100
  GiveItemCreate("leat13","tazok",0,0,0)
  SetGlobal("fl3t13","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("tazok")
  Global("fl3t14","GLOBAL",7)
THEN RESPONSE #100
  GiveItemCreate("misc3m","tazok",3,0,0)
  SetGlobal("fl3t14","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("tazok")
  Global("fl3t15","GLOBAL",7)
THEN RESPONSE #100
  GiveItemCreate("misc3o","tazok",3,0,0)
  SetGlobal("fl3t15","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("tazok")
  Global("fl3t16","GLOBAL",7)
THEN RESPONSE #100
  GiveItemCreate("hamm03","tazok",0,0,0)
  SetGlobal("fl3t16","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("tazok")
  Global("fl3t17","GLOBAL",7)
THEN RESPONSE #100
  GiveItemCreate("clck24","tazok",0,0,0)
  SetGlobal("fl3t17","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("tazok")
  Global("fl3t18","GLOBAL",7)
THEN RESPONSE #100
  GiveItemCreate("chan09","tazok",0,0,0)
  SetGlobal("fl3t18","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("tazok")
  Global("fl3t19","GLOBAL",7)
THEN RESPONSE #100
  GiveItemCreate("halb08","tazok",0,0,0)
  SetGlobal("fl3t19","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("tazok")
  Global("fl3t20","GLOBAL",7)
THEN RESPONSE #100
  GiveItemCreate("sper07","tazok",0,0,0)
  SetGlobal("fl3t20","GLOBAL",-1)
  DestroySelf()
END
