
IF
  Exists("trrak01")
  Global("fl3t01","GLOBAL",9)
THEN RESPONSE #100
  GiveItemCreate("belt06","trrak01",1,0,0)
  SetGlobal("fl3t01","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("trrak01")
  Global("fl3t02","GLOBAL",9)
THEN RESPONSE #100
  GiveItemCreate("ring31","trrak01",0,0,0)
  SetGlobal("fl3t02","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("trrak01")
  Global("fl3t03","GLOBAL",9)
THEN RESPONSE #100
  GiveItemCreate("helm20","trrak01",0,0,0)
  SetGlobal("fl3t03","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("trrak01")
  Global("fl3t04","GLOBAL",9)
THEN RESPONSE #100
  GiveItemCreate("clck03","trrak01",0,0,0)
  SetGlobal("fl3t04","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("trrak01")
  Global("fl3t05","GLOBAL",9)
THEN RESPONSE #100
  GiveItemCreate("slng05","trrak01",0,0,0)
  SetGlobal("fl3t05","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("trrak01")
  Global("fl3t07","GLOBAL",9)
THEN RESPONSE #100
  GiveItemCreate("clck15","trrak01",0,0,0)
  SetGlobal("fl3t07","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("trrak01")
  Global("fl3t08","GLOBAL",9)
THEN RESPONSE #100
  GiveItemCreate("clck16","trrak01",0,0,0)
  SetGlobal("fl3t08","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("trrak01")
  Global("fl3t09","GLOBAL",9)
THEN RESPONSE #100
  GiveItemCreate("clck17","trrak01",0,0,0)
  SetGlobal("fl3t09","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("trrak01")
  Global("fl3t10","GLOBAL",9)
THEN RESPONSE #100
  GiveItemCreate("halb09a","trrak01",0,0,0)
  SetGlobal("fl3t10","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("trrak01")
  Global("fl3t11","GLOBAL",9)
THEN RESPONSE #100
  GiveItemCreate("blun24","trrak01",0,0,0)
  SetGlobal("fl3t11","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("trrak01")
  Global("fl3t12","GLOBAL",9)
THEN RESPONSE #100
  GiveItemCreate("brac11","trrak01",0,0,0)
  SetGlobal("fl3t12","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("trrak01")
  Global("fl3t13","GLOBAL",9)
THEN RESPONSE #100
  GiveItemCreate("leat13","trrak01",0,0,0)
  SetGlobal("fl3t13","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("trrak01")
  Global("fl3t14","GLOBAL",9)
THEN RESPONSE #100
  GiveItemCreate("misc3m","trrak01",3,0,0)
  SetGlobal("fl3t14","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("trrak01")
  Global("fl3t15","GLOBAL",9)
THEN RESPONSE #100
  GiveItemCreate("misc3o","trrak01",3,0,0)
  SetGlobal("fl3t15","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("trrak01")
  Global("fl3t16","GLOBAL",9)
THEN RESPONSE #100
  GiveItemCreate("hamm03","trrak01",0,0,0)
  SetGlobal("fl3t16","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("trrak01")
  Global("fl3t17","GLOBAL",9)
THEN RESPONSE #100
  GiveItemCreate("clck24","trrak01",0,0,0)
  SetGlobal("fl3t17","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("trrak01")
  Global("fl3t18","GLOBAL",9)
THEN RESPONSE #100
  GiveItemCreate("chan09","trrak01",0,0,0)
  SetGlobal("fl3t18","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("trrak01")
  Global("fl3t19","GLOBAL",9)
THEN RESPONSE #100
  GiveItemCreate("halb08","trrak01",0,0,0)
  SetGlobal("fl3t19","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("trrak01")
  Global("fl3t20","GLOBAL",9)
THEN RESPONSE #100
  GiveItemCreate("sper07","trrak01",0,0,0)
  SetGlobal("fl3t20","GLOBAL",-1)
  DestroySelf()
END
