
IF
  Exists("rngsha02")
  Global("fl3t01","GLOBAL",15)
THEN RESPONSE #100
  GiveItemCreate("belt06","rngsha02",1,0,0)
  SetGlobal("fl3t01","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("rngsha02")
  Global("fl3t02","GLOBAL",15)
THEN RESPONSE #100
  GiveItemCreate("ring31","rngsha02",0,0,0)
  SetGlobal("fl3t02","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("rngsha02")
  Global("fl3t03","GLOBAL",15)
THEN RESPONSE #100
  GiveItemCreate("helm20","rngsha02",0,0,0)
  SetGlobal("fl3t03","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("rngsha02")
  Global("fl3t04","GLOBAL",15)
THEN RESPONSE #100
  GiveItemCreate("clck03","rngsha02",0,0,0)
  SetGlobal("fl3t04","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("rngsha02")
  Global("fl3t05","GLOBAL",15)
THEN RESPONSE #100
  GiveItemCreate("slng05","rngsha02",0,0,0)
  SetGlobal("fl3t05","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("rngsha02")
  Global("fl3t07","GLOBAL",15)
THEN RESPONSE #100
  GiveItemCreate("clck15","rngsha02",0,0,0)
  SetGlobal("fl3t07","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("rngsha02")
  Global("fl3t08","GLOBAL",15)
THEN RESPONSE #100
  GiveItemCreate("clck16","rngsha02",0,0,0)
  SetGlobal("fl3t08","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("rngsha02")
  Global("fl3t09","GLOBAL",15)
THEN RESPONSE #100
  GiveItemCreate("clck17","rngsha02",0,0,0)
  SetGlobal("fl3t09","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("rngsha02")
  Global("fl3t10","GLOBAL",15)
THEN RESPONSE #100
  GiveItemCreate("halb09a","rngsha02",0,0,0)
  SetGlobal("fl3t10","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("rngsha02")
  Global("fl3t11","GLOBAL",15)
THEN RESPONSE #100
  GiveItemCreate("blun24","rngsha02",0,0,0)
  SetGlobal("fl3t11","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("rngsha02")
  Global("fl3t12","GLOBAL",15)
THEN RESPONSE #100
  GiveItemCreate("brac11","rngsha02",0,0,0)
  SetGlobal("fl3t12","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("rngsha02")
  Global("fl3t13","GLOBAL",15)
THEN RESPONSE #100
  GiveItemCreate("leat13","rngsha02",0,0,0)
  SetGlobal("fl3t13","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("rngsha02")
  Global("fl3t14","GLOBAL",15)
THEN RESPONSE #100
  GiveItemCreate("misc3m","rngsha02",3,0,0)
  SetGlobal("fl3t14","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("rngsha02")
  Global("fl3t15","GLOBAL",15)
THEN RESPONSE #100
  GiveItemCreate("misc3o","rngsha02",3,0,0)
  SetGlobal("fl3t15","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("rngsha02")
  Global("fl3t16","GLOBAL",15)
THEN RESPONSE #100
  GiveItemCreate("hamm03","rngsha02",0,0,0)
  SetGlobal("fl3t16","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("rngsha02")
  Global("fl3t17","GLOBAL",15)
THEN RESPONSE #100
  GiveItemCreate("clck24","rngsha02",0,0,0)
  SetGlobal("fl3t17","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("rngsha02")
  Global("fl3t18","GLOBAL",15)
THEN RESPONSE #100
  GiveItemCreate("chan09","rngsha02",0,0,0)
  SetGlobal("fl3t18","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("rngsha02")
  Global("fl3t19","GLOBAL",15)
THEN RESPONSE #100
  GiveItemCreate("halb08","rngsha02",0,0,0)
  SetGlobal("fl3t19","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("rngsha02")
  Global("fl3t20","GLOBAL",15)
THEN RESPONSE #100
  GiveItemCreate("sper07","rngsha02",0,0,0)
  SetGlobal("fl3t20","GLOBAL",-1)
  DestroySelf()
END
