
IF
  Exists("AR18ARCH")
  Global("fl3t01","GLOBAL",20)
THEN RESPONSE #100
  GiveItemCreate("belt06","AR18ARCH",1,0,0)
  SetGlobal("fl3t01","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("AR18ARCH")
  Global("fl3t02","GLOBAL",20)
THEN RESPONSE #100
  GiveItemCreate("ring31","AR18ARCH",0,0,0)
  SetGlobal("fl3t02","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("AR18PRIE")
  Global("fl3t03","GLOBAL",20)
THEN RESPONSE #100
  GiveItemCreate("helm20","AR18PRIE",0,0,0)
  SetGlobal("fl3t03","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("ar18Mage")
  Global("fl3t04","GLOBAL",20)
THEN RESPONSE #100
  GiveItemCreate("clck03","ar18Mage",0,0,0)
  SetGlobal("fl3t04","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("gpthief1")
  Global("fl3t05","GLOBAL",20)
THEN RESPONSE #100
  GiveItemCreate("slng05","gpthief1",0,0,0)
  SetGlobal("fl3t05","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("AR18ARCH")
  Global("fl3t07","GLOBAL",20)
THEN RESPONSE #100
  GiveItemCreate("clck15","AR18ARCH",0,0,0)
  SetGlobal("fl3t07","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("AR18PRIE")
  Global("fl3t08","GLOBAL",20)
THEN RESPONSE #100
  GiveItemCreate("clck16","AR18PRIE",0,0,0)
  SetGlobal("fl3t08","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("ar18Mage")
  Global("fl3t09","GLOBAL",20)
THEN RESPONSE #100
  GiveItemCreate("clck17","ar18Mage",0,0,0)
  SetGlobal("fl3t09","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("ar18Mage")
  Global("fl3t10","GLOBAL",20)
THEN RESPONSE #100
  GiveItemCreate("halb09a","ar18Mage",0,0,0)
  SetGlobal("fl3t10","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("gpfight1")
  Global("fl3t11","GLOBAL",20)
THEN RESPONSE #100
  GiveItemCreate("blun24","gpfight1",0,0,0)
  SetGlobal("fl3t11","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("AR18PRIE")
  Global("fl3t12","GLOBAL",20)
THEN RESPONSE #100
  GiveItemCreate("brac11","AR18PRIE",0,0,0)
  SetGlobal("fl3t12","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("gpthief1")
  Global("fl3t13","GLOBAL",20)
THEN RESPONSE #100
  GiveItemCreate("leat13","gpthief1",0,0,0)
  SetGlobal("fl3t13","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("gpthief1")
  Global("fl3t14","GLOBAL",20)
THEN RESPONSE #100
  GiveItemCreate("misc3m","gpthief1",3,0,0)
  SetGlobal("fl3t14","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("ar18Mage")
  Global("fl3t15","GLOBAL",20)
THEN RESPONSE #100
  GiveItemCreate("misc3o","ar18Mage",3,0,0)
  SetGlobal("fl3t15","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("ar18Mage")
  Global("fl3t16","GLOBAL",20)
THEN RESPONSE #100
  GiveItemCreate("hamm03","ar18Mage",0,0,0)
  SetGlobal("fl3t16","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("gpfight1")
  Global("fl3t17","GLOBAL",20)
THEN RESPONSE #100
  GiveItemCreate("clck24","gpfight1",0,0,0)
  SetGlobal("fl3t17","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("AR18PRIE")
  Global("fl3t18","GLOBAL",20)
THEN RESPONSE #100
  GiveItemCreate("chan09","AR18PRIE",0,0,0)
  SetGlobal("fl3t18","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("AR18PRIE")
  Global("fl3t19","GLOBAL",20)
THEN RESPONSE #100
  GiveItemCreate("halb08","AR18PRIE",0,0,0)
  SetGlobal("fl3t19","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("AR18PRIE")
  Global("fl3t20","GLOBAL",20)
THEN RESPONSE #100
  GiveItemCreate("sper07","AR18PRIE",0,0,0)
  SetGlobal("fl3t20","GLOBAL",-1)
  DestroySelf()
END
