
IF
  Exists("pbhunt04")
  Global("fl3t01","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("belt06","pbhunt04",1,0,0)
  SetGlobal("fl3t01","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("pbhunt03")
  Global("fl3t02","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("ring31","pbhunt03",0,0,0)
  SetGlobal("fl3t02","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("pbhunt03")
  Global("fl3t03","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("helm20","pbhunt03",0,0,0)
  SetGlobal("fl3t03","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("pbhunt05")
  Global("fl3t04","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("clck03","pbhunt05",0,0,0)
  SetGlobal("fl3t04","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("pbhunt05")
  Global("fl3t05","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("slng05","pbhunt05",0,0,0)
  SetGlobal("fl3t05","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("pbhunt05")
  Global("fl3t07","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("clck15","pbhunt05",0,0,0)
  SetGlobal("fl3t07","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("pbhunt05")
  Global("fl3t08","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("clck16","pbhunt05",0,0,0)
  SetGlobal("fl3t08","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("pbhunt03")
  Global("fl3t09","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("clck17","pbhunt03",0,0,0)
  SetGlobal("fl3t09","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("pbhunt05")
  Global("fl3t10","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("halb09a","pbhunt05",0,0,0)
  SetGlobal("fl3t10","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("pbhunt01")
  Global("fl3t11","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("blun24","pbhunt01",0,0,0)
  SetGlobal("fl3t11","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("pbhunt01")
  Global("fl3t12","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("brac11","pbhunt01",0,0,0)
  SetGlobal("fl3t12","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("pbhunt01")
  Global("fl3t13","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("leat13","pbhunt01",0,0,0)
  SetGlobal("fl3t13","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("pbhunt01")
  Global("fl3t14","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("misc3m","pbhunt01",3,0,0)
  SetGlobal("fl3t14","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("pbhunt01")
  Global("fl3t15","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("misc3o","pbhunt01",3,0,0)
  SetGlobal("fl3t15","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("pbhunt03")
  Global("fl3t16","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("hamm03","pbhunt03",0,0,0)
  SetGlobal("fl3t16","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("pbhunt03")
  Global("fl3t17","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("clck24","pbhunt03",0,0,0)
  SetGlobal("fl3t17","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("pbhunt01")
  Global("fl3t18","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("chan09","pbhunt01",0,0,0)
  SetGlobal("fl3t18","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("pbhunt05")
  Global("fl3t19","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("halb08","pbhunt05",0,0,0)
  SetGlobal("fl3t19","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("pbhunt03")
  Global("fl3t20","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("sper07","pbhunt03",0,0,0)
  SetGlobal("fl3t20","GLOBAL",-1)
  DestroySelf()
END
