
IF
  Exists("container11")
  Global("fl4t01","GLOBAL",10)
THEN RESPONSE #100
  ActionOverride("container11",CreateItem("amul25",0,0,0))
  SetGlobal("fl4t01","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("container11")
  Global("fl4t02","GLOBAL",10)
THEN RESPONSE #100
  ActionOverride("container11",CreateItem("sw1h33",0,1,0))
  SetGlobal("fl4t02","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("container11")
  Global("fl4t03","GLOBAL",10)
THEN RESPONSE #100
  ActionOverride("container11",CreateItem("staf16",0,30,30))
  SetGlobal("fl4t03","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("container11")
  Global("fl4t04","GLOBAL",10)
THEN RESPONSE #100
  ActionOverride("container11",CreateItem("staf17",1,20,20))
  SetGlobal("fl4t04","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("container11")
  Global("fl4t05","GLOBAL",10)
THEN RESPONSE #100
  ActionOverride("container11",CreateItem("brac06",0,0,0))
  SetGlobal("fl4t05","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("container11")
  Global("fl4t06","GLOBAL",10)
THEN RESPONSE #100
  ActionOverride("container11",CreateItem("brac15",0,0,0))
  SetGlobal("fl4t06","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("container11")
  Global("fl4t07","GLOBAL",10)
THEN RESPONSE #100
  ActionOverride("container11",CreateItem("halb04",0,0,0))
  SetGlobal("fl4t07","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("container11")
  Global("fl4t08","GLOBAL",10)
THEN RESPONSE #100
  ActionOverride("container11",CreateItem("sw1h35",0,0,0))
  SetGlobal("fl4t08","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("container11")
  Global("fl4t09","GLOBAL",10)
THEN RESPONSE #100
  ActionOverride("container11",CreateItem("sw1h54a",0,0,0))
  SetGlobal("fl4t09","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("container11")
  Global("fl4t10","GLOBAL",10)
THEN RESPONSE #100
  ActionOverride("container11",CreateItem("bow19a",0,0,0))
  SetGlobal("fl4t10","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("container11")
  Global("fl4t12","GLOBAL",10)
THEN RESPONSE #100
  ActionOverride("container11",CreateItem("dagg13",0,0,0))
  SetGlobal("fl4t12","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("container11")
  Global("fl4t13","GLOBAL",10)
THEN RESPONSE #100
  ActionOverride("container11",CreateItem("brac08",0,0,0))
  SetGlobal("fl4t13","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("container11")
  Global("fl4t14","GLOBAL",10)
THEN RESPONSE #100
  ActionOverride("container11",CreateItem("shld22",0,0,0))
  SetGlobal("fl4t14","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("container11")
  Global("fl4t15","GLOBAL",10)
THEN RESPONSE #100
  ActionOverride("container11",CreateItem("bow09",0,0,0))
  SetGlobal("fl4t15","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("container11")
  Global("fl4t16","GLOBAL",10)
THEN RESPONSE #100
  ActionOverride("container11",CreateItem("boot04",0,0,0))
  SetGlobal("fl4t16","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("container11")
  Global("fl4t17","GLOBAL",10)
THEN RESPONSE #100
  ActionOverride("container11",CreateItem("sw1h52",0,0,0))
  SetGlobal("fl4t17","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("container11")
  Global("fl4t18","GLOBAL",10)
THEN RESPONSE #100
  ActionOverride("container11",CreateItem("blun22",0,0,0))
  SetGlobal("fl4t18","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("container11")
  Global("fl4t19","GLOBAL",10)
THEN RESPONSE #100
  ActionOverride("container11",CreateItem("sw1h36",0,3,0))
  SetGlobal("fl4t19","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("container11")
  Global("fl4t20","GLOBAL",10)
THEN RESPONSE #100
  ActionOverride("container11",CreateItem("misc3a",1,0,0))
  SetGlobal("fl4t20","GLOBAL",-1)
  DestroySelf()
END
