
IF
  Exists("pwarden")
  Global("fl4t01","GLOBAL",9)
THEN RESPONSE #100
  GiveItemCreate("amul25","pwarden",0,0,0)
  SetGlobal("fl4t01","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("pwarden")
  Global("fl4t02","GLOBAL",9)
THEN RESPONSE #100
  GiveItemCreate("sw1h33","pwarden",0,1,0)
  SetGlobal("fl4t02","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("pwarden")
  Global("fl4t03","GLOBAL",9)
THEN RESPONSE #100
  GiveItemCreate("staf16","pwarden",0,30,30)
  SetGlobal("fl4t03","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("pwarden")
  Global("fl4t04","GLOBAL",9)
THEN RESPONSE #100
  GiveItemCreate("staf17","pwarden",1,20,20)
  SetGlobal("fl4t04","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("pwarden")
  Global("fl4t05","GLOBAL",9)
THEN RESPONSE #100
  GiveItemCreate("brac06","pwarden",0,0,0)
  SetGlobal("fl4t05","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("pwarden")
  Global("fl4t06","GLOBAL",9)
THEN RESPONSE #100
  GiveItemCreate("brac15","pwarden",0,0,0)
  SetGlobal("fl4t06","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("pwarden")
  Global("fl4t07","GLOBAL",9)
THEN RESPONSE #100
  GiveItemCreate("halb04","pwarden",0,0,0)
  SetGlobal("fl4t07","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("pwarden")
  Global("fl4t08","GLOBAL",9)
THEN RESPONSE #100
  GiveItemCreate("sw1h35","pwarden",0,0,0)
  SetGlobal("fl4t08","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("pwarden")
  Global("fl4t09","GLOBAL",9)
THEN RESPONSE #100
  GiveItemCreate("sw1h54a","pwarden",0,0,0)
  SetGlobal("fl4t09","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("pwarden")
  Global("fl4t10","GLOBAL",9)
THEN RESPONSE #100
  GiveItemCreate("bow19a","pwarden",0,0,0)
  SetGlobal("fl4t10","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("pwarden")
  Global("fl4t12","GLOBAL",9)
THEN RESPONSE #100
  GiveItemCreate("dagg13","pwarden",0,0,0)
  SetGlobal("fl4t12","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("pwarden")
  Global("fl4t13","GLOBAL",9)
THEN RESPONSE #100
  GiveItemCreate("brac08","pwarden",0,0,0)
  SetGlobal("fl4t13","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("pwarden")
  Global("fl4t14","GLOBAL",9)
THEN RESPONSE #100
  GiveItemCreate("shld22","pwarden",0,0,0)
  SetGlobal("fl4t14","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("pwarden")
  Global("fl4t15","GLOBAL",9)
THEN RESPONSE #100
  GiveItemCreate("bow09","pwarden",0,0,0)
  SetGlobal("fl4t15","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("pwarden")
  Global("fl4t16","GLOBAL",9)
THEN RESPONSE #100
  GiveItemCreate("boot04","pwarden",0,0,0)
  SetGlobal("fl4t16","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("pwarden")
  Global("fl4t17","GLOBAL",9)
THEN RESPONSE #100
  GiveItemCreate("sw1h52","pwarden",0,0,0)
  SetGlobal("fl4t17","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("pwarden")
  Global("fl4t18","GLOBAL",9)
THEN RESPONSE #100
  GiveItemCreate("blun22","pwarden",0,0,0)
  SetGlobal("fl4t18","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("pwarden")
  Global("fl4t19","GLOBAL",9)
THEN RESPONSE #100
  GiveItemCreate("sw1h36","pwarden",0,3,0)
  SetGlobal("fl4t19","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("pwarden")
  Global("fl4t20","GLOBAL",9)
THEN RESPONSE #100
  GiveItemCreate("misc3a","pwarden",1,0,0)
  SetGlobal("fl4t20","GLOBAL",-1)
  DestroySelf()
END
