
IF
  Exists("wyvfight")
  Global("fl5t01","GLOBAL",14)
THEN RESPONSE #100
  GiveItemCreate("ring27","wyvfight",1,1,1)
  SetGlobal("fl5t01","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("wyvmag14")
  Global("fl5t02","GLOBAL",14)
THEN RESPONSE #100
  GiveItemCreate("blun12","wyvmag14",0,0,0)
  SetGlobal("fl5t02","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("wyvfight")
  Global("fl5t03","GLOBAL",14)
THEN RESPONSE #100
  GiveItemCreate("bow13","wyvfight",0,0,0)
  SetGlobal("fl5t03","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("wyvmag14")
  Global("fl5t04","GLOBAL",14)
THEN RESPONSE #100
  GiveItemCreate("xbow06","wyvmag14",0,0,0)
  SetGlobal("fl5t04","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("wyvfight")
  Global("fl5t05","GLOBAL",14)
THEN RESPONSE #100
  GiveItemCreate("belt10","wyvfight",0,0,0)
  SetGlobal("fl5t05","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("wyvfight")
  Global("fl5t07","GLOBAL",14)
THEN RESPONSE #100
  GiveItemCreate("bow10","wyvfight",0,1,0)
  SetGlobal("fl5t07","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("wyvfight")
  Global("fl5t08","GLOBAL",14)
THEN RESPONSE #100
  GiveItemCreate("helm07","wyvfight",0,0,0)
  SetGlobal("fl5t08","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("wyvfight")
  Global("fl5t09","GLOBAL",14)
THEN RESPONSE #100
  GiveItemCreate("belt07","wyvfight",0,0,0)
  SetGlobal("fl5t09","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("wyvfight")
  Global("fl5t10","GLOBAL",14)
THEN RESPONSE #100
  GiveItemCreate("clck02","wyvfight",0,0,0)
  SetGlobal("fl5t10","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("wyvfight")
  Global("fl5t11","GLOBAL",14)
THEN RESPONSE #100
  GiveItemCreate("leat20","wyvfight",1,0,0)
  SetGlobal("fl5t11","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("wyvfight")
  Global("fl5t12","GLOBAL",14)
THEN RESPONSE #100
  GiveItemCreate("ring23","wyvfight",0,0,0)
  SetGlobal("fl5t12","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("wyvmag14")
  Global("fl5t13","GLOBAL",14)
THEN RESPONSE #100
  GiveItemCreate("bow15","wyvmag14",0,0,0)
  SetGlobal("fl5t13","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("wyvfight")
  Global("fl5t14","GLOBAL",14)
THEN RESPONSE #100
  GiveItemCreate("hamm07","wyvfight",0,0,0)
  SetGlobal("fl5t14","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("wyvfight")
  Global("fl5t16","GLOBAL",14)
THEN RESPONSE #100
  GiveItemCreate("slng06","wyvfight",0,1,0)
  SetGlobal("fl5t16","GLOBAL",-1)
  DestroySelf()
END
