
IF
  Exists("suadsaan")
  Global("fl5t01","GLOBAL",6)
THEN RESPONSE #100
  GiveItemCreate("ring27","suadsaan",1,1,1)
  SetGlobal("fl5t01","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("suadsaan")
  Global("fl5t02","GLOBAL",6)
THEN RESPONSE #100
  GiveItemCreate("blun12","suadsaan",0,0,0)
  SetGlobal("fl5t02","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("suadsaan")
  Global("fl5t03","GLOBAL",6)
THEN RESPONSE #100
  GiveItemCreate("bow13","suadsaan",0,0,0)
  SetGlobal("fl5t03","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("suadsaan")
  Global("fl5t04","GLOBAL",6)
THEN RESPONSE #100
  GiveItemCreate("xbow06","suadsaan",0,0,0)
  SetGlobal("fl5t04","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("suadsaan")
  Global("fl5t05","GLOBAL",6)
THEN RESPONSE #100
  GiveItemCreate("belt10","suadsaan",0,0,0)
  SetGlobal("fl5t05","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("suadsaan")
  Global("fl5t07","GLOBAL",6)
THEN RESPONSE #100
  GiveItemCreate("bow10","suadsaan",0,1,0)
  SetGlobal("fl5t07","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("suadsaan")
  Global("fl5t08","GLOBAL",6)
THEN RESPONSE #100
  GiveItemCreate("helm07","suadsaan",0,0,0)
  SetGlobal("fl5t08","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("suadsaan")
  Global("fl5t09","GLOBAL",6)
THEN RESPONSE #100
  GiveItemCreate("belt07","suadsaan",0,0,0)
  SetGlobal("fl5t09","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("suadsaan")
  Global("fl5t10","GLOBAL",6)
THEN RESPONSE #100
  GiveItemCreate("clck02","suadsaan",0,0,0)
  SetGlobal("fl5t10","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("suadsaan")
  Global("fl5t11","GLOBAL",6)
THEN RESPONSE #100
  GiveItemCreate("leat20","suadsaan",1,0,0)
  SetGlobal("fl5t11","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("suadsaan")
  Global("fl5t12","GLOBAL",6)
THEN RESPONSE #100
  GiveItemCreate("ring23","suadsaan",0,0,0)
  SetGlobal("fl5t12","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("suadsaan")
  Global("fl5t13","GLOBAL",6)
THEN RESPONSE #100
  GiveItemCreate("bow15","suadsaan",0,0,0)
  SetGlobal("fl5t13","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("suadsaan")
  Global("fl5t14","GLOBAL",6)
THEN RESPONSE #100
  GiveItemCreate("hamm07","suadsaan",0,0,0)
  SetGlobal("fl5t14","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("suadsaan")
  Global("fl5t16","GLOBAL",6)
THEN RESPONSE #100
  GiveItemCreate("slng06","suadsaan",0,1,0)
  SetGlobal("fl5t16","GLOBAL",-1)
  DestroySelf()
END
