
IF
  Exists("hlstal")
  Global("fl5t01","GLOBAL",7)
THEN RESPONSE #100
  GiveItemCreate("ring27","hlstal",1,1,1)
  SetGlobal("fl5t01","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("hlkoshi")
  Global("fl5t02","GLOBAL",7)
THEN RESPONSE #100
  GiveItemCreate("blun12","hlkoshi",0,0,0)
  SetGlobal("fl5t02","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("hlsion")
  Global("fl5t03","GLOBAL",7)
THEN RESPONSE #100
  GiveItemCreate("bow13","hlsion",0,0,0)
  SetGlobal("fl5t03","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("hlsion")
  Global("fl5t04","GLOBAL",7)
THEN RESPONSE #100
  GiveItemCreate("xbow06","hlsion",0,0,0)
  SetGlobal("fl5t04","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("hlketta")
  Global("fl5t05","GLOBAL",7)
THEN RESPONSE #100
  GiveItemCreate("belt10","hlketta",0,0,0)
  SetGlobal("fl5t05","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("hlsion")
  Global("fl5t07","GLOBAL",7)
THEN RESPONSE #100
  GiveItemCreate("bow10","hlsion",0,1,0)
  SetGlobal("fl5t07","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("hlmafer")
  Global("fl5t08","GLOBAL",7)
THEN RESPONSE #100
  GiveItemCreate("helm07","hlmafer",0,0,0)
  SetGlobal("fl5t08","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("hlsion")
  Global("fl5t09","GLOBAL",7)
THEN RESPONSE #100
  GiveItemCreate("belt07","hlsion",0,0,0)
  SetGlobal("fl5t09","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("hlolaf")
  Global("fl5t10","GLOBAL",7)
THEN RESPONSE #100
  GiveItemCreate("clck02","hlolaf",0,0,0)
  SetGlobal("fl5t10","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("hlketta")
  Global("fl5t11","GLOBAL",7)
THEN RESPONSE #100
  GiveItemCreate("leat20","hlketta",1,0,0)
  SetGlobal("fl5t11","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("hlketta")
  Global("fl5t12","GLOBAL",7)
THEN RESPONSE #100
  GiveItemCreate("ring23","hlketta",0,0,0)
  SetGlobal("fl5t12","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("hlstal")
  Global("fl5t13","GLOBAL",7)
THEN RESPONSE #100
  GiveItemCreate("bow15","hlstal",0,0,0)
  SetGlobal("fl5t13","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("hlsion")
  Global("fl5t14","GLOBAL",7)
THEN RESPONSE #100
  GiveItemCreate("hamm07","hlsion",0,0,0)
  SetGlobal("fl5t14","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("hlstal")
  Global("fl5t16","GLOBAL",7)
THEN RESPONSE #100
  GiveItemCreate("slng06","hlstal",0,1,0)
  SetGlobal("fl5t16","GLOBAL",-1)
  DestroySelf()
END
