
IF
  Exists("chest6")
  Global("fl5t01","GLOBAL",10)
THEN RESPONSE #100
  ActionOverride("chest6",CreateItem("ring27",1,1,1))
  SetGlobal("fl5t01","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("chest6")
  Global("fl5t02","GLOBAL",10)
THEN RESPONSE #100
  ActionOverride("chest6",CreateItem("blun12",0,0,0))
  SetGlobal("fl5t02","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("chest6")
  Global("fl5t03","GLOBAL",10)
THEN RESPONSE #100
  ActionOverride("chest6",CreateItem("bow13",0,0,0))
  SetGlobal("fl5t03","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("chest6")
  Global("fl5t04","GLOBAL",10)
THEN RESPONSE #100
  ActionOverride("chest6",CreateItem("xbow06",0,0,0))
  SetGlobal("fl5t04","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("chest6")
  Global("fl5t05","GLOBAL",10)
THEN RESPONSE #100
  ActionOverride("chest6",CreateItem("belt10",0,0,0))
  SetGlobal("fl5t05","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("chest6")
  Global("fl5t07","GLOBAL",10)
THEN RESPONSE #100
  ActionOverride("chest6",CreateItem("bow10",0,1,0))
  SetGlobal("fl5t07","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("chest6")
  Global("fl5t08","GLOBAL",10)
THEN RESPONSE #100
  ActionOverride("chest6",CreateItem("helm07",0,0,0))
  SetGlobal("fl5t08","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("chest6")
  Global("fl5t09","GLOBAL",10)
THEN RESPONSE #100
  ActionOverride("chest6",CreateItem("belt07",0,0,0))
  SetGlobal("fl5t09","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("chest6")
  Global("fl5t10","GLOBAL",10)
THEN RESPONSE #100
  ActionOverride("chest6",CreateItem("clck02",0,0,0))
  SetGlobal("fl5t10","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("chest6")
  Global("fl5t11","GLOBAL",10)
THEN RESPONSE #100
  ActionOverride("chest6",CreateItem("leat20",1,0,0))
  SetGlobal("fl5t11","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("chest6")
  Global("fl5t12","GLOBAL",10)
THEN RESPONSE #100
  ActionOverride("chest6",CreateItem("ring23",0,0,0))
  SetGlobal("fl5t12","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("chest6")
  Global("fl5t13","GLOBAL",10)
THEN RESPONSE #100
  ActionOverride("chest6",CreateItem("bow15",0,0,0))
  SetGlobal("fl5t13","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("chest6")
  Global("fl5t14","GLOBAL",10)
THEN RESPONSE #100
  ActionOverride("chest6",CreateItem("hamm07",0,0,0))
  SetGlobal("fl5t14","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("chest6")
  Global("fl5t16","GLOBAL",10)
THEN RESPONSE #100
  ActionOverride("chest6",CreateItem("slng06",0,1,0))
  SetGlobal("fl5t16","GLOBAL",-1)
  DestroySelf()
END
