
IF
  Exists("gpfight1")
  Global("fl5t01","GLOBAL",5)
THEN RESPONSE #100
  GiveItemCreate("ring27","gpfight1",1,1,1)
  SetGlobal("fl5t01","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("gpfight1")
  Global("fl5t02","GLOBAL",5)
THEN RESPONSE #100
  GiveItemCreate("blun12","gpfight1",0,0,0)
  SetGlobal("fl5t02","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("gpsimb")
  Global("fl5t03","GLOBAL",5)
THEN RESPONSE #100
  GiveItemCreate("bow13","gpsimb",0,0,0)
  SetGlobal("fl5t03","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("gpsimb")
  Global("fl5t04","GLOBAL",5)
THEN RESPONSE #100
  GiveItemCreate("xbow06","gpsimb",0,0,0)
  SetGlobal("fl5t04","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("gpthief1")
  Global("fl5t05","GLOBAL",5)
THEN RESPONSE #100
  GiveItemCreate("belt10","gpthief1",0,0,0)
  SetGlobal("fl5t05","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("gpthief1")
  Global("fl5t07","GLOBAL",5)
THEN RESPONSE #100
  GiveItemCreate("bow10","gpthief1",0,1,0)
  SetGlobal("fl5t07","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("gpsimb")
  Global("fl5t08","GLOBAL",5)
THEN RESPONSE #100
  GiveItemCreate("helm07","gpsimb",0,0,0)
  SetGlobal("fl5t08","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("gpthief1")
  Global("fl5t09","GLOBAL",5)
THEN RESPONSE #100
  GiveItemCreate("belt07","gpthief1",0,0,0)
  SetGlobal("fl5t09","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("gppri1")
  Global("fl5t10","GLOBAL",5)
THEN RESPONSE #100
  GiveItemCreate("clck02","gppri1",0,0,0)
  SetGlobal("fl5t10","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("gpsimb")
  Global("fl5t11","GLOBAL",5)
THEN RESPONSE #100
  GiveItemCreate("leat20","gpsimb",1,0,0)
  SetGlobal("fl5t11","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("gpsimb")
  Global("fl5t12","GLOBAL",5)
THEN RESPONSE #100
  GiveItemCreate("ring23","gpsimb",0,0,0)
  SetGlobal("fl5t12","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("gpmage1")
  Global("fl5t13","GLOBAL",5)
THEN RESPONSE #100
  GiveItemCreate("bow15","gpmage1",0,0,0)
  SetGlobal("fl5t13","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("gpsimb")
  Global("fl5t14","GLOBAL",5)
THEN RESPONSE #100
  GiveItemCreate("hamm07","gpsimb",0,0,0)
  SetGlobal("fl5t14","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("gpsimb")
  Global("fl5t16","GLOBAL",5)
THEN RESPONSE #100
  GiveItemCreate("slng06","gpsimb",0,1,0)
  SetGlobal("fl5t16","GLOBAL",-1)
  DestroySelf()
END
