
IF
  Exists("udelder")
  Global("fl6t01","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("sw1h25","udelder",0,0,0)
  SetGlobal("fl6t01","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("udelder")
  Global("fl6t02","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("sw1h30","udelder",0,0,0)
  SetGlobal("fl6t02","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("udelder")
  Global("fl6t03","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("sw1h31","udelder",1,1,0)
  SetGlobal("fl6t03","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("udelder")
  Global("fl6t04","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("ring09","udelder",0,0,0)
  SetGlobal("fl6t04","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("udelder")
  Global("fl6t05","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("bow14","udelder",0,0,0)
  SetGlobal("fl6t05","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("udelder")
  Global("fl6t06","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("brac16","udelder",1,0,0)
  SetGlobal("fl6t06","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("udelder")
  Global("fl6t07","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("rods03","udelder",10,0,0)
  SetGlobal("fl6t07","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("udelder")
  Global("fl6t08","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("scrl07","udelder",1,0,0)
  SetGlobal("fl6t08","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("udelder")
  Global("fl6tx0","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("scrl07","udelder",0,0,0)
  SetGlobal("fl6tx0","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("udelder")
  Global("fl6t09","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("sw2h09","udelder",0,0,0)
  SetGlobal("fl6t09","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("udelder")
  Global("fl6t10","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("wasling","udelder",0,0,0)
  SetGlobal("fl6t10","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("udelder")
  Global("fl6t12","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("shld24","udelder",0,0,0)
  SetGlobal("fl6t12","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("udelder")
  Global("fl6t13","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("scrlag","udelder",0,0,0)
  SetGlobal("fl6t13","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("udelder")
  Global("fl6t14","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("sw1h54b","udelder",0,0,0)
  SetGlobal("fl6t14","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("udelder")
  Global("fl6t15","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("sper10","udelder",0,0,0)
  SetGlobal("fl6t15","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("udelder")
  Global("fl6t16","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("dagg12","udelder",0,0,0)
  SetGlobal("fl6t16","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("udelder")
  Global("fl6t17","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("helm16","udelder",1,1,1)
  SetGlobal("fl6t17","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("udelder")
  Global("fl6t18","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("dagg14","udelder",0,0,0)
  SetGlobal("fl6t18","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("udelder")
  Global("fl6t19","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("helm04","udelder",0,0,0)
  SetGlobal("fl6t19","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("udelder")
  Global("fl6t20","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("sw1h28","udelder",0,0,0)
  SetGlobal("fl6t20","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("udelder")
  Global("fl6t21","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("plat17","udelder",0,0,0)
  SetGlobal("fl6t21","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("udelder")
  Global("fl6t22","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("ring04","udelder",0,0,0)
  SetGlobal("fl6t22","GLOBAL",-1)
  DestroySelf()
END
