
IF
  Exists("uddoor08")
  Global("fl6t01","GLOBAL",15)
THEN RESPONSE #100
  GiveItemCreate("sw1h25","uddoor08",0,0,0)
  SetGlobal("fl6t01","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("uddoor09")
  Global("fl6t02","GLOBAL",15)
THEN RESPONSE #100
  GiveItemCreate("sw1h30","uddoor09",0,0,0)
  SetGlobal("fl6t02","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("uddoor08")
  Global("fl6t03","GLOBAL",15)
THEN RESPONSE #100
  GiveItemCreate("sw1h31","uddoor08",1,1,0)
  SetGlobal("fl6t03","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("uddoor06")
  Global("fl6t04","GLOBAL",15)
THEN RESPONSE #100
  GiveItemCreate("ring09","uddoor06",0,0,0)
  SetGlobal("fl6t04","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("uddoor08")
  Global("fl6t05","GLOBAL",15)
THEN RESPONSE #100
  GiveItemCreate("bow14","uddoor08",0,0,0)
  SetGlobal("fl6t05","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("uddoor05")
  Global("fl6t06","GLOBAL",15)
THEN RESPONSE #100
  GiveItemCreate("brac16","uddoor05",1,0,0)
  SetGlobal("fl6t06","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("uddoor08")
  Global("fl6t07","GLOBAL",15)
THEN RESPONSE #100
  GiveItemCreate("rods03","uddoor08",10,0,0)
  SetGlobal("fl6t07","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("uddoor06")
  Global("fl6t08","GLOBAL",15)
THEN RESPONSE #100
  GiveItemCreate("scrl07","uddoor06",1,0,0)
  SetGlobal("fl6t08","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("uddoor08")
  Global("fl6tx0","GLOBAL",15)
THEN RESPONSE #100
  GiveItemCreate("scrl07","uddoor08",0,0,0)
  SetGlobal("fl6tx0","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("uddoor08")
  Global("fl6t09","GLOBAL",15)
THEN RESPONSE #100
  GiveItemCreate("sw2h09","uddoor08",0,0,0)
  SetGlobal("fl6t09","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("uddoor05")
  Global("fl6t10","GLOBAL",15)
THEN RESPONSE #100
  GiveItemCreate("wasling","uddoor05",0,0,0)
  SetGlobal("fl6t10","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("uddoor05")
  Global("fl6t12","GLOBAL",15)
THEN RESPONSE #100
  GiveItemCreate("shld24","uddoor05",0,0,0)
  SetGlobal("fl6t12","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("uddoor08")
  Global("fl6t13","GLOBAL",15)
THEN RESPONSE #100
  GiveItemCreate("scrlag","uddoor08",0,0,0)
  SetGlobal("fl6t13","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("uddoor09")
  Global("fl6t14","GLOBAL",15)
THEN RESPONSE #100
  GiveItemCreate("sw1h54b","uddoor09",0,0,0)
  SetGlobal("fl6t14","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("uddoor09")
  Global("fl6t15","GLOBAL",15)
THEN RESPONSE #100
  GiveItemCreate("sper10","uddoor09",0,0,0)
  SetGlobal("fl6t15","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("uddoor06")
  Global("fl6t16","GLOBAL",15)
THEN RESPONSE #100
  GiveItemCreate("dagg12","uddoor06",0,0,0)
  SetGlobal("fl6t16","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("uddoor06")
  Global("fl6t17","GLOBAL",15)
THEN RESPONSE #100
  GiveItemCreate("helm16","uddoor06",1,1,1)
  SetGlobal("fl6t17","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("uddoor09")
  Global("fl6t18","GLOBAL",15)
THEN RESPONSE #100
  GiveItemCreate("dagg14","uddoor09",0,0,0)
  SetGlobal("fl6t18","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("uddoor06")
  Global("fl6t19","GLOBAL",15)
THEN RESPONSE #100
  GiveItemCreate("helm04","uddoor06",0,0,0)
  SetGlobal("fl6t19","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("uddoor05")
  Global("fl6t20","GLOBAL",15)
THEN RESPONSE #100
  GiveItemCreate("sw1h28","uddoor05",0,0,0)
  SetGlobal("fl6t20","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("uddoor06")
  Global("fl6t21","GLOBAL",15)
THEN RESPONSE #100
  GiveItemCreate("plat17","uddoor06",0,0,0)
  SetGlobal("fl6t21","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("uddoor06")
  Global("fl6t22","GLOBAL",15)
THEN RESPONSE #100
  GiveItemCreate("ring04","uddoor06",0,0,0)
  SetGlobal("fl6t22","GLOBAL",-1)
  DestroySelf()
END
