
IF
  Exists("firkra02")
  Global("fl6t01","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("sw1h25","firkra02",0,0,0)
  SetGlobal("fl6t01","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("firkra02")
  Global("fl6t02","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("sw1h30","firkra02",0,0,0)
  SetGlobal("fl6t02","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("firkra02")
  Global("fl6t03","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("sw1h31","firkra02",1,1,0)
  SetGlobal("fl6t03","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("firkra02")
  Global("fl6t04","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("ring09","firkra02",0,0,0)
  SetGlobal("fl6t04","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("firkra02")
  Global("fl6t05","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("bow14","firkra02",0,0,0)
  SetGlobal("fl6t05","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("firkra02")
  Global("fl6t06","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("brac16","firkra02",1,0,0)
  SetGlobal("fl6t06","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("firkra02")
  Global("fl6t07","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("rods03","firkra02",10,0,0)
  SetGlobal("fl6t07","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("firkra02")
  Global("fl6t08","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("scrl07","firkra02",1,0,0)
  SetGlobal("fl6t08","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("firkra02")
  Global("fl6tx0","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("scrl07","firkra02",0,0,0)
  SetGlobal("fl6tx0","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("firkra02")
  Global("fl6t09","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("sw2h09","firkra02",0,0,0)
  SetGlobal("fl6t09","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("firkra02")
  Global("fl6t10","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("wasling","firkra02",0,0,0)
  SetGlobal("fl6t10","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("firkra02")
  Global("fl6t12","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("shld24","firkra02",0,0,0)
  SetGlobal("fl6t12","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("firkra02")
  Global("fl6t13","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("scrlag","firkra02",0,0,0)
  SetGlobal("fl6t13","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("firkra02")
  Global("fl6t14","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("sw1h54b","firkra02",0,0,0)
  SetGlobal("fl6t14","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("firkra02")
  Global("fl6t15","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("sper10","firkra02",0,0,0)
  SetGlobal("fl6t15","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("firkra02")
  Global("fl6t16","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("dagg12","firkra02",0,0,0)
  SetGlobal("fl6t16","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("firkra02")
  Global("fl6t17","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("helm16","firkra02",1,1,1)
  SetGlobal("fl6t17","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("firkra02")
  Global("fl6t18","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("dagg14","firkra02",0,0,0)
  SetGlobal("fl6t18","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("firkra02")
  Global("fl6t19","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("helm04","firkra02",0,0,0)
  SetGlobal("fl6t19","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("firkra02")
  Global("fl6t20","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("sw1h28","firkra02",0,0,0)
  SetGlobal("fl6t20","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("firkra02")
  Global("fl6t21","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("plat17","firkra02",0,0,0)
  SetGlobal("fl6t21","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("firkra02")
  Global("fl6t22","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("ring04","firkra02",0,0,0)
  SetGlobal("fl6t22","GLOBAL",-1)
  DestroySelf()
END
