
IF
  Exists("jael01")
  Global("fl6t01","GLOBAL",19)
THEN RESPONSE #100
  GiveItemCreate("sw1h25","jael01",0,0,0)
  SetGlobal("fl6t01","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Jael02")
  Global("fl6t02","GLOBAL",19)
THEN RESPONSE #100
  GiveItemCreate("sw1h30","Jael02",0,0,0)
  SetGlobal("fl6t02","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Jael02")
  Global("fl6t03","GLOBAL",19)
THEN RESPONSE #100
  GiveItemCreate("sw1h31","Jael02",1,1,0)
  SetGlobal("fl6t03","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Jael03")
  Global("fl6t04","GLOBAL",19)
THEN RESPONSE #100
  GiveItemCreate("ring09","Jael03",0,0,0)
  SetGlobal("fl6t04","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("jael01")
  Global("fl6t05","GLOBAL",19)
THEN RESPONSE #100
  GiveItemCreate("bow14","jael01",0,0,0)
  SetGlobal("fl6t05","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Jael03")
  Global("fl6t06","GLOBAL",19)
THEN RESPONSE #100
  GiveItemCreate("brac16","Jael03",1,0,0)
  SetGlobal("fl6t06","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Jael02")
  Global("fl6t07","GLOBAL",19)
THEN RESPONSE #100
  GiveItemCreate("rods03","Jael02",10,0,0)
  SetGlobal("fl6t07","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("jael01")
  Global("fl6t08","GLOBAL",19)
THEN RESPONSE #100
  GiveItemCreate("scrl07","jael01",1,0,0)
  SetGlobal("fl6t08","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Jael02")
  Global("fl6tx0","GLOBAL",19)
THEN RESPONSE #100
  GiveItemCreate("scrl07","Jael02",0,0,0)
  SetGlobal("fl6tx0","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("jael01")
  Global("fl6t09","GLOBAL",19)
THEN RESPONSE #100
  GiveItemCreate("sw2h09","jael01",0,0,0)
  SetGlobal("fl6t09","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Jael02")
  Global("fl6t10","GLOBAL",19)
THEN RESPONSE #100
  GiveItemCreate("wasling","Jael02",0,0,0)
  SetGlobal("fl6t10","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("jael01")
  Global("fl6t12","GLOBAL",19)
THEN RESPONSE #100
  GiveItemCreate("shld24","jael01",0,0,0)
  SetGlobal("fl6t12","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Jael02")
  Global("fl6t13","GLOBAL",19)
THEN RESPONSE #100
  GiveItemCreate("scrlag","Jael02",0,0,0)
  SetGlobal("fl6t13","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Jael02")
  Global("fl6t14","GLOBAL",19)
THEN RESPONSE #100
  GiveItemCreate("sw1h54b","Jael02",0,0,0)
  SetGlobal("fl6t14","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("jael01")
  Global("fl6t15","GLOBAL",19)
THEN RESPONSE #100
  GiveItemCreate("sper10","jael01",0,0,0)
  SetGlobal("fl6t15","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Jael02")
  Global("fl6t16","GLOBAL",19)
THEN RESPONSE #100
  GiveItemCreate("dagg12","Jael02",0,0,0)
  SetGlobal("fl6t16","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Jael02")
  Global("fl6t17","GLOBAL",19)
THEN RESPONSE #100
  GiveItemCreate("helm16","Jael02",1,1,1)
  SetGlobal("fl6t17","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Jael02")
  Global("fl6t18","GLOBAL",19)
THEN RESPONSE #100
  GiveItemCreate("dagg14","Jael02",0,0,0)
  SetGlobal("fl6t18","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Jael02")
  Global("fl6t19","GLOBAL",19)
THEN RESPONSE #100
  GiveItemCreate("helm04","Jael02",0,0,0)
  SetGlobal("fl6t19","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Jael03")
  Global("fl6t20","GLOBAL",19)
THEN RESPONSE #100
  GiveItemCreate("sw1h28","Jael03",0,0,0)
  SetGlobal("fl6t20","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("jael01")
  Global("fl6t21","GLOBAL",19)
THEN RESPONSE #100
  GiveItemCreate("plat17","jael01",0,0,0)
  SetGlobal("fl6t21","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("jael01")
  Global("fl6t22","GLOBAL",19)
THEN RESPONSE #100
  GiveItemCreate("ring04","jael01",0,0,0)
  SetGlobal("fl6t22","GLOBAL",-1)
  DestroySelf()
END
