
IF
  Exists("daqilue")
  Global("fl6t01","GLOBAL",18)
THEN RESPONSE #100
  GiveItemCreate("sw1h25","daqilue",0,0,0)
  SetGlobal("fl6t01","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("daqilue")
  Global("fl6t02","GLOBAL",18)
THEN RESPONSE #100
  GiveItemCreate("sw1h30","daqilue",0,0,0)
  SetGlobal("fl6t02","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("daqilue")
  Global("fl6t03","GLOBAL",18)
THEN RESPONSE #100
  GiveItemCreate("sw1h31","daqilue",1,1,0)
  SetGlobal("fl6t03","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("daqilue")
  Global("fl6t04","GLOBAL",18)
THEN RESPONSE #100
  GiveItemCreate("ring09","daqilue",0,0,0)
  SetGlobal("fl6t04","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("daqilue")
  Global("fl6t05","GLOBAL",18)
THEN RESPONSE #100
  GiveItemCreate("bow14","daqilue",0,0,0)
  SetGlobal("fl6t05","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("daqilue")
  Global("fl6t06","GLOBAL",18)
THEN RESPONSE #100
  GiveItemCreate("brac16","daqilue",1,0,0)
  SetGlobal("fl6t06","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("daqilue")
  Global("fl6t07","GLOBAL",18)
THEN RESPONSE #100
  GiveItemCreate("rods03","daqilue",10,0,0)
  SetGlobal("fl6t07","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("daqilue")
  Global("fl6t08","GLOBAL",18)
THEN RESPONSE #100
  GiveItemCreate("scrl07","daqilue",1,0,0)
  SetGlobal("fl6t08","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("daqilue")
  Global("fl6tx0","GLOBAL",18)
THEN RESPONSE #100
  GiveItemCreate("scrl07","daqilue",0,0,0)
  SetGlobal("fl6tx0","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("daqilue")
  Global("fl6t09","GLOBAL",18)
THEN RESPONSE #100
  GiveItemCreate("sw2h09","daqilue",0,0,0)
  SetGlobal("fl6t09","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("daqilue")
  Global("fl6t10","GLOBAL",18)
THEN RESPONSE #100
  GiveItemCreate("wasling","daqilue",0,0,0)
  SetGlobal("fl6t10","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("daqilue")
  Global("fl6t12","GLOBAL",18)
THEN RESPONSE #100
  GiveItemCreate("shld24","daqilue",0,0,0)
  SetGlobal("fl6t12","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("daqilue")
  Global("fl6t13","GLOBAL",18)
THEN RESPONSE #100
  GiveItemCreate("scrlag","daqilue",0,0,0)
  SetGlobal("fl6t13","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("daqilue")
  Global("fl6t14","GLOBAL",18)
THEN RESPONSE #100
  GiveItemCreate("sw1h54b","daqilue",0,0,0)
  SetGlobal("fl6t14","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("daqilue")
  Global("fl6t15","GLOBAL",18)
THEN RESPONSE #100
  GiveItemCreate("sper10","daqilue",0,0,0)
  SetGlobal("fl6t15","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("daqilue")
  Global("fl6t16","GLOBAL",18)
THEN RESPONSE #100
  GiveItemCreate("dagg12","daqilue",0,0,0)
  SetGlobal("fl6t16","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("daqilue")
  Global("fl6t17","GLOBAL",18)
THEN RESPONSE #100
  GiveItemCreate("helm16","daqilue",1,1,1)
  SetGlobal("fl6t17","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("daqilue")
  Global("fl6t18","GLOBAL",18)
THEN RESPONSE #100
  GiveItemCreate("dagg14","daqilue",0,0,0)
  SetGlobal("fl6t18","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("daqilue")
  Global("fl6t19","GLOBAL",18)
THEN RESPONSE #100
  GiveItemCreate("helm04","daqilue",0,0,0)
  SetGlobal("fl6t19","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("daqilue")
  Global("fl6t20","GLOBAL",18)
THEN RESPONSE #100
  GiveItemCreate("sw1h28","daqilue",0,0,0)
  SetGlobal("fl6t20","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("daqilue")
  Global("fl6t21","GLOBAL",18)
THEN RESPONSE #100
  GiveItemCreate("plat17","daqilue",0,0,0)
  SetGlobal("fl6t21","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("daqilue")
  Global("fl6t22","GLOBAL",18)
THEN RESPONSE #100
  GiveItemCreate("ring04","daqilue",0,0,0)
  SetGlobal("fl6t22","GLOBAL",-1)
  DestroySelf()
END
