
IF
  Exists("TANAR")
  Global("fl6t01","GLOBAL",20)
THEN RESPONSE #100
  GiveItemCreate("sw1h25","TANAR",0,0,0)
  SetGlobal("fl6t01","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("TANAR")
  Global("fl6t02","GLOBAL",20)
THEN RESPONSE #100
  GiveItemCreate("sw1h30","TANAR",0,0,0)
  SetGlobal("fl6t02","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("TANAR")
  Global("fl6t03","GLOBAL",20)
THEN RESPONSE #100
  GiveItemCreate("sw1h31","TANAR",1,1,0)
  SetGlobal("fl6t03","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("TANAR")
  Global("fl6t04","GLOBAL",20)
THEN RESPONSE #100
  GiveItemCreate("ring09","TANAR",0,0,0)
  SetGlobal("fl6t04","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("TANAR")
  Global("fl6t05","GLOBAL",20)
THEN RESPONSE #100
  GiveItemCreate("bow14","TANAR",0,0,0)
  SetGlobal("fl6t05","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("TANAR")
  Global("fl6t06","GLOBAL",20)
THEN RESPONSE #100
  GiveItemCreate("brac16","TANAR",1,0,0)
  SetGlobal("fl6t06","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("TANAR")
  Global("fl6t07","GLOBAL",20)
THEN RESPONSE #100
  GiveItemCreate("rods03","TANAR",10,0,0)
  SetGlobal("fl6t07","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("TANAR")
  Global("fl6t08","GLOBAL",20)
THEN RESPONSE #100
  GiveItemCreate("scrl07","TANAR",1,0,0)
  SetGlobal("fl6t08","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("TANAR")
  Global("fl6tx0","GLOBAL",20)
THEN RESPONSE #100
  GiveItemCreate("scrl07","TANAR",0,0,0)
  SetGlobal("fl6tx0","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("TANAR")
  Global("fl6t09","GLOBAL",20)
THEN RESPONSE #100
  GiveItemCreate("sw2h09","TANAR",0,0,0)
  SetGlobal("fl6t09","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("TANAR")
  Global("fl6t10","GLOBAL",20)
THEN RESPONSE #100
  GiveItemCreate("wasling","TANAR",0,0,0)
  SetGlobal("fl6t10","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("TANAR")
  Global("fl6t12","GLOBAL",20)
THEN RESPONSE #100
  GiveItemCreate("shld24","TANAR",0,0,0)
  SetGlobal("fl6t12","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("TANAR")
  Global("fl6t13","GLOBAL",20)
THEN RESPONSE #100
  GiveItemCreate("scrlag","TANAR",0,0,0)
  SetGlobal("fl6t13","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("TANAR")
  Global("fl6t14","GLOBAL",20)
THEN RESPONSE #100
  GiveItemCreate("sw1h54b","TANAR",0,0,0)
  SetGlobal("fl6t14","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("TANAR")
  Global("fl6t15","GLOBAL",20)
THEN RESPONSE #100
  GiveItemCreate("sper10","TANAR",0,0,0)
  SetGlobal("fl6t15","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("TANAR")
  Global("fl6t16","GLOBAL",20)
THEN RESPONSE #100
  GiveItemCreate("dagg12","TANAR",0,0,0)
  SetGlobal("fl6t16","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("TANAR")
  Global("fl6t17","GLOBAL",20)
THEN RESPONSE #100
  GiveItemCreate("helm16","TANAR",1,1,1)
  SetGlobal("fl6t17","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("TANAR")
  Global("fl6t18","GLOBAL",20)
THEN RESPONSE #100
  GiveItemCreate("dagg14","TANAR",0,0,0)
  SetGlobal("fl6t18","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("TANAR")
  Global("fl6t19","GLOBAL",20)
THEN RESPONSE #100
  GiveItemCreate("helm04","TANAR",0,0,0)
  SetGlobal("fl6t19","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("TANAR")
  Global("fl6t20","GLOBAL",20)
THEN RESPONSE #100
  GiveItemCreate("sw1h28","TANAR",0,0,0)
  SetGlobal("fl6t20","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("TANAR")
  Global("fl6t21","GLOBAL",20)
THEN RESPONSE #100
  GiveItemCreate("plat17","TANAR",0,0,0)
  SetGlobal("fl6t21","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("TANAR")
  Global("fl6t22","GLOBAL",20)
THEN RESPONSE #100
  GiveItemCreate("ring04","TANAR",0,0,0)
  SetGlobal("fl6t22","GLOBAL",-1)
  DestroySelf()
END
