
IF
  Exists("Susuneer")
  Global("fl6t01","GLOBAL",16)
THEN RESPONSE #100
  GiveItemCreate("sw1h25","Susuneer",0,0,0)
  SetGlobal("fl6t01","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Susuneer")
  Global("fl6t02","GLOBAL",16)
THEN RESPONSE #100
  GiveItemCreate("sw1h30","Susuneer",0,0,0)
  SetGlobal("fl6t02","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Susuneer")
  Global("fl6t03","GLOBAL",16)
THEN RESPONSE #100
  GiveItemCreate("sw1h31","Susuneer",1,1,0)
  SetGlobal("fl6t03","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Susuneer")
  Global("fl6t04","GLOBAL",16)
THEN RESPONSE #100
  GiveItemCreate("ring09","Susuneer",0,0,0)
  SetGlobal("fl6t04","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Susuneer")
  Global("fl6t05","GLOBAL",16)
THEN RESPONSE #100
  GiveItemCreate("bow14","Susuneer",0,0,0)
  SetGlobal("fl6t05","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Susuneer")
  Global("fl6t06","GLOBAL",16)
THEN RESPONSE #100
  GiveItemCreate("brac16","Susuneer",1,0,0)
  SetGlobal("fl6t06","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Susuneer")
  Global("fl6t07","GLOBAL",16)
THEN RESPONSE #100
  GiveItemCreate("rods03","Susuneer",10,0,0)
  SetGlobal("fl6t07","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Susuneer")
  Global("fl6t08","GLOBAL",16)
THEN RESPONSE #100
  GiveItemCreate("scrl07","Susuneer",1,0,0)
  SetGlobal("fl6t08","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Susuneer")
  Global("fl6tx0","GLOBAL",16)
THEN RESPONSE #100
  GiveItemCreate("scrl07","Susuneer",0,0,0)
  SetGlobal("fl6tx0","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Susuneer")
  Global("fl6t09","GLOBAL",16)
THEN RESPONSE #100
  GiveItemCreate("sw2h09","Susuneer",0,0,0)
  SetGlobal("fl6t09","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Susuneer")
  Global("fl6t10","GLOBAL",16)
THEN RESPONSE #100
  GiveItemCreate("wasling","Susuneer",0,0,0)
  SetGlobal("fl6t10","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Susuneer")
  Global("fl6t12","GLOBAL",16)
THEN RESPONSE #100
  GiveItemCreate("shld24","Susuneer",0,0,0)
  SetGlobal("fl6t12","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Susuneer")
  Global("fl6t13","GLOBAL",16)
THEN RESPONSE #100
  GiveItemCreate("scrlag","Susuneer",0,0,0)
  SetGlobal("fl6t13","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Susuneer")
  Global("fl6t14","GLOBAL",16)
THEN RESPONSE #100
  GiveItemCreate("sw1h54b","Susuneer",0,0,0)
  SetGlobal("fl6t14","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Susuneer")
  Global("fl6t15","GLOBAL",16)
THEN RESPONSE #100
  GiveItemCreate("sper10","Susuneer",0,0,0)
  SetGlobal("fl6t15","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Susuneer")
  Global("fl6t16","GLOBAL",16)
THEN RESPONSE #100
  GiveItemCreate("dagg12","Susuneer",0,0,0)
  SetGlobal("fl6t16","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Susuneer")
  Global("fl6t17","GLOBAL",16)
THEN RESPONSE #100
  GiveItemCreate("helm16","Susuneer",1,1,1)
  SetGlobal("fl6t17","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Susuneer")
  Global("fl6t18","GLOBAL",16)
THEN RESPONSE #100
  GiveItemCreate("dagg14","Susuneer",0,0,0)
  SetGlobal("fl6t18","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Susuneer")
  Global("fl6t19","GLOBAL",16)
THEN RESPONSE #100
  GiveItemCreate("helm04","Susuneer",0,0,0)
  SetGlobal("fl6t19","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Susuneer")
  Global("fl6t20","GLOBAL",16)
THEN RESPONSE #100
  GiveItemCreate("sw1h28","Susuneer",0,0,0)
  SetGlobal("fl6t20","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Susuneer")
  Global("fl6t21","GLOBAL",16)
THEN RESPONSE #100
  GiveItemCreate("plat17","Susuneer",0,0,0)
  SetGlobal("fl6t21","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Susuneer")
  Global("fl6t22","GLOBAL",16)
THEN RESPONSE #100
  GiveItemCreate("ring04","Susuneer",0,0,0)
  SetGlobal("fl6t22","GLOBAL",-1)
  DestroySelf()
END
