
IF
  Exists("AR18ARCH")
  Global("fl6t01","GLOBAL",21)
THEN RESPONSE #100
  GiveItemCreate("sw1h25","AR18ARCH",0,0,0)
  SetGlobal("fl6t01","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("gpfight1")
  Global("fl6t02","GLOBAL",21)
THEN RESPONSE #100
  GiveItemCreate("sw1h30","gpfight1",0,0,0)
  SetGlobal("fl6t02","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("AR18PRIE")
  Global("fl6t03","GLOBAL",21)
THEN RESPONSE #100
  GiveItemCreate("sw1h31","AR18PRIE",1,1,0)
  SetGlobal("fl6t03","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("ar18Mage")
  Global("fl6t04","GLOBAL",21)
THEN RESPONSE #100
  GiveItemCreate("ring09","ar18Mage",0,0,0)
  SetGlobal("fl6t04","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("gpfight1")
  Global("fl6t05","GLOBAL",21)
THEN RESPONSE #100
  GiveItemCreate("bow14","gpfight1",0,0,0)
  SetGlobal("fl6t05","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("AR18ARCH")
  Global("fl6t06","GLOBAL",21)
THEN RESPONSE #100
  GiveItemCreate("brac16","AR18ARCH",1,0,0)
  SetGlobal("fl6t06","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("gpfight1")
  Global("fl6t07","GLOBAL",21)
THEN RESPONSE #100
  GiveItemCreate("rods03","gpfight1",10,0,0)
  SetGlobal("fl6t07","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("gpfight1")
  Global("fl6t08","GLOBAL",21)
THEN RESPONSE #100
  GiveItemCreate("scrl07","gpfight1",1,0,0)
  SetGlobal("fl6t08","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("AR18ARCH")
  Global("fl6tx0","GLOBAL",21)
THEN RESPONSE #100
  GiveItemCreate("scrl07","AR18ARCH",0,0,0)
  SetGlobal("fl6tx0","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("gpthief1")
  Global("fl6t09","GLOBAL",21)
THEN RESPONSE #100
  GiveItemCreate("sw2h09","gpthief1",0,0,0)
  SetGlobal("fl6t09","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("gpthief1")
  Global("fl6t10","GLOBAL",21)
THEN RESPONSE #100
  GiveItemCreate("wasling","gpthief1",0,0,0)
  SetGlobal("fl6t10","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("gpfight1")
  Global("fl6t12","GLOBAL",21)
THEN RESPONSE #100
  GiveItemCreate("shld24","gpfight1",0,0,0)
  SetGlobal("fl6t12","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("AR18ARCH")
  Global("fl6t13","GLOBAL",21)
THEN RESPONSE #100
  GiveItemCreate("scrlag","AR18ARCH",0,0,0)
  SetGlobal("fl6t13","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("AR18PRIE")
  Global("fl6t14","GLOBAL",21)
THEN RESPONSE #100
  GiveItemCreate("sw1h54b","AR18PRIE",0,0,0)
  SetGlobal("fl6t14","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("gpthief1")
  Global("fl6t15","GLOBAL",21)
THEN RESPONSE #100
  GiveItemCreate("sper10","gpthief1",0,0,0)
  SetGlobal("fl6t15","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("gpthief1")
  Global("fl6t16","GLOBAL",21)
THEN RESPONSE #100
  GiveItemCreate("dagg12","gpthief1",0,0,0)
  SetGlobal("fl6t16","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("ar18Mage")
  Global("fl6t17","GLOBAL",21)
THEN RESPONSE #100
  GiveItemCreate("helm16","ar18Mage",1,1,1)
  SetGlobal("fl6t17","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("AR18PRIE")
  Global("fl6t18","GLOBAL",21)
THEN RESPONSE #100
  GiveItemCreate("dagg14","AR18PRIE",0,0,0)
  SetGlobal("fl6t18","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("gpfight1")
  Global("fl6t19","GLOBAL",21)
THEN RESPONSE #100
  GiveItemCreate("helm04","gpfight1",0,0,0)
  SetGlobal("fl6t19","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("gpthief1")
  Global("fl6t20","GLOBAL",21)
THEN RESPONSE #100
  GiveItemCreate("sw1h28","gpthief1",0,0,0)
  SetGlobal("fl6t20","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("gpfight1")
  Global("fl6t21","GLOBAL",21)
THEN RESPONSE #100
  GiveItemCreate("plat17","gpfight1",0,0,0)
  SetGlobal("fl6t21","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("gpfight1")
  Global("fl6t22","GLOBAL",21)
THEN RESPONSE #100
  GiveItemCreate("ring04","gpfight1",0,0,0)
  SetGlobal("fl6t22","GLOBAL",-1)
  DestroySelf()
END
