
IF
  Exists("ShaDra01")
  Global("fl6t01","GLOBAL",13)
THEN RESPONSE #100
  GiveItemCreate("sw1h25","ShaDra01",0,0,0)
  SetGlobal("fl6t01","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("ShaDra01")
  Global("fl6t02","GLOBAL",13)
THEN RESPONSE #100
  GiveItemCreate("sw1h30","ShaDra01",0,0,0)
  SetGlobal("fl6t02","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("ShaDra01")
  Global("fl6t03","GLOBAL",13)
THEN RESPONSE #100
  GiveItemCreate("sw1h31","ShaDra01",1,1,0)
  SetGlobal("fl6t03","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("ShaDra01")
  Global("fl6t04","GLOBAL",13)
THEN RESPONSE #100
  GiveItemCreate("ring09","ShaDra01",0,0,0)
  SetGlobal("fl6t04","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("ShaDra01")
  Global("fl6t05","GLOBAL",13)
THEN RESPONSE #100
  GiveItemCreate("bow14","ShaDra01",0,0,0)
  SetGlobal("fl6t05","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("ShaDra01")
  Global("fl6t06","GLOBAL",13)
THEN RESPONSE #100
  GiveItemCreate("brac16","ShaDra01",1,0,0)
  SetGlobal("fl6t06","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("ShaDra01")
  Global("fl6t07","GLOBAL",13)
THEN RESPONSE #100
  GiveItemCreate("rods03","ShaDra01",10,0,0)
  SetGlobal("fl6t07","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("ShaDra01")
  Global("fl6t08","GLOBAL",13)
THEN RESPONSE #100
  GiveItemCreate("scrl07","ShaDra01",1,0,0)
  SetGlobal("fl6t08","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("ShaDra01")
  Global("fl6tx0","GLOBAL",13)
THEN RESPONSE #100
  GiveItemCreate("scrl07","ShaDra01",0,0,0)
  SetGlobal("fl6tx0","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("ShaDra01")
  Global("fl6t09","GLOBAL",13)
THEN RESPONSE #100
  GiveItemCreate("sw2h09","ShaDra01",0,0,0)
  SetGlobal("fl6t09","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("ShaDra01")
  Global("fl6t10","GLOBAL",13)
THEN RESPONSE #100
  GiveItemCreate("wasling","ShaDra01",0,0,0)
  SetGlobal("fl6t10","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("ShaDra01")
  Global("fl6t12","GLOBAL",13)
THEN RESPONSE #100
  GiveItemCreate("shld24","ShaDra01",0,0,0)
  SetGlobal("fl6t12","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("ShaDra01")
  Global("fl6t13","GLOBAL",13)
THEN RESPONSE #100
  GiveItemCreate("scrlag","ShaDra01",0,0,0)
  SetGlobal("fl6t13","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("ShaDra01")
  Global("fl6t14","GLOBAL",13)
THEN RESPONSE #100
  GiveItemCreate("sw1h54b","ShaDra01",0,0,0)
  SetGlobal("fl6t14","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("ShaDra01")
  Global("fl6t15","GLOBAL",13)
THEN RESPONSE #100
  GiveItemCreate("sper10","ShaDra01",0,0,0)
  SetGlobal("fl6t15","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("ShaDra01")
  Global("fl6t16","GLOBAL",13)
THEN RESPONSE #100
  GiveItemCreate("dagg12","ShaDra01",0,0,0)
  SetGlobal("fl6t16","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("ShaDra01")
  Global("fl6t17","GLOBAL",13)
THEN RESPONSE #100
  GiveItemCreate("helm16","ShaDra01",1,1,1)
  SetGlobal("fl6t17","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("ShaDra01")
  Global("fl6t18","GLOBAL",13)
THEN RESPONSE #100
  GiveItemCreate("dagg14","ShaDra01",0,0,0)
  SetGlobal("fl6t18","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("ShaDra01")
  Global("fl6t19","GLOBAL",13)
THEN RESPONSE #100
  GiveItemCreate("helm04","ShaDra01",0,0,0)
  SetGlobal("fl6t19","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("ShaDra01")
  Global("fl6t20","GLOBAL",13)
THEN RESPONSE #100
  GiveItemCreate("sw1h28","ShaDra01",0,0,0)
  SetGlobal("fl6t20","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("ShaDra01")
  Global("fl6t21","GLOBAL",13)
THEN RESPONSE #100
  GiveItemCreate("plat17","ShaDra01",0,0,0)
  SetGlobal("fl6t21","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("ShaDra01")
  Global("fl6t22","GLOBAL",13)
THEN RESPONSE #100
  GiveItemCreate("ring04","ShaDra01",0,0,0)
  SetGlobal("fl6t22","GLOBAL",-1)
  DestroySelf()
END
