
IF
  Exists("udmaster")
  Global("fl7t01","GLOBAL",3)
THEN RESPONSE #100
  GiveItemCreate("brac10","udmaster",0,0,0)
  SetGlobal("fl7t01","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("udmaster")
  Global("fl7t02","GLOBAL",3)
THEN RESPONSE #100
  GiveItemCreate("clck26","udmaster",0,0,0)
  SetGlobal("fl7t02","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("udmaster")
  Global("fl7t03","GLOBAL",3)
THEN RESPONSE #100
  GiveItemCreate("wa2helm","udmaster",1,0,0)
  SetGlobal("fl7t03","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("udmaster")
  Global("fl7t04","GLOBAL",3)
THEN RESPONSE #100
  GiveItemCreate("wa2robe","udmaster",0,0,0)
  SetGlobal("fl7t04","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("udmaster")
  Global("fl7t05","GLOBAL",3)
THEN RESPONSE #100
  GiveItemCreate("wa2shiel","udmaster",0,0,0)
  SetGlobal("fl7t05","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("udmaster")
  Global("fl7t06","GLOBAL",3)
THEN RESPONSE #100
  GiveItemCreate("waflail","udmaster",0,0,0)
  SetGlobal("fl7t06","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("udmaster")
  Global("fl7t07","GLOBAL",3)
THEN RESPONSE #100
  GiveItemCreate("chan16","udmaster",0,0,0)
  SetGlobal("fl7t07","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("udmaster")
  Global("fl7t08","GLOBAL",3)
THEN RESPONSE #100
  GiveItemCreate("staf11","udmaster",0,3,1)
  SetGlobal("fl7t08","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("udmaster")
  Global("fl7t09","GLOBAL",3)
THEN RESPONSE #100
  GiveItemCreate("belt08","udmaster",0,0,0)
  SetGlobal("fl7t09","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("udmaster")
  Global("fl7t10","GLOBAL",3)
THEN RESPONSE #100
  GiveItemCreate("plat16","udmaster",0,0,0)
  SetGlobal("fl7t10","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("udmaster")
  Global("fl7t11","GLOBAL",3)
THEN RESPONSE #100
  GiveItemCreate("sw2h08","udmaster",0,0,0)
  SetGlobal("fl7t11","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("udmaster")
  Global("fl7t12","GLOBAL",3)
THEN RESPONSE #100
  GiveItemCreate("halb05","udmaster",0,0,0)
  SetGlobal("fl7t12","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("udmaster")
  Global("fl7t13","GLOBAL",3)
THEN RESPONSE #100
  GiveItemCreate("sw1h51","udmaster",0,1,1)
  SetGlobal("fl7t13","GLOBAL",-1)
  DestroySelf()
END
