
IF
  Exists("jael01")
  Global("fl7t01","GLOBAL",4)
THEN RESPONSE #100
  GiveItemCreate("brac10","jael01",0,0,0)
  SetGlobal("fl7t01","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Jael03")
  Global("fl7t02","GLOBAL",4)
THEN RESPONSE #100
  GiveItemCreate("clck26","Jael03",0,0,0)
  SetGlobal("fl7t02","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Jael02")
  Global("fl7t03","GLOBAL",4)
THEN RESPONSE #100
  GiveItemCreate("wa2helm","Jael02",1,0,0)
  SetGlobal("fl7t03","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Jael03")
  Global("fl7t04","GLOBAL",4)
THEN RESPONSE #100
  GiveItemCreate("wa2robe","Jael03",0,0,0)
  SetGlobal("fl7t04","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("jael01")
  Global("fl7t05","GLOBAL",4)
THEN RESPONSE #100
  GiveItemCreate("wa2shiel","jael01",0,0,0)
  SetGlobal("fl7t05","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Jael02")
  Global("fl7t06","GLOBAL",4)
THEN RESPONSE #100
  GiveItemCreate("waflail","Jael02",0,0,0)
  SetGlobal("fl7t06","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Jael02")
  Global("fl7t07","GLOBAL",4)
THEN RESPONSE #100
  GiveItemCreate("chan16","Jael02",0,0,0)
  SetGlobal("fl7t07","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("jael01")
  Global("fl7t08","GLOBAL",4)
THEN RESPONSE #100
  GiveItemCreate("staf11","jael01",0,3,1)
  SetGlobal("fl7t08","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Jael03")
  Global("fl7t09","GLOBAL",4)
THEN RESPONSE #100
  GiveItemCreate("belt08","Jael03",0,0,0)
  SetGlobal("fl7t09","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Jael03")
  Global("fl7t10","GLOBAL",4)
THEN RESPONSE #100
  GiveItemCreate("plat16","Jael03",0,0,0)
  SetGlobal("fl7t10","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Jael03")
  Global("fl7t11","GLOBAL",4)
THEN RESPONSE #100
  GiveItemCreate("sw2h08","Jael03",0,0,0)
  SetGlobal("fl7t11","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("jael01")
  Global("fl7t12","GLOBAL",4)
THEN RESPONSE #100
  GiveItemCreate("halb05","jael01",0,0,0)
  SetGlobal("fl7t12","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Jael02")
  Global("fl7t13","GLOBAL",4)
THEN RESPONSE #100
  GiveItemCreate("sw1h51","Jael02",0,1,1)
  SetGlobal("fl7t13","GLOBAL",-1)
  DestroySelf()
END
