
IF
  Exists("uddeath2")
  Global("fl7t01","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("brac10","uddeath2",0,0,0)
  SetGlobal("fl7t01","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("uddeath2")
  Global("fl7t02","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("clck26","uddeath2",0,0,0)
  SetGlobal("fl7t02","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("uddeath2")
  Global("fl7t03","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("wa2helm","uddeath2",1,0,0)
  SetGlobal("fl7t03","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("uddeath2")
  Global("fl7t04","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("wa2robe","uddeath2",0,0,0)
  SetGlobal("fl7t04","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("uddeath2")
  Global("fl7t05","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("wa2shiel","uddeath2",0,0,0)
  SetGlobal("fl7t05","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("uddeath2")
  Global("fl7t06","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("waflail","uddeath2",0,0,0)
  SetGlobal("fl7t06","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("uddeath2")
  Global("fl7t07","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("chan16","uddeath2",0,0,0)
  SetGlobal("fl7t07","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("uddeath2")
  Global("fl7t08","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("staf11","uddeath2",0,3,1)
  SetGlobal("fl7t08","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("uddeath2")
  Global("fl7t09","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("belt08","uddeath2",0,0,0)
  SetGlobal("fl7t09","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("uddeath2")
  Global("fl7t10","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("plat16","uddeath2",0,0,0)
  SetGlobal("fl7t10","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("uddeath2")
  Global("fl7t11","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("sw2h08","uddeath2",0,0,0)
  SetGlobal("fl7t11","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("uddeath2")
  Global("fl7t12","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("halb05","uddeath2",0,0,0)
  SetGlobal("fl7t12","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("uddeath2")
  Global("fl7t13","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("sw1h51","uddeath2",0,1,1)
  SetGlobal("fl7t13","GLOBAL",-1)
  DestroySelf()
END
