
IF
  Exists("hllayen")
  Global("fl7t01","GLOBAL",8)
THEN RESPONSE #100
  GiveItemCreate("brac10","hllayen",0,0,0)
  SetGlobal("fl7t01","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("hlrevan")
  Global("fl7t02","GLOBAL",8)
THEN RESPONSE #100
  GiveItemCreate("clck26","hlrevan",0,0,0)
  SetGlobal("fl7t02","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("hlrevan")
  Global("fl7t03","GLOBAL",8)
THEN RESPONSE #100
  GiveItemCreate("wa2helm","hlrevan",1,0,0)
  SetGlobal("fl7t03","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("hlshang")
  Global("fl7t04","GLOBAL",8)
THEN RESPONSE #100
  GiveItemCreate("wa2robe","hlshang",0,0,0)
  SetGlobal("fl7t04","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("hlshang")
  Global("fl7t05","GLOBAL",8)
THEN RESPONSE #100
  GiveItemCreate("wa2shiel","hlshang",0,0,0)
  SetGlobal("fl7t05","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("hlshang")
  Global("fl7t06","GLOBAL",8)
THEN RESPONSE #100
  GiveItemCreate("waflail","hlshang",0,0,0)
  SetGlobal("fl7t06","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("hllayen")
  Global("fl7t07","GLOBAL",8)
THEN RESPONSE #100
  GiveItemCreate("chan16","hllayen",0,0,0)
  SetGlobal("fl7t07","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("hllayen")
  Global("fl7t08","GLOBAL",8)
THEN RESPONSE #100
  GiveItemCreate("staf11","hllayen",0,3,1)
  SetGlobal("fl7t08","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("hlrevan")
  Global("fl7t09","GLOBAL",8)
THEN RESPONSE #100
  GiveItemCreate("belt08","hlrevan",0,0,0)
  SetGlobal("fl7t09","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("hlrevan")
  Global("fl7t10","GLOBAL",8)
THEN RESPONSE #100
  GiveItemCreate("plat16","hlrevan",0,0,0)
  SetGlobal("fl7t10","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("hlshang")
  Global("fl7t11","GLOBAL",8)
THEN RESPONSE #100
  GiveItemCreate("sw2h08","hlshang",0,0,0)
  SetGlobal("fl7t11","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("hlshang")
  Global("fl7t12","GLOBAL",8)
THEN RESPONSE #100
  GiveItemCreate("halb05","hlshang",0,0,0)
  SetGlobal("fl7t12","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("hlshang")
  Global("fl7t13","GLOBAL",8)
THEN RESPONSE #100
  GiveItemCreate("sw1h51","hlshang",0,1,1)
  SetGlobal("fl7t13","GLOBAL",-1)
  DestroySelf()
END
