
IF
  Exists("endtreasure")
  Global("fl7t01","GLOBAL",6)
THEN RESPONSE #100
  ActionOverride("endtreasure",CreateItem("brac10",0,0,0))
  SetGlobal("fl7t01","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("endtreasure")
  Global("fl7t02","GLOBAL",6)
THEN RESPONSE #100
  ActionOverride("endtreasure",CreateItem("clck26",0,0,0))
  SetGlobal("fl7t02","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("endtreasure")
  Global("fl7t03","GLOBAL",6)
THEN RESPONSE #100
  ActionOverride("endtreasure",CreateItem("wa2helm",1,0,0))
  SetGlobal("fl7t03","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("endtreasure")
  Global("fl7t04","GLOBAL",6)
THEN RESPONSE #100
  ActionOverride("endtreasure",CreateItem("wa2robe",0,0,0))
  SetGlobal("fl7t04","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("endtreasure")
  Global("fl7t05","GLOBAL",6)
THEN RESPONSE #100
  ActionOverride("endtreasure",CreateItem("wa2shiel",0,0,0))
  SetGlobal("fl7t05","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("endtreasure")
  Global("fl7t06","GLOBAL",6)
THEN RESPONSE #100
  ActionOverride("endtreasure",CreateItem("waflail",0,0,0))
  SetGlobal("fl7t06","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("endtreasure")
  Global("fl7t07","GLOBAL",6)
THEN RESPONSE #100
  ActionOverride("endtreasure",CreateItem("chan16",0,0,0))
  SetGlobal("fl7t07","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("endtreasure")
  Global("fl7t08","GLOBAL",6)
THEN RESPONSE #100
  ActionOverride("endtreasure",CreateItem("staf11",0,3,1))
  SetGlobal("fl7t08","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("endtreasure")
  Global("fl7t09","GLOBAL",6)
THEN RESPONSE #100
  ActionOverride("endtreasure",CreateItem("belt08",0,0,0))
  SetGlobal("fl7t09","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("endtreasure")
  Global("fl7t10","GLOBAL",6)
THEN RESPONSE #100
  ActionOverride("endtreasure",CreateItem("plat16",0,0,0))
  SetGlobal("fl7t10","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("endtreasure")
  Global("fl7t11","GLOBAL",6)
THEN RESPONSE #100
  ActionOverride("endtreasure",CreateItem("sw2h08",0,0,0))
  SetGlobal("fl7t11","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("endtreasure")
  Global("fl7t12","GLOBAL",6)
THEN RESPONSE #100
  ActionOverride("endtreasure",CreateItem("halb05",0,0,0))
  SetGlobal("fl7t12","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("endtreasure")
  Global("fl7t13","GLOBAL",6)
THEN RESPONSE #100
  ActionOverride("endtreasure",CreateItem("sw1h51",0,1,1))
  SetGlobal("fl7t13","GLOBAL",-1)
  DestroySelf()
END
