
IF
  Exists("udelder")
  Global("fl7t01","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("brac10","udelder",0,0,0)
  SetGlobal("fl7t01","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("udelder")
  Global("fl7t02","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("clck26","udelder",0,0,0)
  SetGlobal("fl7t02","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("udelder")
  Global("fl7t03","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("wa2helm","udelder",1,0,0)
  SetGlobal("fl7t03","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("udelder")
  Global("fl7t04","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("wa2robe","udelder",0,0,0)
  SetGlobal("fl7t04","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("udelder")
  Global("fl7t05","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("wa2shiel","udelder",0,0,0)
  SetGlobal("fl7t05","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("udelder")
  Global("fl7t06","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("waflail","udelder",0,0,0)
  SetGlobal("fl7t06","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("udelder")
  Global("fl7t07","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("chan16","udelder",0,0,0)
  SetGlobal("fl7t07","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("udelder")
  Global("fl7t08","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("staf11","udelder",0,3,1)
  SetGlobal("fl7t08","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("udelder")
  Global("fl7t09","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("belt08","udelder",0,0,0)
  SetGlobal("fl7t09","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("udelder")
  Global("fl7t10","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("plat16","udelder",0,0,0)
  SetGlobal("fl7t10","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("udelder")
  Global("fl7t11","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("sw2h08","udelder",0,0,0)
  SetGlobal("fl7t11","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("udelder")
  Global("fl7t12","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("halb05","udelder",0,0,0)
  SetGlobal("fl7t12","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("udelder")
  Global("fl7t13","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("sw1h51","udelder",0,1,1)
  SetGlobal("fl7t13","GLOBAL",-1)
  DestroySelf()
END
