
IF
  Exists("container6")
  Global("flfat01","GLOBAL",3)
THEN RESPONSE #100
  ActionOverride("container6",CreateItem("blun14a",0,0,0))
  SetGlobal("flfat01","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("container6")
  Global("flfat02","GLOBAL",3)
THEN RESPONSE #100
  ActionOverride("container6",CreateItem("blun14b",0,0,0))
  SetGlobal("flfat02","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("container6")
  Global("flfat03","GLOBAL",3)
THEN RESPONSE #100
  ActionOverride("container6",CreateItem("blun14c",0,0,0))
  SetGlobal("flfat03","GLOBAL",-1)
  DestroySelf()
END
