
IF
  Exists("XAppren2")
  Global("fls5t01","GLOBAL",8)
THEN RESPONSE #100
  GiveItemCreate("scrl7d","XAppren2",1,1,0)
  SetGlobal("fls5t01","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("XAppren2")
  Global("fls5t02","GLOBAL",8)
THEN RESPONSE #100
  GiveItemCreate("scrl7d","XAppren2",1,0,0)
  SetGlobal("fls5t02","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("XAppren2")
  Global("fls5t03","GLOBAL",8)
THEN RESPONSE #100
  GiveItemCreate("scrl6z","XAppren2",1,0,0)
  SetGlobal("fls5t03","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("XAppren2")
  Global("fls5t04","GLOBAL",8)
THEN RESPONSE #100
  GiveItemCreate("scrl6z","XAppren2",1,1,0)
  SetGlobal("fls5t04","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("XAppren2")
  Global("fls5t05","GLOBAL",8)
THEN RESPONSE #100
  GiveItemCreate("scrl6y","XAppren2",1,0,0)
  SetGlobal("fls5t05","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("XAppren2")
  Global("fls5t06","GLOBAL",8)
THEN RESPONSE #100
  GiveItemCreate("scrl2e","XAppren2",1,0,0)
  SetGlobal("fls5t06","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("XAppren2")
  Global("fls5t07","GLOBAL",8)
THEN RESPONSE #100
  GiveItemCreate("scrl2f","XAppren2",1,0,0)
  SetGlobal("fls5t07","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("XAppren2")
  Global("fls5t08","GLOBAL",8)
THEN RESPONSE #100
  GiveItemCreate("scrl2f","XAppren2",1,0,0)
  SetGlobal("fls5t08","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("XAppren2")
  Global("fls5t09","GLOBAL",8)
THEN RESPONSE #100
  GiveItemCreate("scrl5o","XAppren2",1,0,0)
  SetGlobal("fls5t09","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("XAppren2")
  Global("fls5t10","GLOBAL",8)
THEN RESPONSE #100
  GiveItemCreate("scrl5n","XAppren2",1,0,0)
  SetGlobal("fls5t10","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("XAppren2")
  Global("fls5t11","GLOBAL",8)
THEN RESPONSE #100
  GiveItemCreate("scrl2d","XAppren2",1,0,0)
  SetGlobal("fls5t11","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("XAppren2")
  Global("fls5t12","GLOBAL",8)
THEN RESPONSE #100
  GiveItemCreate("scrl6u","XAppren2",1,1,0)
  SetGlobal("fls5t12","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("XAppren2")
  Global("fls5t13","GLOBAL",8)
THEN RESPONSE #100
  GiveItemCreate("scrl6u","XAppren2",1,1,0)
  SetGlobal("fls5t13","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("XAppren2")
  Global("fls5t14","GLOBAL",8)
THEN RESPONSE #100
  GiveItemCreate("scrl6u","XAppren2",1,0,0)
  SetGlobal("fls5t14","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("XAppren2")
  Global("fls5t15","GLOBAL",8)
THEN RESPONSE #100
  GiveItemCreate("scrl6u","XAppren2",1,0,0)
  SetGlobal("fls5t15","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("XAppren2")
  Global("fls5t16","GLOBAL",8)
THEN RESPONSE #100
  GiveItemCreate("scrl6u","XAppren2",1,1,0)
  SetGlobal("fls5t16","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("XAppren2")
  Global("fls5t17","GLOBAL",8)
THEN RESPONSE #100
  GiveItemCreate("scrl6v","XAppren2",1,0,0)
  SetGlobal("fls5t17","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("XAppren2")
  Global("fls5t18","GLOBAL",8)
THEN RESPONSE #100
  GiveItemCreate("scrl6s","XAppren2",1,0,0)
  SetGlobal("fls5t18","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("XAppren2")
  Global("fls5t19","GLOBAL",8)
THEN RESPONSE #100
  GiveItemCreate("scrl6q","XAppren2",1,0,0)
  SetGlobal("fls5t19","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("XAppren2")
  Global("fls5t20","GLOBAL",8)
THEN RESPONSE #100
  GiveItemCreate("scrl5p","XAppren2",1,0,0)
  SetGlobal("fls5t20","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("XAppren2")
  Global("fls5t21","GLOBAL",8)
THEN RESPONSE #100
  GiveItemCreate("scrlal","XAppren2",1,1,0)
  SetGlobal("fls5t21","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("XAppren2")
  Global("fls5t22","GLOBAL",8)
THEN RESPONSE #100
  GiveItemCreate("scrlal","XAppren2",1,1,0)
  SetGlobal("fls5t22","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("XAppren2")
  Global("fls5tx0","GLOBAL",8)
THEN RESPONSE #100
  GiveItemCreate("scrlal","XAppren2",0,0,0)
  SetGlobal("fls5tx0","GLOBAL",-1)
  DestroySelf()
END
