
IF
  Exists("Lehtinan")
  Global("fls6t01","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("scrl8c","Lehtinan",1,0,0)
  SetGlobal("fls6t01","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Lehtinan")
  Global("fls6t02","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("scrl8b","Lehtinan",1,0,0)
  SetGlobal("fls6t02","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Lehtinan")
  Global("fls6t03","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("scrl8a","Lehtinan",1,0,0)
  SetGlobal("fls6t03","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Lehtinan")
  Global("fls6t04","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("scrl7w","Lehtinan",1,0,0)
  SetGlobal("fls6t04","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Lehtinan")
  Global("fls6t05","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("scrl7v","Lehtinan",1,0,0)
  SetGlobal("fls6t05","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Lehtinan")
  Global("fls6t06","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("scrl7u","Lehtinan",1,0,0)
  SetGlobal("fls6t06","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Lehtinan")
  Global("fls6t07","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("scrl7u","Lehtinan",1,0,0)
  SetGlobal("fls6t07","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Lehtinan")
  Global("fls6t08","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("scrl7o","Lehtinan",1,0,0)
  SetGlobal("fls6t08","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Lehtinan")
  Global("fls6tx0","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("scrl7o","Lehtinan",0,0,0)
  SetGlobal("fls6tx0","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Lehtinan")
  Global("fls6t09","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("scrl7t","Lehtinan",1,0,0)
  SetGlobal("fls6t09","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Lehtinan")
  Global("fls6t10","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("scrl7s","Lehtinan",1,0,0)
  SetGlobal("fls6t10","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Lehtinan")
  Global("fls6t11","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("scrl7s","Lehtinan",1,0,0)
  SetGlobal("fls6t11","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Lehtinan")
  Global("fls6t12","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("scrl7s","Lehtinan",1,1,0)
  SetGlobal("fls6t12","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Lehtinan")
  Global("fls6t13","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("scrl7r","Lehtinan",1,0,0)
  SetGlobal("fls6t13","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Lehtinan")
  Global("fls6t14","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("scrl7r","Lehtinan",1,1,0)
  SetGlobal("fls6t14","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Lehtinan")
  Global("fls6t15","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("scrl7o","Lehtinan",1,0,0)
  SetGlobal("fls6t15","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Lehtinan")
  Global("fls6t16","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("scrl7l","Lehtinan",1,0,0)
  SetGlobal("fls6t16","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Lehtinan")
  Global("fls6t17","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("scrl7k","Lehtinan",1,0,0)
  SetGlobal("fls6t17","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Lehtinan")
  Global("fls6t18","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("scrl7j","Lehtinan",1,0,0)
  SetGlobal("fls6t18","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Lehtinan")
  Global("fls6t19","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("scrl7i","Lehtinan",1,0,0)
  SetGlobal("fls6t19","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Lehtinan")
  Global("fls6t20","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("scrl7h","Lehtinan",1,0,0)
  SetGlobal("fls6t20","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Lehtinan")
  Global("fls6t21","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("scrl7f","Lehtinan",1,0,0)
  SetGlobal("fls6t21","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Lehtinan")
  Global("fls6t22","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("scrl7e","Lehtinan",1,0,0)
  SetGlobal("fls6t22","GLOBAL",-1)
  DestroySelf()
END
