
IF
  Exists("XAppren1")
  Global("fls6t01","GLOBAL",16)
THEN RESPONSE #100
  GiveItemCreate("scrl8c","XAppren1",1,0,0)
  SetGlobal("fls6t01","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("XAppren1")
  Global("fls6t02","GLOBAL",16)
THEN RESPONSE #100
  GiveItemCreate("scrl8b","XAppren1",1,0,0)
  SetGlobal("fls6t02","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("XAppren1")
  Global("fls6t03","GLOBAL",16)
THEN RESPONSE #100
  GiveItemCreate("scrl8a","XAppren1",1,0,0)
  SetGlobal("fls6t03","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("XAppren1")
  Global("fls6t04","GLOBAL",16)
THEN RESPONSE #100
  GiveItemCreate("scrl7w","XAppren1",1,0,0)
  SetGlobal("fls6t04","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("XAppren1")
  Global("fls6t05","GLOBAL",16)
THEN RESPONSE #100
  GiveItemCreate("scrl7v","XAppren1",1,0,0)
  SetGlobal("fls6t05","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("XAppren1")
  Global("fls6t06","GLOBAL",16)
THEN RESPONSE #100
  GiveItemCreate("scrl7u","XAppren1",1,0,0)
  SetGlobal("fls6t06","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("XAppren1")
  Global("fls6t07","GLOBAL",16)
THEN RESPONSE #100
  GiveItemCreate("scrl7u","XAppren1",1,0,0)
  SetGlobal("fls6t07","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("XAppren1")
  Global("fls6t08","GLOBAL",16)
THEN RESPONSE #100
  GiveItemCreate("scrl7o","XAppren1",1,0,0)
  SetGlobal("fls6t08","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("XAppren1")
  Global("fls6tx0","GLOBAL",16)
THEN RESPONSE #100
  GiveItemCreate("scrl7o","XAppren1",0,0,0)
  SetGlobal("fls6tx0","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("XAppren1")
  Global("fls6t09","GLOBAL",16)
THEN RESPONSE #100
  GiveItemCreate("scrl7t","XAppren1",1,0,0)
  SetGlobal("fls6t09","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("XAppren1")
  Global("fls6t10","GLOBAL",16)
THEN RESPONSE #100
  GiveItemCreate("scrl7s","XAppren1",1,0,0)
  SetGlobal("fls6t10","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("XAppren1")
  Global("fls6t11","GLOBAL",16)
THEN RESPONSE #100
  GiveItemCreate("scrl7s","XAppren1",1,0,0)
  SetGlobal("fls6t11","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("XAppren1")
  Global("fls6t12","GLOBAL",16)
THEN RESPONSE #100
  GiveItemCreate("scrl7s","XAppren1",1,1,0)
  SetGlobal("fls6t12","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("XAppren1")
  Global("fls6t13","GLOBAL",16)
THEN RESPONSE #100
  GiveItemCreate("scrl7r","XAppren1",1,0,0)
  SetGlobal("fls6t13","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("XAppren1")
  Global("fls6t14","GLOBAL",16)
THEN RESPONSE #100
  GiveItemCreate("scrl7r","XAppren1",1,1,0)
  SetGlobal("fls6t14","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("XAppren1")
  Global("fls6t15","GLOBAL",16)
THEN RESPONSE #100
  GiveItemCreate("scrl7o","XAppren1",1,0,0)
  SetGlobal("fls6t15","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("XAppren1")
  Global("fls6t16","GLOBAL",16)
THEN RESPONSE #100
  GiveItemCreate("scrl7l","XAppren1",1,0,0)
  SetGlobal("fls6t16","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("XAppren1")
  Global("fls6t17","GLOBAL",16)
THEN RESPONSE #100
  GiveItemCreate("scrl7k","XAppren1",1,0,0)
  SetGlobal("fls6t17","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("XAppren1")
  Global("fls6t18","GLOBAL",16)
THEN RESPONSE #100
  GiveItemCreate("scrl7j","XAppren1",1,0,0)
  SetGlobal("fls6t18","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("XAppren1")
  Global("fls6t19","GLOBAL",16)
THEN RESPONSE #100
  GiveItemCreate("scrl7i","XAppren1",1,0,0)
  SetGlobal("fls6t19","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("XAppren1")
  Global("fls6t20","GLOBAL",16)
THEN RESPONSE #100
  GiveItemCreate("scrl7h","XAppren1",1,0,0)
  SetGlobal("fls6t20","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("XAppren1")
  Global("fls6t21","GLOBAL",16)
THEN RESPONSE #100
  GiveItemCreate("scrl7f","XAppren1",1,0,0)
  SetGlobal("fls6t21","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("XAppren1")
  Global("fls6t22","GLOBAL",16)
THEN RESPONSE #100
  GiveItemCreate("scrl7e","XAppren1",1,0,0)
  SetGlobal("fls6t22","GLOBAL",-1)
  DestroySelf()
END
