
IF
  Exists("container4")
  Global("fls6t01","GLOBAL",8)
THEN RESPONSE #100
  ActionOverride("container4",CreateItem("scrl8c",1,0,0))
  SetGlobal("fls6t01","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("container4")
  Global("fls6t02","GLOBAL",8)
THEN RESPONSE #100
  ActionOverride("container4",CreateItem("scrl8b",1,0,0))
  SetGlobal("fls6t02","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("container4")
  Global("fls6t03","GLOBAL",8)
THEN RESPONSE #100
  ActionOverride("container4",CreateItem("scrl8a",1,0,0))
  SetGlobal("fls6t03","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("container4")
  Global("fls6t04","GLOBAL",8)
THEN RESPONSE #100
  ActionOverride("container4",CreateItem("scrl7w",1,0,0))
  SetGlobal("fls6t04","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("container4")
  Global("fls6t05","GLOBAL",8)
THEN RESPONSE #100
  ActionOverride("container4",CreateItem("scrl7v",1,0,0))
  SetGlobal("fls6t05","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("container4")
  Global("fls6t06","GLOBAL",8)
THEN RESPONSE #100
  ActionOverride("container4",CreateItem("scrl7u",1,0,0))
  SetGlobal("fls6t06","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("container4")
  Global("fls6t07","GLOBAL",8)
THEN RESPONSE #100
  ActionOverride("container4",CreateItem("scrl7u",1,0,0))
  SetGlobal("fls6t07","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("container4")
  Global("fls6t08","GLOBAL",8)
THEN RESPONSE #100
  ActionOverride("container4",CreateItem("scrl7o",1,0,0))
  SetGlobal("fls6t08","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("container4")
  Global("fls6tx0","GLOBAL",8)
THEN RESPONSE #100
  ActionOverride("container4",CreateItem("scrl7o",0,0,0))
  SetGlobal("fls6tx0","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("container4")
  Global("fls6t09","GLOBAL",8)
THEN RESPONSE #100
  ActionOverride("container4",CreateItem("scrl7t",1,0,0))
  SetGlobal("fls6t09","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("container4")
  Global("fls6t10","GLOBAL",8)
THEN RESPONSE #100
  ActionOverride("container4",CreateItem("scrl7s",1,0,0))
  SetGlobal("fls6t10","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("container4")
  Global("fls6t11","GLOBAL",8)
THEN RESPONSE #100
  ActionOverride("container4",CreateItem("scrl7s",1,0,0))
  SetGlobal("fls6t11","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("container4")
  Global("fls6t12","GLOBAL",8)
THEN RESPONSE #100
  ActionOverride("container4",CreateItem("scrl7s",1,1,0))
  SetGlobal("fls6t12","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("container4")
  Global("fls6t13","GLOBAL",8)
THEN RESPONSE #100
  ActionOverride("container4",CreateItem("scrl7r",1,0,0))
  SetGlobal("fls6t13","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("container4")
  Global("fls6t14","GLOBAL",8)
THEN RESPONSE #100
  ActionOverride("container4",CreateItem("scrl7r",1,1,0))
  SetGlobal("fls6t14","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("container4")
  Global("fls6t15","GLOBAL",8)
THEN RESPONSE #100
  ActionOverride("container4",CreateItem("scrl7o",1,0,0))
  SetGlobal("fls6t15","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("container4")
  Global("fls6t16","GLOBAL",8)
THEN RESPONSE #100
  ActionOverride("container4",CreateItem("scrl7l",1,0,0))
  SetGlobal("fls6t16","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("container4")
  Global("fls6t17","GLOBAL",8)
THEN RESPONSE #100
  ActionOverride("container4",CreateItem("scrl7k",1,0,0))
  SetGlobal("fls6t17","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("container4")
  Global("fls6t18","GLOBAL",8)
THEN RESPONSE #100
  ActionOverride("container4",CreateItem("scrl7j",1,0,0))
  SetGlobal("fls6t18","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("container4")
  Global("fls6t19","GLOBAL",8)
THEN RESPONSE #100
  ActionOverride("container4",CreateItem("scrl7i",1,0,0))
  SetGlobal("fls6t19","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("container4")
  Global("fls6t20","GLOBAL",8)
THEN RESPONSE #100
  ActionOverride("container4",CreateItem("scrl7h",1,0,0))
  SetGlobal("fls6t20","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("container4")
  Global("fls6t21","GLOBAL",8)
THEN RESPONSE #100
  ActionOverride("container4",CreateItem("scrl7f",1,0,0))
  SetGlobal("fls6t21","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("container4")
  Global("fls6t22","GLOBAL",8)
THEN RESPONSE #100
  ActionOverride("container4",CreateItem("scrl7e",1,0,0))
  SetGlobal("fls6t22","GLOBAL",-1)
  DestroySelf()
END
