
IF
  Exists("MaeVar")
  Global("fls6t01","GLOBAL",21)
THEN RESPONSE #100
  GiveItemCreate("scrl8c","MaeVar",1,0,0)
  SetGlobal("fls6t01","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("MaeVar")
  Global("fls6t02","GLOBAL",21)
THEN RESPONSE #100
  GiveItemCreate("scrl8b","MaeVar",1,0,0)
  SetGlobal("fls6t02","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("MaeVar")
  Global("fls6t03","GLOBAL",21)
THEN RESPONSE #100
  GiveItemCreate("scrl8a","MaeVar",1,0,0)
  SetGlobal("fls6t03","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("MaeVar")
  Global("fls6t04","GLOBAL",21)
THEN RESPONSE #100
  GiveItemCreate("scrl7w","MaeVar",1,0,0)
  SetGlobal("fls6t04","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("MaeVar")
  Global("fls6t05","GLOBAL",21)
THEN RESPONSE #100
  GiveItemCreate("scrl7v","MaeVar",1,0,0)
  SetGlobal("fls6t05","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("MaeVar")
  Global("fls6t06","GLOBAL",21)
THEN RESPONSE #100
  GiveItemCreate("scrl7u","MaeVar",1,0,0)
  SetGlobal("fls6t06","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("MaeVar")
  Global("fls6t07","GLOBAL",21)
THEN RESPONSE #100
  GiveItemCreate("scrl7u","MaeVar",1,0,0)
  SetGlobal("fls6t07","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("MaeVar")
  Global("fls6t08","GLOBAL",21)
THEN RESPONSE #100
  GiveItemCreate("scrl7o","MaeVar",1,0,0)
  SetGlobal("fls6t08","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("MaeVar")
  Global("fls6tx0","GLOBAL",21)
THEN RESPONSE #100
  GiveItemCreate("scrl7o","MaeVar",0,0,0)
  SetGlobal("fls6tx0","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("MaeVar")
  Global("fls6t09","GLOBAL",21)
THEN RESPONSE #100
  GiveItemCreate("scrl7t","MaeVar",1,0,0)
  SetGlobal("fls6t09","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("MaeVar")
  Global("fls6t10","GLOBAL",21)
THEN RESPONSE #100
  GiveItemCreate("scrl7s","MaeVar",1,0,0)
  SetGlobal("fls6t10","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("MaeVar")
  Global("fls6t11","GLOBAL",21)
THEN RESPONSE #100
  GiveItemCreate("scrl7s","MaeVar",1,0,0)
  SetGlobal("fls6t11","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("MaeVar")
  Global("fls6t12","GLOBAL",21)
THEN RESPONSE #100
  GiveItemCreate("scrl7s","MaeVar",1,1,0)
  SetGlobal("fls6t12","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("MaeVar")
  Global("fls6t13","GLOBAL",21)
THEN RESPONSE #100
  GiveItemCreate("scrl7r","MaeVar",1,0,0)
  SetGlobal("fls6t13","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("MaeVar")
  Global("fls6t14","GLOBAL",21)
THEN RESPONSE #100
  GiveItemCreate("scrl7r","MaeVar",1,1,0)
  SetGlobal("fls6t14","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("MaeVar")
  Global("fls6t15","GLOBAL",21)
THEN RESPONSE #100
  GiveItemCreate("scrl7o","MaeVar",1,0,0)
  SetGlobal("fls6t15","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("MaeVar")
  Global("fls6t16","GLOBAL",21)
THEN RESPONSE #100
  GiveItemCreate("scrl7l","MaeVar",1,0,0)
  SetGlobal("fls6t16","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("MaeVar")
  Global("fls6t17","GLOBAL",21)
THEN RESPONSE #100
  GiveItemCreate("scrl7k","MaeVar",1,0,0)
  SetGlobal("fls6t17","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("MaeVar")
  Global("fls6t18","GLOBAL",21)
THEN RESPONSE #100
  GiveItemCreate("scrl7j","MaeVar",1,0,0)
  SetGlobal("fls6t18","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("MaeVar")
  Global("fls6t19","GLOBAL",21)
THEN RESPONSE #100
  GiveItemCreate("scrl7i","MaeVar",1,0,0)
  SetGlobal("fls6t19","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("MaeVar")
  Global("fls6t20","GLOBAL",21)
THEN RESPONSE #100
  GiveItemCreate("scrl7h","MaeVar",1,0,0)
  SetGlobal("fls6t20","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("MaeVar")
  Global("fls6t21","GLOBAL",21)
THEN RESPONSE #100
  GiveItemCreate("scrl7f","MaeVar",1,0,0)
  SetGlobal("fls6t21","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("MaeVar")
  Global("fls6t22","GLOBAL",21)
THEN RESPONSE #100
  GiveItemCreate("scrl7e","MaeVar",1,0,0)
  SetGlobal("fls6t22","GLOBAL",-1)
  DestroySelf()
END
