
IF
  Exists("pbhunt03")
  Global("fls6t01","GLOBAL",9)
THEN RESPONSE #100
  GiveItemCreate("scrl8c","pbhunt03",1,0,0)
  SetGlobal("fls6t01","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("pbhunt03")
  Global("fls6t02","GLOBAL",9)
THEN RESPONSE #100
  GiveItemCreate("scrl8b","pbhunt03",1,0,0)
  SetGlobal("fls6t02","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("pbhunt03")
  Global("fls6t03","GLOBAL",9)
THEN RESPONSE #100
  GiveItemCreate("scrl8a","pbhunt03",1,0,0)
  SetGlobal("fls6t03","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("pbhunt03")
  Global("fls6t04","GLOBAL",9)
THEN RESPONSE #100
  GiveItemCreate("scrl7w","pbhunt03",1,0,0)
  SetGlobal("fls6t04","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("pbhunt03")
  Global("fls6t05","GLOBAL",9)
THEN RESPONSE #100
  GiveItemCreate("scrl7v","pbhunt03",1,0,0)
  SetGlobal("fls6t05","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("pbhunt03")
  Global("fls6t06","GLOBAL",9)
THEN RESPONSE #100
  GiveItemCreate("scrl7u","pbhunt03",1,0,0)
  SetGlobal("fls6t06","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("pbhunt03")
  Global("fls6t07","GLOBAL",9)
THEN RESPONSE #100
  GiveItemCreate("scrl7u","pbhunt03",1,0,0)
  SetGlobal("fls6t07","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("pbhunt03")
  Global("fls6t08","GLOBAL",9)
THEN RESPONSE #100
  GiveItemCreate("scrl7o","pbhunt03",1,0,0)
  SetGlobal("fls6t08","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("pbhunt03")
  Global("fls6tx0","GLOBAL",9)
THEN RESPONSE #100
  GiveItemCreate("scrl7o","pbhunt03",0,0,0)
  SetGlobal("fls6tx0","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("pbhunt03")
  Global("fls6t09","GLOBAL",9)
THEN RESPONSE #100
  GiveItemCreate("scrl7t","pbhunt03",1,0,0)
  SetGlobal("fls6t09","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("pbhunt03")
  Global("fls6t10","GLOBAL",9)
THEN RESPONSE #100
  GiveItemCreate("scrl7s","pbhunt03",1,0,0)
  SetGlobal("fls6t10","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("pbhunt03")
  Global("fls6t11","GLOBAL",9)
THEN RESPONSE #100
  GiveItemCreate("scrl7s","pbhunt03",1,0,0)
  SetGlobal("fls6t11","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("pbhunt03")
  Global("fls6t12","GLOBAL",9)
THEN RESPONSE #100
  GiveItemCreate("scrl7s","pbhunt03",1,1,0)
  SetGlobal("fls6t12","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("pbhunt03")
  Global("fls6t13","GLOBAL",9)
THEN RESPONSE #100
  GiveItemCreate("scrl7r","pbhunt03",1,0,0)
  SetGlobal("fls6t13","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("pbhunt03")
  Global("fls6t14","GLOBAL",9)
THEN RESPONSE #100
  GiveItemCreate("scrl7r","pbhunt03",1,1,0)
  SetGlobal("fls6t14","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("pbhunt03")
  Global("fls6t15","GLOBAL",9)
THEN RESPONSE #100
  GiveItemCreate("scrl7o","pbhunt03",1,0,0)
  SetGlobal("fls6t15","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("pbhunt03")
  Global("fls6t16","GLOBAL",9)
THEN RESPONSE #100
  GiveItemCreate("scrl7l","pbhunt03",1,0,0)
  SetGlobal("fls6t16","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("pbhunt03")
  Global("fls6t17","GLOBAL",9)
THEN RESPONSE #100
  GiveItemCreate("scrl7k","pbhunt03",1,0,0)
  SetGlobal("fls6t17","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("pbhunt03")
  Global("fls6t18","GLOBAL",9)
THEN RESPONSE #100
  GiveItemCreate("scrl7j","pbhunt03",1,0,0)
  SetGlobal("fls6t18","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("pbhunt03")
  Global("fls6t19","GLOBAL",9)
THEN RESPONSE #100
  GiveItemCreate("scrl7i","pbhunt03",1,0,0)
  SetGlobal("fls6t19","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("pbhunt03")
  Global("fls6t20","GLOBAL",9)
THEN RESPONSE #100
  GiveItemCreate("scrl7h","pbhunt03",1,0,0)
  SetGlobal("fls6t20","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("pbhunt03")
  Global("fls6t21","GLOBAL",9)
THEN RESPONSE #100
  GiveItemCreate("scrl7f","pbhunt03",1,0,0)
  SetGlobal("fls6t21","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("pbhunt03")
  Global("fls6t22","GLOBAL",9)
THEN RESPONSE #100
  GiveItemCreate("scrl7e","pbhunt03",1,0,0)
  SetGlobal("fls6t22","GLOBAL",-1)
  DestroySelf()
END
