
IF
  Exists("pbhunt01")
  Global("fls6t01","GLOBAL",17)
THEN RESPONSE #100
  GiveItemCreate("scrl8c","pbhunt01",1,0,0)
  SetGlobal("fls6t01","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("pbhunt01")
  Global("fls6t02","GLOBAL",17)
THEN RESPONSE #100
  GiveItemCreate("scrl8b","pbhunt01",1,0,0)
  SetGlobal("fls6t02","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("pbhunt01")
  Global("fls6t03","GLOBAL",17)
THEN RESPONSE #100
  GiveItemCreate("scrl8a","pbhunt01",1,0,0)
  SetGlobal("fls6t03","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("pbhunt01")
  Global("fls6t04","GLOBAL",17)
THEN RESPONSE #100
  GiveItemCreate("scrl7w","pbhunt01",1,0,0)
  SetGlobal("fls6t04","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("pbhunt01")
  Global("fls6t05","GLOBAL",17)
THEN RESPONSE #100
  GiveItemCreate("scrl7v","pbhunt01",1,0,0)
  SetGlobal("fls6t05","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("pbhunt01")
  Global("fls6t06","GLOBAL",17)
THEN RESPONSE #100
  GiveItemCreate("scrl7u","pbhunt01",1,0,0)
  SetGlobal("fls6t06","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("pbhunt01")
  Global("fls6t07","GLOBAL",17)
THEN RESPONSE #100
  GiveItemCreate("scrl7u","pbhunt01",1,0,0)
  SetGlobal("fls6t07","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("pbhunt01")
  Global("fls6t08","GLOBAL",17)
THEN RESPONSE #100
  GiveItemCreate("scrl7o","pbhunt01",1,0,0)
  SetGlobal("fls6t08","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("pbhunt01")
  Global("fls6tx0","GLOBAL",17)
THEN RESPONSE #100
  GiveItemCreate("scrl7o","pbhunt01",0,0,0)
  SetGlobal("fls6tx0","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("pbhunt01")
  Global("fls6t09","GLOBAL",17)
THEN RESPONSE #100
  GiveItemCreate("scrl7t","pbhunt01",1,0,0)
  SetGlobal("fls6t09","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("pbhunt01")
  Global("fls6t10","GLOBAL",17)
THEN RESPONSE #100
  GiveItemCreate("scrl7s","pbhunt01",1,0,0)
  SetGlobal("fls6t10","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("pbhunt01")
  Global("fls6t11","GLOBAL",17)
THEN RESPONSE #100
  GiveItemCreate("scrl7s","pbhunt01",1,0,0)
  SetGlobal("fls6t11","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("pbhunt01")
  Global("fls6t12","GLOBAL",17)
THEN RESPONSE #100
  GiveItemCreate("scrl7s","pbhunt01",1,1,0)
  SetGlobal("fls6t12","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("pbhunt01")
  Global("fls6t13","GLOBAL",17)
THEN RESPONSE #100
  GiveItemCreate("scrl7r","pbhunt01",1,0,0)
  SetGlobal("fls6t13","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("pbhunt01")
  Global("fls6t14","GLOBAL",17)
THEN RESPONSE #100
  GiveItemCreate("scrl7r","pbhunt01",1,1,0)
  SetGlobal("fls6t14","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("pbhunt01")
  Global("fls6t15","GLOBAL",17)
THEN RESPONSE #100
  GiveItemCreate("scrl7o","pbhunt01",1,0,0)
  SetGlobal("fls6t15","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("pbhunt01")
  Global("fls6t16","GLOBAL",17)
THEN RESPONSE #100
  GiveItemCreate("scrl7l","pbhunt01",1,0,0)
  SetGlobal("fls6t16","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("pbhunt01")
  Global("fls6t17","GLOBAL",17)
THEN RESPONSE #100
  GiveItemCreate("scrl7k","pbhunt01",1,0,0)
  SetGlobal("fls6t17","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("pbhunt01")
  Global("fls6t18","GLOBAL",17)
THEN RESPONSE #100
  GiveItemCreate("scrl7j","pbhunt01",1,0,0)
  SetGlobal("fls6t18","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("pbhunt01")
  Global("fls6t19","GLOBAL",17)
THEN RESPONSE #100
  GiveItemCreate("scrl7i","pbhunt01",1,0,0)
  SetGlobal("fls6t19","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("pbhunt01")
  Global("fls6t20","GLOBAL",17)
THEN RESPONSE #100
  GiveItemCreate("scrl7h","pbhunt01",1,0,0)
  SetGlobal("fls6t20","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("pbhunt01")
  Global("fls6t21","GLOBAL",17)
THEN RESPONSE #100
  GiveItemCreate("scrl7f","pbhunt01",1,0,0)
  SetGlobal("fls6t21","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("pbhunt01")
  Global("fls6t22","GLOBAL",17)
THEN RESPONSE #100
  GiveItemCreate("scrl7e","pbhunt01",1,0,0)
  SetGlobal("fls6t22","GLOBAL",-1)
  DestroySelf()
END
