
IF
  Exists("firmag01")
  Global("fls6t01","GLOBAL",20)
THEN RESPONSE #100
  GiveItemCreate("scrl8c","firmag01",1,0,0)
  SetGlobal("fls6t01","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("firmag01")
  Global("fls6t02","GLOBAL",20)
THEN RESPONSE #100
  GiveItemCreate("scrl8b","firmag01",1,0,0)
  SetGlobal("fls6t02","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("firmag01")
  Global("fls6t03","GLOBAL",20)
THEN RESPONSE #100
  GiveItemCreate("scrl8a","firmag01",1,0,0)
  SetGlobal("fls6t03","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("firmag01")
  Global("fls6t04","GLOBAL",20)
THEN RESPONSE #100
  GiveItemCreate("scrl7w","firmag01",1,0,0)
  SetGlobal("fls6t04","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("firmag01")
  Global("fls6t05","GLOBAL",20)
THEN RESPONSE #100
  GiveItemCreate("scrl7v","firmag01",1,0,0)
  SetGlobal("fls6t05","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("firmag01")
  Global("fls6t06","GLOBAL",20)
THEN RESPONSE #100
  GiveItemCreate("scrl7u","firmag01",1,0,0)
  SetGlobal("fls6t06","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("firmag01")
  Global("fls6t07","GLOBAL",20)
THEN RESPONSE #100
  GiveItemCreate("scrl7u","firmag01",1,0,0)
  SetGlobal("fls6t07","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("firmag01")
  Global("fls6t08","GLOBAL",20)
THEN RESPONSE #100
  GiveItemCreate("scrl7o","firmag01",1,0,0)
  SetGlobal("fls6t08","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("firmag01")
  Global("fls6tx0","GLOBAL",20)
THEN RESPONSE #100
  GiveItemCreate("scrl7o","firmag01",0,0,0)
  SetGlobal("fls6tx0","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("firmag01")
  Global("fls6t09","GLOBAL",20)
THEN RESPONSE #100
  GiveItemCreate("scrl7t","firmag01",1,0,0)
  SetGlobal("fls6t09","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("firmag01")
  Global("fls6t10","GLOBAL",20)
THEN RESPONSE #100
  GiveItemCreate("scrl7s","firmag01",1,0,0)
  SetGlobal("fls6t10","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("firmag01")
  Global("fls6t11","GLOBAL",20)
THEN RESPONSE #100
  GiveItemCreate("scrl7s","firmag01",1,0,0)
  SetGlobal("fls6t11","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("firmag01")
  Global("fls6t12","GLOBAL",20)
THEN RESPONSE #100
  GiveItemCreate("scrl7s","firmag01",1,1,0)
  SetGlobal("fls6t12","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("firmag01")
  Global("fls6t13","GLOBAL",20)
THEN RESPONSE #100
  GiveItemCreate("scrl7r","firmag01",1,0,0)
  SetGlobal("fls6t13","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("firmag01")
  Global("fls6t14","GLOBAL",20)
THEN RESPONSE #100
  GiveItemCreate("scrl7r","firmag01",1,1,0)
  SetGlobal("fls6t14","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("firmag01")
  Global("fls6t15","GLOBAL",20)
THEN RESPONSE #100
  GiveItemCreate("scrl7o","firmag01",1,0,0)
  SetGlobal("fls6t15","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("firmag01")
  Global("fls6t16","GLOBAL",20)
THEN RESPONSE #100
  GiveItemCreate("scrl7l","firmag01",1,0,0)
  SetGlobal("fls6t16","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("firmag01")
  Global("fls6t17","GLOBAL",20)
THEN RESPONSE #100
  GiveItemCreate("scrl7k","firmag01",1,0,0)
  SetGlobal("fls6t17","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("firmag01")
  Global("fls6t18","GLOBAL",20)
THEN RESPONSE #100
  GiveItemCreate("scrl7j","firmag01",1,0,0)
  SetGlobal("fls6t18","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("firmag01")
  Global("fls6t19","GLOBAL",20)
THEN RESPONSE #100
  GiveItemCreate("scrl7i","firmag01",1,0,0)
  SetGlobal("fls6t19","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("firmag01")
  Global("fls6t20","GLOBAL",20)
THEN RESPONSE #100
  GiveItemCreate("scrl7h","firmag01",1,0,0)
  SetGlobal("fls6t20","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("firmag01")
  Global("fls6t21","GLOBAL",20)
THEN RESPONSE #100
  GiveItemCreate("scrl7f","firmag01",1,0,0)
  SetGlobal("fls6t21","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("firmag01")
  Global("fls6t22","GLOBAL",20)
THEN RESPONSE #100
  GiveItemCreate("scrl7e","firmag01",1,0,0)
  SetGlobal("fls6t22","GLOBAL",-1)
  DestroySelf()
END
