
IF
  Exists("obshal06")
  Global("fls7t01","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("scrl8q","obshal06",1,0,0)
  SetGlobal("fls7t01","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("obshal06")
  Global("fls7t02","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("scrl8p","obshal06",1,0,0)
  SetGlobal("fls7t02","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("obshal05")
  Global("fls7t03","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("scrl8o","obshal05",1,1,0)
  SetGlobal("fls7t03","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("obshal03")
  Global("fls7t04","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("scrl8o","obshal03",1,0,0)
  SetGlobal("fls7t04","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("obshal03")
  Global("fls7t05","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("scrl8n","obshal03",1,0,0)
  SetGlobal("fls7t05","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("obshal03")
  Global("fls7t06","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("scrl8i","obshal03",1,1,0)
  SetGlobal("fls7t06","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("obshal06")
  Global("fls7t07","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("scrl8h","obshal06",1,1,0)
  SetGlobal("fls7t07","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("obshal05")
  Global("fls7t08","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("scrl8g","obshal05",1,1,0)
  SetGlobal("fls7t08","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("obshal05")
  Global("fls7t09","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("scrl8f","obshal05",1,0,0)
  SetGlobal("fls7t09","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("obshal06")
  Global("fls7t10","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("scrl8e","obshal06",1,1,0)
  SetGlobal("fls7t10","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("obshal03")
  Global("fls7t11","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("scrl8h","obshal03",1,1,0)
  SetGlobal("fls7t11","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("obshal06")
  Global("fls7t12","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("scrl8o","obshal06",1,1,0)
  SetGlobal("fls7t12","GLOBAL",-1)
  DestroySelf()
END
