
IF
  Exists("mekrath")
  Global("fls7t01","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("scrl8q","mekrath",1,0,0)
  SetGlobal("fls7t01","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("mekrath")
  Global("fls7t02","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("scrl8p","mekrath",1,0,0)
  SetGlobal("fls7t02","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("mekrath")
  Global("fls7t03","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("scrl8o","mekrath",1,1,0)
  SetGlobal("fls7t03","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("mekrath")
  Global("fls7t04","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("scrl8o","mekrath",1,0,0)
  SetGlobal("fls7t04","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("mekrath")
  Global("fls7t05","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("scrl8n","mekrath",1,0,0)
  SetGlobal("fls7t05","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("mekrath")
  Global("fls7t06","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("scrl8i","mekrath",1,1,0)
  SetGlobal("fls7t06","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("mekrath")
  Global("fls7t07","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("scrl8h","mekrath",1,1,0)
  SetGlobal("fls7t07","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("mekrath")
  Global("fls7t08","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("scrl8g","mekrath",1,1,0)
  SetGlobal("fls7t08","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("mekrath")
  Global("fls7t09","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("scrl8f","mekrath",1,0,0)
  SetGlobal("fls7t09","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("mekrath")
  Global("fls7t10","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("scrl8e","mekrath",1,1,0)
  SetGlobal("fls7t10","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("mekrath")
  Global("fls7t11","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("scrl8h","mekrath",1,1,0)
  SetGlobal("fls7t11","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("mekrath")
  Global("fls7t12","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("scrl8o","mekrath",1,1,0)
  SetGlobal("fls7t12","GLOBAL",-1)
  DestroySelf()
END
