
IF
  Exists("BENTHA")
  Global("flsat01","GLOBAL",15)
THEN RESPONSE #100
  GiveItemCreate("scrl66","BENTHA",1,0,0)
  SetGlobal("flsat01","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("BENTHA")
  Global("flsat02","GLOBAL",15)
THEN RESPONSE #100
  GiveItemCreate("scrl66","BENTHA",1,0,0)
  SetGlobal("flsat02","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("BENTHA")
  Global("flsat03","GLOBAL",15)
THEN RESPONSE #100
  GiveItemCreate("scrl66","BENTHA",1,0,0)
  SetGlobal("flsat03","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("BENTHA")
  Global("flsat04","GLOBAL",15)
THEN RESPONSE #100
  GiveItemCreate("scrl66","BENTHA",1,0,0)
  SetGlobal("flsat04","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("BENTHA")
  Global("flsat05","GLOBAL",15)
THEN RESPONSE #100
  GiveItemCreate("scrl67","BENTHA",1,0,0)
  SetGlobal("flsat05","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("BENTHA")
  Global("flsat06","GLOBAL",15)
THEN RESPONSE #100
  GiveItemCreate("scrl67","BENTHA",1,0,0)
  SetGlobal("flsat06","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("BENTHA")
  Global("flsat07","GLOBAL",15)
THEN RESPONSE #100
  GiveItemCreate("scrl67","BENTHA",1,0,0)
  SetGlobal("flsat07","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("BENTHA")
  Global("flsat08","GLOBAL",15)
THEN RESPONSE #100
  GiveItemCreate("scrl67","BENTHA",1,0,0)
  SetGlobal("flsat08","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("BENTHA")
  Global("flsat09","GLOBAL",15)
THEN RESPONSE #100
  GiveItemCreate("scrl67","BENTHA",1,0,0)
  SetGlobal("flsat09","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("BENTHA")
  Global("flsat10","GLOBAL",15)
THEN RESPONSE #100
  GiveItemCreate("scrl68","BENTHA",1,0,0)
  SetGlobal("flsat10","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("BENTHA")
  Global("flsat11","GLOBAL",15)
THEN RESPONSE #100
  GiveItemCreate("scrl68","BENTHA",1,0,0)
  SetGlobal("flsat11","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("BENTHA")
  Global("flsat12","GLOBAL",15)
THEN RESPONSE #100
  GiveItemCreate("scrl68","BENTHA",1,0,0)
  SetGlobal("flsat12","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("BENTHA")
  Global("flsat13","GLOBAL",15)
THEN RESPONSE #100
  GiveItemCreate("scrl71","BENTHA",1,0,0)
  SetGlobal("flsat13","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("BENTHA")
  Global("flsat14","GLOBAL",15)
THEN RESPONSE #100
  GiveItemCreate("scrl71","BENTHA",1,0,0)
  SetGlobal("flsat14","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("BENTHA")
  Global("flsat15","GLOBAL",15)
THEN RESPONSE #100
  GiveItemCreate("scrl81","BENTHA",1,0,0)
  SetGlobal("flsat15","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("BENTHA")
  Global("flsat16","GLOBAL",15)
THEN RESPONSE #100
  GiveItemCreate("scrl81","BENTHA",1,0,0)
  SetGlobal("flsat16","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("BENTHA")
  Global("flsat18","GLOBAL",15)
THEN RESPONSE #100
  GiveItemCreate("scrl83","BENTHA",1,0,0)
  SetGlobal("flsat18","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("BENTHA")
  Global("flsat19","GLOBAL",15)
THEN RESPONSE #100
  GiveItemCreate("scrl83","BENTHA",1,0,0)
  SetGlobal("flsat19","GLOBAL",-1)
  DestroySelf()
END
