
IF
  Exists("NARCIL")
  Global("flsat01","GLOBAL",5)
THEN RESPONSE #100
  GiveItemCreate("scrl66","NARCIL",1,0,0)
  SetGlobal("flsat01","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("NARCIL")
  Global("flsat02","GLOBAL",5)
THEN RESPONSE #100
  GiveItemCreate("scrl66","NARCIL",1,0,0)
  SetGlobal("flsat02","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("NARCIL")
  Global("flsat03","GLOBAL",5)
THEN RESPONSE #100
  GiveItemCreate("scrl66","NARCIL",1,0,0)
  SetGlobal("flsat03","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("NARCIL")
  Global("flsat04","GLOBAL",5)
THEN RESPONSE #100
  GiveItemCreate("scrl66","NARCIL",1,0,0)
  SetGlobal("flsat04","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("NARCIL")
  Global("flsat05","GLOBAL",5)
THEN RESPONSE #100
  GiveItemCreate("scrl67","NARCIL",1,0,0)
  SetGlobal("flsat05","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("NARCIL")
  Global("flsat06","GLOBAL",5)
THEN RESPONSE #100
  GiveItemCreate("scrl67","NARCIL",1,0,0)
  SetGlobal("flsat06","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("NARCIL")
  Global("flsat07","GLOBAL",5)
THEN RESPONSE #100
  GiveItemCreate("scrl67","NARCIL",1,0,0)
  SetGlobal("flsat07","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("NARCIL")
  Global("flsat08","GLOBAL",5)
THEN RESPONSE #100
  GiveItemCreate("scrl67","NARCIL",1,0,0)
  SetGlobal("flsat08","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("NARCIL")
  Global("flsat09","GLOBAL",5)
THEN RESPONSE #100
  GiveItemCreate("scrl67","NARCIL",1,0,0)
  SetGlobal("flsat09","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("NARCIL")
  Global("flsat10","GLOBAL",5)
THEN RESPONSE #100
  GiveItemCreate("scrl68","NARCIL",1,0,0)
  SetGlobal("flsat10","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("NARCIL")
  Global("flsat11","GLOBAL",5)
THEN RESPONSE #100
  GiveItemCreate("scrl68","NARCIL",1,0,0)
  SetGlobal("flsat11","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("NARCIL")
  Global("flsat12","GLOBAL",5)
THEN RESPONSE #100
  GiveItemCreate("scrl68","NARCIL",1,0,0)
  SetGlobal("flsat12","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("NARCIL")
  Global("flsat13","GLOBAL",5)
THEN RESPONSE #100
  GiveItemCreate("scrl71","NARCIL",1,0,0)
  SetGlobal("flsat13","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("NARCIL")
  Global("flsat14","GLOBAL",5)
THEN RESPONSE #100
  GiveItemCreate("scrl71","NARCIL",1,0,0)
  SetGlobal("flsat14","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("NARCIL")
  Global("flsat15","GLOBAL",5)
THEN RESPONSE #100
  GiveItemCreate("scrl81","NARCIL",1,0,0)
  SetGlobal("flsat15","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("NARCIL")
  Global("flsat16","GLOBAL",5)
THEN RESPONSE #100
  GiveItemCreate("scrl81","NARCIL",1,0,0)
  SetGlobal("flsat16","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("NARCIL")
  Global("flsat18","GLOBAL",5)
THEN RESPONSE #100
  GiveItemCreate("scrl83","NARCIL",1,0,0)
  SetGlobal("flsat18","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("NARCIL")
  Global("flsat19","GLOBAL",5)
THEN RESPONSE #100
  GiveItemCreate("scrl83","NARCIL",1,0,0)
  SetGlobal("flsat19","GLOBAL",-1)
  DestroySelf()
END
