
IF
  Exists("TARNESH")
  Global("flsat01","GLOBAL",9)
THEN RESPONSE #100
  GiveItemCreate("scrl66","TARNESH",1,0,0)
  SetGlobal("flsat01","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("TARNESH")
  Global("flsat02","GLOBAL",9)
THEN RESPONSE #100
  GiveItemCreate("scrl66","TARNESH",1,0,0)
  SetGlobal("flsat02","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("TARNESH")
  Global("flsat03","GLOBAL",9)
THEN RESPONSE #100
  GiveItemCreate("scrl66","TARNESH",1,0,0)
  SetGlobal("flsat03","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("TARNESH")
  Global("flsat04","GLOBAL",9)
THEN RESPONSE #100
  GiveItemCreate("scrl66","TARNESH",1,0,0)
  SetGlobal("flsat04","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("TARNESH")
  Global("flsat05","GLOBAL",9)
THEN RESPONSE #100
  GiveItemCreate("scrl67","TARNESH",1,0,0)
  SetGlobal("flsat05","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("TARNESH")
  Global("flsat06","GLOBAL",9)
THEN RESPONSE #100
  GiveItemCreate("scrl67","TARNESH",1,0,0)
  SetGlobal("flsat06","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("TARNESH")
  Global("flsat07","GLOBAL",9)
THEN RESPONSE #100
  GiveItemCreate("scrl67","TARNESH",1,0,0)
  SetGlobal("flsat07","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("TARNESH")
  Global("flsat08","GLOBAL",9)
THEN RESPONSE #100
  GiveItemCreate("scrl67","TARNESH",1,0,0)
  SetGlobal("flsat08","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("TARNESH")
  Global("flsat09","GLOBAL",9)
THEN RESPONSE #100
  GiveItemCreate("scrl67","TARNESH",1,0,0)
  SetGlobal("flsat09","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("TARNESH")
  Global("flsat10","GLOBAL",9)
THEN RESPONSE #100
  GiveItemCreate("scrl68","TARNESH",1,0,0)
  SetGlobal("flsat10","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("TARNESH")
  Global("flsat11","GLOBAL",9)
THEN RESPONSE #100
  GiveItemCreate("scrl68","TARNESH",1,0,0)
  SetGlobal("flsat11","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("TARNESH")
  Global("flsat12","GLOBAL",9)
THEN RESPONSE #100
  GiveItemCreate("scrl68","TARNESH",1,0,0)
  SetGlobal("flsat12","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("TARNESH")
  Global("flsat13","GLOBAL",9)
THEN RESPONSE #100
  GiveItemCreate("scrl71","TARNESH",1,0,0)
  SetGlobal("flsat13","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("TARNESH")
  Global("flsat14","GLOBAL",9)
THEN RESPONSE #100
  GiveItemCreate("scrl71","TARNESH",1,0,0)
  SetGlobal("flsat14","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("TARNESH")
  Global("flsat15","GLOBAL",9)
THEN RESPONSE #100
  GiveItemCreate("scrl81","TARNESH",1,0,0)
  SetGlobal("flsat15","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("TARNESH")
  Global("flsat16","GLOBAL",9)
THEN RESPONSE #100
  GiveItemCreate("scrl81","TARNESH",1,0,0)
  SetGlobal("flsat16","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("TARNESH")
  Global("flsat18","GLOBAL",9)
THEN RESPONSE #100
  GiveItemCreate("scrl83","TARNESH",1,0,0)
  SetGlobal("flsat18","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("TARNESH")
  Global("flsat19","GLOBAL",9)
THEN RESPONSE #100
  GiveItemCreate("scrl83","TARNESH",1,0,0)
  SetGlobal("flsat19","GLOBAL",-1)
  DestroySelf()
END
