
IF
  Exists("ZORDRAL")
  Global("flsat01","GLOBAL",8)
THEN RESPONSE #100
  GiveItemCreate("scrl66","ZORDRAL",1,0,0)
  SetGlobal("flsat01","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("ZORDRAL")
  Global("flsat02","GLOBAL",8)
THEN RESPONSE #100
  GiveItemCreate("scrl66","ZORDRAL",1,0,0)
  SetGlobal("flsat02","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("ZORDRAL")
  Global("flsat03","GLOBAL",8)
THEN RESPONSE #100
  GiveItemCreate("scrl66","ZORDRAL",1,0,0)
  SetGlobal("flsat03","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("ZORDRAL")
  Global("flsat04","GLOBAL",8)
THEN RESPONSE #100
  GiveItemCreate("scrl66","ZORDRAL",1,0,0)
  SetGlobal("flsat04","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("ZORDRAL")
  Global("flsat05","GLOBAL",8)
THEN RESPONSE #100
  GiveItemCreate("scrl67","ZORDRAL",1,0,0)
  SetGlobal("flsat05","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("ZORDRAL")
  Global("flsat06","GLOBAL",8)
THEN RESPONSE #100
  GiveItemCreate("scrl67","ZORDRAL",1,0,0)
  SetGlobal("flsat06","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("ZORDRAL")
  Global("flsat07","GLOBAL",8)
THEN RESPONSE #100
  GiveItemCreate("scrl67","ZORDRAL",1,0,0)
  SetGlobal("flsat07","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("ZORDRAL")
  Global("flsat08","GLOBAL",8)
THEN RESPONSE #100
  GiveItemCreate("scrl67","ZORDRAL",1,0,0)
  SetGlobal("flsat08","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("ZORDRAL")
  Global("flsat09","GLOBAL",8)
THEN RESPONSE #100
  GiveItemCreate("scrl67","ZORDRAL",1,0,0)
  SetGlobal("flsat09","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("ZORDRAL")
  Global("flsat10","GLOBAL",8)
THEN RESPONSE #100
  GiveItemCreate("scrl68","ZORDRAL",1,0,0)
  SetGlobal("flsat10","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("ZORDRAL")
  Global("flsat11","GLOBAL",8)
THEN RESPONSE #100
  GiveItemCreate("scrl68","ZORDRAL",1,0,0)
  SetGlobal("flsat11","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("ZORDRAL")
  Global("flsat12","GLOBAL",8)
THEN RESPONSE #100
  GiveItemCreate("scrl68","ZORDRAL",1,0,0)
  SetGlobal("flsat12","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("ZORDRAL")
  Global("flsat13","GLOBAL",8)
THEN RESPONSE #100
  GiveItemCreate("scrl71","ZORDRAL",1,0,0)
  SetGlobal("flsat13","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("ZORDRAL")
  Global("flsat14","GLOBAL",8)
THEN RESPONSE #100
  GiveItemCreate("scrl71","ZORDRAL",1,0,0)
  SetGlobal("flsat14","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("ZORDRAL")
  Global("flsat15","GLOBAL",8)
THEN RESPONSE #100
  GiveItemCreate("scrl81","ZORDRAL",1,0,0)
  SetGlobal("flsat15","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("ZORDRAL")
  Global("flsat16","GLOBAL",8)
THEN RESPONSE #100
  GiveItemCreate("scrl81","ZORDRAL",1,0,0)
  SetGlobal("flsat16","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("ZORDRAL")
  Global("flsat18","GLOBAL",8)
THEN RESPONSE #100
  GiveItemCreate("scrl83","ZORDRAL",1,0,0)
  SetGlobal("flsat18","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("ZORDRAL")
  Global("flsat19","GLOBAL",8)
THEN RESPONSE #100
  GiveItemCreate("scrl83","ZORDRAL",1,0,0)
  SetGlobal("flsat19","GLOBAL",-1)
  DestroySelf()
END
