
IF
  Exists("ARKUSH")
  Global("flsat01","GLOBAL",18)
THEN RESPONSE #100
  GiveItemCreate("scrl66","ARKUSH",1,0,0)
  SetGlobal("flsat01","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("ARKUSH")
  Global("flsat02","GLOBAL",18)
THEN RESPONSE #100
  GiveItemCreate("scrl66","ARKUSH",1,0,0)
  SetGlobal("flsat02","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("ARKUSH")
  Global("flsat03","GLOBAL",18)
THEN RESPONSE #100
  GiveItemCreate("scrl66","ARKUSH",1,0,0)
  SetGlobal("flsat03","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("ARKUSH")
  Global("flsat04","GLOBAL",18)
THEN RESPONSE #100
  GiveItemCreate("scrl66","ARKUSH",1,0,0)
  SetGlobal("flsat04","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("ARKUSH")
  Global("flsat05","GLOBAL",18)
THEN RESPONSE #100
  GiveItemCreate("scrl67","ARKUSH",1,0,0)
  SetGlobal("flsat05","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("ARKUSH")
  Global("flsat06","GLOBAL",18)
THEN RESPONSE #100
  GiveItemCreate("scrl67","ARKUSH",1,0,0)
  SetGlobal("flsat06","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("ARKUSH")
  Global("flsat07","GLOBAL",18)
THEN RESPONSE #100
  GiveItemCreate("scrl67","ARKUSH",1,0,0)
  SetGlobal("flsat07","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("ARKUSH")
  Global("flsat08","GLOBAL",18)
THEN RESPONSE #100
  GiveItemCreate("scrl67","ARKUSH",1,0,0)
  SetGlobal("flsat08","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("ARKUSH")
  Global("flsat09","GLOBAL",18)
THEN RESPONSE #100
  GiveItemCreate("scrl67","ARKUSH",1,0,0)
  SetGlobal("flsat09","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("ARKUSH")
  Global("flsat10","GLOBAL",18)
THEN RESPONSE #100
  GiveItemCreate("scrl68","ARKUSH",1,0,0)
  SetGlobal("flsat10","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("ARKUSH")
  Global("flsat11","GLOBAL",18)
THEN RESPONSE #100
  GiveItemCreate("scrl68","ARKUSH",1,0,0)
  SetGlobal("flsat11","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("ARKUSH")
  Global("flsat12","GLOBAL",18)
THEN RESPONSE #100
  GiveItemCreate("scrl68","ARKUSH",1,0,0)
  SetGlobal("flsat12","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("ARKUSH")
  Global("flsat13","GLOBAL",18)
THEN RESPONSE #100
  GiveItemCreate("scrl71","ARKUSH",1,0,0)
  SetGlobal("flsat13","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("ARKUSH")
  Global("flsat14","GLOBAL",18)
THEN RESPONSE #100
  GiveItemCreate("scrl71","ARKUSH",1,0,0)
  SetGlobal("flsat14","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("ARKUSH")
  Global("flsat15","GLOBAL",18)
THEN RESPONSE #100
  GiveItemCreate("scrl81","ARKUSH",1,0,0)
  SetGlobal("flsat15","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("ARKUSH")
  Global("flsat16","GLOBAL",18)
THEN RESPONSE #100
  GiveItemCreate("scrl81","ARKUSH",1,0,0)
  SetGlobal("flsat16","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("ARKUSH")
  Global("flsat18","GLOBAL",18)
THEN RESPONSE #100
  GiveItemCreate("scrl83","ARKUSH",1,0,0)
  SetGlobal("flsat18","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("ARKUSH")
  Global("flsat19","GLOBAL",18)
THEN RESPONSE #100
  GiveItemCreate("scrl83","ARKUSH",1,0,0)
  SetGlobal("flsat19","GLOBAL",-1)
  DestroySelf()
END
