
IF
  Exists("JEMBY")
  Global("flsat01","GLOBAL",6)
THEN RESPONSE #100
  GiveItemCreate("scrl66","JEMBY",1,0,0)
  SetGlobal("flsat01","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("JEMBY")
  Global("flsat02","GLOBAL",6)
THEN RESPONSE #100
  GiveItemCreate("scrl66","JEMBY",1,0,0)
  SetGlobal("flsat02","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("JEMBY")
  Global("flsat03","GLOBAL",6)
THEN RESPONSE #100
  GiveItemCreate("scrl66","JEMBY",1,0,0)
  SetGlobal("flsat03","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("JEMBY")
  Global("flsat04","GLOBAL",6)
THEN RESPONSE #100
  GiveItemCreate("scrl66","JEMBY",1,0,0)
  SetGlobal("flsat04","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("JEMBY")
  Global("flsat05","GLOBAL",6)
THEN RESPONSE #100
  GiveItemCreate("scrl67","JEMBY",1,0,0)
  SetGlobal("flsat05","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("JEMBY")
  Global("flsat06","GLOBAL",6)
THEN RESPONSE #100
  GiveItemCreate("scrl67","JEMBY",1,0,0)
  SetGlobal("flsat06","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("JEMBY")
  Global("flsat07","GLOBAL",6)
THEN RESPONSE #100
  GiveItemCreate("scrl67","JEMBY",1,0,0)
  SetGlobal("flsat07","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("JEMBY")
  Global("flsat08","GLOBAL",6)
THEN RESPONSE #100
  GiveItemCreate("scrl67","JEMBY",1,0,0)
  SetGlobal("flsat08","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("JEMBY")
  Global("flsat09","GLOBAL",6)
THEN RESPONSE #100
  GiveItemCreate("scrl67","JEMBY",1,0,0)
  SetGlobal("flsat09","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("JEMBY")
  Global("flsat10","GLOBAL",6)
THEN RESPONSE #100
  GiveItemCreate("scrl68","JEMBY",1,0,0)
  SetGlobal("flsat10","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("JEMBY")
  Global("flsat11","GLOBAL",6)
THEN RESPONSE #100
  GiveItemCreate("scrl68","JEMBY",1,0,0)
  SetGlobal("flsat11","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("JEMBY")
  Global("flsat12","GLOBAL",6)
THEN RESPONSE #100
  GiveItemCreate("scrl68","JEMBY",1,0,0)
  SetGlobal("flsat12","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("JEMBY")
  Global("flsat13","GLOBAL",6)
THEN RESPONSE #100
  GiveItemCreate("scrl71","JEMBY",1,0,0)
  SetGlobal("flsat13","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("JEMBY")
  Global("flsat14","GLOBAL",6)
THEN RESPONSE #100
  GiveItemCreate("scrl71","JEMBY",1,0,0)
  SetGlobal("flsat14","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("JEMBY")
  Global("flsat15","GLOBAL",6)
THEN RESPONSE #100
  GiveItemCreate("scrl81","JEMBY",1,0,0)
  SetGlobal("flsat15","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("JEMBY")
  Global("flsat16","GLOBAL",6)
THEN RESPONSE #100
  GiveItemCreate("scrl81","JEMBY",1,0,0)
  SetGlobal("flsat16","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("JEMBY")
  Global("flsat18","GLOBAL",6)
THEN RESPONSE #100
  GiveItemCreate("scrl83","JEMBY",1,0,0)
  SetGlobal("flsat18","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("JEMBY")
  Global("flsat19","GLOBAL",6)
THEN RESPONSE #100
  GiveItemCreate("scrl83","JEMBY",1,0,0)
  SetGlobal("flsat19","GLOBAL",-1)
  DestroySelf()
END
