
IF
  Exists("KIRIAN")
  Global("flsat01","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("scrl66","KIRIAN",1,0,0)
  SetGlobal("flsat01","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("KIRIAN")
  Global("flsat02","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("scrl66","KIRIAN",1,0,0)
  SetGlobal("flsat02","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("KIRIAN")
  Global("flsat03","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("scrl66","KIRIAN",1,0,0)
  SetGlobal("flsat03","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("KIRIAN")
  Global("flsat04","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("scrl66","KIRIAN",1,0,0)
  SetGlobal("flsat04","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("KIRIAN")
  Global("flsat05","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("scrl67","KIRIAN",1,0,0)
  SetGlobal("flsat05","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("KIRIAN")
  Global("flsat06","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("scrl67","KIRIAN",1,0,0)
  SetGlobal("flsat06","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("KIRIAN")
  Global("flsat07","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("scrl67","KIRIAN",1,0,0)
  SetGlobal("flsat07","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("KIRIAN")
  Global("flsat08","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("scrl67","KIRIAN",1,0,0)
  SetGlobal("flsat08","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("KIRIAN")
  Global("flsat09","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("scrl67","KIRIAN",1,0,0)
  SetGlobal("flsat09","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("KIRIAN")
  Global("flsat10","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("scrl68","KIRIAN",1,0,0)
  SetGlobal("flsat10","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("KIRIAN")
  Global("flsat11","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("scrl68","KIRIAN",1,0,0)
  SetGlobal("flsat11","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("KIRIAN")
  Global("flsat12","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("scrl68","KIRIAN",1,0,0)
  SetGlobal("flsat12","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("KIRIAN")
  Global("flsat13","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("scrl71","KIRIAN",1,0,0)
  SetGlobal("flsat13","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("KIRIAN")
  Global("flsat14","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("scrl71","KIRIAN",1,0,0)
  SetGlobal("flsat14","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("KIRIAN")
  Global("flsat15","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("scrl81","KIRIAN",1,0,0)
  SetGlobal("flsat15","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("KIRIAN")
  Global("flsat16","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("scrl81","KIRIAN",1,0,0)
  SetGlobal("flsat16","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("KIRIAN")
  Global("flsat18","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("scrl83","KIRIAN",1,0,0)
  SetGlobal("flsat18","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("KIRIAN")
  Global("flsat19","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("scrl83","KIRIAN",1,0,0)
  SetGlobal("flsat19","GLOBAL",-1)
  DestroySelf()
END
