
IF
  Exists("DENAK")
  Global("flsat01","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("scrl66","DENAK",1,0,0)
  SetGlobal("flsat01","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("BRENDAN")
  Global("flsat02","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("scrl66","BRENDAN",1,0,0)
  SetGlobal("flsat02","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("BRENDAN")
  Global("flsat03","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("scrl66","BRENDAN",1,0,0)
  SetGlobal("flsat03","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("DIANA")
  Global("flsat04","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("scrl66","DIANA",1,0,0)
  SetGlobal("flsat04","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("DENAK")
  Global("flsat05","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("scrl67","DENAK",1,0,0)
  SetGlobal("flsat05","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("BRENDAN")
  Global("flsat06","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("scrl67","BRENDAN",1,0,0)
  SetGlobal("flsat06","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("BRENDAN")
  Global("flsat07","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("scrl67","BRENDAN",1,0,0)
  SetGlobal("flsat07","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("DIANA")
  Global("flsat08","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("scrl67","DIANA",1,0,0)
  SetGlobal("flsat08","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("DIANA")
  Global("flsat09","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("scrl67","DIANA",1,0,0)
  SetGlobal("flsat09","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("DENAK")
  Global("flsat10","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("scrl68","DENAK",1,0,0)
  SetGlobal("flsat10","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("BRENDAN")
  Global("flsat11","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("scrl68","BRENDAN",1,0,0)
  SetGlobal("flsat11","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("BRENDAN")
  Global("flsat12","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("scrl68","BRENDAN",1,0,0)
  SetGlobal("flsat12","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("BRENDAN")
  Global("flsat13","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("scrl71","BRENDAN",1,0,0)
  SetGlobal("flsat13","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("BRENDAN")
  Global("flsat14","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("scrl71","BRENDAN",1,0,0)
  SetGlobal("flsat14","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("DIANA")
  Global("flsat15","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("scrl81","DIANA",1,0,0)
  SetGlobal("flsat15","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("BRENDAN")
  Global("flsat16","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("scrl81","BRENDAN",1,0,0)
  SetGlobal("flsat16","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("BRENDAN")
  Global("flsat18","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("scrl83","BRENDAN",1,0,0)
  SetGlobal("flsat18","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("DENAK")
  Global("flsat19","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("scrl83","DENAK",1,0,0)
  SetGlobal("flsat19","GLOBAL",-1)
  DestroySelf()
END
