
IF
  Exists("TARNESH")
  Global("flsbt01","GLOBAL",4)
THEN RESPONSE #100
  GiveItemCreate("scrl1b","TARNESH",1,0,0)
  SetGlobal("flsbt01","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("TARNESH")
  Global("flsbt02","GLOBAL",4)
THEN RESPONSE #100
  GiveItemCreate("scrl1b","TARNESH",1,0,0)
  SetGlobal("flsbt02","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("TARNESH")
  Global("flsbt03","GLOBAL",4)
THEN RESPONSE #100
  GiveItemCreate("scrl1b","TARNESH",1,0,0)
  SetGlobal("flsbt03","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("TARNESH")
  Global("flsbt04","GLOBAL",4)
THEN RESPONSE #100
  GiveItemCreate("scrl1c","TARNESH",1,0,0)
  SetGlobal("flsbt04","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("TARNESH")
  Global("flsbt05","GLOBAL",4)
THEN RESPONSE #100
  GiveItemCreate("scrl1c","TARNESH",1,0,0)
  SetGlobal("flsbt05","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("TARNESH")
  Global("flsbt06","GLOBAL",4)
THEN RESPONSE #100
  GiveItemCreate("scrl3g","TARNESH",1,0,0)
  SetGlobal("flsbt06","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("TARNESH")
  Global("flsbt07","GLOBAL",4)
THEN RESPONSE #100
  GiveItemCreate("scrl85","TARNESH",1,0,0)
  SetGlobal("flsbt07","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("TARNESH")
  Global("flsbt08","GLOBAL",4)
THEN RESPONSE #100
  GiveItemCreate("scrl85","TARNESH",1,0,0)
  SetGlobal("flsbt08","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("TARNESH")
  Global("flsbt09","GLOBAL",4)
THEN RESPONSE #100
  GiveItemCreate("scrl87","TARNESH",1,0,0)
  SetGlobal("flsbt09","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("TARNESH")
  Global("flsbt10","GLOBAL",4)
THEN RESPONSE #100
  GiveItemCreate("scrl87","TARNESH",1,0,0)
  SetGlobal("flsbt10","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("TARNESH")
  Global("flsbt11","GLOBAL",4)
THEN RESPONSE #100
  GiveItemCreate("scrl87","TARNESH",1,0,0)
  SetGlobal("flsbt11","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("TARNESH")
  Global("flsbt12","GLOBAL",4)
THEN RESPONSE #100
  GiveItemCreate("scrl89","TARNESH",1,0,0)
  SetGlobal("flsbt12","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("TARNESH")
  Global("flsbt13","GLOBAL",4)
THEN RESPONSE #100
  GiveItemCreate("scrl89","TARNESH",1,0,0)
  SetGlobal("flsbt13","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("TARNESH")
  Global("flsbt14","GLOBAL",4)
THEN RESPONSE #100
  GiveItemCreate("scrl89","TARNESH",1,0,0)
  SetGlobal("flsbt14","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("TARNESH")
  Global("flsbt15","GLOBAL",4)
THEN RESPONSE #100
  GiveItemCreate("scrl91","TARNESH",1,0,0)
  SetGlobal("flsbt15","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("TARNESH")
  Global("flsbt16","GLOBAL",4)
THEN RESPONSE #100
  GiveItemCreate("scrl93","TARNESH",1,0,0)
  SetGlobal("flsbt16","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("TARNESH")
  Global("flsbt17","GLOBAL",4)
THEN RESPONSE #100
  GiveItemCreate("scrl93","TARNESH",1,0,0)
  SetGlobal("flsbt17","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("TARNESH")
  Global("flsbt18","GLOBAL",4)
THEN RESPONSE #100
  GiveItemCreate("scrl94","TARNESH",1,0,0)
  SetGlobal("flsbt18","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("TARNESH")
  Global("flsbt19","GLOBAL",4)
THEN RESPONSE #100
  GiveItemCreate("scrl95","TARNESH",1,0,0)
  SetGlobal("flsbt19","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("TARNESH")
  Global("flsbt20","GLOBAL",4)
THEN RESPONSE #100
  GiveItemCreate("scrl95","TARNESH",1,0,0)
  SetGlobal("flsbt20","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("TARNESH")
  Global("flsbt21","GLOBAL",4)
THEN RESPONSE #100
  GiveItemCreate("scrl96","TARNESH",1,0,0)
  SetGlobal("flsbt21","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("TARNESH")
  Global("flsbt22","GLOBAL",4)
THEN RESPONSE #100
  GiveItemCreate("scrl96","TARNESH",1,0,0)
  SetGlobal("flsbt22","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("TARNESH")
  Global("flsbt23","GLOBAL",4)
THEN RESPONSE #100
  GiveItemCreate("scrl97","TARNESH",1,0,0)
  SetGlobal("flsbt23","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("TARNESH")
  Global("flsbt24","GLOBAL",4)
THEN RESPONSE #100
  GiveItemCreate("scrl99","TARNESH",1,0,0)
  SetGlobal("flsbt24","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("TARNESH")
  Global("flsbt25","GLOBAL",4)
THEN RESPONSE #100
  GiveItemCreate("scrl99","TARNESH",1,0,0)
  SetGlobal("flsbt25","GLOBAL",-1)
  DestroySelf()
END
