
IF
  Exists("DENAK")
  Global("flsbt01","GLOBAL",7)
THEN RESPONSE #100
  GiveItemCreate("scrl1b","DENAK",1,0,0)
  SetGlobal("flsbt01","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("BRENDAN")
  Global("flsbt02","GLOBAL",7)
THEN RESPONSE #100
  GiveItemCreate("scrl1b","BRENDAN",1,0,0)
  SetGlobal("flsbt02","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("BRENDAN")
  Global("flsbt03","GLOBAL",7)
THEN RESPONSE #100
  GiveItemCreate("scrl1b","BRENDAN",1,0,0)
  SetGlobal("flsbt03","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("DIANA")
  Global("flsbt04","GLOBAL",7)
THEN RESPONSE #100
  GiveItemCreate("scrl1c","DIANA",1,0,0)
  SetGlobal("flsbt04","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("DENAK")
  Global("flsbt05","GLOBAL",7)
THEN RESPONSE #100
  GiveItemCreate("scrl1c","DENAK",1,0,0)
  SetGlobal("flsbt05","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("DIANA")
  Global("flsbt06","GLOBAL",7)
THEN RESPONSE #100
  GiveItemCreate("scrl3g","DIANA",1,0,0)
  SetGlobal("flsbt06","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("DIANA")
  Global("flsbt07","GLOBAL",7)
THEN RESPONSE #100
  GiveItemCreate("scrl85","DIANA",1,0,0)
  SetGlobal("flsbt07","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("BRENDAN")
  Global("flsbt08","GLOBAL",7)
THEN RESPONSE #100
  GiveItemCreate("scrl85","BRENDAN",1,0,0)
  SetGlobal("flsbt08","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("BRENDAN")
  Global("flsbt09","GLOBAL",7)
THEN RESPONSE #100
  GiveItemCreate("scrl87","BRENDAN",1,0,0)
  SetGlobal("flsbt09","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("DENAK")
  Global("flsbt10","GLOBAL",7)
THEN RESPONSE #100
  GiveItemCreate("scrl87","DENAK",1,0,0)
  SetGlobal("flsbt10","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("DIANA")
  Global("flsbt11","GLOBAL",7)
THEN RESPONSE #100
  GiveItemCreate("scrl87","DIANA",1,0,0)
  SetGlobal("flsbt11","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("DIANA")
  Global("flsbt12","GLOBAL",7)
THEN RESPONSE #100
  GiveItemCreate("scrl89","DIANA",1,0,0)
  SetGlobal("flsbt12","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("DIANA")
  Global("flsbt13","GLOBAL",7)
THEN RESPONSE #100
  GiveItemCreate("scrl89","DIANA",1,0,0)
  SetGlobal("flsbt13","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("DIANA")
  Global("flsbt14","GLOBAL",7)
THEN RESPONSE #100
  GiveItemCreate("scrl89","DIANA",1,0,0)
  SetGlobal("flsbt14","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("DIANA")
  Global("flsbt15","GLOBAL",7)
THEN RESPONSE #100
  GiveItemCreate("scrl91","DIANA",1,0,0)
  SetGlobal("flsbt15","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("DIANA")
  Global("flsbt16","GLOBAL",7)
THEN RESPONSE #100
  GiveItemCreate("scrl93","DIANA",1,0,0)
  SetGlobal("flsbt16","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("DENAK")
  Global("flsbt17","GLOBAL",7)
THEN RESPONSE #100
  GiveItemCreate("scrl93","DENAK",1,0,0)
  SetGlobal("flsbt17","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("DENAK")
  Global("flsbt18","GLOBAL",7)
THEN RESPONSE #100
  GiveItemCreate("scrl94","DENAK",1,0,0)
  SetGlobal("flsbt18","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("BRENDAN")
  Global("flsbt19","GLOBAL",7)
THEN RESPONSE #100
  GiveItemCreate("scrl95","BRENDAN",1,0,0)
  SetGlobal("flsbt19","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("DENAK")
  Global("flsbt20","GLOBAL",7)
THEN RESPONSE #100
  GiveItemCreate("scrl95","DENAK",1,0,0)
  SetGlobal("flsbt20","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("DENAK")
  Global("flsbt21","GLOBAL",7)
THEN RESPONSE #100
  GiveItemCreate("scrl96","DENAK",1,0,0)
  SetGlobal("flsbt21","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("DIANA")
  Global("flsbt22","GLOBAL",7)
THEN RESPONSE #100
  GiveItemCreate("scrl96","DIANA",1,0,0)
  SetGlobal("flsbt22","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("BRENDAN")
  Global("flsbt23","GLOBAL",7)
THEN RESPONSE #100
  GiveItemCreate("scrl97","BRENDAN",1,0,0)
  SetGlobal("flsbt23","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("BRENDAN")
  Global("flsbt24","GLOBAL",7)
THEN RESPONSE #100
  GiveItemCreate("scrl99","BRENDAN",1,0,0)
  SetGlobal("flsbt24","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("DENAK")
  Global("flsbt25","GLOBAL",7)
THEN RESPONSE #100
  GiveItemCreate("scrl99","DENAK",1,0,0)
  SetGlobal("flsbt25","GLOBAL",-1)
  DestroySelf()
END
