
IF
  Exists("ARKUSH")
  Global("flsbt01","GLOBAL",1)
THEN RESPONSE #100
  GiveItemCreate("scrl1b","ARKUSH",1,0,0)
  SetGlobal("flsbt01","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("ARKUSH")
  Global("flsbt02","GLOBAL",1)
THEN RESPONSE #100
  GiveItemCreate("scrl1b","ARKUSH",1,0,0)
  SetGlobal("flsbt02","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("ARKUSH")
  Global("flsbt03","GLOBAL",1)
THEN RESPONSE #100
  GiveItemCreate("scrl1b","ARKUSH",1,0,0)
  SetGlobal("flsbt03","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("ARKUSH")
  Global("flsbt04","GLOBAL",1)
THEN RESPONSE #100
  GiveItemCreate("scrl1c","ARKUSH",1,0,0)
  SetGlobal("flsbt04","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("ARKUSH")
  Global("flsbt05","GLOBAL",1)
THEN RESPONSE #100
  GiveItemCreate("scrl1c","ARKUSH",1,0,0)
  SetGlobal("flsbt05","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("ARKUSH")
  Global("flsbt06","GLOBAL",1)
THEN RESPONSE #100
  GiveItemCreate("scrl3g","ARKUSH",1,0,0)
  SetGlobal("flsbt06","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("ARKUSH")
  Global("flsbt07","GLOBAL",1)
THEN RESPONSE #100
  GiveItemCreate("scrl85","ARKUSH",1,0,0)
  SetGlobal("flsbt07","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("ARKUSH")
  Global("flsbt08","GLOBAL",1)
THEN RESPONSE #100
  GiveItemCreate("scrl85","ARKUSH",1,0,0)
  SetGlobal("flsbt08","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("ARKUSH")
  Global("flsbt09","GLOBAL",1)
THEN RESPONSE #100
  GiveItemCreate("scrl87","ARKUSH",1,0,0)
  SetGlobal("flsbt09","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("ARKUSH")
  Global("flsbt10","GLOBAL",1)
THEN RESPONSE #100
  GiveItemCreate("scrl87","ARKUSH",1,0,0)
  SetGlobal("flsbt10","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("ARKUSH")
  Global("flsbt11","GLOBAL",1)
THEN RESPONSE #100
  GiveItemCreate("scrl87","ARKUSH",1,0,0)
  SetGlobal("flsbt11","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("ARKUSH")
  Global("flsbt12","GLOBAL",1)
THEN RESPONSE #100
  GiveItemCreate("scrl89","ARKUSH",1,0,0)
  SetGlobal("flsbt12","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("ARKUSH")
  Global("flsbt13","GLOBAL",1)
THEN RESPONSE #100
  GiveItemCreate("scrl89","ARKUSH",1,0,0)
  SetGlobal("flsbt13","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("ARKUSH")
  Global("flsbt14","GLOBAL",1)
THEN RESPONSE #100
  GiveItemCreate("scrl89","ARKUSH",1,0,0)
  SetGlobal("flsbt14","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("ARKUSH")
  Global("flsbt15","GLOBAL",1)
THEN RESPONSE #100
  GiveItemCreate("scrl91","ARKUSH",1,0,0)
  SetGlobal("flsbt15","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("ARKUSH")
  Global("flsbt16","GLOBAL",1)
THEN RESPONSE #100
  GiveItemCreate("scrl93","ARKUSH",1,0,0)
  SetGlobal("flsbt16","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("ARKUSH")
  Global("flsbt17","GLOBAL",1)
THEN RESPONSE #100
  GiveItemCreate("scrl93","ARKUSH",1,0,0)
  SetGlobal("flsbt17","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("ARKUSH")
  Global("flsbt18","GLOBAL",1)
THEN RESPONSE #100
  GiveItemCreate("scrl94","ARKUSH",1,0,0)
  SetGlobal("flsbt18","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("ARKUSH")
  Global("flsbt19","GLOBAL",1)
THEN RESPONSE #100
  GiveItemCreate("scrl95","ARKUSH",1,0,0)
  SetGlobal("flsbt19","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("ARKUSH")
  Global("flsbt20","GLOBAL",1)
THEN RESPONSE #100
  GiveItemCreate("scrl95","ARKUSH",1,0,0)
  SetGlobal("flsbt20","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("ARKUSH")
  Global("flsbt21","GLOBAL",1)
THEN RESPONSE #100
  GiveItemCreate("scrl96","ARKUSH",1,0,0)
  SetGlobal("flsbt21","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("ARKUSH")
  Global("flsbt22","GLOBAL",1)
THEN RESPONSE #100
  GiveItemCreate("scrl96","ARKUSH",1,0,0)
  SetGlobal("flsbt22","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("ARKUSH")
  Global("flsbt23","GLOBAL",1)
THEN RESPONSE #100
  GiveItemCreate("scrl97","ARKUSH",1,0,0)
  SetGlobal("flsbt23","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("ARKUSH")
  Global("flsbt24","GLOBAL",1)
THEN RESPONSE #100
  GiveItemCreate("scrl99","ARKUSH",1,0,0)
  SetGlobal("flsbt24","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("ARKUSH")
  Global("flsbt25","GLOBAL",1)
THEN RESPONSE #100
  GiveItemCreate("scrl99","ARKUSH",1,0,0)
  SetGlobal("flsbt25","GLOBAL",-1)
  DestroySelf()
END
