
IF
  Exists("OULAM")
  Global("flsbt01","GLOBAL",22)
THEN RESPONSE #100
  GiveItemCreate("scrl1b","OULAM",1,0,0)
  SetGlobal("flsbt01","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("OULAM")
  Global("flsbt02","GLOBAL",22)
THEN RESPONSE #100
  GiveItemCreate("scrl1b","OULAM",1,0,0)
  SetGlobal("flsbt02","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("NIEMAIN")
  Global("flsbt03","GLOBAL",22)
THEN RESPONSE #100
  GiveItemCreate("scrl1b","NIEMAIN",1,0,0)
  SetGlobal("flsbt03","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("WHEBER")
  Global("flsbt04","GLOBAL",22)
THEN RESPONSE #100
  GiveItemCreate("scrl1c","WHEBER",1,0,0)
  SetGlobal("flsbt04","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("NIEMAIN")
  Global("flsbt05","GLOBAL",22)
THEN RESPONSE #100
  GiveItemCreate("scrl1c","NIEMAIN",1,0,0)
  SetGlobal("flsbt05","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("WHEBER")
  Global("flsbt06","GLOBAL",22)
THEN RESPONSE #100
  GiveItemCreate("scrl3g","WHEBER",1,0,0)
  SetGlobal("flsbt06","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("WHEBER")
  Global("flsbt07","GLOBAL",22)
THEN RESPONSE #100
  GiveItemCreate("scrl85","WHEBER",1,0,0)
  SetGlobal("flsbt07","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("WHEBER")
  Global("flsbt08","GLOBAL",22)
THEN RESPONSE #100
  GiveItemCreate("scrl85","WHEBER",1,0,0)
  SetGlobal("flsbt08","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("WHEBER")
  Global("flsbt09","GLOBAL",22)
THEN RESPONSE #100
  GiveItemCreate("scrl87","WHEBER",1,0,0)
  SetGlobal("flsbt09","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("WILLIAM")
  Global("flsbt10","GLOBAL",22)
THEN RESPONSE #100
  GiveItemCreate("scrl87","WILLIAM",1,0,0)
  SetGlobal("flsbt10","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("WHEBER")
  Global("flsbt11","GLOBAL",22)
THEN RESPONSE #100
  GiveItemCreate("scrl87","WHEBER",1,0,0)
  SetGlobal("flsbt11","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("WILLIAM")
  Global("flsbt12","GLOBAL",22)
THEN RESPONSE #100
  GiveItemCreate("scrl89","WILLIAM",1,0,0)
  SetGlobal("flsbt12","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("NIEMAIN")
  Global("flsbt13","GLOBAL",22)
THEN RESPONSE #100
  GiveItemCreate("scrl89","NIEMAIN",1,0,0)
  SetGlobal("flsbt13","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("WHEBER")
  Global("flsbt14","GLOBAL",22)
THEN RESPONSE #100
  GiveItemCreate("scrl89","WHEBER",1,0,0)
  SetGlobal("flsbt14","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("WILLIAM")
  Global("flsbt15","GLOBAL",22)
THEN RESPONSE #100
  GiveItemCreate("scrl91","WILLIAM",1,0,0)
  SetGlobal("flsbt15","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("OULAM")
  Global("flsbt16","GLOBAL",22)
THEN RESPONSE #100
  GiveItemCreate("scrl93","OULAM",1,0,0)
  SetGlobal("flsbt16","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("WHEBER")
  Global("flsbt17","GLOBAL",22)
THEN RESPONSE #100
  GiveItemCreate("scrl93","WHEBER",1,0,0)
  SetGlobal("flsbt17","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("NIEMAIN")
  Global("flsbt18","GLOBAL",22)
THEN RESPONSE #100
  GiveItemCreate("scrl94","NIEMAIN",1,0,0)
  SetGlobal("flsbt18","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("WHEBER")
  Global("flsbt19","GLOBAL",22)
THEN RESPONSE #100
  GiveItemCreate("scrl95","WHEBER",1,0,0)
  SetGlobal("flsbt19","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("NIEMAIN")
  Global("flsbt20","GLOBAL",22)
THEN RESPONSE #100
  GiveItemCreate("scrl95","NIEMAIN",1,0,0)
  SetGlobal("flsbt20","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("NIEMAIN")
  Global("flsbt21","GLOBAL",22)
THEN RESPONSE #100
  GiveItemCreate("scrl96","NIEMAIN",1,0,0)
  SetGlobal("flsbt21","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("OULAM")
  Global("flsbt22","GLOBAL",22)
THEN RESPONSE #100
  GiveItemCreate("scrl96","OULAM",1,0,0)
  SetGlobal("flsbt22","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("OULAM")
  Global("flsbt23","GLOBAL",22)
THEN RESPONSE #100
  GiveItemCreate("scrl97","OULAM",1,0,0)
  SetGlobal("flsbt23","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("NIEMAIN")
  Global("flsbt24","GLOBAL",22)
THEN RESPONSE #100
  GiveItemCreate("scrl99","NIEMAIN",1,0,0)
  SetGlobal("flsbt24","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("OULAM")
  Global("flsbt25","GLOBAL",22)
THEN RESPONSE #100
  GiveItemCreate("scrl99","OULAM",1,0,0)
  SetGlobal("flsbt25","GLOBAL",-1)
  DestroySelf()
END
