
IF
  Exists("HAREIS")
  Global("flsbt01","GLOBAL",20)
THEN RESPONSE #100
  GiveItemCreate("scrl1b","HAREIS",1,0,0)
  SetGlobal("flsbt01","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("HAREIS")
  Global("flsbt02","GLOBAL",20)
THEN RESPONSE #100
  GiveItemCreate("scrl1b","HAREIS",1,0,0)
  SetGlobal("flsbt02","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("HAREIS")
  Global("flsbt03","GLOBAL",20)
THEN RESPONSE #100
  GiveItemCreate("scrl1b","HAREIS",1,0,0)
  SetGlobal("flsbt03","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("HAREIS")
  Global("flsbt04","GLOBAL",20)
THEN RESPONSE #100
  GiveItemCreate("scrl1c","HAREIS",1,0,0)
  SetGlobal("flsbt04","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("HAREIS")
  Global("flsbt05","GLOBAL",20)
THEN RESPONSE #100
  GiveItemCreate("scrl1c","HAREIS",1,0,0)
  SetGlobal("flsbt05","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("HAREIS")
  Global("flsbt06","GLOBAL",20)
THEN RESPONSE #100
  GiveItemCreate("scrl3g","HAREIS",1,0,0)
  SetGlobal("flsbt06","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("HAREIS")
  Global("flsbt07","GLOBAL",20)
THEN RESPONSE #100
  GiveItemCreate("scrl85","HAREIS",1,0,0)
  SetGlobal("flsbt07","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("HAREIS")
  Global("flsbt08","GLOBAL",20)
THEN RESPONSE #100
  GiveItemCreate("scrl85","HAREIS",1,0,0)
  SetGlobal("flsbt08","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("HAREIS")
  Global("flsbt09","GLOBAL",20)
THEN RESPONSE #100
  GiveItemCreate("scrl87","HAREIS",1,0,0)
  SetGlobal("flsbt09","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("HAREIS")
  Global("flsbt10","GLOBAL",20)
THEN RESPONSE #100
  GiveItemCreate("scrl87","HAREIS",1,0,0)
  SetGlobal("flsbt10","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("HAREIS")
  Global("flsbt11","GLOBAL",20)
THEN RESPONSE #100
  GiveItemCreate("scrl87","HAREIS",1,0,0)
  SetGlobal("flsbt11","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("HAREIS")
  Global("flsbt12","GLOBAL",20)
THEN RESPONSE #100
  GiveItemCreate("scrl89","HAREIS",1,0,0)
  SetGlobal("flsbt12","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("HAREIS")
  Global("flsbt13","GLOBAL",20)
THEN RESPONSE #100
  GiveItemCreate("scrl89","HAREIS",1,0,0)
  SetGlobal("flsbt13","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("HAREIS")
  Global("flsbt14","GLOBAL",20)
THEN RESPONSE #100
  GiveItemCreate("scrl89","HAREIS",1,0,0)
  SetGlobal("flsbt14","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("HAREIS")
  Global("flsbt15","GLOBAL",20)
THEN RESPONSE #100
  GiveItemCreate("scrl91","HAREIS",1,0,0)
  SetGlobal("flsbt15","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("HAREIS")
  Global("flsbt16","GLOBAL",20)
THEN RESPONSE #100
  GiveItemCreate("scrl93","HAREIS",1,0,0)
  SetGlobal("flsbt16","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("HAREIS")
  Global("flsbt17","GLOBAL",20)
THEN RESPONSE #100
  GiveItemCreate("scrl93","HAREIS",1,0,0)
  SetGlobal("flsbt17","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("HAREIS")
  Global("flsbt18","GLOBAL",20)
THEN RESPONSE #100
  GiveItemCreate("scrl94","HAREIS",1,0,0)
  SetGlobal("flsbt18","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("HAREIS")
  Global("flsbt19","GLOBAL",20)
THEN RESPONSE #100
  GiveItemCreate("scrl95","HAREIS",1,0,0)
  SetGlobal("flsbt19","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("HAREIS")
  Global("flsbt20","GLOBAL",20)
THEN RESPONSE #100
  GiveItemCreate("scrl95","HAREIS",1,0,0)
  SetGlobal("flsbt20","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("HAREIS")
  Global("flsbt21","GLOBAL",20)
THEN RESPONSE #100
  GiveItemCreate("scrl96","HAREIS",1,0,0)
  SetGlobal("flsbt21","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("HAREIS")
  Global("flsbt22","GLOBAL",20)
THEN RESPONSE #100
  GiveItemCreate("scrl96","HAREIS",1,0,0)
  SetGlobal("flsbt22","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("HAREIS")
  Global("flsbt23","GLOBAL",20)
THEN RESPONSE #100
  GiveItemCreate("scrl97","HAREIS",1,0,0)
  SetGlobal("flsbt23","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("HAREIS")
  Global("flsbt24","GLOBAL",20)
THEN RESPONSE #100
  GiveItemCreate("scrl99","HAREIS",1,0,0)
  SetGlobal("flsbt24","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("HAREIS")
  Global("flsbt25","GLOBAL",20)
THEN RESPONSE #100
  GiveItemCreate("scrl99","HAREIS",1,0,0)
  SetGlobal("flsbt25","GLOBAL",-1)
  DestroySelf()
END
