
IF
  Exists("NARCIL")
  Global("flsbt01","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("scrl1b","NARCIL",1,0,0)
  SetGlobal("flsbt01","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("NARCIL")
  Global("flsbt02","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("scrl1b","NARCIL",1,0,0)
  SetGlobal("flsbt02","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("NARCIL")
  Global("flsbt03","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("scrl1b","NARCIL",1,0,0)
  SetGlobal("flsbt03","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("NARCIL")
  Global("flsbt04","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("scrl1c","NARCIL",1,0,0)
  SetGlobal("flsbt04","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("NARCIL")
  Global("flsbt05","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("scrl1c","NARCIL",1,0,0)
  SetGlobal("flsbt05","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("NARCIL")
  Global("flsbt06","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("scrl3g","NARCIL",1,0,0)
  SetGlobal("flsbt06","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("NARCIL")
  Global("flsbt07","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("scrl85","NARCIL",1,0,0)
  SetGlobal("flsbt07","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("NARCIL")
  Global("flsbt08","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("scrl85","NARCIL",1,0,0)
  SetGlobal("flsbt08","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("NARCIL")
  Global("flsbt09","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("scrl87","NARCIL",1,0,0)
  SetGlobal("flsbt09","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("NARCIL")
  Global("flsbt10","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("scrl87","NARCIL",1,0,0)
  SetGlobal("flsbt10","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("NARCIL")
  Global("flsbt11","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("scrl87","NARCIL",1,0,0)
  SetGlobal("flsbt11","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("NARCIL")
  Global("flsbt12","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("scrl89","NARCIL",1,0,0)
  SetGlobal("flsbt12","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("NARCIL")
  Global("flsbt13","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("scrl89","NARCIL",1,0,0)
  SetGlobal("flsbt13","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("NARCIL")
  Global("flsbt14","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("scrl89","NARCIL",1,0,0)
  SetGlobal("flsbt14","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("NARCIL")
  Global("flsbt15","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("scrl91","NARCIL",1,0,0)
  SetGlobal("flsbt15","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("NARCIL")
  Global("flsbt16","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("scrl93","NARCIL",1,0,0)
  SetGlobal("flsbt16","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("NARCIL")
  Global("flsbt17","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("scrl93","NARCIL",1,0,0)
  SetGlobal("flsbt17","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("NARCIL")
  Global("flsbt18","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("scrl94","NARCIL",1,0,0)
  SetGlobal("flsbt18","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("NARCIL")
  Global("flsbt19","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("scrl95","NARCIL",1,0,0)
  SetGlobal("flsbt19","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("NARCIL")
  Global("flsbt20","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("scrl95","NARCIL",1,0,0)
  SetGlobal("flsbt20","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("NARCIL")
  Global("flsbt21","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("scrl96","NARCIL",1,0,0)
  SetGlobal("flsbt21","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("NARCIL")
  Global("flsbt22","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("scrl96","NARCIL",1,0,0)
  SetGlobal("flsbt22","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("NARCIL")
  Global("flsbt23","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("scrl97","NARCIL",1,0,0)
  SetGlobal("flsbt23","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("NARCIL")
  Global("flsbt24","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("scrl99","NARCIL",1,0,0)
  SetGlobal("flsbt24","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("NARCIL")
  Global("flsbt25","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("scrl99","NARCIL",1,0,0)
  SetGlobal("flsbt25","GLOBAL",-1)
  DestroySelf()
END
