
IF
  Exists("NATASHA")
  Global("flsbt01","GLOBAL",15)
THEN RESPONSE #100
  GiveItemCreate("scrl1b","NATASHA",1,0,0)
  SetGlobal("flsbt01","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("NATASHA")
  Global("flsbt02","GLOBAL",15)
THEN RESPONSE #100
  GiveItemCreate("scrl1b","NATASHA",1,0,0)
  SetGlobal("flsbt02","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("NATASHA")
  Global("flsbt03","GLOBAL",15)
THEN RESPONSE #100
  GiveItemCreate("scrl1b","NATASHA",1,0,0)
  SetGlobal("flsbt03","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("NATASHA")
  Global("flsbt04","GLOBAL",15)
THEN RESPONSE #100
  GiveItemCreate("scrl1c","NATASHA",1,0,0)
  SetGlobal("flsbt04","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("NATASHA")
  Global("flsbt05","GLOBAL",15)
THEN RESPONSE #100
  GiveItemCreate("scrl1c","NATASHA",1,0,0)
  SetGlobal("flsbt05","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("NATASHA")
  Global("flsbt06","GLOBAL",15)
THEN RESPONSE #100
  GiveItemCreate("scrl3g","NATASHA",1,0,0)
  SetGlobal("flsbt06","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("NATASHA")
  Global("flsbt07","GLOBAL",15)
THEN RESPONSE #100
  GiveItemCreate("scrl85","NATASHA",1,0,0)
  SetGlobal("flsbt07","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("NATASHA")
  Global("flsbt08","GLOBAL",15)
THEN RESPONSE #100
  GiveItemCreate("scrl85","NATASHA",1,0,0)
  SetGlobal("flsbt08","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("NATASHA")
  Global("flsbt09","GLOBAL",15)
THEN RESPONSE #100
  GiveItemCreate("scrl87","NATASHA",1,0,0)
  SetGlobal("flsbt09","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("NATASHA")
  Global("flsbt10","GLOBAL",15)
THEN RESPONSE #100
  GiveItemCreate("scrl87","NATASHA",1,0,0)
  SetGlobal("flsbt10","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("NATASHA")
  Global("flsbt11","GLOBAL",15)
THEN RESPONSE #100
  GiveItemCreate("scrl87","NATASHA",1,0,0)
  SetGlobal("flsbt11","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("NATASHA")
  Global("flsbt12","GLOBAL",15)
THEN RESPONSE #100
  GiveItemCreate("scrl89","NATASHA",1,0,0)
  SetGlobal("flsbt12","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("NATASHA")
  Global("flsbt13","GLOBAL",15)
THEN RESPONSE #100
  GiveItemCreate("scrl89","NATASHA",1,0,0)
  SetGlobal("flsbt13","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("NATASHA")
  Global("flsbt14","GLOBAL",15)
THEN RESPONSE #100
  GiveItemCreate("scrl89","NATASHA",1,0,0)
  SetGlobal("flsbt14","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("NATASHA")
  Global("flsbt15","GLOBAL",15)
THEN RESPONSE #100
  GiveItemCreate("scrl91","NATASHA",1,0,0)
  SetGlobal("flsbt15","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("NATASHA")
  Global("flsbt16","GLOBAL",15)
THEN RESPONSE #100
  GiveItemCreate("scrl93","NATASHA",1,0,0)
  SetGlobal("flsbt16","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("NATASHA")
  Global("flsbt17","GLOBAL",15)
THEN RESPONSE #100
  GiveItemCreate("scrl93","NATASHA",1,0,0)
  SetGlobal("flsbt17","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("NATASHA")
  Global("flsbt18","GLOBAL",15)
THEN RESPONSE #100
  GiveItemCreate("scrl94","NATASHA",1,0,0)
  SetGlobal("flsbt18","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("NATASHA")
  Global("flsbt19","GLOBAL",15)
THEN RESPONSE #100
  GiveItemCreate("scrl95","NATASHA",1,0,0)
  SetGlobal("flsbt19","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("NATASHA")
  Global("flsbt20","GLOBAL",15)
THEN RESPONSE #100
  GiveItemCreate("scrl95","NATASHA",1,0,0)
  SetGlobal("flsbt20","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("NATASHA")
  Global("flsbt21","GLOBAL",15)
THEN RESPONSE #100
  GiveItemCreate("scrl96","NATASHA",1,0,0)
  SetGlobal("flsbt21","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("NATASHA")
  Global("flsbt22","GLOBAL",15)
THEN RESPONSE #100
  GiveItemCreate("scrl96","NATASHA",1,0,0)
  SetGlobal("flsbt22","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("NATASHA")
  Global("flsbt23","GLOBAL",15)
THEN RESPONSE #100
  GiveItemCreate("scrl97","NATASHA",1,0,0)
  SetGlobal("flsbt23","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("NATASHA")
  Global("flsbt24","GLOBAL",15)
THEN RESPONSE #100
  GiveItemCreate("scrl99","NATASHA",1,0,0)
  SetGlobal("flsbt24","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("NATASHA")
  Global("flsbt25","GLOBAL",15)
THEN RESPONSE #100
  GiveItemCreate("scrl99","NATASHA",1,0,0)
  SetGlobal("flsbt25","GLOBAL",-1)
  DestroySelf()
END
