
IF
  Exists("JEMBY")
  Global("flsbt01","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("scrl1b","JEMBY",1,0,0)
  SetGlobal("flsbt01","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("JEMBY")
  Global("flsbt02","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("scrl1b","JEMBY",1,0,0)
  SetGlobal("flsbt02","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("JEMBY")
  Global("flsbt03","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("scrl1b","JEMBY",1,0,0)
  SetGlobal("flsbt03","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("JEMBY")
  Global("flsbt04","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("scrl1c","JEMBY",1,0,0)
  SetGlobal("flsbt04","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("JEMBY")
  Global("flsbt05","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("scrl1c","JEMBY",1,0,0)
  SetGlobal("flsbt05","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("JEMBY")
  Global("flsbt06","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("scrl3g","JEMBY",1,0,0)
  SetGlobal("flsbt06","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("JEMBY")
  Global("flsbt07","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("scrl85","JEMBY",1,0,0)
  SetGlobal("flsbt07","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("JEMBY")
  Global("flsbt08","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("scrl85","JEMBY",1,0,0)
  SetGlobal("flsbt08","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("JEMBY")
  Global("flsbt09","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("scrl87","JEMBY",1,0,0)
  SetGlobal("flsbt09","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("JEMBY")
  Global("flsbt10","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("scrl87","JEMBY",1,0,0)
  SetGlobal("flsbt10","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("JEMBY")
  Global("flsbt11","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("scrl87","JEMBY",1,0,0)
  SetGlobal("flsbt11","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("JEMBY")
  Global("flsbt12","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("scrl89","JEMBY",1,0,0)
  SetGlobal("flsbt12","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("JEMBY")
  Global("flsbt13","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("scrl89","JEMBY",1,0,0)
  SetGlobal("flsbt13","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("JEMBY")
  Global("flsbt14","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("scrl89","JEMBY",1,0,0)
  SetGlobal("flsbt14","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("JEMBY")
  Global("flsbt15","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("scrl91","JEMBY",1,0,0)
  SetGlobal("flsbt15","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("JEMBY")
  Global("flsbt16","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("scrl93","JEMBY",1,0,0)
  SetGlobal("flsbt16","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("JEMBY")
  Global("flsbt17","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("scrl93","JEMBY",1,0,0)
  SetGlobal("flsbt17","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("JEMBY")
  Global("flsbt18","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("scrl94","JEMBY",1,0,0)
  SetGlobal("flsbt18","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("JEMBY")
  Global("flsbt19","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("scrl95","JEMBY",1,0,0)
  SetGlobal("flsbt19","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("JEMBY")
  Global("flsbt20","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("scrl95","JEMBY",1,0,0)
  SetGlobal("flsbt20","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("JEMBY")
  Global("flsbt21","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("scrl96","JEMBY",1,0,0)
  SetGlobal("flsbt21","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("JEMBY")
  Global("flsbt22","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("scrl96","JEMBY",1,0,0)
  SetGlobal("flsbt22","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("JEMBY")
  Global("flsbt23","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("scrl97","JEMBY",1,0,0)
  SetGlobal("flsbt23","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("JEMBY")
  Global("flsbt24","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("scrl99","JEMBY",1,0,0)
  SetGlobal("flsbt24","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("JEMBY")
  Global("flsbt25","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("scrl99","JEMBY",1,0,0)
  SetGlobal("flsbt25","GLOBAL",-1)
  DestroySelf()
END
