
IF
  Exists("ALAI")
  Global("flsbt01","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("scrl1b","ALAI",1,0,0)
  SetGlobal("flsbt01","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("NAAMAN")
  Global("flsbt02","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("scrl1b","NAAMAN",1,0,0)
  SetGlobal("flsbt02","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("NAAMAN")
  Global("flsbt03","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("scrl1b","NAAMAN",1,0,0)
  SetGlobal("flsbt03","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("ALAI")
  Global("flsbt04","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("scrl1c","ALAI",1,0,0)
  SetGlobal("flsbt04","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("NAAMAN")
  Global("flsbt05","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("scrl1c","NAAMAN",1,0,0)
  SetGlobal("flsbt05","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("NAAMAN")
  Global("flsbt06","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("scrl3g","NAAMAN",1,0,0)
  SetGlobal("flsbt06","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("ALAI")
  Global("flsbt07","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("scrl85","ALAI",1,0,0)
  SetGlobal("flsbt07","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("NAAMAN")
  Global("flsbt08","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("scrl85","NAAMAN",1,0,0)
  SetGlobal("flsbt08","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("NAAMAN")
  Global("flsbt09","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("scrl87","NAAMAN",1,0,0)
  SetGlobal("flsbt09","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("ALAI")
  Global("flsbt10","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("scrl87","ALAI",1,0,0)
  SetGlobal("flsbt10","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("ALAI")
  Global("flsbt11","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("scrl87","ALAI",1,0,0)
  SetGlobal("flsbt11","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("ALAI")
  Global("flsbt12","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("scrl89","ALAI",1,0,0)
  SetGlobal("flsbt12","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("NAAMAN")
  Global("flsbt13","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("scrl89","NAAMAN",1,0,0)
  SetGlobal("flsbt13","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("ALAI")
  Global("flsbt14","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("scrl89","ALAI",1,0,0)
  SetGlobal("flsbt14","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("ALAI")
  Global("flsbt15","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("scrl91","ALAI",1,0,0)
  SetGlobal("flsbt15","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("NAAMAN")
  Global("flsbt16","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("scrl93","NAAMAN",1,0,0)
  SetGlobal("flsbt16","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("NAAMAN")
  Global("flsbt17","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("scrl93","NAAMAN",1,0,0)
  SetGlobal("flsbt17","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("ALAI")
  Global("flsbt18","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("scrl94","ALAI",1,0,0)
  SetGlobal("flsbt18","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("NAAMAN")
  Global("flsbt19","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("scrl95","NAAMAN",1,0,0)
  SetGlobal("flsbt19","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("NAAMAN")
  Global("flsbt20","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("scrl95","NAAMAN",1,0,0)
  SetGlobal("flsbt20","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("ALAI")
  Global("flsbt21","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("scrl96","ALAI",1,0,0)
  SetGlobal("flsbt21","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("NAAMAN")
  Global("flsbt22","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("scrl96","NAAMAN",1,0,0)
  SetGlobal("flsbt22","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("ALAI")
  Global("flsbt23","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("scrl97","ALAI",1,0,0)
  SetGlobal("flsbt23","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("ALAI")
  Global("flsbt24","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("scrl99","ALAI",1,0,0)
  SetGlobal("flsbt24","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("ALAI")
  Global("flsbt25","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("scrl99","ALAI",1,0,0)
  SetGlobal("flsbt25","GLOBAL",-1)
  DestroySelf()
END
