
IF
  Exists("WILLIAM")
  Global("flsbt01","GLOBAL",19)
THEN RESPONSE #100
  GiveItemCreate("scrl1b","WILLIAM",1,0,0)
  SetGlobal("flsbt01","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("WHEBER")
  Global("flsbt02","GLOBAL",19)
THEN RESPONSE #100
  GiveItemCreate("scrl1b","WHEBER",1,0,0)
  SetGlobal("flsbt02","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("WHEBER")
  Global("flsbt03","GLOBAL",19)
THEN RESPONSE #100
  GiveItemCreate("scrl1b","WHEBER",1,0,0)
  SetGlobal("flsbt03","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("OULAM")
  Global("flsbt04","GLOBAL",19)
THEN RESPONSE #100
  GiveItemCreate("scrl1c","OULAM",1,0,0)
  SetGlobal("flsbt04","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("WILLIAM")
  Global("flsbt05","GLOBAL",19)
THEN RESPONSE #100
  GiveItemCreate("scrl1c","WILLIAM",1,0,0)
  SetGlobal("flsbt05","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("WILLIAM")
  Global("flsbt06","GLOBAL",19)
THEN RESPONSE #100
  GiveItemCreate("scrl3g","WILLIAM",1,0,0)
  SetGlobal("flsbt06","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("NIEMAIN")
  Global("flsbt07","GLOBAL",19)
THEN RESPONSE #100
  GiveItemCreate("scrl85","NIEMAIN",1,0,0)
  SetGlobal("flsbt07","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("WILLIAM")
  Global("flsbt08","GLOBAL",19)
THEN RESPONSE #100
  GiveItemCreate("scrl85","WILLIAM",1,0,0)
  SetGlobal("flsbt08","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("WHEBER")
  Global("flsbt09","GLOBAL",19)
THEN RESPONSE #100
  GiveItemCreate("scrl87","WHEBER",1,0,0)
  SetGlobal("flsbt09","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("NIEMAIN")
  Global("flsbt10","GLOBAL",19)
THEN RESPONSE #100
  GiveItemCreate("scrl87","NIEMAIN",1,0,0)
  SetGlobal("flsbt10","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("NIEMAIN")
  Global("flsbt11","GLOBAL",19)
THEN RESPONSE #100
  GiveItemCreate("scrl87","NIEMAIN",1,0,0)
  SetGlobal("flsbt11","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("WHEBER")
  Global("flsbt12","GLOBAL",19)
THEN RESPONSE #100
  GiveItemCreate("scrl89","WHEBER",1,0,0)
  SetGlobal("flsbt12","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("WILLIAM")
  Global("flsbt13","GLOBAL",19)
THEN RESPONSE #100
  GiveItemCreate("scrl89","WILLIAM",1,0,0)
  SetGlobal("flsbt13","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("OULAM")
  Global("flsbt14","GLOBAL",19)
THEN RESPONSE #100
  GiveItemCreate("scrl89","OULAM",1,0,0)
  SetGlobal("flsbt14","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("NIEMAIN")
  Global("flsbt15","GLOBAL",19)
THEN RESPONSE #100
  GiveItemCreate("scrl91","NIEMAIN",1,0,0)
  SetGlobal("flsbt15","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("OULAM")
  Global("flsbt16","GLOBAL",19)
THEN RESPONSE #100
  GiveItemCreate("scrl93","OULAM",1,0,0)
  SetGlobal("flsbt16","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("OULAM")
  Global("flsbt17","GLOBAL",19)
THEN RESPONSE #100
  GiveItemCreate("scrl93","OULAM",1,0,0)
  SetGlobal("flsbt17","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("WILLIAM")
  Global("flsbt18","GLOBAL",19)
THEN RESPONSE #100
  GiveItemCreate("scrl94","WILLIAM",1,0,0)
  SetGlobal("flsbt18","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("WHEBER")
  Global("flsbt19","GLOBAL",19)
THEN RESPONSE #100
  GiveItemCreate("scrl95","WHEBER",1,0,0)
  SetGlobal("flsbt19","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("OULAM")
  Global("flsbt20","GLOBAL",19)
THEN RESPONSE #100
  GiveItemCreate("scrl95","OULAM",1,0,0)
  SetGlobal("flsbt20","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("WHEBER")
  Global("flsbt21","GLOBAL",19)
THEN RESPONSE #100
  GiveItemCreate("scrl96","WHEBER",1,0,0)
  SetGlobal("flsbt21","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("WILLIAM")
  Global("flsbt22","GLOBAL",19)
THEN RESPONSE #100
  GiveItemCreate("scrl96","WILLIAM",1,0,0)
  SetGlobal("flsbt22","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("NIEMAIN")
  Global("flsbt23","GLOBAL",19)
THEN RESPONSE #100
  GiveItemCreate("scrl97","NIEMAIN",1,0,0)
  SetGlobal("flsbt23","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("WHEBER")
  Global("flsbt24","GLOBAL",19)
THEN RESPONSE #100
  GiveItemCreate("scrl99","WHEBER",1,0,0)
  SetGlobal("flsbt24","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("NIEMAIN")
  Global("flsbt25","GLOBAL",19)
THEN RESPONSE #100
  GiveItemCreate("scrl99","NIEMAIN",1,0,0)
  SetGlobal("flsbt25","GLOBAL",-1)
  DestroySelf()
END
