
IF
  Exists("DRELIK")
  Global("flsct01","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("scrl1e","DRELIK",1,0,0)
  SetGlobal("flsct01","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("DRELIK")
  Global("flsct02","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("scrl1e","DRELIK",1,0,0)
  SetGlobal("flsct02","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("DRELIK")
  Global("flsct03","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("scrl1f","DRELIK",1,0,0)
  SetGlobal("flsct03","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("DRELIK")
  Global("flsct04","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("scrl1f","DRELIK",1,0,0)
  SetGlobal("flsct04","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("DRELIK")
  Global("flsct05","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("scrl1g","DRELIK",1,0,0)
  SetGlobal("flsct05","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("DRELIK")
  Global("flsct06","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("scrl1g","DRELIK",1,0,0)
  SetGlobal("flsct06","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("DRELIK")
  Global("flsct07","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("scrl1h","DRELIK",1,0,0)
  SetGlobal("flsct07","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("DRELIK")
  Global("flsct08","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("scrl1i","DRELIK",1,0,0)
  SetGlobal("flsct08","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("DRELIK")
  Global("flsct09","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("scrl1k","DRELIK",1,0,0)
  SetGlobal("flsct09","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("DRELIK")
  Global("flsct10","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("scrl1k","DRELIK",1,0,0)
  SetGlobal("flsct10","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("DRELIK")
  Global("flsct11","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("scrl1k","DRELIK",1,0,0)
  SetGlobal("flsct11","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("DRELIK")
  Global("flsct12","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("scrl1l","DRELIK",1,0,0)
  SetGlobal("flsct12","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("DRELIK")
  Global("flsct13","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("scrl1m","DRELIK",1,0,0)
  SetGlobal("flsct13","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("DRELIK")
  Global("flsct14","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("scrl1n","DRELIK",1,0,0)
  SetGlobal("flsct14","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("DRELIK")
  Global("flsct15","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("scrl1n","DRELIK",1,0,0)
  SetGlobal("flsct15","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("DRELIK")
  Global("flsct16","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("scrl1n","DRELIK",1,0,0)
  SetGlobal("flsct16","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("DRELIK")
  Global("flsct17","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("scrl1o","DRELIK",1,0,0)
  SetGlobal("flsct17","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("DRELIK")
  Global("flsct18","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("scrl1s","DRELIK",1,0,0)
  SetGlobal("flsct18","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("DRELIK")
  Global("flsct19","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("scrl1s","DRELIK",1,0,0)
  SetGlobal("flsct19","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("DRELIK")
  Global("flsct20","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("scrl1t","DRELIK",1,0,0)
  SetGlobal("flsct20","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("DRELIK")
  Global("flsct21","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("scrl1t","DRELIK",1,0,0)
  SetGlobal("flsct21","GLOBAL",-1)
  DestroySelf()
END
