
IF
  Exists("ALAI")
  Global("flsct01","GLOBAL",8)
THEN RESPONSE #100
  GiveItemCreate("scrl1e","ALAI",1,0,0)
  SetGlobal("flsct01","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("ALAI")
  Global("flsct02","GLOBAL",8)
THEN RESPONSE #100
  GiveItemCreate("scrl1e","ALAI",1,0,0)
  SetGlobal("flsct02","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("NAAMAN")
  Global("flsct03","GLOBAL",8)
THEN RESPONSE #100
  GiveItemCreate("scrl1f","NAAMAN",1,0,0)
  SetGlobal("flsct03","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("NAAMAN")
  Global("flsct04","GLOBAL",8)
THEN RESPONSE #100
  GiveItemCreate("scrl1f","NAAMAN",1,0,0)
  SetGlobal("flsct04","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("ALAI")
  Global("flsct05","GLOBAL",8)
THEN RESPONSE #100
  GiveItemCreate("scrl1g","ALAI",1,0,0)
  SetGlobal("flsct05","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("ALAI")
  Global("flsct06","GLOBAL",8)
THEN RESPONSE #100
  GiveItemCreate("scrl1g","ALAI",1,0,0)
  SetGlobal("flsct06","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("NAAMAN")
  Global("flsct07","GLOBAL",8)
THEN RESPONSE #100
  GiveItemCreate("scrl1h","NAAMAN",1,0,0)
  SetGlobal("flsct07","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("ALAI")
  Global("flsct08","GLOBAL",8)
THEN RESPONSE #100
  GiveItemCreate("scrl1i","ALAI",1,0,0)
  SetGlobal("flsct08","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("ALAI")
  Global("flsct09","GLOBAL",8)
THEN RESPONSE #100
  GiveItemCreate("scrl1k","ALAI",1,0,0)
  SetGlobal("flsct09","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("NAAMAN")
  Global("flsct10","GLOBAL",8)
THEN RESPONSE #100
  GiveItemCreate("scrl1k","NAAMAN",1,0,0)
  SetGlobal("flsct10","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("NAAMAN")
  Global("flsct11","GLOBAL",8)
THEN RESPONSE #100
  GiveItemCreate("scrl1k","NAAMAN",1,0,0)
  SetGlobal("flsct11","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("ALAI")
  Global("flsct12","GLOBAL",8)
THEN RESPONSE #100
  GiveItemCreate("scrl1l","ALAI",1,0,0)
  SetGlobal("flsct12","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("NAAMAN")
  Global("flsct13","GLOBAL",8)
THEN RESPONSE #100
  GiveItemCreate("scrl1m","NAAMAN",1,0,0)
  SetGlobal("flsct13","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("ALAI")
  Global("flsct14","GLOBAL",8)
THEN RESPONSE #100
  GiveItemCreate("scrl1n","ALAI",1,0,0)
  SetGlobal("flsct14","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("ALAI")
  Global("flsct15","GLOBAL",8)
THEN RESPONSE #100
  GiveItemCreate("scrl1n","ALAI",1,0,0)
  SetGlobal("flsct15","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("ALAI")
  Global("flsct16","GLOBAL",8)
THEN RESPONSE #100
  GiveItemCreate("scrl1n","ALAI",1,0,0)
  SetGlobal("flsct16","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("NAAMAN")
  Global("flsct17","GLOBAL",8)
THEN RESPONSE #100
  GiveItemCreate("scrl1o","NAAMAN",1,0,0)
  SetGlobal("flsct17","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("NAAMAN")
  Global("flsct18","GLOBAL",8)
THEN RESPONSE #100
  GiveItemCreate("scrl1s","NAAMAN",1,0,0)
  SetGlobal("flsct18","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("ALAI")
  Global("flsct19","GLOBAL",8)
THEN RESPONSE #100
  GiveItemCreate("scrl1s","ALAI",1,0,0)
  SetGlobal("flsct19","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("ALAI")
  Global("flsct20","GLOBAL",8)
THEN RESPONSE #100
  GiveItemCreate("scrl1t","ALAI",1,0,0)
  SetGlobal("flsct20","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("ALAI")
  Global("flsct21","GLOBAL",8)
THEN RESPONSE #100
  GiveItemCreate("scrl1t","ALAI",1,0,0)
  SetGlobal("flsct21","GLOBAL",-1)
  DestroySelf()
END
