
IF
  Exists("krystin")
  Global("flsct01","GLOBAL",6)
THEN RESPONSE #100
  GiveItemCreate("scrl1e","krystin",1,0,0)
  SetGlobal("flsct01","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("krystin")
  Global("flsct02","GLOBAL",6)
THEN RESPONSE #100
  GiveItemCreate("scrl1e","krystin",1,0,0)
  SetGlobal("flsct02","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("krystin")
  Global("flsct03","GLOBAL",6)
THEN RESPONSE #100
  GiveItemCreate("scrl1f","krystin",1,0,0)
  SetGlobal("flsct03","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("krystin")
  Global("flsct04","GLOBAL",6)
THEN RESPONSE #100
  GiveItemCreate("scrl1f","krystin",1,0,0)
  SetGlobal("flsct04","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("krystin")
  Global("flsct05","GLOBAL",6)
THEN RESPONSE #100
  GiveItemCreate("scrl1g","krystin",1,0,0)
  SetGlobal("flsct05","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("krystin")
  Global("flsct06","GLOBAL",6)
THEN RESPONSE #100
  GiveItemCreate("scrl1g","krystin",1,0,0)
  SetGlobal("flsct06","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("krystin")
  Global("flsct07","GLOBAL",6)
THEN RESPONSE #100
  GiveItemCreate("scrl1h","krystin",1,0,0)
  SetGlobal("flsct07","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("krystin")
  Global("flsct08","GLOBAL",6)
THEN RESPONSE #100
  GiveItemCreate("scrl1i","krystin",1,0,0)
  SetGlobal("flsct08","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("krystin")
  Global("flsct09","GLOBAL",6)
THEN RESPONSE #100
  GiveItemCreate("scrl1k","krystin",1,0,0)
  SetGlobal("flsct09","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("krystin")
  Global("flsct10","GLOBAL",6)
THEN RESPONSE #100
  GiveItemCreate("scrl1k","krystin",1,0,0)
  SetGlobal("flsct10","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("krystin")
  Global("flsct11","GLOBAL",6)
THEN RESPONSE #100
  GiveItemCreate("scrl1k","krystin",1,0,0)
  SetGlobal("flsct11","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("krystin")
  Global("flsct12","GLOBAL",6)
THEN RESPONSE #100
  GiveItemCreate("scrl1l","krystin",1,0,0)
  SetGlobal("flsct12","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("krystin")
  Global("flsct13","GLOBAL",6)
THEN RESPONSE #100
  GiveItemCreate("scrl1m","krystin",1,0,0)
  SetGlobal("flsct13","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("krystin")
  Global("flsct14","GLOBAL",6)
THEN RESPONSE #100
  GiveItemCreate("scrl1n","krystin",1,0,0)
  SetGlobal("flsct14","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("krystin")
  Global("flsct15","GLOBAL",6)
THEN RESPONSE #100
  GiveItemCreate("scrl1n","krystin",1,0,0)
  SetGlobal("flsct15","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("krystin")
  Global("flsct16","GLOBAL",6)
THEN RESPONSE #100
  GiveItemCreate("scrl1n","krystin",1,0,0)
  SetGlobal("flsct16","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("krystin")
  Global("flsct17","GLOBAL",6)
THEN RESPONSE #100
  GiveItemCreate("scrl1o","krystin",1,0,0)
  SetGlobal("flsct17","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("krystin")
  Global("flsct18","GLOBAL",6)
THEN RESPONSE #100
  GiveItemCreate("scrl1s","krystin",1,0,0)
  SetGlobal("flsct18","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("krystin")
  Global("flsct19","GLOBAL",6)
THEN RESPONSE #100
  GiveItemCreate("scrl1s","krystin",1,0,0)
  SetGlobal("flsct19","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("krystin")
  Global("flsct20","GLOBAL",6)
THEN RESPONSE #100
  GiveItemCreate("scrl1t","krystin",1,0,0)
  SetGlobal("flsct20","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("krystin")
  Global("flsct21","GLOBAL",6)
THEN RESPONSE #100
  GiveItemCreate("scrl1t","krystin",1,0,0)
  SetGlobal("flsct21","GLOBAL",-1)
  DestroySelf()
END
