
IF
  Exists("Cythan")
  Global("flsct01","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("scrl1e","Cythan",1,0,0)
  SetGlobal("flsct01","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Cythan")
  Global("flsct02","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("scrl1e","Cythan",1,0,0)
  SetGlobal("flsct02","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Cythan")
  Global("flsct03","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("scrl1f","Cythan",1,0,0)
  SetGlobal("flsct03","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Cythan")
  Global("flsct04","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("scrl1f","Cythan",1,0,0)
  SetGlobal("flsct04","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Cythan")
  Global("flsct05","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("scrl1g","Cythan",1,0,0)
  SetGlobal("flsct05","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Cythan")
  Global("flsct06","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("scrl1g","Cythan",1,0,0)
  SetGlobal("flsct06","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Cythan")
  Global("flsct07","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("scrl1h","Cythan",1,0,0)
  SetGlobal("flsct07","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Cythan")
  Global("flsct08","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("scrl1i","Cythan",1,0,0)
  SetGlobal("flsct08","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Cythan")
  Global("flsct09","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("scrl1k","Cythan",1,0,0)
  SetGlobal("flsct09","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Cythan")
  Global("flsct10","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("scrl1k","Cythan",1,0,0)
  SetGlobal("flsct10","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Cythan")
  Global("flsct11","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("scrl1k","Cythan",1,0,0)
  SetGlobal("flsct11","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Cythan")
  Global("flsct12","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("scrl1l","Cythan",1,0,0)
  SetGlobal("flsct12","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Cythan")
  Global("flsct13","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("scrl1m","Cythan",1,0,0)
  SetGlobal("flsct13","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Cythan")
  Global("flsct14","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("scrl1n","Cythan",1,0,0)
  SetGlobal("flsct14","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Cythan")
  Global("flsct15","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("scrl1n","Cythan",1,0,0)
  SetGlobal("flsct15","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Cythan")
  Global("flsct16","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("scrl1n","Cythan",1,0,0)
  SetGlobal("flsct16","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Cythan")
  Global("flsct17","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("scrl1o","Cythan",1,0,0)
  SetGlobal("flsct17","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Cythan")
  Global("flsct18","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("scrl1s","Cythan",1,0,0)
  SetGlobal("flsct18","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Cythan")
  Global("flsct19","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("scrl1s","Cythan",1,0,0)
  SetGlobal("flsct19","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Cythan")
  Global("flsct20","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("scrl1t","Cythan",1,0,0)
  SetGlobal("flsct20","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Cythan")
  Global("flsct21","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("scrl1t","Cythan",1,0,0)
  SetGlobal("flsct21","GLOBAL",-1)
  DestroySelf()
END
