
IF
  Exists("SHALDRISSA")
  Global("flsct01","GLOBAL",21)
THEN RESPONSE #100
  GiveItemCreate("scrl1e","SHALDRISSA",1,0,0)
  SetGlobal("flsct01","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("SHALDRISSA")
  Global("flsct02","GLOBAL",21)
THEN RESPONSE #100
  GiveItemCreate("scrl1e","SHALDRISSA",1,0,0)
  SetGlobal("flsct02","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("SHALDRISSA")
  Global("flsct03","GLOBAL",21)
THEN RESPONSE #100
  GiveItemCreate("scrl1f","SHALDRISSA",1,0,0)
  SetGlobal("flsct03","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("SHALDRISSA")
  Global("flsct04","GLOBAL",21)
THEN RESPONSE #100
  GiveItemCreate("scrl1f","SHALDRISSA",1,0,0)
  SetGlobal("flsct04","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("SHALDRISSA")
  Global("flsct05","GLOBAL",21)
THEN RESPONSE #100
  GiveItemCreate("scrl1g","SHALDRISSA",1,0,0)
  SetGlobal("flsct05","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("SHALDRISSA")
  Global("flsct06","GLOBAL",21)
THEN RESPONSE #100
  GiveItemCreate("scrl1g","SHALDRISSA",1,0,0)
  SetGlobal("flsct06","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("SHALDRISSA")
  Global("flsct07","GLOBAL",21)
THEN RESPONSE #100
  GiveItemCreate("scrl1h","SHALDRISSA",1,0,0)
  SetGlobal("flsct07","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("SHALDRISSA")
  Global("flsct08","GLOBAL",21)
THEN RESPONSE #100
  GiveItemCreate("scrl1i","SHALDRISSA",1,0,0)
  SetGlobal("flsct08","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("SHALDRISSA")
  Global("flsct09","GLOBAL",21)
THEN RESPONSE #100
  GiveItemCreate("scrl1k","SHALDRISSA",1,0,0)
  SetGlobal("flsct09","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("SHALDRISSA")
  Global("flsct10","GLOBAL",21)
THEN RESPONSE #100
  GiveItemCreate("scrl1k","SHALDRISSA",1,0,0)
  SetGlobal("flsct10","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("SHALDRISSA")
  Global("flsct11","GLOBAL",21)
THEN RESPONSE #100
  GiveItemCreate("scrl1k","SHALDRISSA",1,0,0)
  SetGlobal("flsct11","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("SHALDRISSA")
  Global("flsct12","GLOBAL",21)
THEN RESPONSE #100
  GiveItemCreate("scrl1l","SHALDRISSA",1,0,0)
  SetGlobal("flsct12","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("SHALDRISSA")
  Global("flsct13","GLOBAL",21)
THEN RESPONSE #100
  GiveItemCreate("scrl1m","SHALDRISSA",1,0,0)
  SetGlobal("flsct13","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("SHALDRISSA")
  Global("flsct14","GLOBAL",21)
THEN RESPONSE #100
  GiveItemCreate("scrl1n","SHALDRISSA",1,0,0)
  SetGlobal("flsct14","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("SHALDRISSA")
  Global("flsct15","GLOBAL",21)
THEN RESPONSE #100
  GiveItemCreate("scrl1n","SHALDRISSA",1,0,0)
  SetGlobal("flsct15","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("SHALDRISSA")
  Global("flsct16","GLOBAL",21)
THEN RESPONSE #100
  GiveItemCreate("scrl1n","SHALDRISSA",1,0,0)
  SetGlobal("flsct16","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("SHALDRISSA")
  Global("flsct17","GLOBAL",21)
THEN RESPONSE #100
  GiveItemCreate("scrl1o","SHALDRISSA",1,0,0)
  SetGlobal("flsct17","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("SHALDRISSA")
  Global("flsct18","GLOBAL",21)
THEN RESPONSE #100
  GiveItemCreate("scrl1s","SHALDRISSA",1,0,0)
  SetGlobal("flsct18","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("SHALDRISSA")
  Global("flsct19","GLOBAL",21)
THEN RESPONSE #100
  GiveItemCreate("scrl1s","SHALDRISSA",1,0,0)
  SetGlobal("flsct19","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("SHALDRISSA")
  Global("flsct20","GLOBAL",21)
THEN RESPONSE #100
  GiveItemCreate("scrl1t","SHALDRISSA",1,0,0)
  SetGlobal("flsct20","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("SHALDRISSA")
  Global("flsct21","GLOBAL",21)
THEN RESPONSE #100
  GiveItemCreate("scrl1t","SHALDRISSA",1,0,0)
  SetGlobal("flsct21","GLOBAL",-1)
  DestroySelf()
END
