
IF
  Exists("NEVILLE")
  Global("flsct01","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("scrl1e","NEVILLE",1,0,0)
  SetGlobal("flsct01","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("NEVILLE")
  Global("flsct02","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("scrl1e","NEVILLE",1,0,0)
  SetGlobal("flsct02","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("NEVILLE")
  Global("flsct03","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("scrl1f","NEVILLE",1,0,0)
  SetGlobal("flsct03","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("NEVILLE")
  Global("flsct04","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("scrl1f","NEVILLE",1,0,0)
  SetGlobal("flsct04","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("NEVILLE")
  Global("flsct05","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("scrl1g","NEVILLE",1,0,0)
  SetGlobal("flsct05","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("NEVILLE")
  Global("flsct06","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("scrl1g","NEVILLE",1,0,0)
  SetGlobal("flsct06","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("NEVILLE")
  Global("flsct07","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("scrl1h","NEVILLE",1,0,0)
  SetGlobal("flsct07","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("NEVILLE")
  Global("flsct08","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("scrl1i","NEVILLE",1,0,0)
  SetGlobal("flsct08","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("NEVILLE")
  Global("flsct09","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("scrl1k","NEVILLE",1,0,0)
  SetGlobal("flsct09","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("NEVILLE")
  Global("flsct10","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("scrl1k","NEVILLE",1,0,0)
  SetGlobal("flsct10","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("NEVILLE")
  Global("flsct11","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("scrl1k","NEVILLE",1,0,0)
  SetGlobal("flsct11","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("NEVILLE")
  Global("flsct12","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("scrl1l","NEVILLE",1,0,0)
  SetGlobal("flsct12","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("NEVILLE")
  Global("flsct13","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("scrl1m","NEVILLE",1,0,0)
  SetGlobal("flsct13","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("NEVILLE")
  Global("flsct14","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("scrl1n","NEVILLE",1,0,0)
  SetGlobal("flsct14","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("NEVILLE")
  Global("flsct15","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("scrl1n","NEVILLE",1,0,0)
  SetGlobal("flsct15","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("NEVILLE")
  Global("flsct16","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("scrl1n","NEVILLE",1,0,0)
  SetGlobal("flsct16","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("NEVILLE")
  Global("flsct17","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("scrl1o","NEVILLE",1,0,0)
  SetGlobal("flsct17","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("NEVILLE")
  Global("flsct18","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("scrl1s","NEVILLE",1,0,0)
  SetGlobal("flsct18","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("NEVILLE")
  Global("flsct19","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("scrl1s","NEVILLE",1,0,0)
  SetGlobal("flsct19","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("NEVILLE")
  Global("flsct20","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("scrl1t","NEVILLE",1,0,0)
  SetGlobal("flsct20","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("NEVILLE")
  Global("flsct21","GLOBAL",12)
THEN RESPONSE #100
  GiveItemCreate("scrl1t","NEVILLE",1,0,0)
  SetGlobal("flsct21","GLOBAL",-1)
  DestroySelf()
END
