
IF
  Exists("DEGROD")
  Global("flsct01","GLOBAL",2)
THEN RESPONSE #100
  GiveItemCreate("scrl1e","DEGROD",1,0,0)
  SetGlobal("flsct01","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("DEGROD")
  Global("flsct02","GLOBAL",2)
THEN RESPONSE #100
  GiveItemCreate("scrl1e","DEGROD",1,0,0)
  SetGlobal("flsct02","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("DEGROD")
  Global("flsct03","GLOBAL",2)
THEN RESPONSE #100
  GiveItemCreate("scrl1f","DEGROD",1,0,0)
  SetGlobal("flsct03","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("DEGROD")
  Global("flsct04","GLOBAL",2)
THEN RESPONSE #100
  GiveItemCreate("scrl1f","DEGROD",1,0,0)
  SetGlobal("flsct04","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("DEGROD")
  Global("flsct05","GLOBAL",2)
THEN RESPONSE #100
  GiveItemCreate("scrl1g","DEGROD",1,0,0)
  SetGlobal("flsct05","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("DEGROD")
  Global("flsct06","GLOBAL",2)
THEN RESPONSE #100
  GiveItemCreate("scrl1g","DEGROD",1,0,0)
  SetGlobal("flsct06","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("DEGROD")
  Global("flsct07","GLOBAL",2)
THEN RESPONSE #100
  GiveItemCreate("scrl1h","DEGROD",1,0,0)
  SetGlobal("flsct07","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("DEGROD")
  Global("flsct08","GLOBAL",2)
THEN RESPONSE #100
  GiveItemCreate("scrl1i","DEGROD",1,0,0)
  SetGlobal("flsct08","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("DEGROD")
  Global("flsct09","GLOBAL",2)
THEN RESPONSE #100
  GiveItemCreate("scrl1k","DEGROD",1,0,0)
  SetGlobal("flsct09","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("DEGROD")
  Global("flsct10","GLOBAL",2)
THEN RESPONSE #100
  GiveItemCreate("scrl1k","DEGROD",1,0,0)
  SetGlobal("flsct10","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("DEGROD")
  Global("flsct11","GLOBAL",2)
THEN RESPONSE #100
  GiveItemCreate("scrl1k","DEGROD",1,0,0)
  SetGlobal("flsct11","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("DEGROD")
  Global("flsct12","GLOBAL",2)
THEN RESPONSE #100
  GiveItemCreate("scrl1l","DEGROD",1,0,0)
  SetGlobal("flsct12","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("DEGROD")
  Global("flsct13","GLOBAL",2)
THEN RESPONSE #100
  GiveItemCreate("scrl1m","DEGROD",1,0,0)
  SetGlobal("flsct13","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("DEGROD")
  Global("flsct14","GLOBAL",2)
THEN RESPONSE #100
  GiveItemCreate("scrl1n","DEGROD",1,0,0)
  SetGlobal("flsct14","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("DEGROD")
  Global("flsct15","GLOBAL",2)
THEN RESPONSE #100
  GiveItemCreate("scrl1n","DEGROD",1,0,0)
  SetGlobal("flsct15","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("DEGROD")
  Global("flsct16","GLOBAL",2)
THEN RESPONSE #100
  GiveItemCreate("scrl1n","DEGROD",1,0,0)
  SetGlobal("flsct16","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("DEGROD")
  Global("flsct17","GLOBAL",2)
THEN RESPONSE #100
  GiveItemCreate("scrl1o","DEGROD",1,0,0)
  SetGlobal("flsct17","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("DEGROD")
  Global("flsct18","GLOBAL",2)
THEN RESPONSE #100
  GiveItemCreate("scrl1s","DEGROD",1,0,0)
  SetGlobal("flsct18","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("DEGROD")
  Global("flsct19","GLOBAL",2)
THEN RESPONSE #100
  GiveItemCreate("scrl1s","DEGROD",1,0,0)
  SetGlobal("flsct19","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("DEGROD")
  Global("flsct20","GLOBAL",2)
THEN RESPONSE #100
  GiveItemCreate("scrl1t","DEGROD",1,0,0)
  SetGlobal("flsct20","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("DEGROD")
  Global("flsct21","GLOBAL",2)
THEN RESPONSE #100
  GiveItemCreate("scrl1t","DEGROD",1,0,0)
  SetGlobal("flsct21","GLOBAL",-1)
  DestroySelf()
END
