
IF
  Exists("container7")
  Global("flsct01","GLOBAL",14)
THEN RESPONSE #100
  ActionOverride("container7",CreateItem("scrl1e",1,0,0))
  SetGlobal("flsct01","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("container7")
  Global("flsct02","GLOBAL",14)
THEN RESPONSE #100
  ActionOverride("container7",CreateItem("scrl1e",1,0,0))
  SetGlobal("flsct02","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("container7")
  Global("flsct03","GLOBAL",14)
THEN RESPONSE #100
  ActionOverride("container7",CreateItem("scrl1f",1,0,0))
  SetGlobal("flsct03","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("container7")
  Global("flsct04","GLOBAL",14)
THEN RESPONSE #100
  ActionOverride("container7",CreateItem("scrl1f",1,0,0))
  SetGlobal("flsct04","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("container7")
  Global("flsct05","GLOBAL",14)
THEN RESPONSE #100
  ActionOverride("container7",CreateItem("scrl1g",1,0,0))
  SetGlobal("flsct05","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("container7")
  Global("flsct06","GLOBAL",14)
THEN RESPONSE #100
  ActionOverride("container7",CreateItem("scrl1g",1,0,0))
  SetGlobal("flsct06","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("container7")
  Global("flsct07","GLOBAL",14)
THEN RESPONSE #100
  ActionOverride("container7",CreateItem("scrl1h",1,0,0))
  SetGlobal("flsct07","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("container7")
  Global("flsct08","GLOBAL",14)
THEN RESPONSE #100
  ActionOverride("container7",CreateItem("scrl1i",1,0,0))
  SetGlobal("flsct08","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("container7")
  Global("flsct09","GLOBAL",14)
THEN RESPONSE #100
  ActionOverride("container7",CreateItem("scrl1k",1,0,0))
  SetGlobal("flsct09","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("container7")
  Global("flsct10","GLOBAL",14)
THEN RESPONSE #100
  ActionOverride("container7",CreateItem("scrl1k",1,0,0))
  SetGlobal("flsct10","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("container7")
  Global("flsct11","GLOBAL",14)
THEN RESPONSE #100
  ActionOverride("container7",CreateItem("scrl1k",1,0,0))
  SetGlobal("flsct11","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("container7")
  Global("flsct12","GLOBAL",14)
THEN RESPONSE #100
  ActionOverride("container7",CreateItem("scrl1l",1,0,0))
  SetGlobal("flsct12","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("container7")
  Global("flsct13","GLOBAL",14)
THEN RESPONSE #100
  ActionOverride("container7",CreateItem("scrl1m",1,0,0))
  SetGlobal("flsct13","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("container7")
  Global("flsct14","GLOBAL",14)
THEN RESPONSE #100
  ActionOverride("container7",CreateItem("scrl1n",1,0,0))
  SetGlobal("flsct14","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("container7")
  Global("flsct15","GLOBAL",14)
THEN RESPONSE #100
  ActionOverride("container7",CreateItem("scrl1n",1,0,0))
  SetGlobal("flsct15","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("container7")
  Global("flsct16","GLOBAL",14)
THEN RESPONSE #100
  ActionOverride("container7",CreateItem("scrl1n",1,0,0))
  SetGlobal("flsct16","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("container7")
  Global("flsct17","GLOBAL",14)
THEN RESPONSE #100
  ActionOverride("container7",CreateItem("scrl1o",1,0,0))
  SetGlobal("flsct17","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("container7")
  Global("flsct18","GLOBAL",14)
THEN RESPONSE #100
  ActionOverride("container7",CreateItem("scrl1s",1,0,0))
  SetGlobal("flsct18","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("container7")
  Global("flsct19","GLOBAL",14)
THEN RESPONSE #100
  ActionOverride("container7",CreateItem("scrl1s",1,0,0))
  SetGlobal("flsct19","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("container7")
  Global("flsct20","GLOBAL",14)
THEN RESPONSE #100
  ActionOverride("container7",CreateItem("scrl1t",1,0,0))
  SetGlobal("flsct20","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("container7")
  Global("flsct21","GLOBAL",14)
THEN RESPONSE #100
  ActionOverride("container7",CreateItem("scrl1t",1,0,0))
  SetGlobal("flsct21","GLOBAL",-1)
  DestroySelf()
END
