
IF
  Exists("WIVEN")
  Global("flsct01","GLOBAL",7)
THEN RESPONSE #100
  GiveItemCreate("scrl1e","WIVEN",1,0,0)
  SetGlobal("flsct01","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("WIVEN")
  Global("flsct02","GLOBAL",7)
THEN RESPONSE #100
  GiveItemCreate("scrl1e","WIVEN",1,0,0)
  SetGlobal("flsct02","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("WIVEN")
  Global("flsct03","GLOBAL",7)
THEN RESPONSE #100
  GiveItemCreate("scrl1f","WIVEN",1,0,0)
  SetGlobal("flsct03","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("WIVEN")
  Global("flsct04","GLOBAL",7)
THEN RESPONSE #100
  GiveItemCreate("scrl1f","WIVEN",1,0,0)
  SetGlobal("flsct04","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("WIVEN")
  Global("flsct05","GLOBAL",7)
THEN RESPONSE #100
  GiveItemCreate("scrl1g","WIVEN",1,0,0)
  SetGlobal("flsct05","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("WIVEN")
  Global("flsct06","GLOBAL",7)
THEN RESPONSE #100
  GiveItemCreate("scrl1g","WIVEN",1,0,0)
  SetGlobal("flsct06","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("WIVEN")
  Global("flsct07","GLOBAL",7)
THEN RESPONSE #100
  GiveItemCreate("scrl1h","WIVEN",1,0,0)
  SetGlobal("flsct07","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("WIVEN")
  Global("flsct08","GLOBAL",7)
THEN RESPONSE #100
  GiveItemCreate("scrl1i","WIVEN",1,0,0)
  SetGlobal("flsct08","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("WIVEN")
  Global("flsct09","GLOBAL",7)
THEN RESPONSE #100
  GiveItemCreate("scrl1k","WIVEN",1,0,0)
  SetGlobal("flsct09","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("WIVEN")
  Global("flsct10","GLOBAL",7)
THEN RESPONSE #100
  GiveItemCreate("scrl1k","WIVEN",1,0,0)
  SetGlobal("flsct10","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("WIVEN")
  Global("flsct11","GLOBAL",7)
THEN RESPONSE #100
  GiveItemCreate("scrl1k","WIVEN",1,0,0)
  SetGlobal("flsct11","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("WIVEN")
  Global("flsct12","GLOBAL",7)
THEN RESPONSE #100
  GiveItemCreate("scrl1l","WIVEN",1,0,0)
  SetGlobal("flsct12","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("WIVEN")
  Global("flsct13","GLOBAL",7)
THEN RESPONSE #100
  GiveItemCreate("scrl1m","WIVEN",1,0,0)
  SetGlobal("flsct13","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("WIVEN")
  Global("flsct14","GLOBAL",7)
THEN RESPONSE #100
  GiveItemCreate("scrl1n","WIVEN",1,0,0)
  SetGlobal("flsct14","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("WIVEN")
  Global("flsct15","GLOBAL",7)
THEN RESPONSE #100
  GiveItemCreate("scrl1n","WIVEN",1,0,0)
  SetGlobal("flsct15","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("WIVEN")
  Global("flsct16","GLOBAL",7)
THEN RESPONSE #100
  GiveItemCreate("scrl1n","WIVEN",1,0,0)
  SetGlobal("flsct16","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("WIVEN")
  Global("flsct17","GLOBAL",7)
THEN RESPONSE #100
  GiveItemCreate("scrl1o","WIVEN",1,0,0)
  SetGlobal("flsct17","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("WIVEN")
  Global("flsct18","GLOBAL",7)
THEN RESPONSE #100
  GiveItemCreate("scrl1s","WIVEN",1,0,0)
  SetGlobal("flsct18","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("WIVEN")
  Global("flsct19","GLOBAL",7)
THEN RESPONSE #100
  GiveItemCreate("scrl1s","WIVEN",1,0,0)
  SetGlobal("flsct19","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("WIVEN")
  Global("flsct20","GLOBAL",7)
THEN RESPONSE #100
  GiveItemCreate("scrl1t","WIVEN",1,0,0)
  SetGlobal("flsct20","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("WIVEN")
  Global("flsct21","GLOBAL",7)
THEN RESPONSE #100
  GiveItemCreate("scrl1t","WIVEN",1,0,0)
  SetGlobal("flsct21","GLOBAL",-1)
  DestroySelf()
END
