
IF
  Exists("NAAMAN")
  Global("flsdt01","GLOBAL",2)
THEN RESPONSE #100
  GiveItemCreate("scrl1u","NAAMAN",1,0,0)
  SetGlobal("flsdt01","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("NAAMAN")
  Global("flsdt02","GLOBAL",2)
THEN RESPONSE #100
  GiveItemCreate("scrl1u","NAAMAN",1,0,0)
  SetGlobal("flsdt02","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("NAAMAN")
  Global("flsdt03","GLOBAL",2)
THEN RESPONSE #100
  GiveItemCreate("scrl1u","NAAMAN",1,0,0)
  SetGlobal("flsdt03","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("NAAMAN")
  Global("flsdt07","GLOBAL",2)
THEN RESPONSE #100
  GiveItemCreate("scrl5l","NAAMAN",1,1,0)
  SetGlobal("flsdt07","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("NAAMAN")
  Global("flsdt08","GLOBAL",2)
THEN RESPONSE #100
  GiveItemCreate("scrl1z","NAAMAN",1,0,0)
  SetGlobal("flsdt08","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("ALAI")
  Global("flsdt09","GLOBAL",2)
THEN RESPONSE #100
  GiveItemCreate("scrl1z","ALAI",1,0,0)
  SetGlobal("flsdt09","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("NAAMAN")
  Global("flsdt10","GLOBAL",2)
THEN RESPONSE #100
  GiveItemCreate("scrl2a","NAAMAN",1,0,0)
  SetGlobal("flsdt10","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("NAAMAN")
  Global("flsdt11","GLOBAL",2)
THEN RESPONSE #100
  GiveItemCreate("scrl2a","NAAMAN",1,0,0)
  SetGlobal("flsdt11","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("NAAMAN")
  Global("flsdt12","GLOBAL",2)
THEN RESPONSE #100
  GiveItemCreate("scrl2a","NAAMAN",1,0,0)
  SetGlobal("flsdt12","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("ALAI")
  Global("flsdt13","GLOBAL",2)
THEN RESPONSE #100
  GiveItemCreate("scrl5g","ALAI",1,0,0)
  SetGlobal("flsdt13","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("NAAMAN")
  Global("flsdt14","GLOBAL",2)
THEN RESPONSE #100
  GiveItemCreate("scrl5g","NAAMAN",1,0,0)
  SetGlobal("flsdt14","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("ALAI")
  Global("flsdt15","GLOBAL",2)
THEN RESPONSE #100
  GiveItemCreate("scrl5h","ALAI",1,0,0)
  SetGlobal("flsdt15","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("ALAI")
  Global("flsdt16","GLOBAL",2)
THEN RESPONSE #100
  GiveItemCreate("scrl5h","ALAI",1,0,0)
  SetGlobal("flsdt16","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("NAAMAN")
  Global("flsdt17","GLOBAL",2)
THEN RESPONSE #100
  GiveItemCreate("scrl5i","NAAMAN",1,0,0)
  SetGlobal("flsdt17","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("NAAMAN")
  Global("flsdt18","GLOBAL",2)
THEN RESPONSE #100
  GiveItemCreate("scrl5j","NAAMAN",1,0,0)
  SetGlobal("flsdt18","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("ALAI")
  Global("flsdt19","GLOBAL",2)
THEN RESPONSE #100
  GiveItemCreate("scrl5k","ALAI",1,0,0)
  SetGlobal("flsdt19","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("NAAMAN")
  Global("flsdt20","GLOBAL",2)
THEN RESPONSE #100
  GiveItemCreate("scrl5m","NAAMAN",1,0,0)
  SetGlobal("flsdt20","GLOBAL",-1)
  DestroySelf()
END
