
IF
  Exists("container1")
  Global("flsdt01","GLOBAL",11)
THEN RESPONSE #100
  ActionOverride("container1",CreateItem("scrl1u",1,0,0))
  SetGlobal("flsdt01","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("container1")
  Global("flsdt02","GLOBAL",11)
THEN RESPONSE #100
  ActionOverride("container1",CreateItem("scrl1u",1,0,0))
  SetGlobal("flsdt02","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("container1")
  Global("flsdt03","GLOBAL",11)
THEN RESPONSE #100
  ActionOverride("container1",CreateItem("scrl1u",1,0,0))
  SetGlobal("flsdt03","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("container1")
  Global("flsdt07","GLOBAL",11)
THEN RESPONSE #100
  ActionOverride("container1",CreateItem("scrl5l",1,1,0))
  SetGlobal("flsdt07","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("container1")
  Global("flsdt08","GLOBAL",11)
THEN RESPONSE #100
  ActionOverride("container1",CreateItem("scrl1z",1,0,0))
  SetGlobal("flsdt08","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("container1")
  Global("flsdt09","GLOBAL",11)
THEN RESPONSE #100
  ActionOverride("container1",CreateItem("scrl1z",1,0,0))
  SetGlobal("flsdt09","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("container1")
  Global("flsdt10","GLOBAL",11)
THEN RESPONSE #100
  ActionOverride("container1",CreateItem("scrl2a",1,0,0))
  SetGlobal("flsdt10","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("container1")
  Global("flsdt11","GLOBAL",11)
THEN RESPONSE #100
  ActionOverride("container1",CreateItem("scrl2a",1,0,0))
  SetGlobal("flsdt11","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("container1")
  Global("flsdt12","GLOBAL",11)
THEN RESPONSE #100
  ActionOverride("container1",CreateItem("scrl2a",1,0,0))
  SetGlobal("flsdt12","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("container1")
  Global("flsdt13","GLOBAL",11)
THEN RESPONSE #100
  ActionOverride("container1",CreateItem("scrl5g",1,0,0))
  SetGlobal("flsdt13","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("container1")
  Global("flsdt14","GLOBAL",11)
THEN RESPONSE #100
  ActionOverride("container1",CreateItem("scrl5g",1,0,0))
  SetGlobal("flsdt14","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("container1")
  Global("flsdt15","GLOBAL",11)
THEN RESPONSE #100
  ActionOverride("container1",CreateItem("scrl5h",1,0,0))
  SetGlobal("flsdt15","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("container1")
  Global("flsdt16","GLOBAL",11)
THEN RESPONSE #100
  ActionOverride("container1",CreateItem("scrl5h",1,0,0))
  SetGlobal("flsdt16","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("container1")
  Global("flsdt17","GLOBAL",11)
THEN RESPONSE #100
  ActionOverride("container1",CreateItem("scrl5i",1,0,0))
  SetGlobal("flsdt17","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("container1")
  Global("flsdt18","GLOBAL",11)
THEN RESPONSE #100
  ActionOverride("container1",CreateItem("scrl5j",1,0,0))
  SetGlobal("flsdt18","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("container1")
  Global("flsdt19","GLOBAL",11)
THEN RESPONSE #100
  ActionOverride("container1",CreateItem("scrl5k",1,0,0))
  SetGlobal("flsdt19","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("container1")
  Global("flsdt20","GLOBAL",11)
THEN RESPONSE #100
  ActionOverride("container1",CreateItem("scrl5m",1,0,0))
  SetGlobal("flsdt20","GLOBAL",-1)
  DestroySelf()
END
