
IF
  Exists("SewerOgre")
  Global("flsdt01","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("scrl1u","SewerOgre",1,0,0)
  SetGlobal("flsdt01","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("SewerOgre")
  Global("flsdt02","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("scrl1u","SewerOgre",1,0,0)
  SetGlobal("flsdt02","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("SewerOgre")
  Global("flsdt03","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("scrl1u","SewerOgre",1,0,0)
  SetGlobal("flsdt03","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("SewerOgre")
  Global("flsdt07","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("scrl5l","SewerOgre",1,1,0)
  SetGlobal("flsdt07","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("SewerOgre")
  Global("flsdt08","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("scrl1z","SewerOgre",1,0,0)
  SetGlobal("flsdt08","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("SewerOgre")
  Global("flsdt09","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("scrl1z","SewerOgre",1,0,0)
  SetGlobal("flsdt09","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("SewerOgre")
  Global("flsdt10","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("scrl2a","SewerOgre",1,0,0)
  SetGlobal("flsdt10","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("SewerOgre")
  Global("flsdt11","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("scrl2a","SewerOgre",1,0,0)
  SetGlobal("flsdt11","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("SewerOgre")
  Global("flsdt12","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("scrl2a","SewerOgre",1,0,0)
  SetGlobal("flsdt12","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("SewerOgre")
  Global("flsdt13","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("scrl5g","SewerOgre",1,0,0)
  SetGlobal("flsdt13","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("SewerOgre")
  Global("flsdt14","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("scrl5g","SewerOgre",1,0,0)
  SetGlobal("flsdt14","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("SewerOgre")
  Global("flsdt15","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("scrl5h","SewerOgre",1,0,0)
  SetGlobal("flsdt15","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("SewerOgre")
  Global("flsdt16","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("scrl5h","SewerOgre",1,0,0)
  SetGlobal("flsdt16","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("SewerOgre")
  Global("flsdt17","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("scrl5i","SewerOgre",1,0,0)
  SetGlobal("flsdt17","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("SewerOgre")
  Global("flsdt18","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("scrl5j","SewerOgre",1,0,0)
  SetGlobal("flsdt18","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("SewerOgre")
  Global("flsdt19","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("scrl5k","SewerOgre",1,0,0)
  SetGlobal("flsdt19","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("SewerOgre")
  Global("flsdt20","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("scrl5m","SewerOgre",1,0,0)
  SetGlobal("flsdt20","GLOBAL",-1)
  DestroySelf()
END
