
IF
  Exists("SHALDRISSA")
  Global("flset01","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("scrl2d","SHALDRISSA",1,1,0)
  SetGlobal("flset01","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("SHALDRISSA")
  Global("flset02","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("scrl2f","SHALDRISSA",1,1,0)
  SetGlobal("flset02","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("SHALDRISSA")
  Global("flset03","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("scrl2h","SHALDRISSA",1,1,0)
  SetGlobal("flset03","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("SHALDRISSA")
  Global("flset04","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("scrl2e","SHALDRISSA",1,0,0)
  SetGlobal("flset04","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("SHALDRISSA")
  Global("flset05","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("scrl2e","SHALDRISSA",1,0,0)
  SetGlobal("flset05","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("SHALDRISSA")
  Global("flset06","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("scrl2e","SHALDRISSA",1,0,0)
  SetGlobal("flset06","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("SHALDRISSA")
  Global("flset07","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("scrl2g","SHALDRISSA",1,0,0)
  SetGlobal("flset07","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("SHALDRISSA")
  Global("flset08","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("scrl5n","SHALDRISSA",1,0,0)
  SetGlobal("flset08","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("SHALDRISSA")
  Global("flset09","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("scrl5n","SHALDRISSA",1,0,0)
  SetGlobal("flset09","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("SHALDRISSA")
  Global("flset10","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("scrl5o","SHALDRISSA",1,0,0)
  SetGlobal("flset10","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("SHALDRISSA")
  Global("flset11","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("scrl5o","SHALDRISSA",1,0,0)
  SetGlobal("flset11","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("SHALDRISSA")
  Global("flset12","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("scrl5p","SHALDRISSA",1,0,0)
  SetGlobal("flset12","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("SHALDRISSA")
  Global("flset13","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("scrl5p","SHALDRISSA",1,0,0)
  SetGlobal("flset13","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("SHALDRISSA")
  Global("flset14","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("scrl5p","SHALDRISSA",1,0,0)
  SetGlobal("flset14","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("SHALDRISSA")
  Global("flset15","GLOBAL",11)
THEN RESPONSE #100
  GiveItemCreate("scrl5q","SHALDRISSA",1,0,0)
  SetGlobal("flset15","GLOBAL",-1)
  DestroySelf()
END
