
IF
  Exists("Andris")
  Global("flset01","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("scrl2d","Andris",1,1,0)
  SetGlobal("flset01","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Andris")
  Global("flset02","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("scrl2f","Andris",1,1,0)
  SetGlobal("flset02","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Andris")
  Global("flset03","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("scrl2h","Andris",1,1,0)
  SetGlobal("flset03","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Andris")
  Global("flset04","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("scrl2e","Andris",1,0,0)
  SetGlobal("flset04","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Andris")
  Global("flset05","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("scrl2e","Andris",1,0,0)
  SetGlobal("flset05","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Andris")
  Global("flset06","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("scrl2e","Andris",1,0,0)
  SetGlobal("flset06","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Andris")
  Global("flset07","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("scrl2g","Andris",1,0,0)
  SetGlobal("flset07","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Andris")
  Global("flset08","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("scrl5n","Andris",1,0,0)
  SetGlobal("flset08","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Andris")
  Global("flset09","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("scrl5n","Andris",1,0,0)
  SetGlobal("flset09","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Andris")
  Global("flset10","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("scrl5o","Andris",1,0,0)
  SetGlobal("flset10","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Andris")
  Global("flset11","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("scrl5o","Andris",1,0,0)
  SetGlobal("flset11","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Andris")
  Global("flset12","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("scrl5p","Andris",1,0,0)
  SetGlobal("flset12","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Andris")
  Global("flset13","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("scrl5p","Andris",1,0,0)
  SetGlobal("flset13","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Andris")
  Global("flset14","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("scrl5p","Andris",1,0,0)
  SetGlobal("flset14","GLOBAL",-1)
  DestroySelf()
END

IF
  Exists("Andris")
  Global("flset15","GLOBAL",10)
THEN RESPONSE #100
  GiveItemCreate("scrl5q","Andris",1,0,0)
  SetGlobal("flset15","GLOBAL",-1)
  DestroySelf()
END
